'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');const {chromium}=require('playwright');const root=path.resolve(__dirname,'../..'),C=require(root+'/geometry-course/data/course.json'),T=require(root+'/geometry-course/assets/tasks.js');
(async()=>{const server=http.createServer((req,res)=>{let p=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!p.startsWith(root+path.sep))return res.writeHead(403).end();try{if(fs.statSync(p).isDirectory())p+='/index.html';res.setHeader('Content-Type',p.endsWith('.html')?'text/html; charset=utf-8':'text/plain');res.end(fs.readFileSync(p));}catch(e){res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port+'/geometry-course/';const browser=await chromium.launch({executablePath:process.env.GEOMETRY_CHROMIUM||chromium.executablePath(),headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1280,height:900}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));let passed=0;
try{await page.goto(base);assert.equal(await page.locator('.course-card').count(),63);await page.getByRole('button',{name:'8 класс',exact:true}).click();assert.equal(await page.locator('.chapter:visible .course-card:visible').count(),C.units.filter(u=>u.grade===8).length);await page.getByRole('button',{name:'Все классы',exact:true}).click();await page.screenshot({path:root+'/../geometry-private/catalog-desktop.png',fullPage:false});
for(const u of C.units){await page.goto(base+'atlas/'+u.id+'.html');await page.locator('[data-stage="1"]').click();assert.equal(await page.locator('#geo-board canvas').count(),1);await page.locator('#observation').fill('После движения проверяю, сохраняется ли заданная связь.');await page.locator('[data-stage="2"]').click();await page.locator('[data-action="proof-trap"]').click();assert.match(await page.locator('#proof-feedback').innerText(),/чертёж/);const proof=await page.evaluate(()=>COURSE_CONFIG.proof);for(const step of proof.steps){await page.locator('[data-proof="'+step.id+'"]').click();await page.locator('#reason-choice').selectOption('yes');await page.locator('[data-action="reason-check"]').click();}await page.locator('[data-stage="3"]').click();let seed=await page.evaluate(()=>JSON.parse(localStorage.getItem('mathExamGeometry.v1')).units[COURSE_CONFIG.unit.id].seed);let t=T.task(u.calc,seed);for(const step of t.steps){await page.locator('#answer').fill(T.format(step.answer));await page.locator('#answer-form button').click();}await page.locator('[data-action="independent-start"]').click();seed++;t=T.task(u.calc,seed);await page.locator('#answer').fill(T.format(t.answer));await page.locator('#answer-form button').click();assert.match(await page.locator('#answer-feedback').innerText(),/первой попытки/);await page.locator('[data-stage="5"]').click();await page.locator('#written').fill('Проверяю условия. Использую установленную теорему и получаю требуемое утверждение.');await page.locator('[data-action="finish"]').click();assert.equal(await page.locator('#success').count(),1);await page.reload();assert.equal(await page.locator('#written').inputValue(),'Проверяю условия. Использую установленную теорему и получаю требуемое утверждение.');passed++;if(passed%10===0)console.log('Completed new lessons',passed);}
// Pointer geometry construction must persist on reload, and first-attempt state cannot be farmed.
await page.goto(base+'atlas/segments.html');await page.locator('[data-stage="1"]').click();await page.locator('[data-tool="midpoint"]').click();for(const id of ['A','B']){await page.locator('#geo-board .point-select').selectOption(id);await page.locator('#geo-board [data-act="select"]').click();}await page.locator('#geo-board [data-act="goal"]').click();assert.match(await page.locator('.lab-feedback').innerText(),/выполнено/);await page.locator('[data-tool="move"]').click();const rect=await page.locator('#geo-board canvas').boundingBox();await page.mouse.move(rect.x+140/640*rect.width,rect.y+235/420*rect.height);await page.mouse.down();await page.mouse.move(rect.x+180/640*rect.width,rect.y+180/420*rect.height,{steps:5});await page.mouse.up();await page.locator('[data-stage="0"]').click();await page.reload();await page.locator('[data-stage="1"]').click();assert.equal(await page.locator('.point-select option').count(),4);
await page.setViewportSize({width:360,height:800});for(const id of ['segments','pythagoras','trig-circle','homothety']){await page.goto(base+'atlas/'+id+'.html');for(const stage of [0,1,2,3,4,5]){await page.locator('[data-stage="'+stage+'"]').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),id+' overflow stage '+stage);}if(id==='trig-circle'){await page.locator('[data-stage="1"]').click();await page.screenshot({path:root+'/../geometry-private/lesson-mobile.png',fullPage:true});}}
await page.setViewportSize({width:1280,height:900});await page.goto(base+'atlas/pythagoras.html');await page.locator('[data-stage="1"]').click();await page.screenshot({path:root+'/../geometry-private/lesson-desktop.png',fullPage:true});
for(const p of fs.readdirSync(root+'/geometry-course/trainers').filter(p=>p.endsWith('.html'))){await page.goto(base+'trainers/'+p);assert.ok((await page.locator('body').innerText()).length>30);}
await page.goto(base+'teacher-atlas.html');await page.locator('#local-report').click();assert.equal(await page.locator('tbody tr').count(),63);assert.equal(errors.length,0,errors.join('\n'));await page.goto('file://'+root+'/geometry-course/atlas/homothety.html');assert.ok((await page.title()).includes('Гомотетия'));console.log(JSON.stringify({status:'PASS',newLessons:passed,legacyStarts:70,teacherRows:63,mobileWidths:[360],consoleErrors:errors}));
}catch(e){console.error(e);await page.screenshot({path:root+'/../geometry-private/browser-failure.png',fullPage:true});process.exitCode=1;}finally{await browser.close();server.close();}})();
