/* Public course navigator. Browser visits are not learning outcomes. */
(function(){
'use strict';
const map=window.LearningPreparation;if(!map)return;
const $=id=>document.getElementById(id),E=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cabinetOrigin='https://mathexam-board-ladynata.amvera.io';
const key='mathExamFoundations.visits.v1';let visits={},last=null,storageOK=true;
function read(){try{const data=JSON.parse(localStorage.getItem(key)||'null');visits={};last=null;if(!data||data.version!==1)return;for(const item of map.allItems){const time=data.visits?.[item.id];if(Number.isFinite(time)&&time>0)visits[item.id]=time;}if(map.get(data.last?.id)&&['tasks','laboratory'].includes(data.last?.mode))last={id:data.last.id,mode:data.last.mode};}catch(_){storageOK=false;}}
function url(item,mode){return mode==='laboratory'?(item.publicUrl||item.url):item.managedId?cabinetOrigin+item.url:item.url;}
function mark(id,mode){if(!map.get(id))return;visits[id]=Date.now();last={id,mode:mode==='laboratory'?'laboratory':'tasks'};try{localStorage.setItem(key,JSON.stringify({version:1,visits,last}));}catch(_){storageOK=false;}renderResume();}
function row(item,mode){const laboratory=mode==='laboratory',managed=!laboratory&&item.kind==='managed';return `<li class="item" data-item="${E(item.id)}"><div class="item-main"><a href="${E(url(item,mode))}" data-visit="${E(item.id)}" data-mode="${mode}">${E(item.title)} <span aria-hidden="true">→</span></a></div><div class="item-meta"><span class="tag ${managed?'':'local'}">${managed?'Работа в кабинете':'Свободная практика'}</span><span class="visited" data-seen="${E(item.id)}">${visits[item.id]?'Открывали в этом браузере':''}</span>${laboratory&&item.managedId?`<a class="cabinet-link" href="${E(url(item,'tasks'))}" data-visit="${E(item.id)}" data-mode="tasks">С сохранением в кабинете →</a>`:''}</div>${item.note?`<p class="item-note">${E(item.note)}</p>`:''}</li>`;}
function renderRoute(){$('topic-nav').innerHTML=map.groups.map((group,i)=>`<a href="#topic=${E(group.id)}" data-topic="${E(group.id)}">${i+1}. ${E(group.title)}</a>`).join('');$('route').innerHTML=map.groups.map((group,i)=>{const core=group.items.filter(item=>item.tier==='core'),extra=group.items.filter(item=>item.tier==='extra');return `<details class="stage" id="stage-${E(group.id)}" ${i===0?'open':''}><summary><span class="stage-number">${String(i+1).padStart(2,'0')}</span><span><span class="stage-title">${E(group.title)}</span><span class="stage-lead">${E(group.lead)}</span></span><span class="stage-arrow" aria-hidden="true">+</span></summary><div class="stage-body"><ul class="item-list">${core.map(item=>row(item,'tasks')).join('')}</ul>${extra.length?`<details class="extras"><summary>Ещё практика и модели · ${extra.length}</summary><ul class="item-list">${extra.map(item=>row(item,'tasks')).join('')}</ul></details>`:''}</div></details>`;}).join('');}
function renderLab(){const query=$('lab-search').value.trim().toLocaleLowerCase('ru').replace(/ё/g,'е');let count=0;$('laboratory-list').innerHTML=map.groups.map(group=>{const items=group.items.filter(item=>(item.title+' '+group.title+' '+(item.note||'')).toLocaleLowerCase('ru').replace(/ё/g,'е').includes(query));count+=items.length;return items.length?`<section class="lab-group"><h3>${E(group.title)}</h3><ul class="item-list">${items.map(item=>row(item,'laboratory')).join('')}</ul></section>`:'';}).join('');$('lab-count').textContent=count?'Найдено входов к занятиям: '+count+'. Часть занятий доступна в обоих режимах.':'Такую тему пока не нашли. Попробуйте более короткое слово.';}
function renderResume(){const item=last&&map.get(last.id);$('resume').hidden=!item;if(item)$('resume').innerHTML=`<div><p class="small">Последняя открытая тема · ${last.mode==='laboratory'?'лаборатория':'маршрут заданий'}</p><strong>${E(item.title)}</strong><p class="small">Это история открытий, а не оценка результата.</p></div><a class="button" href="${E(url(item,last.mode))}" data-visit="${E(item.id)}" data-mode="${last.mode}">Продолжить →</a>`;document.querySelectorAll('[data-seen]').forEach(el=>el.textContent=visits[el.dataset.seen]?'Открывали в этом браузере':'');$('visits-note').textContent=storageOK?'На этой странице запоминаются только открытые темы в текущем браузере. Открывали: '+Object.keys(visits).length+'. Открытие темы не означает, что она освоена.':'Этот браузер не разрешил сохранить историю открытий. Задания доступны; результаты в кабинете сохраняются отдельно.';}
function setView(view){const laboratory=view==='laboratory';for(const name of ['tasks','laboratory']){const active=name===(laboratory?'laboratory':'tasks'),button=$('tab-'+name);button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;$('panel-'+name).hidden=!active;}if(laboratory)renderLab();}
function fromHash(scroll){const hash=location.hash.slice(1),group=hash.startsWith('topic=')&&map.groups.find(g=>g.id===hash.slice(6));setView(hash==='laboratory'?'laboratory':'tasks');if(group){const stage=$('stage-'+group.id);stage.open=true;if(scroll)stage.scrollIntoView({block:'start'});}}
read();renderRoute();renderResume();fromHash(true);
document.addEventListener('click',event=>{const topic=event.target.closest('a[data-topic]');if(topic&&location.hash==='#topic='+topic.dataset.topic){event.preventDefault();fromHash(true);}const link=event.target.closest('a[data-visit]');if(link)mark(link.dataset.visit,link.dataset.mode);});
document.querySelectorAll('[data-view]').forEach(button=>{button.addEventListener('click',()=>{const hash=button.dataset.view;if(location.hash==='#'+hash)setView(hash);else location.hash=hash;});button.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const next=event.key==='Home'?'tasks':event.key==='End'?'laboratory':button.dataset.view==='tasks'?'laboratory':'tasks';$('tab-'+next).click();$('tab-'+next).focus();});});
$('lab-search').addEventListener('input',renderLab);window.addEventListener('hashchange',()=>fromHash(true));window.addEventListener('pageshow',()=>{read();renderResume();});window.addEventListener('storage',event=>{if(event.key===key){read();renderResume();}});
})();
