(function(){'use strict';if(new URLSearchParams(location.search).get('learning')==='1')return;const D=PathData,$=s=>document.querySelector(s),root=$('#main'),KEY='mathexam.ege-baza.path.v1',E=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let writable=true,state={version:1,serial:11,lessons:{},seen:{},runs:[],active:null};
const integer=(n,max=1e9)=>Number.isSafeInteger(n)&&n>=0&&n<=max;
const answerOK=a=>a&&D.meta.some(m=>m.id===a.id)&&integer(a.seed)&&typeof a.value==='string'&&a.value.length<10000&&typeof a.correct==='boolean';
const runOK=r=>r&&['exam','diagnostic'].includes(r.kind)&&Array.isArray(r.ids)&&r.ids.length===21&&r.ids.every(id=>D.meta.some(l=>l.id===id))&&Array.isArray(r.answers)&&r.answers.length<=21&&r.answers.every(answerOK)&&integer(r.seed)&&integer(r.i,21)&&Number.isFinite(r.start)&&(r.draft===undefined||typeof r.draft==='string'&&r.draft.length<=10000);
function valid(x){return x&&x.version===1&&integer(x.serial)&&x.lessons&&typeof x.lessons==='object'&&!Array.isArray(x.lessons)&&x.seen&&typeof x.seen==='object'&&!Array.isArray(x.seen)&&Object.keys(x.seen).length<20000&&Object.values(x.seen).every(v=>v===true)&&Array.isArray(x.runs)&&x.runs.length<=200&&x.runs.every(runOK)&&Object.entries(x.lessons).every(([k,l])=>D.meta.some(m=>m.id===k)&&l&&integer(l.seed)&&integer(l.stage,4)&&integer(l.step,20)&&integer(l.independent)&&integer(l.guided)&&typeof l.note==='string'&&l.note.length<=10000&&typeof l.draft==='string'&&l.draft.length<=10000&&typeof l.help==='boolean'&&typeof l.attempted==='boolean'&&Array.isArray(l.checks))&&(!x.active||runOK(x.active));}

try{let raw=localStorage.getItem(KEY);if(raw){let x=JSON.parse(raw);if(!valid(x))throw Error();state=x;}}catch(e){writable=false;notice('Сохранение недоступно или повреждено. Исходные данные оставлены без изменений. Текущую работу можно скачать.');}
function notice(t){$('#storage').hidden=false;$('#storage').textContent=t;}
function save(){if(!writable)return;try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){writable=false;notice('Не удалось сохранить работу в браузере. Скачайте отчёт и резервную копию.');}}
function lesson(id){return state.lessons[id]||(state.lessons[id]={seed:id==='equations'?10:state.serial++,stage:0,step:0,help:false,attempted:false,independent:0,guided:0,note:'',draft:'',checks:[]});}
function setHash(s){location.hash=s;}
function feedback(s,bad=false){let f=$('#feedback');if(f){f.textContent=s;f.className='feedback '+(bad?'bad':'good');}}
function taskKey(t){return !t.display&&!t.choices?t.q:JSON.stringify([t.q,t.display||null,(t.labels||[]).slice().sort(),(t.choices||[]).slice().sort()]);}
function seen(t){return !!state.seen[t.q]||!!state.seen[taskKey(t)];}function expose(t){state.seen[taskKey(t)]=true;}
const stageLabels=['Понять','Исследовать','Решить по шагам','Самостоятельно','Объяснить'];
function fresh(id,stage=3){const l=lesson(id);l.seed=state.serial++;if(D.equationPractice?.has(id)){for(let n=1;n<D.equationPractice.count&&seen(D.task(id,l.seed));n++)l.seed=state.serial++;}l.stage=stage;l.step=0;l.help=false;l.attempted=false;l.draft='';l.done=false;save();render();}
const positionNames=['Покупки и округление','Величины и единицы','Таблицы и диаграммы','Вычисления по формулам','Вероятность','Выбор по условиям','Графики и изменение','Логические выводы','Геометрия на сетке','Практическая геометрия','Объёмы и поверхности','Планиметрия','Стереометрия','Числа и дроби','Проценты и отношения','Выражения и функции','Уравнения','Числа, неравенства и ось','Цифры и делимость','Текстовые задачи','Рассуждения и целые числа'];
function map(){
 root.innerHTML='<p class="eyebrow">Тренажёры базового ЕГЭ</p><h1>21 позиция.<br>Начни с нужного навыка.</h1><p class="lead">В каждой теме — смысл, модель, решение по шагам и новый вариант для самостоятельной работы. Открой позицию, чтобы выбрать конкретный тип задачи.</p><div class="actions"><a class="btn primary" href="#foundation">Дроби → проценты → пропорции</a><a class="btn" href="#diagnostic">Определить пробелы</a><a class="btn" href="#exam">Пробная работа · 21 задание</a><a class="btn" href="../work-rate/index.html">Землекопы</a></div><label>Найти тему <input id="search" type="search" placeholder="Например: скидка, логарифм, трапеция"></label><p class="muted">'+D.meta.length+' тематических тренажёра. Это авторские семейства задач, а не полный открытый банк ФИПИ.</p><div id="cards" class="cards"></div>';
 const cards=q=>{$('#cards').innerHTML=positionNames.map((name,i)=>{const items=D.meta.filter(m=>m.pos===i+1&&(!q||(m.title+' '+m.idea+' '+m.pos).toLowerCase().includes(q.toLowerCase())));if(!items.length)return '';return `<section class="card"><span class="badge">Задание ${i+1}</span><h2>${name}</h2><details ${q?'open':''}><summary>${items.length} типов задач — выбрать</summary><ul class="trainer-list">${items.map(m=>{const l=state.lessons[m.id];return `<li><a href="#lesson=${m.id}">${E(m.title)}</a>${l?`<small>Самостоятельно: ${l.independent||0}; разборов: ${l.guided||0}</small>`:''}</li>`;}).join('')}</ul></details></section>`;}).join('')||'<p>Ничего не найдено. Попробуй «дроби», «площадь» или номер задания.</p>';};cards('');$('#search').oninput=e=>cards(e.target.value);
}
function foundation(){
 root.innerHTML='<a href="#map">← Все тренажёры</a><p class="eyebrow">Общий маршрут для школьной математики и ЕГЭ</p><h1>Дроби. Проценты. Пропорции.</h1><p class="lead">Начни с первого непонятного шага. Если умеешь решать без подсказок, переходи дальше. Завершение разбора — подготовка, самостоятельное новое решение — отдельный результат.</p><ol class="foundation-route">'+D.practice.foundation.map(id=>{let m=D.meta.find(x=>x.id===id),l=state.lessons[id];return `<li><h2><a href="#lesson=${id}">${E(m.title)}</a></h2><p>${E(m.idea)}</p><span>${l?`Самостоятельно: ${l.independent||0}. Разборов: ${l.guided||0}.`:'Ещё не открывали.'}</span></li>`;}).join('')+'</ol><div class="actions"><a class="btn" href="../algebra/index.html#base">Базовые действия</a><a class="btn" href="../percent/index.html">Лаборатория процентов</a><a class="btn primary" href="#report">Мои результаты</a></div>';
}
function support(t,omitVisual=false){return window.PathPracticeView?PathPracticeView.markup(t,omitVisual):'';}
function remediationId(meta){if(!meta.expanded)return meta.id;return ({fractions:'fractions',fraction:'share',decimals:'fractions',percent:'choice',change:'percent',proportion:'ratio',division:'ratio',equations:'equations',powers:'powers',signs:'numberline'})[meta.gap]||meta.id;}
function equationPracticeLinks(id){if(id!=='equations'&&!D.equationPractice?.has(id))return '';return `<section class="panel equation-practice-menu"><h2>Потренироваться на похожих уравнениях</h2><p>Четыре набора по 240 разных условий. Выбери один тип: новые варианты останутся линейными уравнениями этого типа.</p><div class="actions">${D.equationPractice.families.map(m=>`<a class="btn ${id===m.id?'primary':''}" href="#lesson=${m.id}" ${id===m.id?'aria-current="page"':''}>${E(m.title)}</a>`).join('')}</div>${D.equationPractice.has(id)?'<p>Кнопки «Ещё по шагам» и «Другие числа» дают новое условие выбранного типа. После 240 показанных условий начнутся повторы; они не добавляют новых самостоятельных успехов.</p>':''}</section>`;}
function showLesson(id){const meta=D.meta.find(m=>m.id===id);if(!meta)return map();let l=lesson(id),t=D.task(id,l.seed);if(l.step>t.steps.length)l.step=0;document.title=meta.title+' · ЕГЭ база';const source=`<p class="source">Связь: базовый ЕГЭ, позиция ${meta.pos}. Задача авторская. <a href="../sources/index.html#p${meta.pos}">Что сверено с ФИПИ</a>.</p>`;
root.innerHTML=`<a href="#map">← Все темы</a><p class="eyebrow">Задание ${meta.pos}</p><h1>${E(meta.title)}</h1><label>Тип задачи в этой позиции <select id="typeSelect">${D.meta.filter(m=>m.pos===meta.pos).map(m=>`<option value="${m.id}" ${m.id===id?'selected':''}>${E(m.title)}</option>`).join('')}</select></label><nav class="stage-nav" aria-label="Шаги урока">${stageLabels.map((s,i)=>`<button data-stage="${i}" ${i===l.stage?'aria-current="step"':''}>${i+1}. ${s}</button>`).join('')}</nav><div id="lesson"></div>${equationPracticeLinks(id)}${id==='motion'?'<p class="callout">Ещё один вид текстовых задач: <a href="../work-rate/index.html">землекопы и совместная работа без уравнений</a>.</p>':''}${source}`;
$('#typeSelect').onchange=e=>setHash('lesson='+e.target.value);root.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{let n=+b.dataset.stage;if(n===3&&l.stage!==3){fresh(id,3);return;}l.stage=n;if(n<3){l.help=true;expose(t);}save();render();});let box=$('#lesson');
if(l.stage===0){expose(t);box.innerHTML=`<section class="panel"><h2>Главная идея</h2><p class="lead">${E(meta.idea)}</p><div class="callout"><b>Перед вычислением спроси себя</b><p>${(id==='equations'||D.equationPractice?.has(id))?'Что именно я переношу: слагаемое или множитель? Почему равенство останется верным?':'Что дано, что неизвестно и какая связь между ними? Какие единицы нужны в ответе?'}</p></div><p class="task">${E(t.q)}</p>${support(t)}<button class="primary" id="next">Исследовать модель →</button></section>`;$('#next').onclick=()=>{l.stage=1;save();render();};}
if(l.stage===1){expose(t);l.help=true;box.innerHTML=`<section class="panel"><p class="task">${E(t.q)}</p>${support(t,t.model.kind==='polygon-build')}${t.model.expansion?`<p class="callout">${E(t.model.expansion)}</p>`:''}<div id="model"></div><button id="next" class="primary">Перейти к решению →</button></section>`;PathModels.mount($('#model'),t);$('#next').onclick=()=>{l.stage=2;save();render();};}
if(l.stage===2){expose(t);box.innerHTML=`<section class="panel"><p class="task">${E(t.q)}</p>${support(t)}<ol class="steps">${t.steps.slice(0,l.step).map(s=>`<li>${E(s.q)} <b>${E(s.a===undefined?'Условия выполнены':D.answerText(s))}</b><br>${E(s.why)}</li>`).join('')}</ol>${l.step<t.steps.length?`<div class="callout"><b>Шаг ${l.step+1}/${t.steps.length}</b><p>${E(t.steps[l.step].q)}</p></div>${answerForm(t)}<button id="hint">Подсказать смысл шага</button><p id="hintText"></p>`:'<h2>Разбор завершён</h2><p>Теперь реши новый вариант, выбрав способ самостоятельно.</p><button id="new" class="primary">Новый самостоятельный вариант</button>'}${(id==='equations'||D.equationPractice?.has(id))?'<button id="moreGuided">Ещё по шагам: похожее уравнение</button>':''}<p id="feedback" class="feedback" role="status"></p><details id="gap"><summary>Мешает пробел в основе?</summary><p>Откройте нужный навык; эта вкладка сохраняет текущий шаг. После тренировки вернитесь сюда.</p><a class="btn" href="#foundation">Маршрут: дроби, проценты, пропорции</a><a class="btn" target="_blank" rel="noopener" href="../algebra/index.html">Знаки, дроби и действия</a> <a class="btn" target="_blank" rel="noopener" href="../percent/index.html">Проценты и пропорции</a></details></section>`;if($('#answerForm')){$('#answer').value=l.draft||'';$('#answer').oninput=e=>{l.draft=e.target.value.slice(0,10000);save();};$('#answerForm').onsubmit=e=>{e.preventDefault();if(!$('#answer').value.trim())return feedback('Сначала введи ответ.',true);let s=t.steps[l.step];if(D.correct(s,$('#answer').value)){l.step++;l.draft='';if(l.step===t.steps.length)l.guided=(l.guided||0)+1;save();render();$('#answer')?.focus();}else{l.help=true;save();feedback('Проверь именно этот шаг. '+s.why,true);EgeRemediation.show({id:remediationId(meta),value:$('#answer').value,expected:s.a});}};$('#hint').onclick=()=>{l.help=true;$('#hintText').textContent=t.steps[l.step].why;save();};}else $('#new').onclick=()=>fresh(id);if($('#moreGuided'))$('#moreGuided').onclick=()=>{const target=id==='equations'?'equations-linear':id;if(target!==id)setHash('lesson='+target);fresh(target,2);};$('#gap').ontoggle=()=>{if($('#gap').open){l.help=true;save();}};}
if(l.stage===3){box.innerHTML=`<section class="panel"><span class="badge">Новый вариант · без открытого разбора</span><p class="task">${E(t.q)}</p>${support(t)}${answerForm(t)}<p id="feedback" class="feedback" role="status"></p><div class="actions"><button id="explain">Разобрать этот вариант</button><button id="new">Другие числа</button><button id="next">Объяснить своими словами →</button></div><p class="muted">Засчитывается первая верная попытка без подсказки на ранее не показанном условии. Повтор и исправление полезны, но отмечаются отдельно.</p></section>`;$('#answer').value=l.draft||'';$('#answer').oninput=e=>{l.draft=e.target.value.slice(0,10000);save();};$('#answerForm').onsubmit=e=>{e.preventDefault();const v=$('#answer').value;if(!v.trim())return feedback('Сначала введи ответ.',true);if(l.done)return feedback('Этот вариант уже проверен. Возьми другие числа.');const ok=D.correct(t,v),clean=!l.attempted&&!l.help&&!seen(t);l.attempted=true;expose(t);if(ok){l.done=true;if(clean)l.independent=(l.independent||0)+1;l.checks=(l.checks||[]).concat({seed:l.seed,correct:true,independent:clean}).slice(-100);feedback(clean?'Верно с первой попытки на новом варианте.':'Верно после помощи, повторного показа или исправления.');}else{l.help=true;feedback('Пока неверно. Проверь знак, единицы и то, что спрашивается. Можно разобрать этот вариант по шагам.',true);EgeRemediation.show({id:remediationId(meta),value:v,expected:t.answer});}save();};$('#explain').onclick=()=>{l.help=true;l.stage=2;expose(t);save();render();};$('#new').onclick=()=>fresh(id);$('#next').onclick=()=>{l.stage=4;save();render();};}
if(l.stage===4){box.innerHTML=`<section class="panel"><h2>Объясни ход мысли</h2><p>Какую связь ты использовал? Почему действие допустимо? Как можно проверить ответ другим способом?</p><textarea id="note" placeholder="Я выбрал(а)… потому что… Проверил(а)…">${E(l.note||'')}</textarea><p class="muted">Текст сохранится для обсуждения с преподавателем. Автоматическая проверка не оценивает качество объяснения.</p><div class="actions"><a class="btn" href="#report">Мой отчёт</a><a class="btn primary" href="#lesson=${nextLesson(id)}">Следующая тема →</a></div></section>`;$('#note').oninput=e=>{l.note=e.target.value.slice(0,10000);save();};}save();}
function nextLesson(id){const list=D.practice.foundation;if(list.includes(id)&&list.indexOf(id)<list.length-1)return list[list.indexOf(id)+1];return D.meta[(D.meta.findIndex(m=>m.id===id)+1)%D.meta.length].id;}
function answerForm(t){return '<form id="answerForm"><label for="answer">Твой ответ</label><div class="actions"><input id="answer" maxlength="10000" autocomplete="off" placeholder="'+(t?.answerKind==='match'?'Четыре цифры, например 2413':t?.answerKind==='multi'?'Номера, например 134':t?.answerKind==='solutions'?'Любое подходящее число':'Число или дробь, например 2/3')+'"><button class="primary" type="submit">Проверить</button></div></form>';}
function examPool(pos){return PathExamPool.select(D.meta,pos);}
function startRun(kind){if(state.active&&state.active.kind!==kind){root.innerHTML='<h1>Есть незавершённая проверка</h1><p>Сначала завершите её или сохраните как прерванную.</p><button id="resume">Продолжить</button> <button id="finish">Завершить с текущими ответами</button>';$('#resume').onclick=()=>setHash(state.active.kind);$('#finish').onclick=()=>finishRun(true);return;}if(!state.active){root.innerHTML=`<h1>${kind==='exam'?'Пробная работа':'Найдём точку старта'}</h1><p>21 авторская задача, по одной на позицию. Можно пропускать. Ответы и разбор появятся после завершения. Эта выборка не охватывает все подтипы экзамена.</p><p>${kind==='exam'?'Ориентир — 180 минут. Часы не отправляют работу автоматически.':'Время не ограничено. Диагностика нужна для выбора темы, а не для отметки.'}</p><button id="start" class="primary">Начать</button>`;$('#start').onclick=()=>{state.active={kind,seed:state.serial++,ids:Array.from({length:21},(_,i)=>examPool(i+1)[state.serial%examPool(i+1).length].id),i:0,answers:[],start:Date.now(),assisted:false};save();render();};return;}const r=state.active;if(r.i>=21)return finishRun(false);let id=r.ids[r.i],t=D.task(id,r.seed+r.i);root.innerHTML=`<p class="eyebrow">${r.kind==='exam'?'Пробная работа':'Диагностика'} · ${r.i+1}/21</p><div class="meter"><span style="width:${r.i/21*100}%"></span></div><section class="panel"><p class="task">${E(t.q)}</p>${support(t)}${answerForm(t)}<p id="feedback" role="status"></p><div class="actions"><button id="skip">Пока не знаю</button><button id="finish">Завершить сейчас</button></div><p class="muted">Прошло ${Math.floor((Date.now()-r.start)/60000)} мин. Открытие обучения во время проверки будет отмечено как помощь.</p></section>`;$('#answer').value=r.draft||'';$('#answer').oninput=e=>{r.draft=e.target.value.slice(0,10000);save();};const next=skip=>{let v=skip?'':$('#answer').value;if(!skip&&!v.trim())return feedback('Введите ответ или выберите «Пока не знаю».',true);r.answers.push({id,seed:r.seed+r.i,value:v,correct:!skip&&D.correct(t,v),previouslySeen:seen(t)});expose(t);r.draft='';r.i++;save();render();};$('#answerForm').onsubmit=e=>{e.preventDefault();next(false);};$('#skip').onclick=()=>next(true);$('#finish').onclick=()=>finishRun(true);}
function finishRun(interrupted){let r=state.active;if(!r)return;while(r.answers.length<21){let i=r.answers.length;r.answers.push({id:r.ids[i],seed:r.seed+i,value:'',correct:false,skipped:true});}r.finished=Date.now();r.interrupted=interrupted;state.runs.push(r);state.runs=state.runs.slice(-200);state.active=null;save();setHash('report');}
function report(){let latest=state.runs.at(-1),wrong=latest?.answers.filter(x=>!x.correct)||[];root.innerHTML=`<h1>Что уже получается</h1><p>Подсказки, исправления и ранее показанные условия учитываются отдельно. Отчёт не означает полного освоения позиции экзамена.</p>${latest?`<section class="panel"><h2>Последняя ${latest.kind==='exam'?'пробная работа':'диагностика'}: ${latest.answers.filter(x=>x.correct).length}/21</h2><p>${latest.interrupted?'Завершена досрочно. ':''}${latest.assisted?'С обращением к обучению. ':''}${latest.answers.some(x=>x.previouslySeen)?'Часть условий была показана раньше.':''}</p>${wrong.length?`<div class="callout"><b>Следующий шаг</b><p>Начни с темы «${E(D.meta.find(m=>m.id===wrong[0].id).title)}».</p><a class="btn primary" href="#lesson=${wrong[0].id}">Разобраться в первой трудности</a></div>`:'<p>Эта выборка решена. Попробуй новые варианты и вернись к темам через день.</p>'}<details><summary>Ответы и объяснения</summary><ol>${latest.answers.map(a=>{let t=D.task(a.id,a.seed),last=t.steps.at(-1);return `<li><b>${a.correct?'Верно':'Повторить'} · ${E(D.meta.find(m=>m.id===a.id).title)}</b><p>${E(t.q)}</p><p>Ваш ответ: ${E(a.value||'пропуск')}. ${t.rule||t.answerKind==='solutions'?'Возможны разные ответы; проверяются все условия.':'Ответ: '+E(D.answerText(t))+'.'} ${E(last.why)}</p><a href="#lesson=${a.id}">Урок</a></li>`;}).join('')}</ol></details></section>`:''}<div class="scroll"><table><thead><tr><th>Тема</th><th>Разборов</th><th>Новых самостоятельных</th></tr></thead><tbody>${D.meta.map(m=>{let l=state.lessons[m.id]||{};return `<tr><td><a href="#lesson=${m.id}">${m.pos}. ${E(m.title)}</a></td><td>${l.guided||0}</td><td>${l.independent||0}</td></tr>`;}).join('')}</tbody></table></div><div class="actions"><button id="export">Скачать работу и резервную копию</button><label>Восстановить свою копию <input type="file" id="import" accept="application/json"></label></div><p id="feedback" role="status"></p><p class="muted">Восстановление заменяет только данные этого нового маршрута. Старые модули, тренажёры и их ключи не затрагиваются.</p>`;$('#export').onclick=()=>download(state);$('#import').onchange=async e=>{try{let f=e.target.files[0];if(!f||f.size>2000000)throw Error();let x=JSON.parse(await f.text());if(!valid(x))throw Error();download(state,'before-import.json');state=x;writable=true;save();report();feedback('Копия восстановлена; предыдущая работа выгружена отдельным файлом.');}catch(e){feedback('Файл не подходит. Текущая работа не изменена.',true);}};}
function download(x,name='EGE_baza_work.json'){let u=URL.createObjectURL(new Blob([JSON.stringify(x,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function render(){let h=location.hash.slice(1)||'map';if(state.active&&!['exam','diagnostic','report'].includes(h)){state.active.assisted=true;save();}if(h.startsWith('lesson='))showLesson(h.slice(7));else if(h==='diagnostic'||h==='exam')startRun(h);else if(h==='report')report();else if(h==='foundation')foundation();else map();}
window.addEventListener('hashchange',()=>{render();root.focus({preventScroll:true});});window.addEventListener('pagehide',save);window.PathCourse={state:()=>state,valid,KEY};render();})();
