(function(){'use strict';const D=PathData,$=s=>document.querySelector(s),root=$('#main'),KEY='mathexam.ege-baza.path.v1',E=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let writable=true,state={version:1,serial:11,lessons:{},seen:{},runs:[],active:null};
const integer=(n,max=1e9)=>Number.isSafeInteger(n)&&n>=0&&n<=max;
const answerOK=a=>a&&D.meta.some(m=>m.id===a.id)&&integer(a.seed)&&typeof a.value==='string'&&a.value.length<10000&&typeof a.correct==='boolean';
const runOK=r=>r&&['exam','diagnostic'].includes(r.kind)&&Array.isArray(r.ids)&&r.ids.length===21&&r.ids.every(id=>D.meta.some(l=>l.id===id))&&Array.isArray(r.answers)&&r.answers.length<=21&&r.answers.every(answerOK)&&integer(r.seed)&&integer(r.i,21)&&Number.isFinite(r.start);
function valid(x){return x&&x.version===1&&integer(x.serial)&&x.lessons&&typeof x.lessons==='object'&&!Array.isArray(x.lessons)&&x.seen&&typeof x.seen==='object'&&!Array.isArray(x.seen)&&Object.keys(x.seen).length<20000&&Object.values(x.seen).every(v=>v===true)&&Array.isArray(x.runs)&&x.runs.length<=200&&x.runs.every(runOK)&&Object.entries(x.lessons).every(([k,l])=>D.meta.some(m=>m.id===k)&&l&&integer(l.seed)&&integer(l.stage,4)&&integer(l.step,20)&&integer(l.independent)&&integer(l.guided)&&typeof l.note==='string'&&l.note.length<=10000&&typeof l.draft==='string'&&l.draft.length<=10000&&typeof l.help==='boolean'&&typeof l.attempted==='boolean'&&Array.isArray(l.checks))&&(!x.active||runOK(x.active));}

try{let raw=localStorage.getItem(KEY);if(raw){let x=JSON.parse(raw);if(!valid(x))throw Error();state=x;}}catch(e){writable=false;notice('Сохранение недоступно или повреждено. Исходные данные оставлены без изменений. Текущую работу можно скачать.');}
function notice(t){$('#storage').hidden=false;$('#storage').textContent=t;}
function save(){if(!writable)return;try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){writable=false;notice('Не удалось сохранить работу в браузере. Скачайте отчёт и резервную копию.');}}
function lesson(id){return state.lessons[id]||(state.lessons[id]={seed:id==='equations'?10:state.serial++,stage:0,step:0,help:false,attempted:false,independent:0,guided:0,note:'',draft:'',checks:[]});}
function setHash(s){location.hash=s;}
function feedback(s,bad=false){let f=$('#feedback');if(f){f.textContent=s;f.className='feedback '+(bad?'bad':'good');}}
function seen(t){return !!state.seen[t.q];}function expose(t){state.seen[t.q]=true;}
const stageLabels=['Понять','Исследовать','Решить по шагам','Самостоятельно','Объяснить'];
function fresh(id,stage=3){const l=lesson(id);l.seed=state.serial++;l.stage=stage;l.step=0;l.help=false;l.attempted=false;l.draft='';l.done=false;save();render();}
function map(){root.innerHTML='<p class="eyebrow">От понятного действия к экзамену</p><h1>Разобраться. Попробовать.<br>Решить самостоятельно.</h1><p class="lead">Выберите тему или начните с короткой проверки: она подскажет следующий урок. Можно ошибаться, возвращаться к основе и продолжать с того же шага.</p><div class="actions"><a class="btn primary" href="#diagnostic">Определить пробелы</a><a class="btn" href="#exam">Пробная работа · 21 задание</a></div><label>Найти тему <input id="search" type="search" placeholder="Например: проценты, уравнения"></label><div class="cards" id="cards"></div>';const cards=q=>{$('#cards').innerHTML=D.meta.filter(m=>(m.title+' '+m.pos).toLowerCase().includes(q.toLowerCase())).map(m=>{let l=state.lessons[m.id];return `<article class="card"><span class="badge">Задание ${m.pos}</span><h2>${E(m.title)}</h2><p>${E(m.idea)}</p><p class="muted">${l?`Самостоятельно: ${l.independent||0}. Разборов: ${l.guided||0}.`:'Можно начать с любой темы.'}</p><a class="btn" href="#lesson=${m.id}">${l?'Продолжить':'Начать'}</a></article>`;}).join('');};cards('');$('#search').oninput=e=>cards(e.target.value);}
function showLesson(id){const meta=D.meta.find(m=>m.id===id);if(!meta)return map();let l=lesson(id),t=D.task(id,l.seed);if(l.step>t.steps.length)l.step=0;document.title=meta.title+' · ЕГЭ база';const source=`<p class="source">Связь: базовый ЕГЭ, позиция ${meta.pos}. Задача авторская. <a href="../sources/index.html#p${meta.pos}">Что сверено с ФИПИ</a>.</p>`;
root.innerHTML=`<a href="#map">← Все темы</a><p class="eyebrow">Задание ${meta.pos}</p><h1>${E(meta.title)}</h1><nav class="stage-nav" aria-label="Шаги урока">${stageLabels.map((s,i)=>`<button data-stage="${i}" ${i===l.stage?'aria-current="step"':''}>${i+1}. ${s}</button>`).join('')}</nav><div id="lesson"></div>${source}`;
root.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{let n=+b.dataset.stage;if(n===3&&l.stage!==3){fresh(id,3);return;}l.stage=n;if(n<3){l.help=true;expose(t);}save();render();});let box=$('#lesson');
if(l.stage===0){expose(t);box.innerHTML=`<section class="panel"><h2>Главная идея</h2><p class="lead">${E(meta.idea)}</p><div class="callout"><b>Перед вычислением спроси себя</b><p>${id==='equations'?'Что именно я переношу: слагаемое или множитель? Почему равенство останется верным?':'Что дано, что неизвестно и какая связь между ними? Какие единицы нужны в ответе?'}</p></div><p class="task">${E(t.q)}</p><button class="primary" id="next">Исследовать модель →</button></section>`;$('#next').onclick=()=>{l.stage=1;save();render();};}
if(l.stage===1){expose(t);l.help=true;box.innerHTML=`<section class="panel"><p class="task">${E(t.q)}</p><div id="model"></div><button id="next" class="primary">Перейти к решению →</button></section>`;PathModels.mount($('#model'),t);$('#next').onclick=()=>{l.stage=2;save();render();};}
if(l.stage===2){expose(t);box.innerHTML=`<section class="panel"><p class="task">${E(t.q)}</p><ol class="steps">${t.steps.slice(0,l.step).map(s=>`<li>${E(s.q)} <b>${E(s.a===undefined?'Условия выполнены':D.F(s.a))}</b><br>${E(s.why)}</li>`).join('')}</ol>${l.step<t.steps.length?`<div class="callout"><b>Шаг ${l.step+1}/${t.steps.length}</b><p>${E(t.steps[l.step].q)}</p></div>${answerForm()}<button id="hint">Подсказать смысл шага</button><p id="hintText"></p>`:'<h2>Разбор завершён</h2><p>Теперь реши новый вариант, выбрав способ самостоятельно.</p><button id="new" class="primary">Новый самостоятельный вариант</button>'}<p id="feedback" class="feedback" role="status"></p><details id="gap"><summary>Мешает пробел в основе?</summary><p>Откройте нужный навык; эта вкладка сохраняет текущий шаг. После тренировки вернитесь сюда.</p><a class="btn" target="_blank" rel="noopener" href="../algebra/index.html">Знаки, дроби и действия</a> <a class="btn" target="_blank" rel="noopener" href="../percent/index.html">Проценты и пропорции</a></details></section>`;if($('#answerForm')){$('#answer').value=l.draft||'';$('#answer').oninput=e=>{l.draft=e.target.value;save();};$('#answerForm').onsubmit=e=>{e.preventDefault();if(!$('#answer').value.trim())return feedback('Сначала введи ответ.',true);let s=t.steps[l.step];if(D.correct(s,$('#answer').value)){l.step++;l.draft='';if(l.step===t.steps.length)l.guided=(l.guided||0)+1;save();render();}else{l.help=true;save();feedback('Проверь именно этот шаг. '+s.why,true);}};$('#hint').onclick=()=>{l.help=true;$('#hintText').textContent=t.steps[l.step].why;save();};}else $('#new').onclick=()=>fresh(id);$('#gap').ontoggle=()=>{if($('#gap').open){l.help=true;save();}};}
if(l.stage===3){box.innerHTML=`<section class="panel"><span class="badge">Новый вариант · без открытого разбора</span><p class="task">${E(t.q)}</p>${answerForm()}<p id="feedback" class="feedback" role="status"></p><div class="actions"><button id="explain">Разобрать этот вариант</button><button id="new">Другие числа</button><button id="next">Объяснить своими словами →</button></div><p class="muted">Засчитывается первая верная попытка без подсказки на ранее не показанном условии. Повтор и исправление полезны, но отмечаются отдельно.</p></section>`;$('#answer').value=l.draft||'';$('#answer').oninput=e=>{l.draft=e.target.value;save();};$('#answerForm').onsubmit=e=>{e.preventDefault();const v=$('#answer').value;if(!v.trim())return feedback('Сначала введи ответ.',true);if(l.done)return feedback('Этот вариант уже проверен. Возьми другие числа.');const ok=D.correct(t,v),clean=!l.attempted&&!l.help&&!seen(t);l.attempted=true;expose(t);if(ok){l.done=true;if(clean)l.independent=(l.independent||0)+1;l.checks=(l.checks||[]).concat({seed:l.seed,correct:true,independent:clean}).slice(-100);feedback(clean?'Верно с первой попытки на новом варианте.':'Верно после помощи, повторного показа или исправления.');}else{l.help=true;feedback('Пока неверно. Проверь знак, единицы и то, что спрашивается. Можно разобрать этот вариант по шагам.',true);}save();};$('#explain').onclick=()=>{l.help=true;l.stage=2;expose(t);save();render();};$('#new').onclick=()=>fresh(id);$('#next').onclick=()=>{l.stage=4;save();render();};}
if(l.stage===4){box.innerHTML=`<section class="panel"><h2>Объясни ход мысли</h2><p>Какую связь ты использовал? Почему действие допустимо? Как можно проверить ответ другим способом?</p><textarea id="note" placeholder="Я выбрал(а)… потому что… Проверил(а)…">${E(l.note||'')}</textarea><p class="muted">Текст сохранится для обсуждения с преподавателем. Автоматическая проверка не оценивает качество объяснения.</p><div class="actions"><a class="btn" href="#report">Мой отчёт</a><a class="btn primary" href="#lesson=${D.meta[(D.meta.indexOf(meta)+1)%D.meta.length].id}">Следующая тема →</a></div></section>`;$('#note').oninput=e=>{l.note=e.target.value.slice(0,10000);save();};}save();}
function answerForm(){return '<form id="answerForm"><label for="answer">Твой ответ</label><div class="actions"><input id="answer" autocomplete="off" placeholder="Число или дробь, например 2/3"><button class="primary" type="submit">Проверить</button></div></form>';}
function startRun(kind){if(state.active&&state.active.kind!==kind){root.innerHTML='<h1>Есть незавершённая проверка</h1><p>Сначала завершите её или сохраните как прерванную.</p><button id="resume">Продолжить</button> <button id="finish">Завершить с текущими ответами</button>';$('#resume').onclick=()=>setHash(state.active.kind);$('#finish').onclick=()=>finishRun(true);return;}if(!state.active){root.innerHTML=`<h1>${kind==='exam'?'Пробная работа':'Найдём точку старта'}</h1><p>21 авторская задача, по одной на позицию. Можно пропускать. Ответы и разбор появятся после завершения. Эта выборка не охватывает все подтипы экзамена.</p><p>${kind==='exam'?'Ориентир — 180 минут. Часы не отправляют работу автоматически.':'Время не ограничено. Диагностика нужна для выбора темы, а не для отметки.'}</p><button id="start" class="primary">Начать</button>`;$('#start').onclick=()=>{state.active={kind,seed:state.serial++,ids:Array.from({length:21},(_,i)=>D.meta.filter(m=>m.pos===i+1)[state.serial%D.meta.filter(m=>m.pos===i+1).length].id),i:0,answers:[],start:Date.now(),assisted:false};save();render();};return;}const r=state.active;if(r.i>=21)return finishRun(false);let id=r.ids[r.i],t=D.task(id,r.seed+r.i);root.innerHTML=`<p class="eyebrow">${r.kind==='exam'?'Пробная работа':'Диагностика'} · ${r.i+1}/21</p><div class="meter"><span style="width:${r.i/21*100}%"></span></div><section class="panel"><p class="task">${E(t.q)}</p>${answerForm()}<p id="feedback" role="status"></p><div class="actions"><button id="skip">Пока не знаю</button><button id="finish">Завершить сейчас</button></div><p class="muted">Прошло ${Math.floor((Date.now()-r.start)/60000)} мин. Открытие обучения во время проверки будет отмечено как помощь.</p></section>`;const next=skip=>{let v=skip?'':$('#answer').value;if(!skip&&!v.trim())return feedback('Введите ответ или выберите «Пока не знаю».',true);r.answers.push({id,seed:r.seed+r.i,value:v,correct:!skip&&D.correct(t,v),previouslySeen:seen(t)});expose(t);r.i++;save();render();};$('#answerForm').onsubmit=e=>{e.preventDefault();next(false);};$('#skip').onclick=()=>next(true);$('#finish').onclick=()=>finishRun(true);}
function finishRun(interrupted){let r=state.active;if(!r)return;while(r.answers.length<21){let i=r.answers.length;r.answers.push({id:r.ids[i],seed:r.seed+i,value:'',correct:false,skipped:true});}r.finished=Date.now();r.interrupted=interrupted;state.runs.push(r);state.runs=state.runs.slice(-200);state.active=null;save();setHash('report');}
function report(){let latest=state.runs.at(-1),wrong=latest?.answers.filter(x=>!x.correct)||[];root.innerHTML=`<h1>Что уже получается</h1><p>Подсказки, исправления и ранее показанные условия учитываются отдельно. Отчёт не означает полного освоения позиции экзамена.</p>${latest?`<section class="panel"><h2>Последняя ${latest.kind==='exam'?'пробная работа':'диагностика'}: ${latest.answers.filter(x=>x.correct).length}/21</h2><p>${latest.interrupted?'Завершена досрочно. ':''}${latest.assisted?'С обращением к обучению. ':''}${latest.answers.some(x=>x.previouslySeen)?'Часть условий была показана раньше.':''}</p>${wrong.length?`<div class="callout"><b>Следующий шаг</b><p>Начни с темы «${E(D.meta.find(m=>m.id===wrong[0].id).title)}».</p><a class="btn primary" href="#lesson=${wrong[0].id}">Разобраться в первой трудности</a></div>`:'<p>Эта выборка решена. Попробуй новые варианты и вернись к темам через день.</p>'}<details><summary>Ответы и объяснения</summary><ol>${latest.answers.map(a=>{let t=D.task(a.id,a.seed),last=t.steps.at(-1);return `<li><b>${a.correct?'Верно':'Повторить'} · ${E(D.meta.find(m=>m.id===a.id).title)}</b><p>${E(t.q)}</p><p>Ваш ответ: ${E(a.value||'пропуск')}. ${t.rule?'Возможны разные ответы; проверяются все условия.':'Ответ: '+E(D.F(t.answer))+'.'} ${E(last.why)}</p><a href="#lesson=${a.id}">Урок</a></li>`;}).join('')}</ol></details></section>`:''}<div class="scroll"><table><thead><tr><th>Тема</th><th>Разборов</th><th>Новых самостоятельных</th></tr></thead><tbody>${D.meta.map(m=>{let l=state.lessons[m.id]||{};return `<tr><td><a href="#lesson=${m.id}">${m.pos}. ${E(m.title)}</a></td><td>${l.guided||0}</td><td>${l.independent||0}</td></tr>`;}).join('')}</tbody></table></div><div class="actions"><button id="export">Скачать работу и резервную копию</button><label>Восстановить свою копию <input type="file" id="import" accept="application/json"></label></div><p id="feedback" role="status"></p><p class="muted">Восстановление заменяет только данные этого нового маршрута. Старые модули, тренажёры и их ключи не затрагиваются.</p>`;$('#export').onclick=()=>download(state);$('#import').onchange=async e=>{try{let f=e.target.files[0];if(!f||f.size>2000000)throw Error();let x=JSON.parse(await f.text());if(!valid(x))throw Error();download(state,'before-import.json');state=x;writable=true;save();report();feedback('Копия восстановлена; предыдущая работа выгружена отдельным файлом.');}catch(e){feedback('Файл не подходит. Текущая работа не изменена.',true);}};}
function download(x,name='EGE_baza_work.json'){let u=URL.createObjectURL(new Blob([JSON.stringify(x,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function render(){let h=location.hash.slice(1)||'map';if(state.active&&!['exam','diagnostic','report'].includes(h)){state.active.assisted=true;save();}if(h.startsWith('lesson='))showLesson(h.slice(7));else if(h==='diagnostic'||h==='exam')startRun(h);else if(h==='report')report();else map();}
window.addEventListener('hashchange',()=>{render();root.focus({preventScroll:true});});window.addEventListener('pagehide',save);window.PathCourse={state:()=>state,valid,KEY};render();})();
