(function(root){'use strict';
const E=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const F=PathData.F;
function table(headers,rows,caption='Данные задачи'){
 return `<div class="scroll"><table class="task-table"><caption>${E(caption)}</caption><thead><tr>${headers.map(h=>`<th scope="col">${E(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((v,i)=>i?`<td>${E(v)}</td>`:`<th scope="row">${E(v)}</th>`).join('')}</tr>`).join('')}</tbody></table></div>`;
}
function chart(d){
 const lo=Math.min(0,...d.values),hi=Math.max(1,...d.values),span=hi-lo||1,n=d.values.length;
 const X=i=>65+i*460/Math.max(1,n-1),Y=v=>255-(v-lo)/span*205;
 let g='';for(let i=0;i<=4;i++){let v=lo+span*i/4,y=Y(v);g+=`<path d="M48 ${y}H552" stroke="#dbe5dd"/><text x="42" y="${y+5}" text-anchor="end">${E(F(v))}</text>`;}
 if(d.kind==='bars')g+=d.values.map((v,i)=>`<rect x="${X(i)-18}" y="${Math.min(Y(v),Y(0))}" width="36" height="${Math.abs(Y(0)-Y(v))||1}" fill="#216e56"/><text x="${X(i)}" y="${Y(v)-10}" text-anchor="middle">${E(F(v))}</text>`).join('');
 else g+=`<polyline points="${d.values.map((v,i)=>X(i)+','+Y(v)).join(' ')}" fill="none" stroke="#216e56" stroke-width="4"/>`+d.values.map((v,i)=>`<circle cx="${X(i)}" cy="${Y(v)}" r="5" fill="#9d472b"/>`).join('');
 g+=d.labels.map((s,i)=>`<text x="${X(i)}" y="285" text-anchor="middle">${E(s)}</text>`).join('');
 return `<svg class="task-figure" viewBox="0 0 600 310" role="img" aria-label="${E(d.yLabel)}: график с точными данными в таблице ниже"><text x="50" y="25">${E(d.yLabel)}</text>${g}</svg><details class="equivalent-data"><summary>Точные значения графика в таблице</summary>${table(['Отметка',d.yLabel],d.labels.map((s,i)=>[s,F(d.values[i])]))}</details>`;
}
function polygon(d,construction=false){
 const xs=d.points.map(p=>p[0]),ys=d.points.map(p=>p[1]),w=Math.max(...xs),h=Math.max(...ys),scale=Math.min(450/(w||1),230/(h||1)),X=x=>60+x*scale,Y=y=>280-y*scale;let grid='';
 if(d.grid){for(let x=0;x<=w;x++)grid+=`<path d="M${X(x)} ${Y(0)}V${Y(h)}"/>`;for(let y=0;y<=h;y++)grid+=`<path d="M${X(0)} ${Y(y)}H${X(w)}"/>`;}
 return `<svg class="task-figure" viewBox="0 0 600 330" role="img" aria-label="Фигура на единичной сетке; координаты вершин приведены под рисунком"><g stroke="#c9d9ce" stroke-width="1">${grid}</g><polygon points="${d.points.map(([x,y])=>X(x)+','+Y(y)).join(' ')}" fill="#6caa8870" stroke="#185940" stroke-width="3"/>${construction?`<path d="M${X(0)} ${Y(0)}H${X(w)}V${Y(h)}H${X(0)}Z" fill="none" stroke="#a44629" stroke-width="3" stroke-dasharray="6"/>`:''}${d.points.map(([x,y],i)=>`<circle cx="${X(x)}" cy="${Y(y)}" r="4" fill="#185940"/><text x="${X(x)+8}" y="${Y(y)-9}">${'ABCDEF'[i]}</text>`).join('')}<text x="60" y="318">Сторона клетки = 1</text></svg><details><summary>Координаты вершин по порядку</summary><p>${d.points.map(([x,y],i)=>`${'ABCDEF'[i]}(${x}; ${y})`).join(', ')}</p></details>`;
}
function numberline(d){const lo=Math.floor(Math.min(...d.values))-1,hi=Math.ceil(Math.max(...d.values))+1,X=v=>45+(v-lo)/(hi-lo)*510;let s='';for(let n=lo;n<=hi;n++)s+=`<path d="M${X(n)} 110v12" stroke="#617a6b"/><text x="${X(n)}" y="150" text-anchor="middle">${n}</text>`;return `<svg class="task-figure" viewBox="0 0 600 180" role="img" aria-label="Точки расположены слева направо; интервалы приведены ниже"><path d="M30 116H565" stroke="#617a6b"/>${s}${d.values.map((v,i)=>`<circle cx="${X(v)}" cy="116" r="5" fill="#a44629"/><text x="${X(v)}" y="88" text-anchor="middle">${E(d.names[i])}</text>`).join('')}</svg><p class="muted">${d.values.map((v,i)=>`${d.names[i]}: ${Number.isInteger(v)?'ровно '+v:'между '+Math.floor(v)+' и '+Math.ceil(v)}`).join('; ')}.</p>`;}
function visual(t){const d=t.display;if(!d)return '';if(d.kind==='table')return table(d.headers,d.rows);if(['bars','graph'].includes(d.kind))return chart(d);if(d.kind==='polygon')return polygon(d);if(d.kind==='numberline')return numberline(d);if(d.kind==='triangle-label')return `<svg class="task-figure" viewBox="0 0 600 320" role="img" aria-label="Прямоугольный треугольник ABC, прямой угол при C"><path d="M70 255H510L70 45Z" fill="#d5e9da" stroke="#216e56" stroke-width="3"/><path d="M70 235H90V255" fill="none" stroke="#216e56"/><text x="46" y="270">C</text><text x="517" y="265">A</text><text x="51" y="36">B</text><text x="270" y="285">${d.a}</text><text x="28" y="160">${d.b}</text><text x="300" y="140">${d.c}</text></svg><p class="muted">Чертёж схематический; размеры берём из условия.</p>`;return '';}
function markup(t,omitVisual=false){return `<div class="task-support">${omitVisual?'':visual(t)}${t.labels?`<ol class="match-labels" type="A">${t.labels.map(x=>`<li>${E(x)}</li>`).join('')}</ol>`:''}${t.choices?`<ol class="task-choices">${t.choices.map(x=>`<li>${E(x)}</li>`).join('')}</ol>`:''}</div>`;}
const previous=PathModels.mount;
PathModels.mount=function(el,t){const m=t.model;
 if(m.kind==='fraction-bars'){
  const [num,den]=m.fractions[0];let selected=new Set();el.innerHTML=`<p>Построй ${num}/${den} одного целого. Выбирай доли кнопками — мышью, касанием или клавишей пробела.</p><div class="fraction-builder">${Array.from({length:den},(_,i)=>`<button aria-label="Доля ${i+1} из ${den}" aria-pressed="false" data-share="${i}">${i+1}</button>`).join('')}</div><button id="checkShares">Проверить модель</button><p id="modelFeedback" role="status"></p><p>Знаменатель сообщает, на сколько равных частей разделено целое. Числитель — сколько таких частей взято.</p>`;
  el.querySelectorAll('[data-share]').forEach(b=>b.onclick=()=>{let n=+b.dataset.share;selected.has(n)?selected.delete(n):selected.add(n);b.setAttribute('aria-pressed',String(selected.has(n)));});el.querySelector('#checkShares').onclick=()=>el.querySelector('#modelFeedback').textContent=selected.size===num?`Построено верно: ${num} из ${den} равных долей.`:`Выбрано ${selected.size} долей. Нужно ${num}; размер одной доли остаётся 1/${den}.`;return;
 }
 if(m.kind==='percent-base'){
  const part=m.whole*m.p/100;el.innerHTML=`<p>В этой модели ${m.p}% — это ${F(part)}. Какое число принимаем за 100%?</p><div class="actions"><button data-base="part">${F(part)}</button><button data-base="whole">${m.whole}</button></div><p id="baseFeedback" role="status"></p><div id="percentExperiment"></div>`;
  el.querySelectorAll('[data-base]').forEach(b=>b.onclick=()=>{const ok=b.dataset.base==='whole';el.querySelector('#baseFeedback').textContent=ok?'Верно: всё количество — 100%. Часть сравниваем с этим целым.':'Это только часть. Вопрос: каково всё количество, от которого взяты проценты?';if(ok){el.querySelector('#percentExperiment').innerHTML=`<label>Процент <input id="percentSlide" type="range" min="0" max="100" value="${m.p}" step="1"></label><div class="percent-bar"><span></span></div><p id="percentRead" aria-live="polite"></p>`;const draw=()=>{let p=+el.querySelector('#percentSlide').value;el.querySelector('.percent-bar span').style.width=p+'%';el.querySelector('#percentRead').textContent=`${p}% от ${m.whole} = ${F(m.whole*p/100)}. Целое остаётся тем же.`;};el.querySelector('#percentSlide').oninput=draw;draw();}});return;
 }
 if(m.kind==='ratio-parts'){
  const n=m.a+m.b;el.innerHTML=`<p>Собери отношение ${m.a}:${m.b}. Первой группе нужны ${m.a} равных долей, второй — ${m.b}. Все ${n} долей составляют ${m.total}.</p><div class="fraction-builder">${Array.from({length:n},(_,i)=>`<button data-ratio="${i}" aria-pressed="false">${i+1}</button>`).join('')}</div><button id="checkRatio">Проверить первую группу</button><p id="ratioRead" role="status"></p>`;let chosen=new Set();el.querySelectorAll('[data-ratio]').forEach(b=>b.onclick=()=>{let x=+b.dataset.ratio;chosen.has(x)?chosen.delete(x):chosen.add(x);b.setAttribute('aria-pressed',String(chosen.has(x)));});el.querySelector('#checkRatio').onclick=()=>el.querySelector('#ratioRead').textContent=chosen.size===m.a?`Первая группа ${m.a}/${n} целого. Одна доля — ${F(m.total/n)}. Теперь вычисли вторую группу.`:`Выбрано ${chosen.size}. Первой группе нужны ${m.a} долей из ${n}, а не из ${m.b}.`;return;
 }
 if(m.kind==='polygon-build'){
  el.innerHTML='<p>Выбери вспомогательное построение, которое помогает найти площадь.</p><div class="actions"><button id="auxRect">Достроить до прямоугольника</button><button id="auxDiagonal">Провести произвольную диагональ</button></div><div id="construction"></div><p id="constructionRead" role="status"></p>';
  el.querySelector('#construction').innerHTML=polygon(t.display);el.querySelector('#auxRect').onclick=()=>{el.querySelector('#construction').innerHTML=polygon(t.display,true);el.querySelector('#constructionRead').textContent='Теперь можно вычесть лишние части. У параллелограмма их можно перенести, сохранив основание и высоту. Найди нужные длины по клеткам.';};el.querySelector('#auxDiagonal').onclick=()=>el.querySelector('#constructionRead').textContent='Диагональ разделяет фигуру, но площади получившихся частей ещё нужно найти. Попробуй построение по линиям сетки.';return;
 }
 if(m.kind==='interval-signs'){
  let a=m.a,b=m.b;el.innerHTML=`<p>Проверь точки на промежутках и сами границы. Знаменатель x−${b} не может равняться нулю.</p><label>Проверяемая точка <input id="testPoint" type="range" min="${a-3}" max="${b+3}" step="0.5" value="${a}"></label><p id="pointRead" role="status"></p>`;const draw=()=>{let x=+el.querySelector('#testPoint').value,p=(x-a)*(x-b);el.querySelector('#pointRead').textContent=`x=${F(x)}. (x−${a})(x−${b}) ${p<0?'отрицательно':p>0?'положительно':'равно нулю'}. Дробь (x−${a})/(x−${b}) ${x===b?'не определена':(x-a)/(x-b)>0?'положительна':(x-a)/(x-b)<0?'отрицательна':'равна нулю'}.`;};el.querySelector('#testPoint').oninput=draw;draw();return;
 }
 if(m.kind==='digit-work'){
  el.innerHTML=`<p>Собери четырёхзначное число и проверь все условия.</p><div class="digit-row">${Array.from({length:4},(_,i)=>`<label>Цифра ${i+1}<select data-place="${i}">${Array.from({length:10},(_,n)=>`<option>${n}</option>`).join('')}</select></label>`).join('')}</div><button id="checkDigits">Проверить число</button><p id="digitRead" role="status"></p>`;el.querySelector('#checkDigits').onclick=()=>{let s=[...el.querySelectorAll('select')].map(x=>x.value).join(''),sum=[...s].reduce((a,x)=>a+Number(x),0),product=[...s].reduce((a,x)=>a*Number(x),1);el.querySelector('#digitRead').textContent=`${s}: сумма цифр ${sum}, произведение ${product}. ${s[0]==='0'?'Запись начинается с нуля, это не четырёхзначное число.':PathData.correct(t,s)?'Все условия выполнены. Возможны и другие ответы.':'Проверь делимость и ограничения на цифры.'}`;};return;
 }
 if(m.kind==='data-read'&&t.display){
  let d=t.display;el.innerHTML='<p>Выбери строку или отметку, чтобы прочитать её отдельно.</p><div class="actions" id="dataSelect"></div><p id="dataRead" role="status"></p>';
  let labels=d.kind==='table'?d.rows.map(r=>r[0]):d.labels||d.names;el.querySelector('#dataSelect').innerHTML=labels.map((v,i)=>`<button data-item="${i}">${E(v)}</button>`).join('');el.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{let i=+b.dataset.item;el.querySelector('#dataRead').textContent=d.kind==='table'?d.headers.map((h,j)=>h+': '+d.rows[i][j]).join('; '):labels[i]+': '+F(d.values[i]);});return;
 }
 if(m.kind==='statements'){el.innerHTML='<p>Для каждого утверждения попробуй построить контрпример. Если хотя бы один пример удовлетворяет условию и опровергает утверждение, оно не обязательно верно.</p>'+t.choices.map((s,i)=>`<details><summary>Проверяем: ${E(s)}</summary><p>${E(t.steps[i].why)}</p><p>${t.steps[i].a?'Следует из условия.':'Не обязательно верно. В условии недостаточно такой связи.'}</p></details>`).join('');return;}
 previous(el,t);
};
root.PathPracticeView={markup,visual,polygon};
})(window);
