(function(){
'use strict';
const C=window.SovietMath,B=window.SovietBoard,$=id=>document.getElementById(id),KEY='mathExam.sovietMath.v1';
const renderMode=new URLSearchParams(location.search).has('render');
const defaults=()=>window.SovietProgress.defaults(!matchMedia('(prefers-reduced-motion: reduce)').matches);
let state=defaults(),original=null,saveBlocked=false,topic=null,mode='learn',plan=null,camera='overview',animation=0;
function notice(s){$('notice').textContent=s;$('notice').hidden=false;}
if(!renderMode){try{original=localStorage.getItem(KEY);if(original){const loaded=window.SovietProgress.readState(JSON.parse(original));state=loaded.state;if(loaded.migrated)notice('Разборы обновлены. Прежние результаты сохранены; обновлённый пример начнём с начала.');}}catch(e){saveBlocked=true;notice('Сохранённая запись не открылась. Она оставлена без изменений. Сейчас можно заниматься без сохранения и скачать результат.');}}
function save(){if(renderMode||saveBlocked)return;try{if(localStorage.getItem(KEY)!==original){saveBlocked=true;notice('Работа изменилась в другой вкладке. Чтобы сохранить её, обнови эту страницу. Текущий результат можно скачать.');return;}original=JSON.stringify(state);localStorage.setItem(KEY,original);}catch(e){saveBlocked=true;notice('Браузер не смог сохранить работу. Результат можно скачать до закрытия страницы.');}}
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function independent(r){return !r.errors&&!r.help&&!r.repeated;}
function renderCatalog(){
 $('topic-count').textContent=C.topics.length;$('video-count').textContent=C.topics.length;$('topics').replaceChildren();$('stage-nav').replaceChildren();
 C.stages.forEach((stage,j)=>{const a=el('a',(j+1)+'. '+stage.title);a.href='#stage-'+stage.id;$('stage-nav').append(a);const sec=el('section',undefined,'stage');sec.id='stage-'+stage.id;const head=el('div',undefined,'stage-head');head.append(el('span',String(j+1).padStart(2,'0'),'stage-number'));const title=el('div');title.append(el('h2',stage.title),el('p',stage.note));head.append(title);sec.append(head);const grid=el('div',undefined,'topic-grid');
 C.topics.filter(t=>t.stage===stage.id).forEach(t=>{const i=C.topics.indexOf(t),card=el('article',undefined,'topic-card'),num=el('div',String(i+1).padStart(2,'0'),'number');const count=state.records.filter(r=>r.topic===t.id&&independent(r)).length;if(count)num.append(el('span',count+' самостоятельно','badge'));const h=el('h3'),link=el('a',t.title);link.href='#'+t.id;h.append(link);const go=el('div',undefined,'go'),open=el('a','Открыть →');open.href='#'+t.id;go.append(open,el('span','Тренажёр + видео','badge'));card.append(num,h,el('p',t.description),go);grid.append(card);});sec.append(grid);$('topics').append(sec);});
 if(state.lastTopic){$('resume').href='#'+state.lastTopic;$('resume').hidden=false;}renderReport();
}
function renderReport(){const box=$('report-summary');box.replaceChildren();if(!state.records.length){box.append(el('p','Пока нет завершённых самостоятельных попыток. Разборы и видео не начисляют результат.'));return;}C.topics.forEach(t=>{const rows=state.records.filter(r=>r.topic===t.id);if(!rows.length)return;const row=el('div',undefined,'report-row');row.append(el('b',t.title),el('span',rows.filter(independent).length+' новых без помощи · '+rows.length+' попыток'));box.append(row);});}
function session(){return state.sessions[topic.id+':'+mode];}
function newSession(id,m,index){const s={topic:id,mode:m,index,step:0,accepted:false,done:false,draft:'',errors:0,help:0,hint:false};state.sessions[id+':'+m]=s;return s;}
function hideFeedback(){$('feedback').textContent='';$('feedback').className='';}
function showFeedback(text,error=false){$('feedback').textContent=text;$('feedback').className=error?'error':'';}
function recordPlan(r){return(r.revision===1?C.legacyMake:C.make)(r.topic,r.index);}
function identity(p){if(p.kind==='division'){const t=p.division.task;return JSON.stringify({division:[C.number(t.dividend),C.number(t.divisor),t.level]});}return JSON.stringify({prompt:p.prompt,visual:p.visual});}
function isRepeat(s){if(s.mode!=='practice')return false;const rows=state.records.filter(r=>r.topic===s.topic);if(s.done)return rows.slice().reverse().find(r=>r.index===s.index)?.repeated||false;const current=identity(C.make(s.topic,s.index));return rows.some(r=>identity(recordPlan(r))===current);}
function finishRecord(s){if(s.mode!=='practice')return;const current=identity(plan);state.records.push({revision:C.revision,topic:s.topic,index:s.index,at:Date.now(),errors:s.errors,help:s.help,repeated:state.records.some(r=>r.topic===s.topic&&identity(recordPlan(r))===current)});}
function renderSource(){const source=window.SovietSources.forTopic(topic.id),box=$('lesson-source');box.replaceChildren();const link=el('a',source.authors+'. Арифметика · '+source.grade+' · '+source.year+' г.');link.href=source.url;link.title=source.bookTitle;link.target='_blank';link.rel='noopener';box.append(link,el('span',source.section+(source.pages?' · с. '+source.pages:'')),el('small',source.exerciseNote));}
function renderFrame(progress=1,transition=1){if(!plan||mode==='video')return;const s=session(),completed=s.step+(s.accepted?1:0);B.draw($('board'),plan,completed,{title:topic.title,source:window.SovietSources.forTopic(topic.id).label,activeStep:s.step,reveal:!!s.hint,camera,progress,transition,reducedMotion:!state.motion});const areas=B.layout||{main:{x:480,y:180,w:768,h:564},helper:{x:32,y:180,w:424,h:564}};for(const key of ['main','helper']){const dest=$('mobile-'+key),r=areas[key];dest.width=r.w;dest.height=r.h;dest.getContext('2d').drawImage($('board'),r.x,r.y,r.w,r.h,0,0,r.w,r.h);}}
function animate(){cancelAnimationFrame(animation);if(!state.motion){renderFrame(1,1);return;}const start=performance.now();const tick=now=>{const p=Math.min(1,(now-start)/2400);renderFrame(p,p);if(p<1)animation=requestAnimationFrame(tick);};animation=requestAnimationFrame(tick);}
function renderWork(){
 if(mode==='video')return;const s=session();plan=C.make(topic.id,s.index);$('lesson-idea').hidden=mode!=='learn'||!plan.introduction;$('lesson-idea').textContent=plan.introduction||'';$('problem').textContent=plan.prompt;$('text-problem').textContent=plan.prompt;$('mode-label').textContent=mode==='learn'?'Разберём вместе':'Тренировка · пример '+s.index;$('step-counter').textContent='Шаг '+(s.step+1)+' из '+plan.steps.length;$('work-status').textContent=mode==='learn'?'Разбор с помощью':s.help?'С помощью':s.errors?'С исправлениями':isRepeat(s)?'Повторение':'Самостоятельно';
 const a=plan.steps[s.step];$('question').textContent=s.done?'Пример разобран':a.prompt;$('answer').value=s.draft;$('answer').disabled=s.accepted;$('check').hidden=s.accepted;$('continue').hidden=!s.accepted||s.done;$('answer-form').hidden=s.done||mode==='learn';$('hint').hidden=s.done||mode==='learn';$('reveal').hidden=s.done||(mode==='learn'&&s.accepted);$('reveal').textContent=mode==='learn'?'Посмотреть объяснение':'Показать этот шаг';$('hint').disabled=s.accepted;$('reveal').disabled=s.accepted;$('hint-text').hidden=!s.hint||s.done;$('hint-text').textContent=a.hint||'';$('step-explanation').hidden=mode!=='learn'||!s.accepted;$('step-explanation').textContent=a.explanation||a.hint||a.record;$('learn-next').hidden=mode!=='learn'||!s.accepted||s.done;$('answer').inputMode=a.raw?.options||String(a.answer).includes('/')?'text':'decimal';
 const opts=$('answer-options');opts.replaceChildren();opts.hidden=!a.raw?.options||s.accepted;if(a.raw?.options)for(const op of a.raw.options){const b=el('button',op.label);b.type='button';b.className='light';b.addEventListener('click',()=>{$('answer').value=op.value;s.draft=op.value;save();$('answer').focus();});opts.append(b);}
 $('finish').hidden=!s.done;if(s.done){$('finish-text').textContent=mode==='learn'?'Все шаги остаются на доске. Теперь попробуй другой пример самостоятельно.':s.help?'Пример решён с помощью. Для проверки навыка попробуй новое условие.':s.errors?'Ошибки исправлены. Теперь попробуй другой пример без ошибок.':isRepeat(s)?'Повтор выполнен без ошибок и подсказок. Он отмечен как повторение; для нового результата выбери другой пример.':'Все шаги выполнены без ошибок и подсказок.';}
 $('solution-log').replaceChildren();plan.steps.slice(0,s.step+(s.accepted?1:0)).forEach(a=>$('solution-log').append(el('li',a.record||a.prompt+' Ответ: '+a.answer)));$('motion').checked=state.motion;$('overview').setAttribute('aria-pressed',camera==='overview');$('detail').setAttribute('aria-pressed',camera==='detail');renderFrame(0);renderReport();
}
function setMode(m){cancelAnimationFrame(animation);$('video').pause();mode=m;for(const name of ['learn','practice','video'])$('mode-'+name).classList.toggle('selected',name===m);$('video-area').hidden=m!=='video';$('practice-area').hidden=m==='video';hideFeedback();if(m==='video'){const path='media/'+topic.id+'.mp4';if(!$('video').getAttribute('src')?.endsWith(path)){$('video').src=path;$('video').load();}$('download-video').href=path;$('video-error').hidden=true;return;}state.lastMode=m;if(!session())newSession(topic.id,m,m==='learn'?0:1);save();renderWork();}
function openTopic(id){topic=C.topics.find(t=>t.id===id);if(!topic)return;state.lastTopic=id;save();$('catalog').hidden=true;$('lesson').hidden=false;$('lesson-title').textContent=topic.title;$('lesson-description').textContent=topic.description;$('stage-title').textContent=C.stages.find(s=>s.id===topic.stage).title;$('lesson-position').textContent=(C.topics.indexOf(topic)+1)+' / '+C.topics.length;$('board-link').href='../trainers/trainer-board.html?trainer='+encodeURIComponent('/soviet-math/index.html#'+id);const next=C.topics[C.topics.indexOf(topic)+1];$('next-topic').href=next?'#'+next.id:'#';$('next-topic').textContent=next?'Следующая тема →':'Вернуться к темам';setMode(state.lastMode||'learn');document.title=topic.title+' · Математика по советским учебникам';}
function route(){let hash;try{hash=decodeURIComponent(location.hash.slice(1));}catch(e){hash='unknown';}if(!hash||hash.startsWith('stage-')){cancelAnimationFrame(animation);$('video').pause();$('catalog').hidden=false;$('lesson').hidden=true;renderCatalog();document.title='Математика по советским учебникам · MathExam';if(hash)requestAnimationFrame(()=>document.getElementById(hash)?.scrollIntoView());return;}if(!C.topics.some(t=>t.id===hash)){notice('Такой темы пока нет. Выбери тему из списка.');history.replaceState(null,'',location.pathname);route();return;}openTopic(hash);renderSource();}
$('answer-form').addEventListener('submit',e=>{e.preventDefault();if(mode==='video')return;const s=session();if(s.accepted)return;s.draft=$('answer').value;if(!s.draft.trim()){showFeedback('Введи ответ на этот шаг.',true);return;}if(!C.check(s.draft,plan.steps[s.step])){s.errors++;save();showFeedback('Пока не сходится. Проверь этот шаг; уже выполненное решение осталось на доске.',true);return;}s.accepted=true;s.done=s.step===plan.steps.length-1;if(s.done)finishRecord(s);save();renderWork();showFeedback(s.done?'Готово. Все действия можно перечитать на доске.':'Верно. Запись добавлена к решению.');animate();if(!s.done)$('continue').focus();});
$('answer').addEventListener('input',()=>{if(mode==='video')return;session().draft=$('answer').value;save();});
function continueStep(){const s=session();if(!s.accepted||s.done)return;s.step++;s.accepted=false;s.draft='';s.hint=false;save();hideFeedback();renderWork();if(mode==='practice')$('answer').focus({preventScroll:true});else $('reveal').focus({preventScroll:true});}
$('continue').addEventListener('click',continueStep);$('learn-next').addEventListener('click',continueStep);
$('hint').addEventListener('click',()=>{const s=session();if(!s.hint){s.help++;s.hint=true;save();}renderWork();animate();});
$('reveal').addEventListener('click',()=>{const s=session();if(s.accepted)return;s.help++;s.hint=true;s.accepted=true;s.draft=String(plan.steps[s.step].answer);s.done=s.step===plan.steps.length-1;if(s.done)finishRecord(s);save();renderWork();showFeedback(mode==='learn'?'':'Посмотри, как этот шаг связан с предыдущими.');animate();if(mode==='learn')$(s.done?'new-task':'learn-next').focus({preventScroll:true});});
function another(){const old=state.sessions[topic.id+':practice'];newSession(topic.id,'practice',old?old.index+1:1);setMode('practice');}
$('new-task').addEventListener('click',another);$('after-video').addEventListener('click',another);$('same-example').addEventListener('click',()=>{newSession(topic.id,'learn',0);setMode('learn');});$('repeat').addEventListener('click',()=>{const s=session();newSession(topic.id,mode,s.index);save();hideFeedback();renderWork();});
for(const m of ['learn','practice','video'])$('mode-'+m).addEventListener('click',()=>setMode(m));
$('overview').addEventListener('click',()=>{camera='overview';cancelAnimationFrame(animation);renderWork();});$('detail').addEventListener('click',()=>{camera='detail';renderWork();animate();});$('motion').addEventListener('change',()=>{state.motion=$('motion').checked;save();animate();});$('video').addEventListener('error',()=>{$('video-error').hidden=false;});
$('export-report').addEventListener('click',()=>{const text=['Математика по советским учебникам','Результаты в текущем браузере',new Date().toLocaleDateString('ru-RU'),''].concat(C.topics.flatMap(t=>{const rr=state.records.filter(r=>r.topic===t.id);return rr.length?[t.title+': '+rr.filter(independent).length+' новых без ошибок и помощи; попыток '+rr.length]:[]})).join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=el('a');a.href=url;a.download='soviet-math-results.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
window.addEventListener('hashchange',()=>{route();if(!location.hash.startsWith('#stage-'))window.scrollTo(0,0);});document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(animation);$('video').pause();}});
window.__soviet={state:()=>JSON.parse(JSON.stringify(state)),plan:()=>plan,render:(id,count,options={})=>{const t=C.topics.find(t=>t.id===id);B.draw($('board'),C.make(id,0),count,{title:t.title,reveal:true,...options});},key:KEY};
if(renderMode)document.body.classList.add('render-mode');renderCatalog();route();
})();
