/* One fixed, author-written example. Native MathML; local-only standalone
 * progress; the existing board bridge owns persistence in embedded mode. */
(function () {
'use strict';
const $ = id => document.getElementById(id);
const m = body => '<math xmlns="http://www.w3.org/1998/Math/MathML"><mrow>'+body+'</mrow></math>';
const x = '<mi>x</mi>', x2 = '<msup>'+x+'<mn>2</mn></msup>';
const n = value => '<mn>'+value+'</mn>', op = value => '<mo>'+value+'</mo>';
const row = value => '<mrow>'+value+'</mrow>';
const frac = (a,b) => '<mfrac>'+row(a)+row(b)+'</mfrac>';
const par = value => row(op('(')+value+op(')'));
const sqrt = value => '<msqrt>'+value+'</msqrt>';
const base = frac(n(25)+op('−')+x2,n(16));
const arg = frac(n(24)+op('+')+n(2)+x+op('−')+x2,n(14));
const log = (b,a) => '<msub><mi mathvariant="normal">log</mi>'+row(b)+'</msub>'+par(a);
const f = value => '<div class="formula">'+m(value)+'</div>';
const sys = rows => '<div class="formula system"><span class="system-brace" aria-hidden="true">{</span><div class="system-rows" aria-label="Система: все условия одновременно">'+rows.map(m).join('')+'</div></div>';
const domainRows = [base+op('>')+n(0),base+op('≠')+n(1),arg+op('>')+n(0)];
const solvedDomain = [n('−4')+op('<')+x+op('<')+n(5),x+op('≠')+n('−3')+op(',')+x+op('≠')+n(3)];
const product = par(x2+op('−')+n(9))+par(x2+op('−')+n(16)+x+op('−')+n(17))+op('>')+n(0);
const interval = (a,b) => op('(')+n(a)+op(';')+n(b)+op(')');
const answer = x+op('∈')+interval('−4','−3')+op('∪')+interval('−1','3');
const polySolution = interval('−∞','−3')+op('∪')+interval('−1','3')+op('∪')+interval('17','+∞');
const choice = (id,label,options,correct) => ({id,label,kind:'choice',options,correct});
const number = (id,label,correct) => ({id,label,kind:'number',correct:String(correct)});
const axis = (id,label,points,correct,refs=[]) => ({id,label,kind:'axis',points,correct,refs});
const option = (id,html) => ({id,html});
const steps = [
 {title:'Найдём основание и аргумент',phase:'Знакомимся с примером',body:'<p>У логарифма есть основание и аргумент. Выберите выражение для каждой подписи.</p>',fields:[choice('base','Основание логарифма',[option('base',m(base)),option('arg',m(arg))],'base'),choice('arg','Аргумент логарифма',[option('base',m(base)),option('arg',m(arg))],'arg')],hint:'Основание записано нижним индексом у знака log. Аргумент — выражение, от которого берётся логарифм.',record:'<p><span class="base-key">Основание:</span> '+m(base)+'</p><p><span class="arg-key">Аргумент:</span> '+m(arg)+'</p>'},
 {title:'Соберём систему ОДЗ',phase:'Находим ОДЗ',body:'<p>Отметьте <strong>три обязательных условия</strong>. Они должны выполняться одновременно.</p>',fields:[{id:'requirements',label:'Какие условия нужны?',kind:'checks',options:[option('base-positive',m(domainRows[0])),option('argument-one',m(arg+op('≠')+n(1))),option('base-nonunit',m(domainRows[1])),option('argument-positive',m(domainRows[2])),option('base-over-one',m(base+op('>')+n(1)))],correct:['base-positive','base-nonunit','argument-positive']}],hint:'Основание положительное и не равно 1. Аргумент положительный. Основание может быть меньше 1; аргументу равняться 1 можно.',record:sys(domainRows)+'<p>Это ОДЗ: значения, при которых логарифм определён.</p>'},
 {title:'Решим первую строку системы',phase:'Находим ОДЗ',body:'<p>Знаменатель 16 положительный. Умножаем на него, сохраняя знак:</p>'+f(base+op('>')+n(0)+op('⇔')+n(25)+op('−')+x2+op('>')+n(0))+'<p>Прибавляем '+m(x2)+' к обеим частям: получаем '+m(x2+op('<')+n(25))+'. Граничные значения — −5 и 5.</p>',fields:[axis('base-axis','Где квадрат числа меньше 25?',[-5,5],['s1'])],hint:'Например, 0 подходит: 0² < 25. Берём промежуток между −5 и 5. Сами концы не подходят: там квадрат равен 25.',record:f(n('−5')+op('<')+x+op('<')+n(5))},
 {title:'Исключим основание, равное единице',phase:'Находим ОДЗ',body:'<p>Во второй строке стоит знак ≠. Чтобы найти запрещённые значения, временно решим равенство:</p>'+f(base+op('=')+n(1)+op('⇔')+n(25)+op('−')+x2+op('=')+n(16))+f(x2+op('=')+n(9))+'<p>Какие два числа в квадрате дают 9?</p>',fields:[number('low','Меньшее запрещённое число',-3),number('high','Большее запрещённое число',3)],hint:'Это −3 и 3: (−3)² = 9 и 3² = 9. Оба значения исключаем.',record:f(x+op('≠')+n('−3')+op(',')+x+op('≠')+n(3))},
 {title:'Подготовим третью строку',phase:'Находим ОДЗ',body:'<p>Аргумент должен быть положительным. Умножаем на положительное число 14:</p>'+f(arg+op('>')+n(0)+op('⇔')+n(24)+op('+')+n(2)+x+op('−')+x2+op('>')+n(0))+'<p>Теперь умножаем обе части на −1. Меняем знаки <strong>всех слагаемых</strong> и знак неравенства.</p>',fields:[choice('quadratic','Что получится?',[option('wrong-sign',m(x2+op('−')+n(2)+x+op('−')+n(24)+op('>')+n(0))),option('correct',m(x2+op('−')+n(2)+x+op('−')+n(24)+op('<')+n(0))),option('wrong-term',m(x2+op('+')+n(2)+x+op('−')+n(24)+op('<')+n(0)))],'correct')],hint:'После умножения на −1 получаем −24 − 2x + x² < 0. Запишем слагаемые начиная с x².',record:f(x2+op('−')+n(2)+x+op('−')+n(24)+op('<')+n(0))},
 {title:'Найдём корни',phase:'Находим ОДЗ',body:'<p>Для метода интервалов решаем уравнение:</p>'+f(x2+op('−')+n(2)+x+op('−')+n(24)+op('=')+n(0))+'<p>Подставляем числа 1, −2 и −24 в формулу корней:</p>'+f(x+op('=')+frac(n(2)+op('±')+sqrt(n(4)+op('+')+n(96)),n(2)))+'<p>Сначала вычислите число под корнем. Затем найдите оба корня.</p>',fields:[number('discriminant','Число под корнем',100),number('low','Меньший корень',-4),number('high','Больший корень',6)],hint:'4 + 96 = 100; √100 = 10. (2 − 10) : 2 = −4; (2 + 10) : 2 = 6.',record:f(x+op('=')+frac(n(2)+op('±')+n(10),n(2)))+f(x+op('=')+n('−4')+op(';')+x+op('=')+n(6))},
 {title:'Решим третье неравенство',phase:'Находим ОДЗ',body:f(x2+op('−')+n(2)+x+op('−')+n(24)+op('<')+n(0))+'<p>Корни −4 и 6. Перед '+m(x2)+' стоит плюс. Трёхчлен отрицателен между корнями.</p>',fields:[axis('argument-axis','Отметьте решение. Нужен строгий знак <.',[-4,6],['s1'])],hint:'Берём только участок между −4 и 6. Концы оставляем пустыми, потому что в корнях трёхчлен равен нулю.',record:f(n('−4')+op('<')+x+op('<')+n(6))},
 {title:'Пересечём три условия ОДЗ',phase:'Находим ОДЗ',body:'<p>Все строки должны выполняться одновременно:</p>'+sys([n('−5')+op('<')+x+op('<')+n(5),x+op('≠')+n('−3')+op(',')+x+op('≠')+n(3),n('−4')+op('<')+x+op('<')+n(6)])+'<p>Сверху показаны три решения. На нижней оси соберите <strong>их общую часть</strong>.</p>',fields:[axis('domain-axis','Общая часть — ОДЗ',[-5,-4,-3,3,5,6],['s2','s3','s4'],[{label:'−5 < x < 5',tokens:['s1','s2','s3','s4','p1','p2','p3']},{label:'x ≠ −3, x ≠ 3',tokens:['s0','s1','s2','s3','s4','s5','s6','p0','p1','p4','p5']},{label:'−4 < x < 6',tokens:['s2','s3','s4','s5','p2','p3','p4']}])],hint:'Оба промежутка пересекаются от −4 до 5. Внутри исключаем −3 и 3. Выберите три участка: (−4; −3), (−3; 3), (3; 5). Все отмеченные концы пустые.',record:sys(solvedDomain)+'<p>ОДЗ найдено. Это ещё не ответ: теперь решаем само неравенство.</p>'},
 {title:'Заменим единицу логарифмом',phase:'Преобразуем неравенство',body:'<p>Вернёмся к исходному неравенству:</p>'+f(log(base,arg)+op('>')+n(1))+'<p>Логарифм от своего основания равен 1. Чем заполним место аргумента справа?</p>'+f(n(1)+op('=')+log(base,'<mtext>?</mtext>')),fields:[choice('unit','Выберите аргумент',[option('one',m(n(1))),option('same-base',m(base)),option('same-arg',m(arg))],'same-base')],hint:'Основание и аргумент этого нового логарифма должны совпасть. Тогда его значение равно 1.',record:f(log(base,arg)+op('>')+log(base,base))},
 {title:'Перейдём к произведению',phase:'Преобразуем неравенство',body:'<p>На ОДЗ можно сравнить два аргумента, учитывая основание. Если основание больше 1, знак сохраняется; если между 0 и 1 — меняется.</p><p>Это объединяет одно правило: <strong>«основание минус 1» × «первый аргумент минус второй» &gt; 0</strong>.</p><p>Выберите верную запись. Это равносильное неравенство на ОДЗ, а не равенство значений выражений.</p>',fields:[choice('rational','Какое произведение нужно?',[
 option('reverse',m(par(base+op('−')+n(1))+par(base+op('−')+arg)+op('>')+n(0))),
 option('correct',m(par(base+op('−')+n(1))+par(arg+op('−')+base)+op('>')+n(0))),
 option('argument-factor',m(par(arg+op('−')+n(1))+par(arg+op('−')+base)+op('>')+n(0)))],'correct')],hint:'В первой скобке вычитаем 1 из основания. Во второй вычитаем второй аргумент из первого: дробь со знаменателем 14 минус дробь со знаменателем 16.',record:f(par(base+op('−')+n(1))+par(arg+op('−')+base)+op('>')+n(0))},
 {title:'Упростим первую скобку',phase:'Преобразуем неравенство',body:'<p>Записываем единицу как дробь со знаменателем 16:</p>'+f(base+op('−')+n(1)+op('=')+base+op('−')+frac(n(16),n(16))+op('=')+frac(n(25)+op('−')+x2+op('−')+n(16),n(16)))+'<p>Вычислите 25 − 16.</p>',fields:[number('constant','Какое число останется перед −x²?',9)],hint:'25 − 16 = 9. Числитель станет 9 − x².',record:f(base+op('−')+n(1)+op('=')+frac(n(9)+op('−')+x2,n(16)))},
 {title:'Приведём вторую скобку к одному знаменателю',phase:'Преобразуем неравенство',body:f(arg+op('−')+base)+'<p>Знаменатели — 14 и 16. Найдите наименьший общий знаменатель и дополнительные множители.</p>',fields:[number('denominator','Общий знаменатель',112),number('first','На что умножаем 14?',8),number('second','На что умножаем 16?',7)],hint:'14 × 8 = 112 и 16 × 7 = 112. На те же числа умножаем соответствующие числители.',record:f(frac(n(8)+par(n(24)+op('+')+n(2)+x+op('−')+x2)+op('−')+n(7)+par(n(25)+op('−')+x2),n(112)))},
 {title:'Раскроем скобки и приведём подобные',phase:'Преобразуем неравенство',body:'<p>Работаем с числителем:</p>'+f(n(8)+par(n(24)+op('+')+n(2)+x+op('−')+x2)+op('−')+n(7)+par(n(25)+op('−')+x2))+f(n(192)+op('+')+n(16)+x+op('−')+n(8)+x2+op('−')+n(175)+op('+')+n(7)+x2)+'<p>У '+m(x2)+' получаем −8 + 7 = −1; у '+m(x)+' остаётся 16. Вычислите свободное число.</p>',fields:[number('coefficient','Коэффициент при x²: −8 + 7 =',-1),number('constant','192 − 175 =',17)],hint:'192 − 175 = 17. Значит, числитель равен −x² + 16x + 17. Обратите внимание: −7 × (−x²) даёт +7x².',record:f(arg+op('−')+base+op('=')+frac(op('−')+x2+op('+')+n(16)+x+op('+')+n(17),n(112)))},
 {title:'Уберём знаменатели и два минуса',phase:'Преобразуем неравенство',body:'<p>Подставим обе упрощённые скобки:</p>'+f(frac(n(9)+op('−')+x2,n(16))+op('·')+frac(op('−')+x2+op('+')+n(16)+x+op('+')+n(17),n(112))+op('>')+n(0))+'<p>Умножаем на положительное число 16 × 112. Затем выносим минус из <strong>каждой</strong> скобки:</p>'+f(n(9)+op('−')+x2+op('=')+op('−')+par(x2+op('−')+n(9)))+f(op('−')+x2+op('+')+n(16)+x+op('+')+n(17)+op('=')+op('−')+par(x2+op('−')+n(16)+x+op('−')+n(17)))+'<p>Два вынесенных минуса дают плюс. Какой знак останется?</p>',fields:[choice('sign','Знак между произведением и нулём',[option('lt','<strong>&lt; 0</strong>'),option('gt','<strong>&gt; 0</strong>'),option('ge','<strong>≥ 0</strong>')],'gt')],hint:'Знаменатели положительные, а два минуса дали плюс. Поэтому знак > сохраняется.',record:sys(solvedDomain.concat([product]))},
 {title:'Найдём все граничные точки',phase:'Метод интервалов и ответ',body:'<p>Первый множитель '+m(x2+op('−')+n(9))+' равен нулю при −3 и 3. Для второго решим:</p>'+f(x2+op('−')+n(16)+x+op('−')+n(17)+op('=')+n(0))+f(x+op('=')+frac(n(16)+op('±')+sqrt(n(256)+op('+')+n(68)),n(2)))+'<p>256 + 68 = 324; √324 = 18. Вычислите два корня второго множителя.</p>',fields:[number('low','Меньший корень',-1),number('high','Больший корень',17)],hint:'(16 − 18) : 2 = −1. (16 + 18) : 2 = 17. Всего четыре точки: −3, −1, 3, 17.',record:f(par(x+op('+')+n(3))+par(x+op('+')+n(1))+par(x+op('−')+n(3))+par(x+op('−')+n(17))+op('>')+n(0))},
 {title:'Определим знаки на пяти промежутках',phase:'Метод интервалов и ответ',body:'<p>Точки расставлены по порядку: −3, −1, 3, 17.</p>'+f(par(x+op('+')+n(3))+par(x+op('+')+n(1))+par(x+op('−')+n(3))+par(x+op('−')+n(17)))+'<p>Справа от 17 все множители положительные. При переходе через каждый корень один множитель меняет знак. Заполните знаки <strong>слева направо</strong>.</p>',fields:[['s0','Левее −3','plus'],['s1','Между −3 и −1','minus'],['s2','Между −1 и 3','plus'],['s3','Между 3 и 17','minus'],['s4','Правее 17','plus']].map(([id,label,correct])=>choice(id,label,[option('plus','+'),option('minus','−')],correct)),hint:'Начните справа: плюс. Двигайтесь влево и меняйте знак после каждой точки. Получится +, −, +, −, +.',record:'<p>Знаки слева направо: <strong>+ &nbsp; − &nbsp; + &nbsp; − &nbsp; +</strong>.</p>'},
 {title:'Выберем положительные промежутки',phase:'Метод интервалов и ответ',body:f(product)+'<p>Нужны все участки со знаком плюс. ОДЗ пока не пересекаем — это следующий шаг.</p>',fields:[axis('polynomial-axis','Где произведение больше нуля?',[-3,-1,3,17],['s0','s2','s4'])],hint:'Берём левее −3, между −1 и 3 и правее 17. Корни не включаем: в них произведение равно 0, а требуется > 0.',record:f(x+op('∈')+polySolution)},
 {title:'Пересечём решение с ОДЗ',phase:'Метод интервалов и ответ',body:'<p>Соберём всё в последнюю систему:</p>'+sys(solvedDomain.concat([x+op('∈')+polySolution]))+'<p>На нижней оси оставьте только числа, которые подходят <strong>и неравенству, и ОДЗ</strong>.</p>',fields:[axis('final-axis','Общая часть — окончательный ответ',[-4,-3,-1,3,5,17],['s1','s3'],[{label:'Решение неравенства',tokens:['s0','s1','s3','s6','p0']},{label:'ОДЗ',tokens:['s1','s2','s3','s4','p2']}])],hint:'Левый луч ограничивается точкой −4. Промежуток (−1; 3) остаётся целиком. Правее 17 нет значений из ОДЗ. Выберите (−4; −3) и (−1; 3), все концы оставьте пустыми.',record:f(answer)+'<p>−4, −3 и 3 запрещены ОДЗ. При −1 произведение равно нулю, поэтому это число тоже не входит в ответ.</p>'}
];
window.MathExamGuidedLesson={
 steps,
 problemHtml:m(log('<mstyle mathcolor="#2455ba">'+base+'</mstyle>','<mstyle mathcolor="#a84b13">'+arg+'</mstyle>')+op('>')+n(1)),
 answerHtml:m(answer),
 solvedDomainHtml:sys(solvedDomain),
 domainStepIndex:7,
 initialDomainHtml:sys(domainRows),
 initialDomainStepIndex:1,
 storageKey:'mathExam.logOneExample.v1',
 trainerId:'profile-log-one-example',
 apiName:'__logExample',
 title:'Логарифмическое неравенство · MathExam',
 reportName:'logarithm-result.txt',
 reportProblem:'log_((25−x²)/16)((24+2x−x²)/14) > 1',
 reportAnswer:'(−4; −3) ∪ (−1; 3)'
};
})();
