/* One fixed, author-written example. Native MathML; local-only standalone
 * progress; the existing board bridge owns persistence in embedded mode. */
(function () {
'use strict';
const $ = id => document.getElementById(id);
const m = body => '<math xmlns="http://www.w3.org/1998/Math/MathML"><mrow>'+body+'</mrow></math>';
const x = '<mi>x</mi>', x2 = '<msup>'+x+'<mn>2</mn></msup>';
const n = value => '<mn>'+value+'</mn>', op = value => '<mo>'+value+'</mo>';
const row = value => '<mrow>'+value+'</mrow>';
const frac = (a,b) => '<mfrac>'+row(a)+row(b)+'</mfrac>';
const par = value => row(op('(')+value+op(')'));
const sqrt = value => '<msqrt>'+value+'</msqrt>';
const base = frac(n(25)+op('−')+x2,n(16));
const arg = frac(n(24)+op('+')+n(2)+x+op('−')+x2,n(14));
const log = (b,a) => '<msub><mi mathvariant="normal">log</mi>'+row(b)+'</msub>'+par(a);
const f = value => '<div class="formula">'+m(value)+'</div>';
const sys = rows => '<div class="formula system"><span class="system-brace" aria-hidden="true">{</span><div class="system-rows" aria-label="Система: все условия одновременно">'+rows.map(m).join('')+'</div></div>';
const domainRows = [base+op('>')+n(0),base+op('≠')+n(1),arg+op('>')+n(0)];
const solvedDomain = [n('−4')+op('<')+x+op('<')+n(5),x+op('≠')+n('−3')+op(',')+x+op('≠')+n(3)];
const product = par(x2+op('−')+n(9))+par(x2+op('−')+n(16)+x+op('−')+n(17))+op('>')+n(0);
const interval = (a,b) => op('(')+n(a)+op(';')+n(b)+op(')');
const answer = x+op('∈')+interval('−4','−3')+op('∪')+interval('−1','3');
const polySolution = interval('−∞','−3')+op('∪')+interval('−1','3')+op('∪')+interval('17','+∞');
const choice = (id,label,options,correct) => ({id,label,kind:'choice',options,correct});
const number = (id,label,correct) => ({id,label,kind:'number',correct:String(correct)});
const axis = (id,label,points,correct,refs=[]) => ({id,label,kind:'axis',points,correct,refs});
const option = (id,html) => ({id,html});
const steps = [
 {title:'Найдём основание и аргумент',phase:'Знакомимся с примером',body:'<p>У логарифма есть основание и аргумент. Выберите выражение для каждой подписи.</p>',fields:[choice('base','Основание логарифма',[option('base',m(base)),option('arg',m(arg))],'base'),choice('arg','Аргумент логарифма',[option('base',m(base)),option('arg',m(arg))],'arg')],hint:'Основание записано нижним индексом у знака log. Аргумент — выражение, от которого берётся логарифм.',record:'<p><span class="base-key">Основание:</span> '+m(base)+'</p><p><span class="arg-key">Аргумент:</span> '+m(arg)+'</p>'},
 {title:'Соберём систему ОДЗ',phase:'Находим ОДЗ',body:'<p>Отметьте <strong>три обязательных условия</strong>. Они должны выполняться одновременно.</p>',fields:[{id:'requirements',label:'Какие условия нужны?',kind:'checks',options:[option('base-positive',m(domainRows[0])),option('argument-one',m(arg+op('≠')+n(1))),option('base-nonunit',m(domainRows[1])),option('argument-positive',m(domainRows[2])),option('base-over-one',m(base+op('>')+n(1)))],correct:['base-positive','base-nonunit','argument-positive']}],hint:'Основание положительное и не равно 1. Аргумент положительный. Основание может быть меньше 1; аргументу равняться 1 можно.',record:sys(domainRows)+'<p>Это ОДЗ: значения, при которых логарифм определён.</p>'},
 {title:'Решим первую строку системы',phase:'Находим ОДЗ',body:'<p>Знаменатель 16 положительный. Умножаем на него, сохраняя знак:</p>'+f(base+op('>')+n(0)+op('⇔')+n(25)+op('−')+x2+op('>')+n(0))+'<p>Прибавляем '+m(x2)+' к обеим частям: получаем '+m(x2+op('<')+n(25))+'. Граничные значения — −5 и 5.</p>',fields:[axis('base-axis','Где квадрат числа меньше 25?',[-5,5],['s1'])],hint:'Например, 0 подходит: 0² < 25. Берём промежуток между −5 и 5. Сами концы не подходят: там квадрат равен 25.',record:f(n('−5')+op('<')+x+op('<')+n(5))},
 {title:'Исключим основание, равное единице',phase:'Находим ОДЗ',body:'<p>Во второй строке стоит знак ≠. Чтобы найти запрещённые значения, временно решим равенство:</p>'+f(base+op('=')+n(1)+op('⇔')+n(25)+op('−')+x2+op('=')+n(16))+f(x2+op('=')+n(9))+'<p>Какие два числа в квадрате дают 9?</p>',fields:[number('low','Меньшее запрещённое число',-3),number('high','Большее запрещённое число',3)],hint:'Это −3 и 3: (−3)² = 9 и 3² = 9. Оба значения исключаем.',record:f(x+op('≠')+n('−3')+op(',')+x+op('≠')+n(3))},
 {title:'Подготовим третью строку',phase:'Находим ОДЗ',body:'<p>Аргумент должен быть положительным. Умножаем на положительное число 14:</p>'+f(arg+op('>')+n(0)+op('⇔')+n(24)+op('+')+n(2)+x+op('−')+x2+op('>')+n(0))+'<p>Теперь умножаем обе части на −1. Меняем знаки <strong>всех слагаемых</strong> и знак неравенства.</p>',fields:[choice('quadratic','Что получится?',[option('wrong-sign',m(x2+op('−')+n(2)+x+op('−')+n(24)+op('>')+n(0))),option('correct',m(x2+op('−')+n(2)+x+op('−')+n(24)+op('<')+n(0))),option('wrong-term',m(x2+op('+')+n(2)+x+op('−')+n(24)+op('<')+n(0)))],'correct')],hint:'После умножения на −1 получаем −24 − 2x + x² < 0. Запишем слагаемые начиная с x².',record:f(x2+op('−')+n(2)+x+op('−')+n(24)+op('<')+n(0))},
 {title:'Найдём корни',phase:'Находим ОДЗ',body:'<p>Для метода интервалов решаем уравнение:</p>'+f(x2+op('−')+n(2)+x+op('−')+n(24)+op('=')+n(0))+'<p>Подставляем числа 1, −2 и −24 в формулу корней:</p>'+f(x+op('=')+frac(n(2)+op('±')+sqrt(n(4)+op('+')+n(96)),n(2)))+'<p>Сначала вычислите число под корнем. Затем найдите оба корня.</p>',fields:[number('discriminant','Число под корнем',100),number('low','Меньший корень',-4),number('high','Больший корень',6)],hint:'4 + 96 = 100; √100 = 10. (2 − 10) : 2 = −4; (2 + 10) : 2 = 6.',record:f(x+op('=')+frac(n(2)+op('±')+n(10),n(2)))+f(x+op('=')+n('−4')+op(';')+x+op('=')+n(6))},
 {title:'Решим третье неравенство',phase:'Находим ОДЗ',body:f(x2+op('−')+n(2)+x+op('−')+n(24)+op('<')+n(0))+'<p>Корни −4 и 6. Перед '+m(x2)+' стоит плюс. Трёхчлен отрицателен между корнями.</p>',fields:[axis('argument-axis','Отметьте решение. Нужен строгий знак <.',[-4,6],['s1'])],hint:'Берём только участок между −4 и 6. Концы оставляем пустыми, потому что в корнях трёхчлен равен нулю.',record:f(n('−4')+op('<')+x+op('<')+n(6))},
 {title:'Пересечём три условия ОДЗ',phase:'Находим ОДЗ',body:'<p>Все строки должны выполняться одновременно:</p>'+sys([n('−5')+op('<')+x+op('<')+n(5),x+op('≠')+n('−3')+op(',')+x+op('≠')+n(3),n('−4')+op('<')+x+op('<')+n(6)])+'<p>Сверху показаны три решения. На нижней оси соберите <strong>их общую часть</strong>.</p>',fields:[axis('domain-axis','Общая часть — ОДЗ',[-5,-4,-3,3,5,6],['s2','s3','s4'],[{label:'−5 < x < 5',tokens:['s1','s2','s3','s4','p1','p2','p3']},{label:'x ≠ −3, x ≠ 3',tokens:['s0','s1','s2','s3','s4','s5','s6','p0','p1','p4','p5']},{label:'−4 < x < 6',tokens:['s2','s3','s4','s5','p2','p3','p4']}])],hint:'Оба промежутка пересекаются от −4 до 5. Внутри исключаем −3 и 3. Выберите три участка: (−4; −3), (−3; 3), (3; 5). Все отмеченные концы пустые.',record:sys(solvedDomain)+'<p>ОДЗ найдено. Это ещё не ответ: теперь решаем само неравенство.</p>'},
 {title:'Заменим единицу логарифмом',phase:'Преобразуем неравенство',body:'<p>Вернёмся к исходному неравенству:</p>'+f(log(base,arg)+op('>')+n(1))+'<p>Логарифм от своего основания равен 1. Чем заполним место аргумента справа?</p>'+f(n(1)+op('=')+log(base,'<mtext>?</mtext>')),fields:[choice('unit','Выберите аргумент',[option('one',m(n(1))),option('same-base',m(base)),option('same-arg',m(arg))],'same-base')],hint:'Основание и аргумент этого нового логарифма должны совпасть. Тогда его значение равно 1.',record:f(log(base,arg)+op('>')+log(base,base))},
 {title:'Перейдём к произведению',phase:'Преобразуем неравенство',body:'<p>На ОДЗ можно сравнить два аргумента, учитывая основание. Если основание больше 1, знак сохраняется; если между 0 и 1 — меняется.</p><p>Это объединяет одно правило: <strong>«основание минус 1» × «первый аргумент минус второй» &gt; 0</strong>.</p><p>Выберите верную запись. Это равносильное неравенство на ОДЗ, а не равенство значений выражений.</p>',fields:[choice('rational','Какое произведение нужно?',[
 option('reverse',m(par(base+op('−')+n(1))+par(base+op('−')+arg)+op('>')+n(0))),
 option('correct',m(par(base+op('−')+n(1))+par(arg+op('−')+base)+op('>')+n(0))),
 option('argument-factor',m(par(arg+op('−')+n(1))+par(arg+op('−')+base)+op('>')+n(0)))],'correct')],hint:'В первой скобке вычитаем 1 из основания. Во второй вычитаем второй аргумент из первого: дробь со знаменателем 14 минус дробь со знаменателем 16.',record:f(par(base+op('−')+n(1))+par(arg+op('−')+base)+op('>')+n(0))},
 {title:'Упростим первую скобку',phase:'Преобразуем неравенство',body:'<p>Записываем единицу как дробь со знаменателем 16:</p>'+f(base+op('−')+n(1)+op('=')+base+op('−')+frac(n(16),n(16))+op('=')+frac(n(25)+op('−')+x2+op('−')+n(16),n(16)))+'<p>Вычислите 25 − 16.</p>',fields:[number('constant','Какое число останется перед −x²?',9)],hint:'25 − 16 = 9. Числитель станет 9 − x².',record:f(base+op('−')+n(1)+op('=')+frac(n(9)+op('−')+x2,n(16)))},
 {title:'Приведём вторую скобку к одному знаменателю',phase:'Преобразуем неравенство',body:f(arg+op('−')+base)+'<p>Знаменатели — 14 и 16. Найдите наименьший общий знаменатель и дополнительные множители.</p>',fields:[number('denominator','Общий знаменатель',112),number('first','На что умножаем 14?',8),number('second','На что умножаем 16?',7)],hint:'14 × 8 = 112 и 16 × 7 = 112. На те же числа умножаем соответствующие числители.',record:f(frac(n(8)+par(n(24)+op('+')+n(2)+x+op('−')+x2)+op('−')+n(7)+par(n(25)+op('−')+x2),n(112)))},
 {title:'Раскроем скобки и приведём подобные',phase:'Преобразуем неравенство',body:'<p>Работаем с числителем:</p>'+f(n(8)+par(n(24)+op('+')+n(2)+x+op('−')+x2)+op('−')+n(7)+par(n(25)+op('−')+x2))+f(n(192)+op('+')+n(16)+x+op('−')+n(8)+x2+op('−')+n(175)+op('+')+n(7)+x2)+'<p>У '+m(x2)+' получаем −8 + 7 = −1; у '+m(x)+' остаётся 16. Вычислите свободное число.</p>',fields:[number('coefficient','Коэффициент при x²: −8 + 7 =',-1),number('constant','192 − 175 =',17)],hint:'192 − 175 = 17. Значит, числитель равен −x² + 16x + 17. Обратите внимание: −7 × (−x²) даёт +7x².',record:f(arg+op('−')+base+op('=')+frac(op('−')+x2+op('+')+n(16)+x+op('+')+n(17),n(112)))},
 {title:'Уберём знаменатели и два минуса',phase:'Преобразуем неравенство',body:'<p>Подставим обе упрощённые скобки:</p>'+f(frac(n(9)+op('−')+x2,n(16))+op('·')+frac(op('−')+x2+op('+')+n(16)+x+op('+')+n(17),n(112))+op('>')+n(0))+'<p>Умножаем на положительное число 16 × 112. Затем выносим минус из <strong>каждой</strong> скобки:</p>'+f(n(9)+op('−')+x2+op('=')+op('−')+par(x2+op('−')+n(9)))+f(op('−')+x2+op('+')+n(16)+x+op('+')+n(17)+op('=')+op('−')+par(x2+op('−')+n(16)+x+op('−')+n(17)))+'<p>Два вынесенных минуса дают плюс. Какой знак останется?</p>',fields:[choice('sign','Знак между произведением и нулём',[option('lt','<strong>&lt; 0</strong>'),option('gt','<strong>&gt; 0</strong>'),option('ge','<strong>≥ 0</strong>')],'gt')],hint:'Знаменатели положительные, а два минуса дали плюс. Поэтому знак > сохраняется.',record:sys(solvedDomain.concat([product]))},
 {title:'Найдём все граничные точки',phase:'Метод интервалов и ответ',body:'<p>Первый множитель '+m(x2+op('−')+n(9))+' равен нулю при −3 и 3. Для второго решим:</p>'+f(x2+op('−')+n(16)+x+op('−')+n(17)+op('=')+n(0))+f(x+op('=')+frac(n(16)+op('±')+sqrt(n(256)+op('+')+n(68)),n(2)))+'<p>256 + 68 = 324; √324 = 18. Вычислите два корня второго множителя.</p>',fields:[number('low','Меньший корень',-1),number('high','Больший корень',17)],hint:'(16 − 18) : 2 = −1. (16 + 18) : 2 = 17. Всего четыре точки: −3, −1, 3, 17.',record:f(par(x+op('+')+n(3))+par(x+op('+')+n(1))+par(x+op('−')+n(3))+par(x+op('−')+n(17))+op('>')+n(0))},
 {title:'Определим знаки на пяти промежутках',phase:'Метод интервалов и ответ',body:'<p>Точки расставлены по порядку: −3, −1, 3, 17.</p>'+f(par(x+op('+')+n(3))+par(x+op('+')+n(1))+par(x+op('−')+n(3))+par(x+op('−')+n(17)))+'<p>Справа от 17 все множители положительные. При переходе через каждый корень один множитель меняет знак. Заполните знаки <strong>слева направо</strong>.</p>',fields:[['s0','Левее −3','plus'],['s1','Между −3 и −1','minus'],['s2','Между −1 и 3','plus'],['s3','Между 3 и 17','minus'],['s4','Правее 17','plus']].map(([id,label,correct])=>choice(id,label,[option('plus','+'),option('minus','−')],correct)),hint:'Начните справа: плюс. Двигайтесь влево и меняйте знак после каждой точки. Получится +, −, +, −, +.',record:'<p>Знаки слева направо: <strong>+ &nbsp; − &nbsp; + &nbsp; − &nbsp; +</strong>.</p>'},
 {title:'Выберем положительные промежутки',phase:'Метод интервалов и ответ',body:f(product)+'<p>Нужны все участки со знаком плюс. ОДЗ пока не пересекаем — это следующий шаг.</p>',fields:[axis('polynomial-axis','Где произведение больше нуля?',[-3,-1,3,17],['s0','s2','s4'])],hint:'Берём левее −3, между −1 и 3 и правее 17. Корни не включаем: в них произведение равно 0, а требуется > 0.',record:f(x+op('∈')+polySolution)},
 {title:'Пересечём решение с ОДЗ',phase:'Метод интервалов и ответ',body:'<p>Соберём всё в последнюю систему:</p>'+sys(solvedDomain.concat([x+op('∈')+polySolution]))+'<p>На нижней оси оставьте только числа, которые подходят <strong>и неравенству, и ОДЗ</strong>.</p>',fields:[axis('final-axis','Общая часть — окончательный ответ',[-4,-3,-1,3,5,17],['s1','s3'],[{label:'Решение неравенства',tokens:['s0','s1','s3','s6','p0']},{label:'ОДЗ',tokens:['s1','s2','s3','s4','p2']}])],hint:'Левый луч ограничивается точкой −4. Промежуток (−1; 3) остаётся целиком. Правее 17 нет значений из ОДЗ. Выберите (−4; −3) и (−1; 3), все концы оставьте пустыми.',record:f(answer)+'<p>−4, −3 и 3 запрещены ОДЗ. При −1 произведение равно нулю, поэтому это число тоже не входит в ответ.</p>'}
];
const STORAGE_KEY='mathExam.logOneExample.v1';
const embedded=window.parent!==window || new URLSearchParams(location.search).get('groupLesson')==='1';
const listeners=new Set();
const blank=()=>({schema:1,step:0,answers:{},solved:[],helps:[],errors:0,feedback:{kind:'',message:''}});
let state=blank(), observed=null, stale=false, storageUnavailable=false, newer=null;
const clone=v=>JSON.parse(JSON.stringify(v));
const plain=v=>!!v&&typeof v==='object'&&!Array.isArray(v)&&(Object.getPrototypeOf(v)===Object.prototype||Object.getPrototypeOf(v)===null);
const integer=v=>Number.isInteger(v)&&v>=0&&v<=100000;
const tokens=field=>Array.from({length:field.points.length+1},(_,i)=>'s'+i).concat(field.points.map((_,i)=>'p'+i));
function numeric(v){return typeof v==='string'&&/^[−-]?\d+(?:[.,]\d+)?$/.test(v.trim())?Number(v.trim().replace('−','-').replace(',','.')):NaN;}
function correct(field,value){if(Array.isArray(field.correct))return Array.isArray(value)&&value.length===field.correct.length&&field.correct.every(x=>value.includes(x));return field.kind==='number'?numeric(value)===Number(field.correct):value===field.correct;}
function validate(v){
 if(!plain(v)||v.schema!==1||!Number.isInteger(v.step)||v.step<0||v.step>steps.length||!plain(v.answers)||!Array.isArray(v.solved)||!Array.isArray(v.helps)||!integer(v.errors)||!plain(v.feedback)||!['','good','wrong'].includes(v.feedback.kind)||typeof v.feedback.message!=='string'||v.feedback.message.length>1000)return false;
 if(v.solved.length>steps.length||v.solved.some((q,i)=>q!==i)||v.step>v.solved.length)return false;
 if(new Set(v.helps).size!==v.helps.length||v.helps.some(q=>!Number.isInteger(q)||q<0||q>=steps.length))return false;
 if(Object.keys(v.answers).some(k=>!/^\d+$/.test(k)||Number(k)>=steps.length))return false;
 for(const [key,values]of Object.entries(v.answers)){
  if(!plain(values))return false;const fields=steps[Number(key)].fields;
  for(const [id,value]of Object.entries(values)){
   const field=fields.find(f=>f.id===id);if(!field)return false;
   if(field.kind==='checks'||field.kind==='axis'){const allowed=field.kind==='axis'?tokens(field):field.options.map(o=>o.id);if(!Array.isArray(value)||new Set(value).size!==value.length||value.some(t=>!allowed.includes(t)))return false;}
   else if(typeof value!=='string'||value.length>80||(field.kind==='choice'&&!field.options.some(o=>o.id===value)&&value!==''))return false;
  }
 }
 if(v.solved.some(i=>!steps[i].fields.every(f=>correct(f,v.answers[i]?.[f.id]))))return false;
 return true;
}
function decode(raw){try{const v=JSON.parse(raw);return validate(v)?v:null;}catch(_){return null;}}
function note(s){$('storage-note').textContent=s;$('storage-note').hidden=!s;}
function storageChanged(raw){stale=true;newer=decode(raw);note('В другой вкладке сохранена новая работа. Эта вкладка приостановлена, чтобы её не затереть.');$('load-newer').hidden=!newer;lock();}
function canAct(){if(stale)return false;if(!embedded&&!storageUnavailable){try{const raw=localStorage.getItem(STORAGE_KEY);if(raw!==observed){storageChanged(raw);return false;}}catch(_){storageUnavailable=true;}}return true;}
function changed(){if(!embedded&&!storageUnavailable&&!stale){try{observed=JSON.stringify(state);localStorage.setItem(STORAGE_KEY,observed);}catch(_){storageUnavailable=true;note('Не удалось сохранить работу в браузере. Не закрывайте страницу до завершения; результат можно скачать.');}}listeners.forEach(fn=>fn());saveStatus();}
function saveStatus(){$('save-status').textContent=embedded?'Работа открыта на доске. Сохранением управляет доска.':stale?'Старая вкладка приостановлена.':storageUnavailable?'Автосохранение недоступно в этом браузере.':'Прогресс сохраняется в этом браузере. Можно закрыть страницу и продолжить позже.';}
function applyState(value){if(!validate(value))return false;state=clone(value);render(false);return true;}
function lock(){document.querySelectorAll('#check,#next,#hint,#restart,#restart-confirm').forEach(e=>{e.disabled=stale;});document.querySelectorAll('#exercise input,#exercise button,#previous,#restart,#restart-confirm').forEach(e=>{if(stale)e.disabled=true;});if(stale)document.querySelectorAll('[data-axis]').forEach(e=>e.setAttribute('aria-disabled','true'));saveStatus();}
function el(tag,txt,cls){const e=document.createElement(tag);if(txt!==undefined)e.textContent=txt;if(cls)e.className=cls;return e;}
function segmentLabel(points,i){return(i===0?'(−∞': '('+points[i-1])+'; '+(i===points.length?'+∞)':points[i]+')');}
function selectionLabel(field,selected){const parts=[];for(let i=0;i<=field.points.length;i++){if(selected.includes('s'+i))parts.push(segmentLabel(field.points,i));if(i<field.points.length&&selected.includes('p'+i))parts.push('{'+field.points[i]+'}');}return parts.length?parts.join(' ∪ '):'Пока ничего не отмечено';}
function axisSvg(field,selected,interactive,label){
 const NS='http://www.w3.org/2000/svg', svg=document.createElementNS(NS,'svg');const pts=field.points;const width=pts.length<=2?420:650, gap=(width-100)/(pts.length+1);const positions=pts.map((_,i)=>50+(i+1)*gap);const stops=[25,...positions,width-25];
 svg.setAttribute('viewBox','0 0 '+width+' 112');svg.setAttribute('class',pts.length<=2?'small-axis':'');svg.setAttribute('role','group');svg.setAttribute('aria-label',label);
 const add=(tag,attrs,parent=svg)=>{const q=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))q.setAttribute(k,v);parent.append(q);return q;};
 add('line',{x1:20,y1:51,x2:width-18,y2:51,stroke:'#a8bbb2','stroke-width':2});add('path',{d:'M '+(width-27)+' 46 L '+(width-17)+' 51 L '+(width-27)+' 56',fill:'none',stroke:'#71867b','stroke-width':2});
 for(let i=0;i<=pts.length;i++){
  const chosen=selected.includes('s'+i), g=add('g',interactive?{class:'axis-segment',role:'button',tabindex:0,'data-axis':field.id,'data-token':'s'+i,'aria-pressed':chosen,'aria-label':'Промежуток '+segmentLabel(pts,i)}:{});
  if(interactive)add('rect',{class:'hit',x:stops[i]+7,y:29,width:Math.max(8,stops[i+1]-stops[i]-14),height:44,fill:'transparent',rx:6},g);
  add('line',{x1:stops[i]+(i===0?0:7),y1:51,x2:stops[i+1]-(i===pts.length?0:7),y2:51,stroke:chosen?'#176f58':'#cbd9d2','stroke-width':chosen?7:4},g);
 }
 for(let i=0;i<pts.length;i++){
  const chosen=selected.includes('p'+i),g=add('g',interactive?{class:'axis-point',role:'button',tabindex:0,'data-axis':field.id,'data-token':'p'+i,'aria-pressed':chosen,'aria-label':'Точка '+pts[i]}:{});
  if(interactive)add('rect',{class:'hit',x:positions[i]-22,y:67,width:44,height:44,rx:6,fill:'transparent'},g);
  add('circle',{cx:positions[i],cy:51,r:5,stroke:'#176f58','stroke-width':2,fill:chosen?'#176f58':'white'},g);
  const t=add('text',{x:positions[i],y:93,'text-anchor':'middle',fill:'#203b34','font-size':17,'font-family':'system-ui'},g);t.textContent=String(pts[i]).replace('-','−');
 }
 return svg;
}
function renderAxis(field,values,disabled){const wrap=el('div',undefined,'axis-block');wrap.append(el('h3',field.label));
 for(const ref of field.refs){wrap.append(el('p',ref.label,'axis-help'));const scroll=el('div',undefined,'axis-scroll');scroll.append(axisSvg(field,ref.tokens,false,ref.label));wrap.append(scroll);}
 if(field.refs.length)wrap.append(el('p','Ваша общая часть','axis-help'));
 const scroll=el('div',undefined,'axis-scroll');scroll.append(axisSvg(field,values,!disabled,field.label));wrap.append(scroll);
 const help=el('p','Нажмите на нужные участки линии. Чтобы включить граничную точку, нажмите на число под ней. Пустые точки не входят в решение.','axis-help');wrap.append(help);
 if(field.points.length>2)wrap.append(el('p','Расстояния условные. На всех строках одинаковые числа стоят друг под другом. На телефоне ось можно прокрутить вправо.','axis-help'));
 const selected=el('p','Выбрано: '+selectionLabel(field,values),'axis-selection');selected.dataset.selection=field.id;wrap.append(selected);return wrap;}
function renderFields(){const host=$('fields');host.replaceChildren();if(state.step>=steps.length)return;const step=steps[state.step],values=state.answers[state.step]||{},disabled=state.solved.includes(state.step)||stale;let numberGroup=null;
 for(const field of step.fields){if(field.kind==='number'){if(!numberGroup){numberGroup=el('div',undefined,'number-fields');host.append(numberGroup);}const label=el('label',undefined,'number-field');label.append(el('span',field.label));const input=el('input');input.type='text';input.inputMode='text';input.autocomplete='off';input.spellcheck=false;input.dataset.field=field.id;input.value=values[field.id]||'';input.disabled=disabled;input.maxLength=80;label.append(input);numberGroup.append(label);continue;}
 numberGroup=null;if(field.kind==='axis'){host.append(renderAxis(field,values[field.id]||[],disabled));continue;}
 const fs=el('fieldset');fs.disabled=disabled;fs.append(el('legend',field.label));const options=el('div',undefined,'options');
 for(const o of field.options){const label=el('label',undefined,'option'),input=el('input');input.type=field.kind==='checks'?'checkbox':'radio';input.dataset.field=field.id;input.dataset.choice=o.id;input.name=field.id;input.value=o.id;input.checked=field.kind==='checks'?(values[field.id]||[]).includes(o.id):values[field.id]===o.id;const body=el('span',undefined,'option-content');body.innerHTML=o.html;label.append(input,body);options.append(label);}fs.append(options);host.append(fs);
 }
}
function renderNotebook(){const host=$('notebook');host.replaceChildren();$('notebook-empty').hidden=state.solved.length>0;
 for(const i of state.solved){const li=el('li');li.dataset.notebookStep=String(i);li.append(el('h3',(i+1)+'. '+steps[i].title));const body=el('div');body.innerHTML=steps[i].record;li.append(body);host.append(li);}
 $('saved-domain').innerHTML=state.solved.includes(7)?'<p class="eyebrow">Сохраняем ОДЗ</p>'+sys(solvedDomain):state.solved.includes(1)?'<p class="eyebrow">Наша система ОДЗ</p>'+sys(domainRows):'';
}
function report(){return 'Логарифмическое неравенство · MathExam\nlog_((25−x²)/16)((24+2x−x²)/14) > 1\nПройдено шагов: '+state.solved.length+' из '+steps.length+'\nПодсказки на шагах: '+(state.helps.length?state.helps.map(i=>i+1).join(', '):'не использованы')+'\nПроверок с ошибкой: '+state.errors+'\n'+(state.solved.length===steps.length?'Ответ: (−4; −3) ∪ (−1; 3)\n':'')+'Страница: '+location.href.split('?')[0].split('#')[0];}
function markOverflow(){let wide=false;document.querySelectorAll('#exercise .formula,#exercise .option-content').forEach(e=>{const overflow=e.scrollWidth>e.clientWidth+2;e.classList.toggle('scrollable-formula',overflow);if(overflow){wide=true;e.tabIndex=0;e.setAttribute('aria-describedby','formula-scroll-note');}else{e.removeAttribute('tabindex');e.removeAttribute('aria-describedby');}});$('formula-scroll-note').hidden=!wide;}
window.addEventListener('resize',markOverflow);
function render(focus){const done=state.step===steps.length;$('exercise').hidden=done;$('completion').hidden=!done;$('progress').value=state.solved.length;$('step-count').textContent=done?'Готово':('Шаг '+(state.step+1)+' из '+steps.length);$('phase').textContent=done?'Решение завершено':steps[state.step].phase;$('previous').disabled=state.step===0||stale;
 if(!done){const s=steps[state.step],passed=state.solved.includes(state.step);$('step-title').textContent=s.title;$('explanation').innerHTML=s.body;renderFields();$('check').hidden=passed;$('next').hidden=!passed;$('next').textContent=state.step===steps.length-1?'Завершить разбор →':'Следующий шаг →';$('hint').hidden=passed;$('hint-text').hidden=!state.helps.includes(state.step);$('hint-text').textContent=s.hint;$('feedback').className='feedback '+(passed?'good':state.feedback.kind);$('feedback').textContent=passed?'Верно. Запись добавлена в тетрадь. Можно перейти дальше.':state.feedback.message;}
 else{$('final-answer').innerHTML=m(answer);$('result-status').textContent=state.helps.length?'Разобрано с подсказками. Чтобы проверить себя, решите ещё раз без них.':'Все шаги выполнены без подсказок.';$('report').value=report();}
 renderNotebook();lock();saveStatus();requestAnimationFrame(markOverflow);if(focus){const target=done?$('complete-title'):$('step-title');target.focus({preventScroll:true});$('current').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
}
function changeValue(fieldId,value){if(!canAct()||state.solved.includes(state.step)||state.step>=steps.length)return;state.answers[state.step] ||= {};state.answers[state.step][fieldId]=value;state.feedback={kind:'',message:''};$('feedback').textContent='';changed();}
$('fields').addEventListener('input',event=>{const e=event.target;if(!e.dataset.field||e.type==='radio'||e.type==='checkbox')return;changeValue(e.dataset.field,e.value);});
$('fields').addEventListener('change',event=>{const e=event.target;if(!e.dataset.field)return;if(e.type==='radio')changeValue(e.dataset.field,e.value);else if(e.type==='checkbox'){const prev=state.answers[state.step]?.[e.dataset.field]||[];changeValue(e.dataset.field,e.checked?[...prev,e.value]:prev.filter(x=>x!==e.value));}});
function toggleAxis(event){const target=event.target.closest('[data-axis]');if(!target||!canAct()||state.solved.includes(state.step)||target.getAttribute('aria-disabled')==='true')return;const field=steps[state.step].fields.find(f=>f.id===target.dataset.axis);const value=state.answers[state.step]?.[field.id]||[],token=target.dataset.token;changeValue(field.id,value.includes(token)?value.filter(q=>q!==token):value.concat(token));const active=state.answers[state.step][field.id];target.setAttribute('aria-pressed',String(active.includes(token)));const line=target.querySelector('line'),circle=target.querySelector('circle');if(line){line.setAttribute('stroke',active.includes(token)?'#176f58':'#cbd9d2');line.setAttribute('stroke-width',active.includes(token)?7:4);}if(circle)circle.setAttribute('fill',active.includes(token)?'#176f58':'white');document.querySelector('[data-selection="'+field.id+'"]').textContent='Выбрано: '+selectionLabel(field,active);}
$('fields').addEventListener('click',toggleAxis);$('fields').addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.matches('[data-axis]')){event.preventDefault();toggleAxis(event);}});
$('form').addEventListener('submit',event=>{event.preventDefault();if(!canAct()||state.step>=steps.length||state.solved.includes(state.step))return;const s=steps[state.step],failed=s.fields.filter(f=>!correct(f,state.answers[state.step]?.[f.id]));if(failed.length){state.errors++;state.feedback={kind:'wrong',message:'Пока не совпало. Проверьте: '+failed.map(f=>f.label).join('; ')+'. Можно открыть подсказку.'};}else{state.solved.push(state.step);state.feedback={kind:'good',message:'Верно.'};}changed();render(false);});
$('next').addEventListener('click',()=>{if(!canAct()||!state.solved.includes(state.step))return;state.step++;state.feedback={kind:'',message:''};changed();render(true);});
$('previous').addEventListener('click',()=>{if(!canAct()||state.step===0)return;state.step--;state.feedback={kind:'',message:''};changed();render(true);});
$('hint').addEventListener('click',()=>{if(!canAct()||state.step>=steps.length)return;if(!state.helps.includes(state.step))state.helps.push(state.step);changed();$('hint-text').hidden=false;$('hint-text').textContent=steps[state.step].hint;});
$('restart').addEventListener('click',()=>{if(canAct())$('restart-box').hidden=false;});$('restart-cancel').addEventListener('click',()=>{$('restart-box').hidden=true;});$('restart-confirm').addEventListener('click',()=>{if(!canAct())return;state=blank();$('restart-box').hidden=true;changed();render(true);});
$('copy-report').addEventListener('click',async()=>{$('report').value=report();try{await navigator.clipboard.writeText(report());$('report-note').textContent='Скопировано. Вставьте текст в сообщение учителю.';}catch(_){$('report').parentElement.open=true;$('report').focus();$('report').select();$('report-note').textContent='Автоматическое копирование недоступно. Текст выделен — скопируйте его вручную.';}});
$('download-report').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([report()],{type:'text/plain;charset=utf-8'}));const link=el('a');link.href=url;link.download='logarithm-result.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('report-note').textContent='Результат подготовлен для скачивания.';});
$('load-newer').addEventListener('click',()=>{try{const raw=localStorage.getItem(STORAGE_KEY),value=decode(raw);if(!value)return;observed=raw;state=value;stale=false;newer=null;note('');$('load-newer').hidden=true;render(false);}catch(_){note('Не удалось прочитать сохранение. Попробуйте обновить страницу.');}});
window.addEventListener('storage',event=>{if(!embedded&&(event.key===STORAGE_KEY||event.key===null)&&event.newValue!==observed)storageChanged(event.key===null?null:event.newValue);});
if(!embedded){try{observed=localStorage.getItem(STORAGE_KEY);if(observed){const v=decode(observed);if(v)state=v;else{storageUnavailable=true;note('Сохранение этого примера повреждено. Начата новая работа без перезаписи старого сохранения.');}}}catch(_){storageUnavailable=true;note('Браузер не разрешил автосохранение. Решать пример можно; в конце скачайте результат.');}}
$('problem').innerHTML=m(log('<mstyle mathcolor="#2455ba">'+base+'</mstyle>','<mstyle mathcolor="#a84b13">'+arg+'</mstyle>')+op('>')+n(1));
render(false);
window.__logExample=Object.freeze({getState:()=>clone(state),applyState,steps:clone(steps),storageKey:STORAGE_KEY});
if(window.MathExamBoard)window.MathExamBoard.register({id:'profile-log-one-example',version:'1.0.0',stateSchemaVersion:1,parentOrigin:location.origin,getState:()=>clone(state),applyState(value){if(!applyState(value))throw new TypeError('Invalid logarithm lesson state');},subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn);}});
})();
