const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const D=require('../../ege-baza/path/data.js'),root=path.resolve(__dirname,'../..'),errors=[],mime={'.js':'text/javascript','.css':'text/css','.html':'text/html'};
const server=http.createServer((req,res)=>{let f=path.join(root,decodeURIComponent(new URL(req.url,'http://local').pathname));if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!f.startsWith(root)||!fs.existsSync(f))return res.writeHead(404).end();res.setHeader('Content-Type',mime[path.extname(f)]||'application/octet-stream');fs.createReadStream(f).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH});try{let p=await browser.newPage({viewport:{width:1280,height:900}}),url='http://127.0.0.1:'+server.address().port;p.on('pageerror',e=>errors.push(e.message));await p.goto(url);assert.equal(await p.locator('h1').count(),1);await p.getByRole('link',{name:'Начать · определить пробелы'}).click();await p.click('#start');await p.fill('#answer','');await p.click('button[type=submit]');assert.match(await p.locator('#feedback').innerText(),/Введите/);await p.click('#skip');await p.click('#finish');await p.waitForURL('**#report');assert.match(await p.locator('h2').first().innerText(),/0\/21/);
for(let m of D.meta){await p.goto(url+'/ege-baza/path/index.html#lesson='+m.id);await p.click('[data-stage="1"]');assert.equal(await p.locator('#model').count(),1);await p.click('[data-stage="2"]');let state=await p.evaluate(id=>PathCourse.state().lessons[id],m.id),t=D.task(m.id,state.seed);for(let step of t.steps){let answer=step.a;if(step.rule){for(let n=10000;n<100000;n++)if(D.correct(step,String(n))){answer=n;break;}}await p.fill('#answer',String(answer));await p.click('button[type=submit]');}assert.match(await p.locator('#lesson').innerText(),/Разбор завершён/);await p.click('#new');state=await p.evaluate(id=>PathCourse.state().lessons[id],m.id);t=D.task(m.id,state.seed);let answer=t.answer;if(t.rule){for(let n=10000;n<100000;n++)if(D.correct(t,String(n))){answer=n;break;}}await p.fill('#answer',String(answer));await p.click('button[type=submit]');assert.match(await p.locator('#feedback').innerText(),/Верно/);}
await p.goto(url+'/ege-baza/path/index.html#lesson=equations');await p.evaluate(()=>{PathCourse.state().lessons.equations.seed=10;localStorage.setItem(PathCourse.KEY,JSON.stringify(PathCourse.state()));});await p.reload();await p.click('[data-stage="1"]');await p.locator('.term').nth(1).click();await p.click('[data-sign="-1"]');assert.match(await p.locator('#signwhy').innerText(),/Одинаковое действие/);await p.click('#moveTerm');await p.waitForFunction(()=>document.querySelector('#eqFeedback').textContent.includes('Равенство сохранено'));assert((await p.locator('[data-side="1"]').innerText()).includes('−'));await p.fill('#divisor','0');await p.click('#divide');assert.match(await p.locator('#eqFeedback').innerText(),/ноль/);
for(let width of [1280,768,360]){await p.setViewportSize({width,height:900});for(let id of ['equations','triangle','scale','graphs','reasoning','integers']){await p.goto(url+'/ege-baza/path/index.html#lesson='+id);await p.click('[data-stage="1"]');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+width+id);}if(process.env.COURSE_SCREENSHOT_DIR){fs.mkdirSync(process.env.COURSE_SCREENSHOT_DIR,{recursive:true});await p.screenshot({path:path.join(process.env.COURSE_SCREENSHOT_DIR,'release-'+width+'.png'),fullPage:true});}}
await p.goto(url+'/ege-baza/path/index.html#lesson=equations');await p.click('[data-stage="2"]');await p.click('[data-stage="3"]');await p.click('#new');await p.fill('#answer','123/7');await p.reload();assert.equal(await p.locator('#answer').inputValue(),'123/7');await p.evaluate(()=>localStorage.setItem('old.student.data','keep'));await p.goto(url+'/ege-baza/path/index.html#report');let dl=p.waitForEvent('download');await p.click('#export');await dl;assert.equal(await p.evaluate(()=>localStorage.getItem('old.student.data')),'keep');// Corrupt saved data must not be overwritten or interpreted as earned progress.
await p.addInitScript(()=>localStorage.setItem('mathexam.ege-baza.path.v1','{"version":1,"lessons":{"equations":{"seed":-1}}}'));await p.reload();assert(await p.locator('#storage').isVisible());assert((await p.evaluate(()=>localStorage.getItem(PathCourse.KEY))).includes('"seed":-1'));
// Former session-only sections restore their own state, without touching other modules.
for(const section of ['algebra','percent','reasoning']){await p.goto(url+'/ege-baza/'+section+'/index.html');await p.locator('footer button').first().click();await p.reload();assert.equal(await p.locator('#draft-notice').count(),0,'valid restored '+section);let key='mathexam.ege-baza.'+section+'.draft.v1';assert(await p.evaluate(k=>!!localStorage.getItem(k),key));}
assert.deepEqual(errors,[]);console.log('RELEASE_BROWSER_PASS: all 28 lesson flows, independent tasks, transfer/cancellation, zero division, 3 widths, restoration, download, old key preservation.');}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
