const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),D=require('../../ege-baza/work-rate/data.js');
const root=path.resolve(__dirname,'../..'),errors=[],server=http.createServer((req,res)=>{let f=path.join(root,new URL(req.url,'http://local').pathname);if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f))return res.writeHead(404).end();res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html'})[path.extname(f)]||'application/octet-stream');fs.createReadStream(f).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH});try{const p=await browser.newPage({viewport:{width:1280,height:900},reducedMotion:'reduce'});p.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:'+server.address().port,url=base+'/ege-baza/work-rate/index.html';
await p.goto(base+'/ege-baza/index.html');await p.getByRole('link',{name:'Землекопы: работа без уравнений'}).click();await p.waitForURL('**/work-rate/index.html');assert(await p.locator('#play').isDisabled());await p.click('[data-predict="first"]');assert.match(await p.locator('#prediction').innerText(),/Верно/);await p.click('#finish');assert.match(await p.locator('#workSummary').innerText(),/100%/);await p.selectOption('#unit','1');assert.match(await p.locator('#sameTime').innerText(),/= 4 ч/);await p.selectOption('#unit','24');assert.match(await p.locator('#sameTime').innerText(),/= 4 ч/);
await p.locator('#time').focus();await p.keyboard.press('ArrowLeft');assert((await p.locator('#clock').innerText()).startsWith('3,99'));await p.uncheck('#noMotion');await p.click('#zero');await p.click('#play');await p.waitForFunction(()=>Number(document.querySelector('#time').value)>.05);await p.click('#play');await p.check('#noMotion');
await p.selectOption('#workMode','many');await p.fill('#firstTime','12');await p.locator('#firstTime').blur();await p.fill('#secondTime','12');await p.locator('#secondTime').blur();await p.fill('#horizon','6');await p.locator('#horizon').blur();await p.click('#finish');assert.match(await p.locator('#workSummary').innerText(),/1 огорода по объёму/);assert.match(await p.locator('#workSummary').innerText(),/Полностью готовы: 0/);assert.match(await p.locator('#workSummary').innerText(),/Незавершённых: 2/);await p.fill('#horizon','120000');await p.locator('#horizon').blur();await p.click('#finish');assert.match(await p.locator('#workSummary').innerText(),/Полностью готовы: 20000/);await p.selectOption('#workMode','one');
for(const k of D.kinds){await p.goto(url+'#learn');await p.selectOption('#kind',k.id);for(const method of k.id==='joint'?['units','fractions']:['units']){if(k.id==='joint')await p.click('[data-method="'+method+'"]');const a=await p.evaluate(()=>WorkRateCourse.state().activities.learn),t=D.make(k.id,a.seed),steps=method==='fractions'?t.fractionSteps:t.steps;for(const s of steps){await p.fill('#answer',String(s.a));await p.click('button[type=submit]');}assert.match(await p.locator('#body').innerText(),/Разбор завершён/);}await p.click('#nextTask');await p.waitForURL('**#practice');const a=await p.evaluate(()=>WorkRateCourse.state().activities.practice),t=D.make(k.id,a.seed);await p.fill('#answer',String(t.answer));await p.click('button[type=submit]');assert.match(await p.locator('#body').innerText(),/Решение найдено/);}
// A wrong first attempt, help, and reopened statements must not earn independent credit.
await p.click('#new');await p.fill('#answer','999999');await p.click('button[type=submit]');let a=await p.evaluate(()=>WorkRateCourse.state().activities.practice);await p.fill('#answer',String(D.make(a.kind,a.seed).answer));await p.click('button[type=submit]');assert.equal(await p.evaluate(()=>WorkRateCourse.state().records.at(-1).independent),false);
await p.click('#new');await p.fill('#answer','7/3');await p.reload();assert.equal(await p.locator('#answer').inputValue(),'7/3');await p.click('#hint');await p.waitForURL('**#learn');assert.equal(await p.evaluate(()=>WorkRateCourse.state().activities.practice.help),true);
await p.goto(url+'#practice');a=await p.evaluate(()=>WorkRateCourse.state().activities.practice);await p.fill('#answer',String(D.make(a.kind,a.seed).answer));await p.click('button[type=submit]');assert.equal(await p.evaluate(()=>WorkRateCourse.state().records.at(-1).independent),false);
for(const width of [1280,768,360]){await p.setViewportSize({width,height:900});for(const hash of ['lab','learn','report']){await p.goto(url+'#'+hash);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+hash+' '+width+' '+JSON.stringify(await p.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).map(e=>({tag:e.tagName,id:e.id,cls:e.className,text:e.innerText?.slice(0,60)})).slice(0,8))));}if(width===360&&process.env.COURSE_SCREENSHOT_DIR){await p.goto(url+'#lab');fs.mkdirSync(process.env.COURSE_SCREENSHOT_DIR,{recursive:true});await p.screenshot({path:path.join(process.env.COURSE_SCREENSHOT_DIR,'diggers-phone.png'),fullPage:true});}}
await p.goto(url+'#report');await p.evaluate(()=>localStorage.setItem('old.student.work','unchanged'));const download=p.waitForEvent('download');await p.locator('footer button').click();await download;assert.equal(await p.evaluate(()=>localStorage.getItem('old.student.work')),'unchanged');
const key=await p.evaluate(()=>WorkRateCourse.key);await p.addInitScript(key=>localStorage.setItem(key,'{"broken":true}'),key);await p.reload();assert(await p.locator('#draft-notice').isVisible());assert.equal(await p.evaluate(key=>localStorage.getItem(key),key),'{"broken":true}');assert.deepEqual(errors,[]);console.log('WORK_RATE_BROWSER_PASS: nine families and unlimited garden counts, both joint-work methods, independent vs assisted, animation/manual/keyboard, draft reload, export, old keys, corrupt state, 3 widths.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
