const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const R=require('../../ege-baza/remediation.js'),D=require('../../ege-baza/path/data.js'),root=path.resolve(__dirname,'../..');
const server=http.createServer((req,res)=>{let f=path.join(root,new URL(req.url,'http://local').pathname);if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!f.startsWith(root+path.sep)||!fs.existsSync(f))return res.writeHead(404).end();res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html'})[path.extname(f)]||'application/octet-stream');fs.createReadStream(f).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH});try{const p=await browser.newPage({viewport:{width:360,height:900},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:'+server.address().port;
// Weak fractions: mistake -> precisely chosen old trainer -> the same saved task.
await p.goto(base+'/ege-baza/path/index.html#lesson=fractions');await p.click('[data-stage="2"]');let before=await p.evaluate(()=>PathCourse.state().lessons.fractions);await p.fill('#answer','1/0');await p.click('button[type=submit]');assert.match(await p.locator('#ege-remediation').innerText(),/Смысл дроби/);await p.locator('#ege-remediation a').click();assert(p.url().includes('fraction-meaning.html'));assert(await p.locator('#ege-return').isVisible());await p.locator('#ege-return a').click();let after=await p.evaluate(()=>PathCourse.state().lessons.fractions);assert.equal(after.seed,before.seed);assert.equal(after.step,before.step);assert.equal(await p.locator('#answer').inputValue(),'1/0');assert.equal(after.independent,0);
// Sign mistake: same magnitude, opposite sign gets sign practice, not harder equations.
await p.goto(base+'/ege-baza/path/index.html#lesson=equations');await p.click('[data-stage="2"]');before=await p.evaluate(()=>PathCourse.state().lessons.equations);let t=D.task('equations',before.seed);await p.fill('#answer',String(-t.steps[0].a));await p.click('button[type=submit]');assert.match(await p.locator('#ege-remediation a').innerText(),/разными знаками/);
// Wrong percentage base: targeted percentage change practice.
await p.goto(base+'/ege-baza/path/index.html#lesson=percent');await p.click('[data-stage="2"]');await p.fill('#answer','1');await p.click('button[type=submit]');assert.match(await p.locator('#ege-remediation a').innerText(),/новая база/);
// Every return control must work without writing unrelated student keys.
await p.evaluate(()=>localStorage.setItem('student.unrelated','keep'));for(const skill of Object.values(R.skills)){await p.goto(base+skill.path+'?returnTo='+encodeURIComponent('/ege-baza/path/index.html#lesson=percent'));assert(await p.locator('#ege-return a').isVisible(),skill.path);assert.equal(await p.evaluate(()=>localStorage.getItem('student.unrelated')),'keep');assert(await p.evaluate(()=>document.querySelector('#ege-return').getBoundingClientRect().right<=innerWidth+1),'return control phone overflow');}
// Reject an attacker-controlled external return target.
await p.goto(base+R.skills.signs.path+'?returnTo='+encodeURIComponent('https://example.com/'));assert.equal(await p.locator('#ege-return').count(),0);
// Work-rate learner: confusing hours and work gets the meaning-of-fraction route.
await p.goto(base+'/ege-baza/work-rate/index.html#practice');await p.fill('#answer','18');await p.click('button[type=submit]');assert.match(await p.locator('#ege-remediation a').innerText(),/Смысл дроби/);await p.locator('#ege-remediation a').click();await p.locator('#ege-return a').click();assert.equal(await p.locator('#answer').inputValue(),'18');assert.equal(await p.evaluate(()=>WorkRateCourse.state().activities.practice.help),true);
assert.deepEqual(errors,[]);console.log('VIRTUAL_STUDENT_PASS: fractions, signs, percentage base, work/time confusion, nine old trainers, same-step return, no false mastery, unrelated keys, safe return URLs.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
