(function(){'use strict';
const lessons=(globalThis.MordLessons||[]).sort((a,b)=>a.order-b.order),byId=new Map(lessons.map(l=>[l.id,l])),tasks=new Map(lessons.flatMap(l=>l.tasks.map(t=>[t.id,{t,l}]))),main=document.getElementById('main');
let cleanup=()=>{},state;try{state=MordState.create(lessons,localStorage);}catch(_){state=MordState.create(lessons,{getItem(){throw Error();}});}
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(label,id,quiet=false)=>'<button type="button" class="button'+(quiet?' quiet':'')+'" id="'+id+'">'+label+'</button>';
const total=lessons.reduce((n,l)=>n+l.tasks.length,0),books=[...new Set([...tasks.values()].map(x=>x.t.book).filter(x=>/^\d/.test(x)))];
const chapters={0:['Перед §4','Устроим окружность','Два коротких вводных урока, чтобы не начинать с заучивания.'],4:['§4','Числовая окружность','Путь, точка, направление, дуги и полные обороты.'],5:['§5','Окружность на координатной плоскости','Координаты превращают рисунок в точный инструмент.'],6:['§6','Синус, косинус, тангенс и котангенс','От смысла функций — к значениям, тождествам и неравенствам.']};
function board(hash){return window.self!==window.top?'':'<a class="button quiet board-link" href="/trainers/trainer-board.html?trainer='+encodeURIComponent('/ege-profil/circle/index.html'+(globalThis.ProfileRouteNav?.query()||'')+hash)+'">Открыть на доске</a>';}
function warn(){const w=document.getElementById('storage-warning');w.hidden=!state.warning;w.textContent=state.warning;}
function save(){state.save();warn();}
function shell(html){cleanup();cleanup=()=>{};main.innerHTML=html;globalThis.ProfileRouteNav?.render();warn();const h=main.querySelector('h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}window.scrollTo(0,0);}
function counts(l){const ids=l?l.tasks.map(t=>t.id):[...tasks.keys()];return {done:ids.filter(id=>state.data.records[id]?.practised).length,independent:ids.filter(id=>state.data.records[id]?.independent).length,guided:ids.filter(id=>state.data.records[id]?.guided).length};}
function title(t){return t.book==='Подготовка'?'Подготовка '+t.part:'№'+t.book+(t.part?' ('+t.part+')':'');}
function status(t){const r=state.data.records[t.id];return r?.independent?'Решено с первой попытки без помощи':r?.guided?'Разобрано по шагам':r?.practised?'Есть завершённая тренировка':'Ещё не решали';}
function jump(){return '<form id="jump-form" class="jump-form"><label for="book-number">Открыть номер учебника<input id="book-number" placeholder="Например, 4.7" autocomplete="off"></label><button class="button quiet" type="submit">Найти номер</button><span id="jump-message" role="status" class="small"></span></form>';}
function bindJump(){const f=document.getElementById('jump-form');if(f)f.onsubmit=e=>{e.preventDefault();const n=f.querySelector('input').value.trim().replace(/^№\s*/,'').replace(',','.');if(books.includes(n))location.hash='number/'+n;else document.getElementById('jump-message').textContent='Есть номера 4.1–4.20, 5.1–5.14, 6.1–6.41. Введите номер с точкой.';};}
function home(){const next=lessons.find(l=>counts(l).done<l.tasks.length)||lessons[0];shell('<section class="hero"><div><p class="eyebrow">Мордкович · 10–11 · §§4–6</p><h1>Сначала —<br><em>одна окружность.</em></h1><p class="lead">Намотать числовую прямую. Найти точку. Увидеть координаты. И только потом — понять тригонометрию.</p><div class="actions"><a class="button" href="#lesson/'+next.id+'">'+(counts().done?'Продолжить по порядку':'Начать с самого начала')+' →</a>'+board('#home')+'</div><p class="small muted">'+books.length+' номеров учебника · '+[...tasks.values()].filter(x=>/^\d/.test(x.t.book)).length+' отдельных заданий · '+lessons.length+' урока</p></div><div class="hero-art" aria-hidden="true"><svg viewBox="0 0 360 340"><defs><pattern id="grid" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M24 0H0V24" fill="none" stroke="#dce6e2" stroke-width=".6"/></pattern></defs><rect width="360" height="340" fill="url(#grid)"/><path d="M25 175H333M179 25V315" stroke="#9ab0a7"/><circle cx="179" cy="175" r="116" fill="#e9f4ef" fill-opacity=".6" stroke="#518d77" stroke-width="2"/><path d="M295 175A116 116 0 0 0 179 59" fill="none" stroke="#c58337" stroke-width="7" stroke-linecap="round"/><path d="M179 175L261 93" stroke="#16665d" stroke-width="3"/><circle cx="261" cy="93" r="7" fill="#16665d"/><text x="273" y="81" fill="#16665d" font-size="20">M(t)</text><text x="304" y="181">A</text><text x="173" y="44">B</text><text x="43" y="181">C</text><text x="172" y="312">D</text><text x="165" y="194">O</text><text x="205" y="153" fill="#16665d">R = 1</text><text x="56" y="333" fill="#536975" font-size="13">разные числа — одна точка?</text></svg></div></section><div class="how"><span><b>01</b> Попробовать руками</span><span><b>02</b> Объяснить каждый шаг</span><span><b>03</b> Решить самостоятельно</span></div>'+jump()+Object.entries(chapters).map(([ch,[label,name,sub]])=>'<section class="chapter"><div class="section-head"><span class="num">'+label+'</span><div><h2>'+name+'</h2><p>'+sub+'</p></div></div><div class="lesson-grid">'+lessons.filter(l=>l.chapter===Number(ch)).map(l=>{const c=counts(l);return '<a class="lesson-card" href="#lesson/'+l.id+'"><p class="eyebrow">'+(ch==='0'?'Авторская подготовка':range(l))+'</p><h3>'+esc(l.title)+'</h3><p>'+esc(l.summary)+'</p><span class="status">'+c.done+' из '+l.tasks.length+' заданий завершено ↗</span></a>';}).join('')+'</div></section>').join('')+'<aside class="note"><b>Продолжение к ЕГЭ.</b> <a href="../trigonometry/index.html">Весь курс тригонометрии: Мордкович и экзаменационная практика →</a></aside><aside class="note">Здесь подробно разобраны присланные §§4–6. Это начало тригонометрии по учебнику, а не весь курс 10–11 классов. Можно двигаться по порядку или найти конкретный номер.</aside>');bindJump();}
function range(l){const a=[...new Set(l.tasks.map(t=>t.book))];return a.length===1?'№'+a[0]:'№'+a[0]+'–'+a[a.length-1];}
function crumb(l){return '<p class="breadcrumb"><a href="#home">Маршрут</a><span>/</span>'+esc(l.title)+'</p>';}
function cards(items){return '<div class="task-list">'+items.map(t=>'<article class="task-card" data-task="'+t.id+'"><h3>'+title(t)+'</h3><div class="task-preview">'+t.prompt+'</div><div class="actions"><a class="button" href="#task/'+t.id+'/guided">По шагам</a><a class="button quiet" href="#task/'+t.id+'/independent">Самостоятельно</a></div><p class="status">'+status(t)+'</p></article>').join('')+'</div>';}
function lesson(l,returnId,returnMode){state.assistLesson(l);const idx=lessons.indexOf(l),prev=lessons[idx-1],next=lessons[idx+1],first=l.tasks.find(t=>!state.data.records[t.id]?.practised)||l.tasks[0];shell(crumb(l)+'<p class="eyebrow">'+(l.chapter?'§'+l.chapter+' · '+range(l):'Перед учебником · авторская подготовка')+'</p><h1>'+esc(l.title)+'</h1><p class="lead">'+esc(l.summary)+'</p>'+(returnId&&tasks.has(returnId)?'<div class="note"><a class="button" href="#task/'+returnId+'/'+returnMode+'">Вернуться на сохранённый шаг</a><p class="small">Объяснение отмечено как помощь; черновик сохранён.</p></div>':'')+'<div class="lesson-layout"><div><section class="panel theory">'+l.intro+'</section><section class="panel"><p class="eyebrow">Лаборатория</p><h2>Проверьте своими руками</h2><div id="lab"></div></section></div><aside><section class="panel"><h2>От смысла к решению</h2><p class="small">Сначала исследуйте модель, затем откройте задачу. В режиме «По шагам» проверяется каждый ход, в самостоятельном — итог.</p><div class="actions"><a class="button" href="#task/'+first.id+'/guided">К первой нерешённой</a>'+board('#lesson/'+l.id)+'</div><p class="small muted">Задачи не закрыты: любой номер можно открыть сразу.</p></section><section class="panel"><h3>Маршрут</h3>'+(prev?'<p><a href="#lesson/'+prev.id+'">← '+esc(prev.title)+'</a></p>':'')+(next?'<p><a href="#lesson/'+next.id+'">'+esc(next.title)+' →</a></p>':'<p>Основа пройдена. <a href="../trigonometry/index.html#exam">Перейти к закреплению и применению на ЕГЭ →</a></p>')+'</section></aside></div><section id="practice"><div class="section-head"><div><h2>Задачи этого урока</h2><p>Номер и буква совпадают с присланными страницами.</p></div></div>'+cards(l.tasks)+'</section>');const lab=MordLab.mount(document.getElementById('lab'),l.lab||{mode:'angle'},{practice:false});cleanup=()=>lab.destroy();}
function numberPage(n){const all=[...tasks.values()].filter(x=>x.t.book===n);shell('<p class="breadcrumb"><a href="#home">Маршрут</a></p><p class="eyebrow">Найдено в учебном блоке</p><h1>№'+esc(n)+'</h1>'+cards(all.map(x=>x.t))+jump());bindJump();}
function fieldHTML(f,draft,seed){const id='field-'+f.id,label=f.label||'Ответ';if(f.kind==='number')return '<div class="answer-field"><label for="'+id+'">'+label+'<input type="text" id="'+id+'" data-field="'+f.id+'" value="'+esc(draft??'')+'" autocomplete="off" placeholder="Дробь, √2/2 или 2*pi/3"></label></div>';
 if(f.kind==='point')return '<div class="answer-field point-field" data-field="'+f.id+'"><p class="point-note">'+label+'<br>Поставьте точку на модели, затем зафиксируйте её здесь. Для разных концов дуги сохраните каждую точку отдельно.</p><button class="button quiet" type="button" data-capture="'+f.id+'">Зафиксировать: '+label+'</button><span class="small point-saved" role="status">'+(draft!==undefined&&draft!==''?' Точка сохранена.':' Точка ещё не сохранена.')+'</span><button class="button quiet" type="button" data-restore="'+f.id+'" '+(draft===undefined||draft===''?'hidden':'')+'>Показать эту точку</button></div>';
 const opts=MordCheck.shuffle(f.options||[],seed+f.id);
 if(f.kind==='order'){const selected=Array.isArray(draft)?draft:[];return '<fieldset class="answer-field" data-field="'+f.id+'"><legend>'+label+'</legend><p class="small muted">Нажимайте числа от наименьшего к наибольшему. Нажатие на выбранное число возвращает его в набор.</p><div class="order-selected" id="order-'+f.id+'" aria-label="Ваш порядок">'+selected.map((v,i)=>{const o=f.options.find(o=>o.value===v);return o?'<button class="order-item" type="button" data-remove="'+f.id+'" data-value="'+esc(v)+'">'+(i+1)+'. '+o.label+' ×</button>':'';}).join('')+'</div><div class="order-pool">'+opts.filter(o=>!selected.includes(o.value)).map(o=>'<button class="order-item" type="button" data-add="'+f.id+'" data-value="'+esc(o.value)+'">'+o.label+'</button>').join('')+'</div></fieldset>';}
 return '<fieldset class="answer-field" data-field="'+f.id+'"><legend>'+label+(f.kind==='multi'?' <span class="small muted">(выберите все подходящие)</span>':'')+'</legend><div class="choices">'+opts.map((o,i)=>'<label class="choice"><input type="'+(f.kind==='multi'?'checkbox':'radio')+'" name="'+f.id+'" value="'+esc(o.value)+'" '+((f.kind==='multi'&&Array.isArray(draft)&&draft.includes(o.value))||(f.kind==='choice'&&draft===o.value)?'checked':'')+'><span>'+o.label+'</span></label>').join('')+(f.kind==='multi'?'<label class="choice"><input type="checkbox" name="'+f.id+'" value="__none" '+(Array.isArray(draft)&&draft.length===0?'checked':'')+'><span>Ни один из вариантов</span></label>':'')+'</div></fieldset>';}
function finalQuestion(t){return {prompt:'Решите задачу и дайте полный ответ.',fields:t.fields,hint:t.steps[0]?.hint||'Вернитесь к определениям и к опорным точкам.',why:'Итоговый ответ проверен.'};}
function practice(t,l,mode){const s=state.start(t.id,mode);if(s.done)return result(t,l,s);const qs=mode==='guided'?[...t.steps,finalQuestion(t)]:[finalQuestion(t)],q=qs[s.step]||qs[0];let lab;
 shell(crumb(l)+'<div class="practice-head"><div><p class="eyebrow">'+(mode==='guided'?'С решением по шагам':'Самостоятельная попытка')+' · '+(s.familiar?'знакомая задача':'первое открытие')+'</p><h1>'+title(t)+'</h1></div><a href="#lesson/'+l.id+'/'+t.id+'/'+mode+'">К объяснению и обратно</a></div><div class="practice-layout"><section class="panel task-panel"><div class="task-condition">'+t.prompt+'</div>'+(mode==='guided'?'<ol class="steps" aria-label="Шаги решения">'+qs.map((x,i)=>'<li class="'+(i===s.step?'current':i<s.step?'passed':'')+'" '+(i===s.step?'aria-current="step"':'')+'>'+(i+1)+'</li>').join(''):'<p class="small muted">Подсказку можно открыть в любой момент. Тогда результат отметится как решение с помощью.</p>')+'<div class="question">'+q.prompt+'</div><form id="answer-form">'+q.fields.map(f=>fieldHTML(f,s.draft[f.id],t.id+':'+s.step)).join('')+'<p class="small muted">В числовых полях: π = pi, умножение — *. Например, 2*pi/3 или sqrt(3)/2. На рисунке допускается небольшая погрешность.</p><div class="actions"><button class="button" type="submit" id="check">Проверить</button>'+btn('Подсказка','hint',true)+'</div></form><div id="feedback" class="feedback" role="status" aria-live="polite"></div><div id="hint-box" class="hint-box" hidden></div><div class="actions">'+btn(mode==='guided'&&s.step<qs.length-1?'Следующий шаг →':'Завершить задачу','next')+'</div></section><aside class="panel practice-lab"><p class="eyebrow">Ваше построение</p><div id="lab"></div><p class="lab-note">Исследуйте модель. Точные значения и готовые пояснения скрыты; их открытие будет отмечено как помощь.</p><p class="small muted">'+(s.familiar?'Это знакомое условие: повтор полезен, но не считается новым самостоятельным решением.':'Новая самостоятельная отметка возможна только с первой попытки без помощи.')+'</p><a href="#lesson/'+l.id+'/'+t.id+'/'+mode+'">Восстановить правило и вернуться</a></aside></div>');
 const config={...(t.lab||l.lab||{mode:'angle'}),angle:s.angle};
 lab=MordLab.mount(document.getElementById('lab'),config,{practice:true,onChange:value=>{const a=typeof value==='number'?value:value?.angle;if(Number.isFinite(a)){s.angle=a;save();}},onHelp:()=>{s.assisted=true;save();}});cleanup=()=>lab.destroy();
 const form=document.getElementById('answer-form'),feedback=document.getElementById('feedback'),next=document.getElementById('next');next.disabled=!s.solved;
 function collect(){for(const f of q.fields){if(f.kind==='number')s.draft[f.id]=form.querySelector('[data-field="'+f.id+'"]').value;else if(f.kind==='point'){/* Each construction is explicitly captured, including separate arc endpoints. */}else if(f.kind==='choice')s.draft[f.id]=new FormData(form).get(f.id)||'';else if(f.kind==='multi'){const vals=new FormData(form).getAll(f.id);s.draft[f.id]=vals.length===1&&vals[0]==='__none'?[]:vals;s.draft[f.id+'None']=vals.includes('__none')?'yes':'';}else if(!Array.isArray(s.draft[f.id]))s.draft[f.id]=[];}save();}
 function lock(){for(const e of form.querySelectorAll('input,button'))if(e.id!=='hint')e.disabled=true;next.disabled=false;}
 function good(){feedback.className='feedback good';feedback.innerHTML='Верно. '+(mode==='guided'?(q.why||'Можно перейти дальше.'):'Завершите задачу, чтобы увидеть разбор.');lock();}
 if(s.solved)good();form.addEventListener('input',collect);form.addEventListener('change',e=>{const target=e.target;if(target.type==='checkbox'&&target.checked){for(const other of form.querySelectorAll('input[type=checkbox]'))if(other.name===target.name&&other!==target&&(target.value==='__none'||other.value==='__none'))other.checked=false;}collect();});
 form.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||s.solved)return;if(b.dataset.capture){const id=b.dataset.capture;s.draft[id]=String(lab.getAngle());save();const field=b.closest('.point-field');field.querySelector('.point-saved').textContent=' Точка сохранена.';field.querySelector('[data-restore]').hidden=false;}else if(b.dataset.restore){const input=document.querySelector('#lab [data-angle-input]');input.value=s.draft[b.dataset.restore];input.dispatchEvent(new Event('change',{bubbles:true}));}else if(b.dataset.add||b.dataset.remove){const id=b.dataset.add||b.dataset.remove,v=b.dataset.value;collect();const a=Array.isArray(s.draft[id])?s.draft[id]:[];s.draft[id]=b.dataset.add?[...a,v]:a.filter(x=>x!==v);save();b.closest('fieldset').outerHTML=fieldHTML(q.fields.find(f=>f.id===id),s.draft[id],t.id+':'+s.step);}});
 form.onsubmit=e=>{e.preventDefault();if(s.solved)return;collect();const incomplete=q.fields.some(f=>(s.draft[f.id]===''||s.draft[f.id]===undefined||(Array.isArray(s.draft[f.id])&&s.draft[f.id].length===0&&s.draft[f.id+'None']!=='yes')));if(incomplete){feedback.className='feedback';feedback.textContent='Заполните все поля или сделайте выбор. Для нескольких ответов отметьте все подходящие варианты.';return;}
 const wrong=q.fields.filter(f=>!MordCheck.check(f,s.draft[f.id]));if(!wrong.length){s.solved=true;save();good();next.focus({preventScroll:true});}else{s.wrong=true;save();feedback.className='feedback bad';feedback.textContent='Пока не сходится. '+(q.fields.length>1?'Проверьте поле «'+String(wrong[0].label||'Ответ').replace(/<[^>]+>/g,'')+'». ':'')+'Проверьте направление, знак и условие. Можно исправить ответ или открыть подсказку.';}};
 document.getElementById('hint').onclick=()=>{s.assisted=true;save();const h=document.getElementById('hint-box');h.hidden=false;h.innerHTML='<b>Помощь к этому шагу</b><p>'+q.hint+'</p>'+(mode==='independent'?'<a class="button quiet" href="#task/'+t.id+'/guided">Разобрать эту задачу по шагам</a>':'');};
 next.onclick=()=>{if(!s.solved)return;if(s.step<qs.length-1){s.step++;s.draft={};s.solved=false;save();practice(t,l,mode);}else{state.finish(s);result(t,l,s);}};
}
function answerLabel(f){if(f.kind==='number')return Number.isInteger(f.expected)?String(f.expected):Number(f.expected.toPrecision(9)).toLocaleString('ru-RU',{maximumFractionDigits:9});if(f.kind==='point')return 'точка на окружности (см. объяснение)';const values=Array.isArray(f.expected)?f.expected:[f.expected];return values.map(v=>f.options.find(o=>o.value===v)?.label||esc(v)).join(f.kind==='order'?' &lt; ':'; ');}
function result(t,l,s){const r=state.data.records[t.id],fresh=s.mode==='independent'&&!s.assisted&&!s.wrong&&!s.familiar,idx=l.tasks.indexOf(t),next=l.tasks[idx+1];shell(crumb(l)+'<section class="panel result-panel"><span class="result-symbol" aria-hidden="true">✓</span><p class="eyebrow">'+title(t)+' · завершено</p><h1>'+(fresh?'Решили самостоятельно.':'Разобрались с задачей.')+'</h1><p class="lead">'+(fresh?'Первая попытка на новом условии, без подсказок. Это успех в этой задаче, а не отметка освоения всей темы.':s.mode==='guided'?'Все шаги и итог проверены. Для самостоятельной проверки выберите ещё не открывавшийся подпункт.':s.familiar?'Знакомое условие сохранено как повторение.':'Решение после ошибки или с помощью сохранено как тренировка.')+'</p><div class="solution"><h2>Почему это работает</h2><div>'+t.explanation+'</div><details><summary>Полная цепочка шагов</summary><ol class="solution-list">'+t.steps.map(q=>'<li><b>'+q.prompt+'</b><p>'+q.why+'</p>'+q.fields.map(f=>'<p class="small">'+f.label+': '+answerLabel(f)+'</p>').join('')+'</li>').join('')+'</ol></details></div><div class="actions">'+(next?'<a class="button" href="#task/'+next.id+'/'+s.mode+'">Следующий подпункт →</a>':'<a class="button" href="#lesson/'+(lessons[lessons.indexOf(l)+1]?.id||l.id)+'">Следующий урок →</a>')+'<a class="button quiet" href="#lesson/'+l.id+'">Все задачи урока</a>'+btn('Повторить эту задачу','repeat',true)+'</div><p><a href="#progress">Мой отчёт</a> · <a href="#home">Маршрут</a></p></section>');document.getElementById('repeat').onclick=()=>{state.start(t.id,s.mode,true);practice(t,l,s.mode);};}
function download(text,name,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function progress(){const c=counts();shell('<p class="eyebrow">Моя работа</p><h1>Видно, что уже получается.</h1><p class="lead">Завершено '+c.done+' из '+total+' заданий. Из них '+c.independent+' впервые решены без помощи и ошибок.</p><p>По шагам: '+c.guided+'. Повторы и ответы после подсказки полезны для обучения, но не прибавляют самостоятельные успехи. Это история данного браузера; облачный журнал здесь не подключён.</p><div class="actions">'+btn('Скачать отчёт','export')+(state.original?btn('Скачать исходное сохранение','raw-export',true):'')+'</div><div class="progress-grid">'+lessons.map(l=>{const x=counts(l);return '<article class="panel"><p class="eyebrow">'+range(l)+'</p><h2><a href="#lesson/'+l.id+'">'+esc(l.title)+'</a></h2><p>Завершено: '+x.done+' / '+l.tasks.length+'<br>Новые с первой попытки: '+x.independent+'<br>Разобраны по шагам: '+x.guided+'</p><progress max="'+l.tasks.length+'" value="'+x.done+'" aria-label="Завершённые задачи: '+esc(l.title)+'"></progress></article>';}).join('')+'</div>');document.getElementById('export').onclick=()=>download(JSON.stringify(state.export(),null,2),'mordkovich-circle-progress.json');if(state.original)document.getElementById('raw-export').onclick=()=>download(state.original,'mordkovich-original-save.txt','text/plain');}
function sources(){shell('<section class="panel theory"><p class="eyebrow">Содержание и источники</p><h1>По каким страницам учимся.</h1><p>Основа этого блока — присланные владельцем сайта страницы задачника Мордковича для 10–11 классов: §4 №4.1–4.20, §5 №5.1–5.14, §6 №6.1–6.41. Повторные снимки страниц исключены. Обложка и выходные данные не представлены, поэтому год и конкретная редакция не приписываются.</p><p>Условия привязаны к номерам на этих страницах; объяснения, пошаговые вопросы и визуализации подготовлены для курса. Два вводных урока — авторская подготовка, не номера учебника. Сканированные страницы на сайте не размещаются.</p><p>'+books.length+' номеров, '+[...tasks.values()].filter(x=>/^\d/.test(x.t.book)).length+' отдельных заданий по изображениям и '+[...tasks.values()].filter(x=>!/^\d/.test(x.t.book)).length+' подготовительных упражнений. Охват ограничен присланными §§4–6; это не весь учебник и не полный профильный ЕГЭ.</p><p>На числовой окружности дугу читаем от первой буквы ко второй против часовой стрелки. Различаем длину направленной дуги и меньшую дугу; открытые дуги не содержат концов. Все формулы семейств сопровождаются условием k ∈ ℤ.</p><p>Точность положения точки в построении проверяется с небольшой угловой погрешностью. Рисунок помогает увидеть связь; доказательство опирается на определения и точные преобразования. В числовых полях можно вводить π, дроби и корни.</p><p>Если в присланном условии обнаружено неверное равенство, в соответствующем тренажёре оно прямо разобрано как проверка утверждения, с контрпримером. Ошибка не выдаётся за тождество.</p><a class="button" href="#home">К маршруту</a></section>');}
function route(){const [page,id,mode,extra]=location.hash.slice(1).split('/');if(page==='lesson'&&byId.has(id))return lesson(byId.get(id),mode,extra);if(page==='task'&&tasks.has(id)&&['guided','independent'].includes(mode)){const {t,l}=tasks.get(id);return practice(t,l,mode);}if(page==='number'&&books.includes(id))return numberPage(id);if(page==='progress')return progress();if(page==='sources')return sources();home();}
window.addEventListener('hashchange',route);route();
})();
