(function(root){'use strict';
const KEY='mathexam.mordkovichCircle.v1';
function create(lessons,storage){
 const tasks=new Map(lessons.flatMap(l=>l.tasks.map(t=>[t.id,t])));let raw='',warning='',blocked=false,snapshots={};
 const data={version:1,seen:{},records:{},sessions:{}};
 const shape=v=>v&&v.version===1&&v.seen&&typeof v.seen==='object'&&!Array.isArray(v.seen)&&v.records&&typeof v.records==='object'&&!Array.isArray(v.records)&&v.sessions&&typeof v.sessions==='object'&&!Array.isArray(v.sessions);
 function cleanDraft(d){const out={};if(!d||typeof d!=='object')return out;for(const[k,v]of Object.entries(d).slice(0,24)){if(k==='__proto__'||k==='constructor')continue;out[k]=Array.isArray(v)?v.slice(0,30).map(x=>String(x).slice(0,200)):String(v).slice(0,300);}return out;}
 function merge(v,loadSessions){for(const[id,t]of tasks){const seen=Number(v.seen[id]);if(Number.isFinite(seen)&&seen>=0)data.seen[id]=Math.max(data.seen[id]||0,Math.min(100000,Math.floor(seen)));const r=v.records[id];if(r&&typeof r==='object'){const own=data.records[id]||(data.records[id]={guided:false,independent:false,practised:false});own.guided=own.guided||r.guided===true;own.independent=own.independent||r.independent===true;own.practised=own.practised||r.practised===true;}}
  if(loadSessions)for(const[key,s]of Object.entries(v.sessions)){const i=key.lastIndexOf(':');const id=key.slice(0,i),mode=key.slice(i+1),t=tasks.get(id);if(!t||!s||!['guided','independent'].includes(mode)||!Number.isInteger(s.step)||s.step<0||s.step>t.steps.length)continue;const clean={taskId:id,mode,step:s.step,draft:cleanDraft(s.draft),solved:!!s.solved,done:!!s.done,assisted:mode==='guided'||!!s.assisted,wrong:!!s.wrong,familiar:!!s.familiar,angle:Number.isFinite(s.angle)?s.angle:0,started:typeof s.started==='string'?s.started.slice(0,40):'',registered:!!s.registered,updatedAt:Number.isFinite(s.updatedAt)?s.updatedAt:0};if(!data.sessions[key])data.sessions[key]=clean;else if(clean.updatedAt>(data.sessions[key].updatedAt||0))Object.assign(data.sessions[key],clean);}}
 try{raw=storage.getItem(KEY)||'';if(raw){const v=JSON.parse(raw);if(!shape(v))throw Error();merge(v,true);}}catch(_){blocked=true;warning='Сохранение недоступно или повреждено. Исходные данные оставлены без изменений. Текущую работу можно скачать в отчёте.';}
 snapshots=Object.fromEntries(Object.entries(data.sessions).map(([k,s])=>[k,JSON.stringify(s)]));
 function save(){if(blocked)return false;try{for(const[k,s]of Object.entries(data.sessions))if(JSON.stringify(s)!==snapshots[k])s.updatedAt=Math.max(Date.now(),(s.updatedAt||0)+1);const current=storage.getItem(KEY);if(current){const v=JSON.parse(current);if(!shape(v))throw Error();merge(v,true);}storage.setItem(KEY,JSON.stringify(data));snapshots=Object.fromEntries(Object.entries(data.sessions).map(([k,s])=>[k,JSON.stringify(s)]));return true;}catch(_){try{raw=storage.getItem(KEY)||raw;}catch(__){}blocked=true;warning='Не удалось сохранить результаты. Существующие данные не заменены; скачайте отчёт перед закрытием.';return false;}}
 function start(id,mode,restart=false){if(!tasks.has(id)||!['guided','independent'].includes(mode))throw Error('Unknown task');const key=id+':'+mode;if(data.sessions[key]&&!restart)return data.sessions[key];save();const s={taskId:id,mode,step:0,draft:{},solved:false,done:false,assisted:mode==='guided',wrong:false,familiar:!!data.seen[id],angle:0,started:new Date().toISOString(),registered:false};data.seen[id]=(data.seen[id]||0)+1;data.sessions[key]=s;save();return s;}
 function finish(s){if(s.registered)return;const r=data.records[s.taskId]||(data.records[s.taskId]={guided:false,independent:false,practised:false});r.practised=true;if(s.mode==='guided')r.guided=true;else if(!s.assisted&&!s.wrong&&!s.familiar)r.independent=true;s.done=true;s.registered=true;save();}
 function assistLesson(l){let changed=false;for(const t of l.tasks){const s=data.sessions[t.id+':independent'];if(s&&!s.done&&!s.assisted){s.assisted=true;changed=true;}}if(changed)save();}
 return {KEY,data,start,finish,save,assistLesson,get warning(){return warning},get original(){return raw},export(){return {kind:'mordkovich-circle',storage:'local-browser',exportedAt:new Date().toISOString(),...data}}};
}
const api={KEY,create};root.MordState=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
