(function(){'use strict';
const $=id=>document.getElementById(id),M=LabMath,fmt=(v,n=3)=>(Math.abs(v)<1e-9?0:+v.toFixed(n)).toString().replace('.',','),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=s=>{s=String(s).trim().replace(/−/g,'-').replace(',','.');return /^[+-]?(\d+(\.\d*)?|\.\d+)$/.test(s)?Number(s):null;};
let tab='stereo',solid=null,animation=0,quizState=null,report=[],runs={stereo:0,plane:0,trig:0,ineq:0};
const subjects={stereo:'Задания 11 и 13 · Объём и подобие',plane:'Задание 12 · Построение и доказательство',trig:'Задания 12 и 16 · Координаты и угол',ineq:'Задание 18 · Неравенства и числовая ось'};
function feedback(id,text,wrong=false){$(id).textContent=text;$(id).className='feedback'+(wrong?' warn':'');}
function stop(){if(animation)cancelAnimationFrame(animation);animation=0;if($('animateSolid'))$('animateSolid').textContent='▶ Запустить движение';}
function layout(visual,lesson){$('lab').innerHTML=`<div class="grid"><section class="card visual">${visual}</section><section class="card">${lesson}</section></div>`;}
function showTab(t){stop();if(quizState){quizState.assisted=true;}if(solid){solid.destroy();solid=null;}tab=t;document.querySelectorAll('[data-tab]').forEach(b=>{if(b.dataset.tab===t)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});$('subject').textContent=subjects[t];$('quiz').hidden=true;$('lab').hidden=false;({stereo:renderStereo,plane:renderPlane,trig:renderTrig,ineq:renderIneq})[t]();}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
const answerBlock=(id,label='Ваш ответ')=>`<div class="row"><label>${label}: <input id="${id}" class="num" inputmode="decimal" type="text" autocomplete="off"></label><button class="primary" id="${id}Check">Проверить</button></div>`;
function bindNumber(id,expected,success,wrong){$(id+'Check').onclick=()=>{const n=number($(id).value);if(n===null){wrong('Введите число. Можно использовать запятую.');return;}if(Math.abs(n-expected)<1e-6)success();else wrong();};$(id).onkeydown=e=>{if(e.key==='Enter')$(id+'Check').click();};}
let stereoMode='water',solidValue=0;
function renderStereo(){layout(`<div id="solid" class="canvas3d"></div><div class="controls"><div class="row"><button id="turnLeft" aria-label="Повернуть модель влево">↶ Повернуть</button><button id="turnRight" aria-label="Повернуть модель вправо">Повернуть ↷</button><button id="turnUp">Вид выше</button><button id="home">Начальный вид</button><button id="zoomIn">Приблизить</button><button id="zoomOut">Отдалить</button></div><label for="solidMode">Ситуация</label><select id="solidMode"><option value="water">Погружение детали — вытеснение воды</option><option value="cone">Сечение конуса — подобие и объём</option></select><label id="parameterLabel" for="solidParameter"></label><input type="range" id="solidParameter" min="0" max="100" step="1" value="0"><div class="row"><button id="animateSolid">▶ Запустить движение</button></div><p class="note">Модель можно вращать мышью или пальцем. Сосуд показан прозрачным, чтобы были видны вода и деталь.</p></div>`,`<span class="badge">ИССЛЕДУЕМ ОБЪЁМ</span><h2 id="solidTitle"></h2><p id="solidTask"></p><div class="facts" id="solidFacts"></div><p id="solidMeaning"></p><div class="formula" id="solidFormula"></div><div id="solidQuestion"></div><div id="solidFeedback" class="feedback" role="status"></div><details><summary>Связь с задачей на экзамене</summary><p id="solidExam"></p></details>`);
 solid=new SolidView($('solid'));$('solidMode').value=stereoMode;$('turnLeft').onclick=()=>solid.rotate(-.25);$('turnRight').onclick=()=>solid.rotate(.25);$('turnUp').onclick=()=>solid.rotate(0,-.15);$('home').onclick=()=>solid.home();$('zoomIn').onclick=()=>solid.zoom(.9);$('zoomOut').onclick=()=>solid.zoom(1.1);
 $('solidMode').onchange=()=>{stop();stereoMode=$('solidMode').value;solidValue=stereoMode==='water'?0:50;configureSolid();};$('solidParameter').oninput=()=>{stop();solidValue=+$('solidParameter').value;updateSolid();};$('animateSolid').onclick=()=>{if(animation){stop();return;}let previous=0;solidValue=stereoMode==='water'?0:10;$('animateSolid').textContent='❚❚ Остановить';const tick=time=>{if(!previous)previous=time;solidValue=Math.min(100,solidValue+Math.min(time-previous,100)*.012);previous=time;updateSolid();if(solidValue>=100){stop();return;}animation=requestAnimationFrame(tick);};animation=requestAnimationFrame(tick);};configureSolid();
}
function configureSolid(){const water=stereoMode==='water';$('solidParameter').min=water?0:10;$('solidParameter').max=100;$('solidParameter').value=solidValue;$('solidTitle').textContent=water?'Куда поднимается вода?':'Почему объём меняется в кубе?';$('solidTask').textContent=water?'В сосуде с площадью дна 100 см² налито 400 см³ воды. Медленно погружайте куб с ребром 4 см. Количество воды не меняется.':'Радиус исходного конуса 3 см, высота 6 см. Передвигайте параллельное основанию сечение. k — доля высоты малого конуса от вершины.';$('parameterLabel').textContent=water?'Погружение детали':'k: доля высоты от вершины';$('solidQuestion').innerHTML=(water?'<h3>Теперь другая задача</h3><p>Площадь дна 80 см². После полного погружения детали уровень поднялся на 1,5 см. Найдите объём детали в см³.</p>':'<h3>Предскажите без движения</h3><p>Малый конус имеет половину высоты исходного. Во сколько раз его объём меньше?</p>')+answerBlock('solidAnswer');bindNumber('solidAnswer',water?120:8,()=>feedback('solidFeedback',water?'Верно: 80 · 1,5 = 120 см³. Дополнительный объём под уровнем воды заняла деталь.':'Верно: (1/2)³ = 1/8. Уменьшились и высота, и две линейные величины, задающие площадь основания.'),message=>feedback('solidFeedback',message||(water?'Нужно умножить площадь дна на подъём уровня, а не на полную высоту воды.':'При k = 1/2 радиус тоже уменьшается вдвое. Во сколько раз уменьшится площадь основания?'),true));$('solidExam').textContent=water?'При полном погружении объём детали равен Sдна · Δh. Для неполного погружения это объём только погружённой части. Сосуд должен вмещать воду без перелива.':'Считать отношение высот нужно от общей вершины. Если высоту разделили 1 : 2 от вершины, k = 1/3, а отношение объёмов равно 1/27. Это не 1/2 и не 1/3.';feedback('solidFeedback','');solid.mode=stereoMode;solid.home();updateSolid();}
function updateSolid(){const k=solidValue/100;$('solidParameter').value=solidValue;solid.set(stereoMode,k);if(stereoMode==='water'){const b=7*(1-k),level=M.water(b),submerged=16*Math.max(0,Math.min(4,level-b));$('solidFacts').innerHTML=`<div>Уровень воды<b>${fmt(level)} см</b></div><div>Подъём уровня<b>${fmt(level-4)} см</b></div>`;$('solidMeaning').textContent=submerged<1e-6?'Деталь пока не касается воды. Уровень остаётся прежним.':submerged<64-1e-6?'В воде только часть детали. Уровень растёт по мере погружения.':'Вся деталь под водой. Дальнейшее опускание не меняет уровень.';$('solidFormula').textContent=`Погружённая часть: ${fmt(submerged)} см³ = 100 · ${fmt(level-4)} см³ (округлённо).`;}else{const c=M.cone(k);$('solidFacts').innerHTML=`<div>Доля высоты k<b>${fmt(k)}</b></div><div>Доля объёма k³<b>${fmt(c.volumeRatio)}</b></div>`;$('solidMeaning').textContent=`Высота малого конуса ${fmt(c.height)} см, радиус ${fmt(c.radius)} см. Площадь основания меняется в k² раз, затем ещё умножается на k из-за высоты.`;$('solidFormula').textContent=`Vмал / Vбольш = k² · k = k³ = ${fmt(c.volumeRatio,5)}.`;}}
let planeMode='median',planeVariant=0,planeStep=0,planeTool='midpoint',chosenPoints=[],planeLog=[],planePlan=false,planeMethod='median';
const triangles=[[10,12],[13,10],[17,16]],circles=[[5,6],[6.5,5],[8.5,8]];
function renderPlane(){planePlan=false;planeMethod='median';planeStep=0;planeLog=[];chosenPoints=[];planeTool=planeMode==='median'?'midpoint':'segment';layout(`<svg id="planeSvg" class="drawing" viewBox="0 0 420 340" role="img" aria-label="Чертёж задачи. Для выбора точек также доступны кнопки ниже."></svg><div class="controls"><label for="planeMode">Задача с построением</label><select id="planeMode"><option value="median">Равнобедренный треугольник: медиана и площадь</option><option value="circle">Хорды и прямой угол</option></select><div class="tools"><button data-tool="midpoint">Середина двух точек</button><button data-tool="segment">Отрезок по двум точкам</button><button data-tool="perpendicular">Перпендикуляр к прямой</button></div><p id="constructionHelp" class="note"></p><div class="row pointcontrols" id="pointButtons"></div><div class="row" style="margin-top:12px"><button id="resetPlane">Начать построение заново</button><button id="newPlane">Другие размеры</button></div></div>`,`<span class="badge">ПОСТРОЙТЕ СВОИМИ РУКАМИ</span><h2 id="planeTitle"></h2><p id="planeGiven"></p><div class="pill" id="planeStep"></div><div id="planeInstruction"></div><div class="feedback" id="planeFeedback" role="status"></div><div class="steps" id="planeLog"></div>`);$('planeMode').value=planeMode;$('planeMode').onchange=()=>{planeMode=$('planeMode').value;renderPlane();};$('resetPlane').onclick=renderPlane;$('newPlane').onclick=()=>{planeVariant=(planeVariant+1)%3;renderPlane();};document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{planeTool=b.dataset.tool;chosenPoints=[];drawPlane();});planeInstruction();drawPlane();}
function planeData(){if(planeMode==='median'){const [a,b]=triangles[planeVariant],h=M.isosceles(a,b).height;return {a,b,h,points:{A:[-b/2,0],B:[0,h],C:[b/2,0],M:[0,0]}};}const[r,ac]=circles[planeVariant],p=M.chord(r,ac);return {r,ac,bc:p.other,points:{A:[-r,0],B:[r,0],C:[p.x,p.y]}};}
function drawPlane(){const d=planeData(),median=planeMode==='median',s=median?Math.min(330/d.b,235/d.h):135/d.r,X=x=>210+x*s,Y=y=>median?285-y*s:180-y*s,points=d.points;let svg='';const seg=(a,b,color='#315a70',width=3,dash='')=>`<line x1="${X(points[a][0])}" y1="${Y(points[a][1])}" x2="${X(points[b][0])}" y2="${Y(points[b][1])}" stroke="${color}" stroke-width="${width}" stroke-dasharray="${dash}"/>`;
 if(median){svg+=`<polygon points="${['A','B','C'].map(n=>[X(points[n][0]),Y(points[n][1])].join(',')).join(' ')}" fill="#edf4ee" stroke="#315a70" stroke-width="3"/>`;if(planeStep>=2)svg+=seg('B','M','#b65e22');if(planeStep>=3)svg+=`<path d="M210,273h12v12" fill="none" stroke="#b65e22" stroke-width="2"/>`;svg+=`<text x="90" y="${Y(d.h/2)}" font-size="21">${d.a}</text><text x="312" y="${Y(d.h/2)}" font-size="21">${d.a}</text><text x="210" y="327" text-anchor="middle" font-size="21">AC = ${d.b}</text>`;}else{svg+=`<circle cx="210" cy="180" r="135" fill="#f2f6ef" stroke="#315a70" stroke-width="2"/>`+seg('A','B');if(planeStep>=1)svg+=seg('A','C','#b65e22');if(planeStep>=2)svg+=seg('B','C','#b65e22');svg+=`<text x="210" y="207" text-anchor="middle" font-size="19">AB = ${2*d.r}</text>`;if(planeStep>=1)svg+=`<text x="${(X(points.A[0])+X(points.C[0]))/2-27}" y="${(Y(points.A[1])+Y(points.C[1]))/2}" font-size="18">${d.ac}</text>`;}
 const names=Object.keys(points).filter(n=>n!=='M'||planeStep>=1);for(const n of names){const [x,y]=points[n],selected=chosenPoints.includes(n);svg+=`<g data-point="${n}" style="cursor:pointer"><circle cx="${X(x)}" cy="${Y(y)}" r="19" fill="transparent"/><circle cx="${X(x)}" cy="${Y(y)}" r="${selected?9:6}" fill="${selected?'#b65e22':'#086d5b'}"/><text x="${X(x)+12}" y="${Y(y)-10}" font-size="22" font-weight="650">${n}</text></g>`;}$('planeSvg').innerHTML=svg;$('planeSvg').querySelectorAll('[data-point]').forEach(el=>el.onclick=()=>choosePoint(el.dataset.point));$('pointButtons').innerHTML=names.map(n=>`<button data-pick="${n}" aria-pressed="${chosenPoints.includes(n)}">${n}</button>`).join('');$('pointButtons').querySelectorAll('button').forEach(b=>b.onclick=()=>choosePoint(b.dataset.pick));document.querySelectorAll('[data-tool]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tool===planeTool)));$('constructionHelp').textContent=planeTool==='perpendicular'?'Выберите точку, из которой опускаете перпендикуляр, затем две точки прямой.':planeTool==='midpoint'?'Выберите две точки — построим середину отрезка.':'Выберите начало и конец отрезка. Нажимать можно на чертеже или на кнопках.';}
function choosePoint(n){
 if(!planePlan){feedback('planeFeedback','Сначала выберите идею дополнительного построения.',true);return;}
 if(planeStep>1){feedback('planeFeedback','Построение готово. Теперь объясните его и выполните вычисления.');return;}
 if(chosenPoints.includes(n)){chosenPoints=[];drawPlane();return;}chosenPoints.push(n);
 if(planeTool==='perpendicular'){
  if(chosenPoints.length===3){const [from,a,b]=chosenPoints;chosenPoints=[];
   if(planeMode==='median'&&planeMethod==='height'&&planeStep===0&&from==='B'&&[a,b].sort().join('')==='AC'){
    const pts=planeData().points,foot=M.perpendicularFoot(pts[from],pts[a],pts[b]);
    if(foot&&Math.abs(foot[0])<1e-8&&Math.abs(foot[1])<1e-8){planeStep=2;planeLog.push('Из B опущен перпендикуляр BM к прямой AC. M — основание высоты.');feedback('planeFeedback','Высота построена. Теперь обоснуйте, почему M — середина.');planeInstruction();}
   }else feedback('planeFeedback',planeMode==='circle'?'Здесь нужны хорды AC и BC. Выберите инструмент «Отрезок».':planeMethod==='height'?'Выберите сначала вершину B, затем A и C: нужна высота к основанию.':'Выбран путь через середину AC. Для пути через высоту начните построение заново.',true);
  }drawPlane();return;
 }
 if(chosenPoints.length===2){const pair=chosenPoints.slice().sort().join(''),median=planeMode==='median',needPair=median?(planeStep===0?'AC':'BM'):(planeStep===0?'AC':'BC'),needTool=median&&planeStep===0?'midpoint':'segment';chosenPoints=[];
 if(planeMethod==='height'&&median){feedback('planeFeedback','Для выбранного способа нужен инструмент «Перпендикуляр».',true);}
 else if(pair===needPair&&planeTool===needTool){planeLog.push(median?(planeStep===0?'Построена середина M стороны AC.':'Проведена медиана BM.'):(planeStep===0?'Проведена хорда AC.':'Проведена хорда BC.'));planeStep++;planeTool='segment';feedback('planeFeedback','Построение выполнено.');planeInstruction();}
 else feedback('planeFeedback','Это построение не выполняет текущий шаг. Проверьте инструмент и выбранные точки.',true);
 }drawPlane();}
function planeInstruction(){const d=planeData(),median=planeMode==='median';$('planeTitle').textContent=median?'Высота, которую Вы построили':'Прямой угол из диаметра';$('planeGiven').textContent=median?`AB = BC = ${d.a}, AC = ${d.b}. Найдите площадь треугольника ABC.`:`AB — диаметр окружности, AB = ${2*d.r}. Точка C лежит на окружности, AC = ${d.ac}. Найдите BC.`;$('planeStep').textContent=planeStep<5?`Шаг ${planeStep+1} из 5`:'Решение завершено';$('planeLog').innerHTML=planeLog.map(t=>`<p class="stepdone">${esc(t)}</p>`).join('');const box=$('planeInstruction');
 if(!planePlan){$('planeStep').textContent='Сначала идея';box.innerHTML='<p class="taskquestion">Какое построение поможет найти искомую величину?</p><div class="options">'+(median?['Медиана из B к основанию AC','Высота из B к основанию AC','Только продолжить боковую сторону AB']:['Соединить C с концами диаметра A и B','Только провести касательную в C','Только отметить центр окружности']).map((v,i)=>`<button data-plan="${i}">${v}</button>`).join('')+'</div>';box.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>{const k=+b.dataset.plan;if(median?k<2:k===0){planePlan=true;planeMethod=median&&k===1?'height':'median';planeTool=planeMethod==='height'?'perpendicular':median?'midpoint':'segment';planeLog.push(median?(k===1?'Идея: найти высоту и использовать площадь.':'Идея: медиана к основанию даёт высоту.'):'Идея: получить вписанный угол, опирающийся на диаметр.');feedback('planeFeedback','Теперь выполните выбранное построение.');planeInstruction();drawPlane();}else feedback('planeFeedback',median?'Так не появятся ни известная высота, ни удобный прямоугольный треугольник. Что нужно для площади?':'Нам нужен треугольник с диаметром-гипотенузой. Какие две хорды его образуют?',true);});return;}
 if(median&&planeMethod==='height'&&planeStep===0){box.innerHTML='<p class="taskquestion">Опустите перпендикуляр из B на прямую AC.</p><p>Инструмент «Перпендикуляр»: выберите B, затем A и C.</p>';return;}
 if(planeStep<2){box.innerHTML=`<p class="taskquestion">${median?(planeStep===0?'Постройте середину M стороны AC.':'Соедините вершину B с точкой M.'):(planeStep===0?'Проведите хорду AC.':'Проведите хорду BC, чтобы появился треугольник.')}</p><p>Выберите инструмент под чертежом и две нужные точки.</p>`;return;}
 if(planeStep===2){box.innerHTML=`<p class="taskquestion">${median?(planeMethod==='height'?'Почему M делит AC пополам?':'Почему BM — ещё и высота?'):'Почему угол ACB прямой?'}</p><div class="options">${(median?(planeMethod==='height'?['Любая высота делит сторону пополам','В равнобедренном треугольнике высота к основанию — медиана','Это верно только по рисунку']:['Любая медиана — высота','В равнобедренном треугольнике медиана к основанию — высота','Так кажется на рисунке']):['Он опирается на диаметр AB','Все углы на окружности прямые','У хорды всегда прямой угол']).map((t,i)=>`<button data-reason="${i}">${t}</button>`).join('')}</div>`;box.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(+b.dataset.reason===(median?1:0)){planeLog.push(median?'BM ⟂ AC: использовано свойство равнобедренного треугольника.':'∠ACB = 90°: вписанный угол опирается на диаметр.');planeStep++;feedback('planeFeedback','Верное обоснование.');planeInstruction();drawPlane();}else feedback('planeFeedback','Нужно свойство фигуры, которое следует из условия, а не из её внешнего вида.',true);});return;}
 if(!median&&planeStep===3){box.innerHTML='<p class="taskquestion">Какая сторона — гипотенуза?</p><div class="choices">'+['AC','BC','AB'].map(n=>`<button data-hyp="${n}">${n}</button>`).join('')+'</div>';box.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(b.dataset.hyp==='AB'){planeLog.push('Гипотенуза AB лежит напротив прямого угла C.');planeStep++;planeInstruction();}else feedback('planeFeedback','Гипотенуза лежит напротив прямого угла.',true);});return;}
 if(planeStep<5){const value=median?(planeStep===3?d.h:d.b*d.h/2):d.bc;box.innerHTML=`<p class="taskquestion">${median?(planeStep===3?`AM = ${d.b/2}. Найдите BM по теореме Пифагора.`:'Вычислите площадь по основанию AC и высоте BM.'):'Вычислите длину BC по теореме Пифагора.'}</p>`+answerBlock('planeAnswer');bindNumber('planeAnswer',value,()=>{planeLog.push(median?(planeStep===3?`BM = √(${d.a}² − ${d.b/2}²) = ${fmt(d.h)}.`:`S = ${d.b} · ${fmt(d.h)} / 2 = ${fmt(value)}.`):`BC = √(${2*d.r}² − ${d.ac}²) = ${fmt(d.bc)}.`);planeStep++;feedback('planeFeedback','Верно.');planeInstruction();drawPlane();},m=>feedback('planeFeedback',m||(median&&planeStep===4?'В формуле площади треугольника есть деление на 2.':'Вычтите квадрат известного катета из квадрата гипотенузы, затем извлеките корень.'),true));return;}
 box.innerHTML='<h3>Построение → свойство → вычисление</h3><p>Вы построили вспомогательный отрезок и обосновали, почему он помогает. Теперь попробуйте другие размеры или самостоятельную проверку.</p>';}
let angle=30,trigDragging=false,lastPointerAngle=0;
function exactTrig(value){const entries=[[0,'0'],[.5,'1/2'],[-.5,'−1/2'],[Math.SQRT1_2,'√2/2'],[-Math.SQRT1_2,'−√2/2'],[Math.sqrt(3)/2,'√3/2'],[-Math.sqrt(3)/2,'−√3/2'],[1,'1'],[-1,'−1']];return entries.find(([n])=>Math.abs(n-value)<1e-8)?.[1]||'≈ '+fmt(value);}
function renderTrig(){layout(`<svg id="circleSvg" class="drawing interactive" viewBox="0 0 420 420" role="img" aria-label="Единичная окружность. Угол изменяется перетаскиванием точки или управлением ниже."></svg><div class="legend"><span class="cos">x = cos α</span><span class="sin">y = sin α</span></div><div class="controls"><label for="angle">Угол α, градусы</label><input type="range" id="angle" min="-720" max="1080" step="1" value="30"><div class="row"><button data-angle-delta="-360">− оборот</button><button data-angle-delta="-30">−30°</button><button data-angle-delta="30">+30°</button><button data-angle-delta="360">+ оборот</button></div><label for="angleInput">Точное значение угла</label><div class="row"><input id="angleInput" class="num" type="number" min="-720" max="1080" step="1" value="30"><button id="setAngle">Поставить точку</button></div><label><input type="checkbox" id="showTan"> Показать ось тангенсов x = 1</label><div class="row" style="margin-top:12px"><button data-jump="30">30°</button><button data-jump="150">150°</button><button data-jump="-210">−210°</button><button data-jump="750">750°</button><button data-jump="90">90°</button></div></div>`,`<span class="badge">ОТ ТРЕУГОЛЬНИКА К ОКРУЖНОСТИ</span><h2>Угол — путь.<br>Синус и косинус — координаты.</h2><div class="formula" id="angleReadout"></div><div class="facts" id="trigFacts"></div><p id="quadrant"></p><p id="turnMeaning"></p><p id="tanMeaning"></p><details open><summary>Почему именно координаты?</summary><p>Радиус равен 1. В первой четверти горизонтальный катет, делённый на гипотенузу, равен x/1 = x: это косинус. Вертикальный катет даёт синус.</p><p>За пределами первой четверти длина катета остаётся положительной, но координаты имеют знаки. Поэтому синус и косинус определяем через координаты точки, а не через длины катетов.</p><p>Радианы измеряют угол отношением длины дуги к радиусу. На единичной окружности полный оборот: 2π радиан = 360°.</p></details><h3>Проверьте три связи</h3><ol><li>Перейдите от 30° к 150°: какая координата сохранилась?</li><li>Сравните 150° и −210°: точка та же, а путь другой.</li><li>Поставьте 750°: уберите два оборота и найдите синус.</li></ol><p class="taskquestion">Вычислите 24 sin 750°.</p>${answerBlock('trigAnswer')}<div id="trigFeedback" class="feedback" role="status"></div>`);
 $('angle').oninput=()=>setAngle(+$('angle').value);$('setAngle').onclick=()=>{const n=number($('angleInput').value);if(n===null||n< -720||n>1080||!Number.isInteger(n)){feedback('trigFeedback','Введите целое число градусов от −720 до 1080.',true);return;}setAngle(n);};$('angleInput').onkeydown=e=>{if(e.key==='Enter')$('setAngle').click();};document.querySelectorAll('[data-angle-delta]').forEach(b=>b.onclick=()=>setAngle(angle+ +b.dataset.angleDelta));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>setAngle(+b.dataset.jump));$('showTan').onchange=drawTrig;
 const svg=$('circleSvg'),pointerAngle=e=>{const r=svg.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*420-190,y=210-(e.clientY-r.top)/r.height*420;return Math.atan2(y,x)*180/Math.PI;};svg.onpointerdown=e=>{trigDragging=true;lastPointerAngle=pointerAngle(e);svg.setPointerCapture(e.pointerId);};svg.onpointermove=e=>{if(!trigDragging)return;const a=pointerAngle(e);let delta=a-lastPointerAngle;if(delta>180)delta-=360;if(delta< -180)delta+=360;lastPointerAngle=a;setAngle(angle+delta);};svg.onpointerup=svg.onpointercancel=()=>trigDragging=false;bindNumber('trigAnswer',12,()=>feedback('trigFeedback','Верно: 750° = 720° + 30°, sin 750° = 1/2, поэтому 24 · 1/2 = 12.'),m=>feedback('trigFeedback',m||'Полные обороты не меняют координаты. После двух оборотов остаётся 30°. Нужна вертикальная координата.',true));drawTrig();}
function setAngle(v){angle=Math.max(-720,Math.min(1080,Math.round(v)));drawTrig();}
function drawTrig(){const a=M.trig(angle),r=130,cx=190,cy=210,x=cx+r*a.cos,y=cy-r*a.sin;let s=`<defs><clipPath id="trigClip"><rect x="18" y="25" width="380" height="365"/></clipPath></defs><line x1="20" y1="210" x2="395" y2="210" stroke="#91a49b"/><line x1="190" y1="25" x2="190" y2="390" stroke="#91a49b"/><circle cx="190" cy="210" r="130" fill="#f5f7ef" fill-opacity=".5" stroke="#6c8578" stroke-width="2"/><text x="387" y="200" font-size="18">x</text><text x="201" y="29" font-size="18">y</text><text x="325" y="235" font-size="18">1</text><text x="44" y="236" font-size="18">−1</text><text x="202" y="80" font-size="18">1</text><text x="202" y="355" font-size="18">−1</text>`;
 const steps=Math.max(2,Math.ceil(a.principal/4));let arc='';for(let i=0;i<=steps;i++){const t=a.principal*i/steps*Math.PI/180;arc+=(i?'L':'M')+(cx+42*Math.cos(t))+','+(cy-42*Math.sin(t));}s+=`<path d="${arc}" fill="none" stroke="#8b5dac" stroke-width="3"/><path d="M190,210H${x}V${y}Z" fill="#f1dbc8" opacity=".45"/><line x1="190" y1="210" x2="${x}" y2="${y}" stroke="#315f8e" stroke-width="3"/><line x1="190" y1="210" x2="${x}" y2="210" stroke="#086d5b" stroke-width="5"/><line x1="190" y1="210" x2="190" y2="${y}" stroke="#ab4b17" stroke-width="5"/><path d="M${x},210V${y}H190" fill="none" stroke="#8a9d93" stroke-dasharray="5 5"/><circle cx="${x}" cy="${y}" r="9" fill="#315f8e" stroke="white" stroke-width="3"/><text x="${x+12}" y="${y-12}" font-size="22" font-weight="700">P</text>`;
 if($('showTan').checked){s+=`<line x1="320" y1="30" x2="320" y2="385" stroke="#9068a3" stroke-width="2"/>`;if(a.tan!==null)s+=`<g clip-path="url(#trigClip)"><line x1="60" y1="${cy+r*a.tan}" x2="320" y2="${cy-r*a.tan}" stroke="#9068a3" stroke-dasharray="5 5"/><line x1="320" y1="210" x2="320" y2="${cy-r*a.tan}" stroke="#9068a3" stroke-width="5"/><circle cx="320" cy="${cy-r*a.tan}" r="5" fill="#9068a3"/></g>`;}
 $('circleSvg').innerHTML=s;$('angle').value=angle;$('angleInput').value=angle;$('angleReadout').textContent=`α = ${angle}° = ${M.radLabel(angle)} рад`;$('trigFacts').innerHTML=`<div>Горизонталь · cos α<b>${exactTrig(a.cos)}</b></div><div>Вертикаль · sin α<b>${exactTrig(a.sin)}</b></div>`;$('quadrant').textContent=a.principal%90===0?'Точка на координатной оси. Одна из координат равна нулю.':`Точка в ${Math.floor(a.principal/90)+1}-й четверти. Косинус ${a.cos>0?'положителен':'отрицателен'}, синус ${a.sin>0?'положителен':'отрицателен'}.`;const turns=(angle-a.principal)/360;$('turnMeaning').textContent=`${angle}° = ${turns} · 360° + ${a.principal}°. Та же точка, что при ${a.principal}°. Положительное направление — против часовой стрелки; отрицательное — по часовой.`;$('tanMeaning').textContent=$('showTan').checked?(a.tan===null?'cos α = 0. Тангенс не определён: делить на ноль нельзя.':`tg α = sin α / cos α ≈ ${fmt(a.tan)}.`+(Math.abs(a.tan)>1.3?' Пересечение с осью тангенсов за пределами окна.':'')):'';}
let caseIndex=0,ineqStep=0,selectedZones=[],selectedClosed=[];
function renderIneq(){ineqStep=0;const t=M.cases[caseIndex];selectedZones=t.zones.map(()=>false);selectedClosed=t.closed.map(()=>false);layout(`<div class="controls"><label for="ineqCase">Навык внутри задания 18</label><select id="ineqCase">${M.cases.map((c,i)=>`<option value="${i}">${i+1}. ${c.title}</option>`).join('')}</select></div><svg id="numberLine" class="drawing" viewBox="0 0 540 180" role="img" aria-label="Числовая прямая с выбираемыми промежутками"></svg><div class="controls"><div id="intervalControls" hidden><p class="note">Нажмите на нужные промежутки. Для каждой границы выберите: входит она или нет.</p><div id="zoneButtons" class="zonebuttons"></div><div id="endButtons" class="boundary"></div><p id="selectedInterval" class="formula"></p><label for="probe">Проверить отдельное число подстановкой</label><input id="probe" type="range" min="-6" max="7" step="0.25" value="0"><p id="probeText" class="testpoint"></p></div><p class="note">Сперва область определения и границы. Затем — построение решения.</p></div>`,`<span class="badge">СОБИРАЕМ РЕШЕНИЕ НА ОСИ</span><h2 id="ineqTitle"></h2><div class="formula" id="ineqExpression"></div><div class="pill" id="ineqStep"></div><div id="ineqInstruction"></div><div class="feedback" id="ineqFeedback" role="status"></div><div id="ineqSummary"></div><details><summary>Четыре вопроса к каждому неравенству</summary><ol><li>Где выражение определено?</li><li>Где оно равно нулю или не определено?</li><li>Какой знак на каждом промежутке?</li><li>Какие границы входят?</li></ol><p>Закрашенная точка входит, пустая — нет. «И» означает пересечение условий; «или» — объединение решений.</p></details>`);$('ineqCase').value=caseIndex;$('ineqCase').onchange=()=>{caseIndex=+$('ineqCase').value;renderIneq();};$('probe').oninput=drawProbe;ineqInstruction();drawNumberLine();}
function ineqInstruction(){const t=M.cases[caseIndex];$('ineqTitle').textContent=t.title;$('ineqExpression').textContent=t.expr;$('ineqStep').textContent=`Шаг ${Math.min(3,ineqStep+1)} из 3`;$('intervalControls').hidden=ineqStep<2;const box=$('ineqInstruction');if(ineqStep===0){box.innerHTML='<h3>Где выражение определено?</h3><div class="options">'+t.domainOptions.map((s,i)=>`<button data-domain="${i}">${s}</button>`).join('')+'</div>';box.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(+b.dataset.domain===t.domainAnswer){ineqStep++;feedback('ineqFeedback','Область определения учтена.');ineqInstruction();}else feedback('ineqFeedback','Проверьте знаменатели и аргументы логарифмов. Нули числителя сами по себе не запрещены.',true);});return;}
 if(ineqStep===1){box.innerHTML=`<h3>Найдите границы промежутков</h3><p>${t.boundary}</p><p class="note">${t.boundaryAnswer.length===1?'Введите одно число.':'Введите два числа через точку с запятой.'}</p><div class="row"><label>Границы: <input class="num" id="boundaries" type="text" placeholder="${t.roots.length===1?'число':'a; b'}"></label><button class="primary" id="checkBounds">Продолжить</button></div>`;$('checkBounds').onclick=()=>{const a=$('boundaries').value.split(';').map(number).sort((x,y)=>x-y);if(a.length===t.boundaryAnswer.length&&a.every((v,i)=>v!==null&&Math.abs(v-t.boundaryAnswer[i])<1e-8)){ineqStep++;feedback('ineqFeedback','Границы найдены. Постройте множество решений.');ineqInstruction();drawNumberLine();drawProbe();}else feedback('ineqFeedback','Пересчитайте границы. Для дробей учитываются нули числителя и знаменателя; для логарифма — также граница ОДЗ.',true);};$('boundaries').onkeydown=e=>{if(e.key==='Enter')$('checkBounds').click();};return;}
 box.innerHTML='<h3>Постройте решение</h3><p>Выберите все подходящие промежутки и отметьте границы.</p><div class="row"><button id="checkIntervals" class="primary">Проверить построение</button><button id="ineqHint">Подсказка</button></div>';$('ineqHint').onclick=()=>feedback('ineqFeedback',t.hint);$('checkIntervals').onclick=()=>{if(selectedZones.every((v,i)=>v===t.zones[i])&&selectedClosed.every((v,i)=>v===t.closed[i])){feedback('ineqFeedback','Верно. '+t.why);$('ineqSummary').innerHTML=`<div class="formula">${esc(t.answer)}</div><p>На самостоятельной проверке потребуется узнать такое решение среди нескольких рисунков.</p>`;}else{const forbidden=t.roots.some((v,i)=>selectedClosed[i]&&!t.domain(v));feedback('ineqFeedback',forbidden?'Включена точка, в которой исходное выражение не определено. Проверьте область определения.':'Проверьте знаки на промежутках и каждую границу отдельно. Используйте подстановку пробной точки.',true);}};drawIntervalControls();}
const LX=v=>35+(v+6)/13*470;
function drawNumberLine(){const t=M.cases[caseIndex];let s='<line x1="25" y1="90" x2="520" y2="90" stroke="#617970" stroke-width="2"/>';for(let n=-6;n<=7;n++){s+=`<line x1="${LX(n)}" x2="${LX(n)}" y1="83" y2="97" stroke="#91a69a"/>`;if(n===-6||n===0||n===7||(ineqStep>=2&&t.roots.includes(n)))s+=`<text x="${LX(n)}" y="127" text-anchor="middle" font-size="20">${n}</text>`;};if(ineqStep>=2){const bounds=[-6,...t.roots,7];for(let i=0;i<selectedZones.length;i++){if(selectedZones[i])s+=`<line x1="${LX(bounds[i])}" x2="${LX(bounds[i+1])}" y1="90" y2="90" stroke="#187963" stroke-width="10"/>`;s+=`<rect data-zone="${i}" x="${LX(bounds[i])+10}" y="52" width="${Math.max(8,LX(bounds[i+1])-LX(bounds[i])-20)}" height="60" fill="transparent" style="cursor:pointer"/>`;}t.roots.forEach((v,i)=>{s+=`<g data-end="${i}" style="cursor:pointer"><circle cx="${LX(v)}" cy="90" r="19" fill="transparent"/><circle cx="${LX(v)}" cy="90" r="8" stroke="#174e43" stroke-width="3" fill="${selectedClosed[i]?'#174e43':'white'}"/></g>`;});}$('numberLine').innerHTML=s;$('numberLine').querySelectorAll('[data-zone]').forEach(el=>el.onclick=()=>toggleZone(+el.dataset.zone));$('numberLine').querySelectorAll('[data-end]').forEach(el=>el.onclick=()=>toggleEnd(+el.dataset.end));if(ineqStep>=2)drawIntervalControls();}
function toggleZone(i){selectedZones[i]=!selectedZones[i];drawNumberLine();drawProbe();}function toggleEnd(i){selectedClosed[i]=!selectedClosed[i];drawNumberLine();drawProbe();}
function drawIntervalControls(){const t=M.cases[caseIndex],b=['−∞',...t.roots,'+∞'];$('zoneButtons').innerHTML=selectedZones.map((v,i)=>`<button data-zone-button="${i}" aria-pressed="${v}">(${b[i]}; ${b[i+1]})</button>`).join('');$('zoneButtons').querySelectorAll('button').forEach(el=>el.onclick=()=>toggleZone(+el.dataset.zoneButton));$('endButtons').innerHTML=t.roots.map((v,i)=>`<button data-end-button="${i}" aria-pressed="${selectedClosed[i]}">${selectedClosed[i]?'●':'○'} ${v}: ${selectedClosed[i]?'входит':'не входит'}</button>`).join('');$('endButtons').querySelectorAll('button').forEach(el=>el.onclick=()=>toggleEnd(+el.dataset.endButton));const chosen=selectedZones.map((v,i)=>v?`(${b[i]}; ${b[i+1]})`:null).filter(Boolean),points=t.roots.filter((v,i)=>selectedClosed[i]);$('selectedInterval').textContent='Выбрано: '+(chosen.concat(points.map(v=>`{${v}}`)).join(' ∪ ')||'пустое множество');}
function drawProbe(){const t=M.cases[caseIndex],x=+$('probe').value;if(!t.domain(x)){$('probeText').textContent=`x = ${fmt(x)}: выражение не определено. Эта точка не может входить.`;return;}const ok=M.contains(t,x),marked=M.selectedContains(t,x,selectedZones,selectedClosed);$('probeText').textContent=`x = ${fmt(x)}: разность левой и правой частей ≈ ${fmt(t.value(x))}. Исходное неравенство ${ok?'верно':'неверно'}. У Вас точка ${marked?'включена':'не включена'}.`;}
const lineSVG=(min,max,roots,zones,closed,labels)=>{const X=x=>25+(x-min)/(max-min)*430;let s='<svg class="drawing quizgraph" viewBox="0 0 480 130" role="img" aria-label="Числовая ось"><line x1="20" x2="460" y1="65" y2="65" stroke="#657e73" stroke-width="2"/>';for(let n=Math.ceil(min);n<=max;n++)s+=`<line x1="${X(n)}" x2="${X(n)}" y1="60" y2="70" stroke="#91a79b"/><text x="${X(n)}" y="100" text-anchor="middle" font-size="16">${n}</text>`;const b=[min,...roots,max];zones.forEach((v,i)=>{if(v)s+=`<line x1="${X(b[i])}" x2="${X(b[i+1])}" y1="65" y2="65" stroke="#19765f" stroke-width="8"/>`;});roots.forEach((v,i)=>{s+=`<circle cx="${X(v)}" cy="65" r="6" fill="${closed[i]?'#153e31':'white'}" stroke="#153e31" stroke-width="2"/>`;if(labels)s+=`<text x="${X(v)}" y="44" text-anchor="middle" font-size="18">${labels[i]}</text>`;});return s+'</svg>';};
const quizBanks={
stereo:[
 {q:'В сосуд полностью погрузили деталь. Площадь дна 75 см², уровень поднялся на 1,2 см. Объём детали, см³?',a:90,why:'Объём детали равен 75 · 1,2 = 90 см³.'},
 {q:'В сосуде с постоянной площадью сечения было 6 л воды. После полного погружения детали уровень стал в 1,25 раза выше. Объём детали, см³?',a:1500,why:'Прирост занятого объёма: 6 · 0,25 = 1,5 л = 1500 см³. Сама вода не прибавилась.'},
 {q:'Параллельное основанию сечение отсекло от конуса малый конус с высотой в 3 раза меньше исходной. Его объём 5. Найдите объём исходного конуса.',a:135,why:'Линейный масштаб 1/3. Объём малого конуса составляет 1/27, поэтому исходный объём 5 · 27 = 135.'},
 {q:'Воду из цилиндра высотой слоя 20 см перелили в цилиндр с радиусом вдвое больше. Какова высота слоя, см?',a:5,why:'Площадь основания выросла в 4 раза. При том же объёме высота 20 / 4 = 5 см.'}
],
plane:[
 {q:'У равнобедренного треугольника боковые стороны 15, основание 18. Медиана к основанию проведена. Чему равна его площадь?',a:108,why:'Половина основания 9. Высота √(225 − 81) = 12. Площадь 18 · 12 / 2 = 108.'},
 {q:'AB — диаметр 25, C на окружности. Хорда AC = 7. Найдите BC.',a:24,why:'∠ACB прямой. BC = √(25² − 7²) = √576 = 24.'},
 {q:'В каком случае медиана треугольника гарантированно является высотой?',options:['В любом треугольнике','Медиана к основанию равнобедренного треугольника','Если на рисунке она вертикальна'],a:1,why:'Нужно свойство фигуры. Вертикальное положение на экране ничего не доказывает.'},
 {q:'В прямоугольном треугольнике гипотенуза 13, один катет 5. Найдите второй катет.',a:12,why:'Квадрат катета равен 13² − 5² = 144, катет равен 12.'}
],
trig:[
 {q:'Найдите 18 sin 390°.',a:9,why:'390° = 360° + 30°. Синус равен 1/2; произведение равно 9.'},
 {q:'Чему равен cos 150°?',options:['√3/2','−√3/2','1/2','−1/2'],a:1,why:'150° во второй четверти. Горизонтальная координата отрицательна: cos 150° = −cos 30° = −√3/2.'},
 {q:'Выразите 210° в радианах.',options:['7π/6','6π/7','7π/12','3π/2'],a:0,why:'210 · π/180 = 7π/6.'},
 {q:'Чему равен tg 270°?',options:['0','1','−1','Не определён'],a:3,why:'cos 270° = 0; в отношении sin/cos нельзя делить на ноль.'}
],
ineq:[
 {q:'Решите −3x + 6 ≥ 0.',options:['x ≥ 2','x ≤ 2','x < 2','x ≤ −2'],a:1,why:'−3x ≥ −6. Деление на −3 меняет знак: x ≤ 2.'},
 {q:'Выберите решение (x − 2)/(x + 4) ≤ 0.',options:['[−4; 2]','(−4; 2]','(−4; 2)','(−∞; −4) ∪ [2; +∞)'],a:1,why:'−4 запрещено, 2 допустимо и даёт ноль. Между ними дробь отрицательна.'},
 {q:'Решите log₃(x + 2) > 1.',options:['x > 1','x > −2','x < 1','−2 < x < 1'],a:0,why:'ОДЗ: x > −2. Логарифм возрастает, x + 2 > 3, значит x > 1; это условие уже удовлетворяет ОДЗ.'},
 {q:'Решите (1/2)ˣ < 1/8.',options:['x < 3','x > 3','x < −3','x > −3'],a:1,why:'1/8 = (1/2)³. Функция убывает: меньшему значению соответствует больший показатель.'},
 {q:'Сопоставьте: А) log₂(x − 1) > 2; Б) 2^(7 − x) > 4; В) (x − 1)/(x − 5) < 0; Г) 1/((x − 1)(x − 5)) > 0. Решения: 1) x < 5; 2) 1 < x < 5; 3) x > 5; 4) x < 1 или x > 5. Введите четыре номера в порядке АБВГ.',a:3124,code:true,why:'А: x > 5 — №3. Б: 7 − x > 2, x < 5 — №1. В: разные знаки между 1 и 5 — №2. Г: одинаковые знаки вне промежутка — №4.',diagram:()=>'<p class="note">Рисунки решений в порядке 1–4:</p>'+[[[5],[true,false]],[[1,5],[false,true,false]],[[5],[false,true]],[[1,5],[true,false,true]]].map(([r,z],i)=>`<p>${i+1})</p>`+lineSVG(-1,7,r,z,r.map(()=>false))).join('')},
 {q:'На оси точки A, B, C, D идут слева направо. Сопоставьте им числа: 1) √18; 2) log₂12; 3) 7/3; 4) (1/5)⁻¹. Введите номера в порядке ABCD.',a:3214,code:true,why:'7/3 ≈ 2,33; 3 < log₂12 < 4; 4 < √18 < 5; (1/5)⁻¹ = 5. Поэтому A–3, B–2, C–1, D–4.',diagram:()=>lineSVG(0,6,[7/3,Math.log2(12),Math.sqrt(18),5],[false,false,false,false,false],[true,true,true,true],['A','B','C','D'])}
]};
$('openQuiz').onclick=()=>{stop();if(quizState&&quizState.tab===tab){$('lab').hidden=true;$('quiz').hidden=false;renderQuiz();return;}if(quizState){report.push({topic:quizState.tab,status:'прервана',answers:quizState.answers,assisted:true});}runs[tab]++;quizState={tab,index:0,answers:[],assisted:false,repeated:runs[tab]>1,selection:null};$('lab').hidden=true;$('quiz').hidden=false;renderQuiz();};
function renderQuiz(){const q=quizState,bank=quizBanks[q.tab],task=bank[q.index];$('quiz').innerHTML=`<div class="card quizcard"><span class="badge">САМОСТОЯТЕЛЬНАЯ ПРОВЕРКА · ${q.index+1}/${bank.length}</span><p class="note">Подсказки и разбор появятся после последнего ответа. Возврат в лабораторию отметит попытку как учебную.${q.repeated?' Это повтор знакомого набора.':''}</p><div class="track"><span style="width:${q.index/bank.length*100}%"></span></div><p class="taskquestion">${esc(task.q)}</p>${task.diagram?task.diagram():''}<div id="quizInput"></div><div class="quiz-controls"><button class="primary" id="submitQuiz">Ответить</button><button id="skipQuiz">Пропустить</button><button id="backQuiz">Обратиться к модели</button></div><p id="quizError" role="status"></p></div>`;q.selection=null;if(task.options){$('quizInput').innerHTML='<div class="options">'+task.options.map((o,i)=>`<button data-answer="${i}" aria-pressed="false">${esc(o)}</button>`).join('')+'</div>';$('quizInput').querySelectorAll('button').forEach(b=>b.onclick=()=>{q.selection=+b.dataset.answer;$('quizInput').querySelectorAll('button').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));});}else{$('quizInput').innerHTML='<label>Ответ: <input id="quizNumber" class="num" type="text" inputmode="decimal"></label><p class="note">'+(task.code?'Четыре номера без пробелов.':'Можно использовать точку или запятую.')+'</p>';$('quizNumber').oninput=()=>q.selection=$('quizNumber').value;$('quizNumber').onkeydown=e=>{if(e.key==='Enter')$('submitQuiz').click();};}$('submitQuiz').onclick=()=>submitQuiz(false);$('skipQuiz').onclick=()=>submitQuiz(true);$('backQuiz').onclick=()=>{q.assisted=true;$('lab').hidden=false;$('quiz').hidden=true;};}
function submitQuiz(skip){const q=quizState,bank=quizBanks[q.tab],t=bank[q.index];const answer=skip?null:t.options?q.selection:number(q.selection===null?'':q.selection);if(!skip&&(answer===null||(t.code&&!/^[1-4]{4}$/.test(String(q.selection).trim())))){$('quizError').textContent=t.code?'Введите четыре номера от 1 до 4.':'Сначала выберите или введите ответ.';return;}q.answers.push({question:t.q,answer,correct:answer!==null&&Math.abs(answer-t.a)<1e-8});q.index++;if(q.index<bank.length){renderQuiz();return;}const score=q.answers.filter(a=>a.correct).length;report.push({...q,date:new Date().toISOString(),score,total:bank.length});$('quiz').innerHTML=`<div class="card quizcard"><span class="badge">РЕЗУЛЬТАТ ЭТОЙ ПОПЫТКИ</span><h2>${score} из ${bank.length}</h2><p>${q.assisted?'Учебная попытка: Вы обращались к модели.':q.repeated?'Повтор знакомого набора.':'Самостоятельная первая попытка.'} Это проверка выбранных навыков, не всего экзамена.</p>${bank.map((t,i)=>`<div class="review"><b>${q.answers[i].correct?'✓':'○'} ${esc(t.q)}</b><p>${q.answers[i].answer===null?'Ответ пропущен.':'Ваш ответ: '+esc(t.options?t.options[q.answers[i].answer]:q.answers[i].answer)}</p><p>${esc(t.why)}</p></div>`).join('')}<button id="finishQuiz">Вернуться к лаборатории</button></div>`;quizState=null;$('finishQuiz').onclick=()=>{$('lab').hidden=false;$('quiz').hidden=true;};}
$('report').onclick=()=>{if(!report.length){$('reportStatus').textContent='Сначала завершите хотя бы одну самостоятельную проверку.';return;}const text=['MathExam. Лаборатории базового ЕГЭ',...report.map(r=>`${subjects[r.tab||r.topic]}\n${r.status||`${r.score}/${r.total}`} · ${r.assisted?'с обращением к модели':r.repeated?'повтор знакомого набора':'самостоятельно'}\n`+r.answers.map((a,i)=>`${i+1}. ${a.answer===null?'пропуск':a.correct?'верно':'ошибка'} — ${a.question}`).join('\n'))].join('\n\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='MathExam_Labs_Report.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
window.addEventListener('pagehide',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
window.MathExamLabs={quizBanks,number,getState:()=>({tab,angle,planeStep,planePlan,planeMethod,caseIndex,ineqStep,selectedZones:[...selectedZones],selectedClosed:[...selectedClosed],solidValue,stereoMode,quizState,report}),setTab:showTab};
function syncMobile(){const el=$('mobileTask');el.hidden=$('lab').hidden;if(el.hidden)return;let title='',text='';if(tab==='stereo'){title=$('solidTitle')?.textContent||'';text=$('solidTask')?.textContent||'';}else if(tab==='plane'){title=$('planeGiven')?.textContent||'';text=$('planeInstruction')?.firstElementChild?.textContent||'';}else if(tab==='ineq'){title=M.cases[caseIndex].expr;text=$('ineqInstruction')?.firstElementChild?.textContent||'';}else{title='Точка P = (cos α; sin α)';text='Перемещайте точку. Сравните 30° и 150°, затем 150° и −210°. Проследите за горизонтальной и вертикальной координатами.';}const value=title+'\n'+text;if(el.dataset.value===value)return;el.dataset.value=value;el.replaceChildren();const b=document.createElement('strong'),p=document.createElement('span');b.textContent=title;p.textContent=text;el.append(b,p);}
new MutationObserver(syncMobile).observe($('lab'),{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['hidden']});
showTab('stereo');syncMobile();
})();
