'use strict';const assert=require('assert/strict'),path=require('path'),root=path.resolve(__dirname,'../..'),S=require(root+'/stereo-course/assets/space.js'),T=require(root+'/stereo-course/assets/tasks.js'),A=require(root+'/stereo-course/assets/answer.js'),C=require(root+'/stereo-course/data/course.json');let checks=0;
function near(a,b,eps=1e-7){assert.ok(Math.abs(a-b)<eps,`${a} != ${b}`);checks++;}
assert.deepEqual(C.units.flatMap(u=>u.points).sort((a,b)=>a-b),Array.from({length:99},(_,i)=>i+1));
for(let i=0;i<200;i++){const a=1+i%5,b=1+i%7,h=1+i%6,box=S.solid('box',a,b,h);near(S.area(S.section(box,{n:[0,0,1],d:h/2})),a*b);near(S.area(S.section(box,{n:[1,0,0],d:0})),b*h);assert.equal(S.section(box,{n:[0,0,1],d:h+1}).length,0);const n=S.unit([Math.sin(i+.4),Math.cos(i+1),Math.sin(i+2)]),pl={n,d:S.dot(n,[0,0,h/2])},cut=S.section(box,pl);assert.ok(cut.length>=3&&cut.length<=6);for(const p of cut){near(S.dot(n,p),pl.d);assert.ok(Math.abs(p[0])<=a/2+1e-7&&Math.abs(p[1])<=b/2+1e-7&&p[2]>=-1e-7&&p[2]<=h+1e-7);}const foot=S.foot([2,3,4],pl);near(S.dot(n,foot),pl.d);near(S.norm(S.cross(S.sub([2,3,4],foot),n)),0);const py=S.solid('pyramid',a,b,h);near(S.area(S.section(py,{n:[0,0,1],d:h/2})),a*a/4);}
const sphere={center:[0,0,3],r:3};assert.equal(S.sphereSection(sphere,{n:[0,0,1],d:6}).length,1);assert.equal(S.sphereSection(sphere,{n:[0,0,1],d:7}).length,0);for(const p of S.sphereSection(sphere,{n:[0,0,1],d:4})){near(S.dist(p,sphere.center),3);near(p[2],4);}
for(const u of C.units)for(let seed=0;seed<200;seed++){const t=T.make(u.task,seed);assert.ok(A.equal(A.format(t.a),t.a),u.id);for(const s of t.steps)assert.ok(A.equal(A.format(s.a),s.a),u.id);checks+=t.steps.length+1;}
// Verify geometry and numeric statements against independent invariants.
for(let seed=0;seed<100;seed++){const q=T.make('box-diagonal',seed),n=q.q.match(/\d+/g).map(Number);near(q.a*q.a,n[0]**2+n[1]**2+n[2]**2);const e=T.make('euler',seed),z=e.q.match(/\d+/g).map(Number);near(z[0]-z[1]+e.a,2);assert.ok(z[0]>=4&&z[1]>=6&&e.a>=4);}
near(S.linePlaneAngle([1,0,1],{n:[0,0,1],d:0}),45);near(S.angle([1,0,0],[-1,0,0]),0);near(S.angle([1,0,0],[-1,0,0],false),180);assert.equal(S.plane([0,0,0],[1,0,0],[2,0,0]),null);console.log(JSON.stringify({status:'PASS',units:C.units.length,sourcePoints:99,checks}));
