(function(root){
'use strict';
const D=root.M9Exercises,C=root.M9Checks,KEY='mathexam.makarychev9.exercises.v1';
const blank=()=>({schema:'mathexam-m9-exercises',version:1,records:{},sessions:{}});
const key=(n,p)=>n+':'+p;
function getPart(k){const [n,p]=k.split(':').map(Number);return D.byNumber[n]?.parts[p];}
function validate(x){
 if(!x||x.schema!=='mathexam-m9-exercises'||x.version!==1||!x.records||!x.sessions||Array.isArray(x.records)||Array.isArray(x.sessions))throw Error('Неизвестный формат файла результатов.');
 const y=blank();if(Object.keys(x.records).length>5000||Object.keys(x.sessions).length>5000)throw Error('Слишком большой файл.');
 for(const [k,r] of Object.entries(x.records)){if(!getPart(k)||!r||!['seen','learn','check','independent'].every(f=>typeof r[f]==='boolean'))throw Error('Повреждён результат задания.');y.records[k]={seen:r.seen,learn:r.learn,check:r.check,independent:r.independent};}
 for(const [k,s] of Object.entries(x.sessions)){const p=getPart(k);if(!p||!s||!['learn','check'].includes(s.mode)||!Number.isInteger(s.index)||s.index<0||s.index>(s.mode==='learn'?p.steps:p.steps.filter(a=>a.final)).length||!['assisted','mistake','familiar','correct'].every(f=>typeof s[f]==='boolean')||!Number.isInteger(s.hint)||s.hint<0||s.hint>2||typeof s.message!=='string'||s.message.length>5000)throw Error('Повреждён сохранённый шаг.');if(s.draft!==null&&typeof s.draft!=='string'&&!Array.isArray(s.draft)&&typeof s.draft!=='object')throw Error('Повреждён черновик.');if(JSON.stringify(s.draft).length>5000)throw Error('Черновик слишком большой.');y.sessions[k]={mode:s.mode,index:s.index,assisted:s.assisted,mistake:s.mistake,familiar:s.familiar,correct:s.correct,hint:s.hint,message:s.message,draft:s.draft};}
 return y;
}
root.M9ExerciseState={KEY,blank,validate};if(typeof module!=='undefined'){module.exports=root.M9ExerciseState;return;}
const main=document.getElementById('main'),notice=document.getElementById('notice');let state=blank(),blocked=false,current=null;
try{const raw=localStorage.getItem(KEY);if(raw)state=validate(JSON.parse(raw));}catch(e){blocked=true;notice.textContent='Прежние результаты не удалось прочитать. Они не перезаписаны. В «Моих результатах» можно скачать исходную запись. Новые действия пока не сохраняются.';}
function save(){if(blocked)return;try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){notice.textContent='Не удалось сохранить результат. Скачайте копию в «Моих результатах» до закрытия страницы.';}}
function esc(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function href(n,p=0){return '#'+n+'/'+p;}
function record(k){return state.records[k]||(state.records[k]={seen:false,learn:false,check:false,independent:false});}
function completed(e){return e.parts.every((p,i)=>{const r=state.records[key(e.number,i)];return r&&(r.learn||r.check);});}
function board(hash,label='Открыть на доске'){if(root.self!==root.top)return '';const src='/school/m9-exercises/index.html'+hash;return '<a class="button quiet" href="../../trainers/trainer-board.html?trainer='+encodeURIComponent(src)+'">'+label+'</a>';}
function card(e){const done=e.parts.filter((_,i)=>{const r=state.records[key(e.number,i)];return r&&(r.learn||r.check);}).length;return '<a class="task-card" href="'+href(e.number)+'"><span class="number">№ '+e.number+'</span><span class="badge">'+(completed(e)?'Разобрано':e.enrichment?'Углубление':'Доступно')+'</span><h3>'+esc(e.title)+'</h3><p>'+e.parts.length+' '+(e.parts.length%100>=11&&e.parts.length%100<=14?'частей':e.parts.length%10===1?'часть':e.parts.length%10>=2&&e.parts.length%10<=4?'части':'частей')+' · с. '+e.page+' · выполнено '+done+'</p></a>';}
function catalog(){
 const parts=D.exercises.reduce((n,e)=>n+e.parts.length,0);
 main.innerHTML='<section class="hero"><p class="eyebrow">Макарычев · 9 класс · 2023</p><h1>Твой номер.<br>Твой ход решения.</h1><p class="lead">Выбирай задание из учебника. Строй, сравнивай, предлагай свои примеры и объясняй каждый шаг.</p><div class="stats"><div><b>'+D.exercises.length+' / '+D.total+'</b><span>номеров с тренажёрами</span></div><div><b>'+parts+'</b><span>частей заданий</span></div><div><b>'+D.exercises.filter(completed).length+'</b><span>номеров разобрано тобой</span></div></div></section><section class="panel featured"><form id="find" class="search"><label for="number">Какой номер в учебнике?<input id="number" type="number" min="1" max="891" placeholder="Например, 20" required></label><button>Найти задание</button>'+board('#catalog')+'</form><div id="find-result" role="status"></div><p class="tiny">Сейчас проверены № 1–97, включая все их подпункты. Это все нумерованные упражнения главы I; контрольные вопросы пока отдельно не реализованы. № 98–891 ещё не представлены тренажёрами. Тематические занятия по остальному учебнику доступны в основном курсе.</p></section><h2>Готовые задания</h2><div class="grid">'+D.exercises.map(card).join('')+'</div>';
 document.getElementById('find').onsubmit=e=>{e.preventDefault();const n=Number(document.getElementById('number').value);if(D.byNumber[n])location.hash=href(n);else document.getElementById('find-result').innerHTML='<p>№ '+esc(n)+' ещё не готов. <a href="../index.html?course=makarychev9#course/makarychev9">Открыть занятия по темам учебника →</a></p>';};
}
function steps(p,s){return s.mode==='learn'?p.steps:p.steps.filter(a=>a.final);}
function newSession(k,mode){const r=record(k);const s={mode,index:0,assisted:false,mistake:false,familiar:r.seen,correct:false,hint:0,message:'',draft:null};r.seen=true;state.sessions[k]=s;save();return s;}
function fmt(v){return String(v).replace('.',',');}
function lineSVG(low,high,v,interval){
 const x=n=>35+(n-low)/(high-low)*530,spacing=Math.ceil((high-low)/8);let ticks='';for(let n=Math.ceil(low/spacing)*spacing;n<=high;n+=spacing)ticks+='<line x1="'+x(n)+'" y1="62" x2="'+x(n)+'" y2="74" class="axis"/><text x="'+x(n)+'" y="100" text-anchor="middle">'+fmt(n)+'</text>';
 let mark='';if(interval){const a=interval.low==='-inf'?low:Number(interval.low),b=interval.high==='inf'?high:Number(interval.high);if(Number.isFinite(a)&&Number.isFinite(b)&&a<=b){mark='<line x1="'+x(Math.max(low,a))+'" x2="'+x(Math.min(high,b))+'" y1="68" y2="68" class="fill"/>';if(interval.low!=='-inf')mark+='<circle cx="'+x(a)+'" cy="68" r="7" class="'+(interval.left?'selected-end':'open-end')+'"/>';else mark+='<text x="20" y="73">←</text>';if(interval.high!=='inf')mark+='<circle cx="'+x(b)+'" cy="68" r="7" class="'+(interval.right?'selected-end':'open-end')+'"/>';else mark+='<text x="571" y="73">→</text>';}}
 else if(v!==null&&Number.isFinite(Number(v)))mark='<circle cx="'+x(Number(v))+'" cy="68" r="10" class="point"/>';
 return '<svg class="line" viewBox="0 0 600 125" role="img" aria-label="'+(interval?'Выбранный промежуток':'Числовая прямая и поставленная точка')+'"><line x1="25" y1="68" x2="577" y2="68" class="axis"/>'+ticks+mark+'</svg>';
}
function constructionSVG(t,d){
 let point=null,a=t.initial;try{a=C.number(d?.a??String(t.initial)).value;}catch(_){}try{point=C.number(d?.point??'').value;}catch(_){}
 const x=35+(a-t.bounds[0])/(t.bounds[1]-t.bounds[0])*530;
 return lineSVG(...t.bounds,point,null).replace('</svg>','<circle cx="'+x+'" cy="68" r="5" fill="#243b35"/><text x="'+x+'" y="40" text-anchor="middle">a</text></svg>');
}
function taskFigure(kind){
 if(kind==='points84')return '<figure class="task-figure"><svg viewBox="0 0 600 130" role="img" aria-label="Прямая: A между 1 и 2, B между 2 и 3, C между 3 и 4, D между 5 и 6"><line x1="25" x2="580" y1="70" y2="70" class="axis"/>'+Array.from({length:7},(_,n)=>'<line x1="'+(30+n*88)+'" x2="'+(30+n*88)+'" y1="64" y2="76" class="axis"/><text x="'+(30+n*88)+'" y="103" text-anchor="middle">'+n+'</text>').join('')+[[1.25,'A'],[25/9,'B'],[Math.sqrt(11),'C'],[123/23,'D']].map(([n,l])=>'<circle cx="'+(30+n*88)+'" cy="70" r="5" fill="#136d54"/><text x="'+(30+n*88)+'" y="40" text-anchor="middle">'+l+'</text>').join('')+'</svg><figcaption>Рисунок 6а: восстановленная схема. Выбери букву в ответе ниже.</figcaption></figure>';
 if(kind!=='plan97')return '';
 let grid='';for(let i=0;i<=23;i++)grid+='<path d="M'+(30+i*22)+' 30V514"/>';for(let i=0;i<=22;i++)grid+='<path d="M30 '+(30+i*22)+'H536"/>';
 const rect=(id,x,y,w,h)=>'<rect data-region="'+id+'" x="'+(30+x*22)+'" y="'+(30+y*22)+'" width="'+w*22+'" height="'+h*22+'"/><text x="'+(30+(x+w/2)*22)+'" y="'+(36+(y+h/2)*22)+'" text-anchor="middle">'+id+'</text>';
 return '<figure class="task-figure plan"><svg viewBox="0 0 570 550" role="img" aria-label="План в клетках по 5 метров. Сверху слева здание 2, справа прямоугольник 4. Снизу слева ограда участка 3, справа площадка 1. Считайте клетки по границам."><g stroke="#ced9d1" stroke-width="1">'+grid+'</g><g fill="#dceadf" fill-opacity=".65" stroke="#345c4c" stroke-width="2">'+rect('2',2,2,11,8)+rect('4',16,2,4,5)+rect('1',14,11,6,9)+'<rect data-region="fence" x="52" y="294" width="242" height="198" fill="none" stroke-dasharray="5 3"/><path data-region="3" d="M74 448V338H118V316H162V338H206V448Z M228 338H272V382H228Z M228 426H272V470H228Z"/><text x="140" y="410" text-anchor="middle">3</text></g><text x="30" y="539">Одна клетка: 5 × 5 м</text></svg><div class="row map-tools">'+[['2','Выделить 2'],['3','Выделить 3'],['1','Выделить 1'],['4','Выделить 4'],['fence','Обвести ограду 3']].map(([id,l])=>'<button type="button" class="quiet" data-highlight="'+id+'" aria-pressed="false">'+l+'</button>').join('')+'</div><figcaption>Восстановленная схема по рисунку учебника. Выделяй объекты кнопками; ответы вводи ниже.</figcaption></figure>';
}
function formSketch(t,d){
 if(t.rule.kind!=='parking'&&t.rule.kind!=='room')return '';
 try{const v={};for(const f of t.fields)if(d?.[f.id])v[f.id]=C.number(d[f.id]).value;
 if(t.rule.kind==='room'){
  if(!(v.length>0&&v.width>0&&v.height>0))return '<p class="tiny">После ввода трёх размеров появится план комнаты.</p>';
  const k=230/Math.max(v.length,v.width),w=v.length*k,h=v.width*k;return '<svg viewBox="0 0 340 310" role="img" aria-label="План комнаты по вашим размерам"><rect x="55" y="35" width="'+w+'" height="'+h+'" fill="#e4eee6" stroke="#136d54" stroke-width="2"/><text x="55" y="25">'+esc(fmt(v.length))+' м</text><text x="8" y="150" transform="rotate(-90 8 150)">'+esc(fmt(v.width))+' м</text><text x="55" y="299">Высота: '+esc(fmt(v.height))+' м</text></svg>';
 }
 if(![20,25].includes(v.side)||![1,2].includes(v.rows)||!Number.isInteger(v.places)||v.places<1||v.places>15)return '<p class="tiny">Для схемы: сторона 20 или 25 м, один или два ряда, 1–15 мест в ряду.</p>';
 const depth=v.side===25?20:25,k=14,w=v.side*k,h=depth*k;let cars='';for(let r=0;r<v.rows;r++)for(let i=0;i<v.places;i++)cars+='<rect x="'+(30+i*2.5*k)+'" y="'+(30+r*(5.3+6)*k)+'" width="'+2.5*k+'" height="'+5.3*k+'" fill="#c7dfd0" stroke="#136d54"/>';
 return '<svg viewBox="0 0 590 420" role="img" aria-label="Схема выбранных рядов парковки; контур участка чёрный"><rect x="30" y="30" width="'+w+'" height="'+h+'" fill="#f4f4ef" stroke="#243b35" stroke-width="3"/>'+cars+'<text x="30" y="405">Длина ряда '+v.side+' м · глубина участка '+depth+' м</text></svg><p class="tiny">Проверь: не выходят ли места за контур? Между рядами оставлено 6 м.</p>';
 }catch(_){return '<p class="tiny">Заверши ввод размеров, чтобы обновить схему.</p>';}
}
function controls(t,s){
 const r=t.rule,d=s.draft;
 if(r.type==='construction'){const a=d&&typeof d==='object'?d:{a:String(t.initial),point:''};return '<label>Координата исходной точки a<input data-field="a" type="text" value="'+esc(a.a)+'" '+(s.correct?'disabled':'')+'></label><label>Координата твоей точки<input data-field="point" type="text" value="'+esc(a.point)+'" '+(s.correct?'disabled':'')+'></label><div id="visual">'+constructionSVG(t,a)+'</div><p class="tiny">Тёмная точка — a; зелёная — твоя. Нажми на прямую, перетащи точку или введи координату с клавиатуры. Допуск 0,02. '+r.min+' &lt; a &lt; '+r.max+'.</p>';}
 if(r.type==='form'){const a=d&&typeof d==='object'?d:{};return '<div class="answer-fields">'+t.fields.map(f=>'<label>'+esc(f.label)+'<input data-field="'+esc(f.id)+'" type="text" maxlength="600" value="'+esc(a[f.id]||'')+'" '+(s.correct?'disabled':'')+'></label>').join('')+'</div><div id="form-sketch">'+formSketch(t,a)+'</div><p class="tiny">Десятичная запятая и дроби допустимы. Результаты сохраняются в этом браузере.</p>';}

 if(r.type==='angle'){const a=d&&typeof d==='object'?d:{angle:90,reading:''};return angleSVG(a.angle)+'<div class="row"><button type="button" class="quiet" data-rotate="-5" '+(s.correct?'disabled':'')+'>−5°</button><button type="button" class="quiet" data-rotate="-1" '+(s.correct?'disabled':'')+'>−1°</button><button type="button" class="quiet" data-rotate="1" '+(s.correct?'disabled':'')+'>+1°</button><button type="button" class="quiet" data-rotate="5" '+(s.correct?'disabled':'')+'>+5°</button></div><p class="tiny">Перемещайте конец луча мышью или меняйте положение кнопками. Читайте шкалу от правого нуля.</p><label for="angle-reading">По шкале транспортира получилось, градусов<input id="angle-reading" type="text" value="'+esc(a.reading)+'" '+(s.correct?'disabled':'')+'></label>';}
 if(r.type==='choice'||r.type==='oneof')return '<fieldset class="choices"><legend>'+(r.type==='oneof'?'Выберите одну подходящую единицу;':'Выберите все подходящие ответы;')+' затем нажмите «Проверить».</legend>'+t.options.map(([id,text])=>'<label class="choice"><input type="'+(r.type==='oneof'?'radio':'checkbox')+'" name="choice" value="'+esc(id)+'" '+(Array.isArray(d)&&d.includes(id)?'checked':'')+' '+(s.correct?'disabled':'')+'>'+esc(text)+'</label>').join('')+'</fieldset>';
 if(r.type==='order'){const order=Array.isArray(d)&&d.length===t.options.length?d:t.options.map(x=>x[0]);return '<p class="tiny">Переставляйте карточки кнопками вверх и вниз. Они доступны с клавиатуры.</p><ol class="order">'+order.map((id,i)=>'<li data-token="'+esc(id)+'"><span>'+esc(id)+'</span><button type="button" class="quiet" data-move="'+i+':-1" aria-label="Поднять '+esc(id)+'" '+(i===0||s.correct?'disabled':'')+'>↑</button><button type="button" class="quiet" data-move="'+i+':1" aria-label="Опустить '+esc(id)+'" '+(i===order.length-1||s.correct?'disabled':'')+'>↓</button></li>').join('')+'</ol>';}
 if(r.type==='interval'){const a=d&&typeof d==='object'?d:{low:'0',high:'1',left:false,right:false};const opts=['-inf','-2','0','1','2.5','3','4','5','7.5','10.5','inf'];return '<div class="interval-controls">'+['low','high'].map(f=>'<div><label>'+(f==='low'?'Левая граница':'Правая граница')+'<select id="'+f+'" '+(s.correct?'disabled':'')+'>'+opts.map(v=>'<option value="'+v+'" '+(a[f]===v?'selected':'')+'>'+({'-inf':'−∞',inf:'+∞'}[v]||fmt(v))+'</option>').join('')+'</select></label><label class="check-label"><input id="'+(f==='low'?'left':'right')+'" type="checkbox" '+(a[f==='low'?'left':'right']?'checked':'')+' '+(s.correct?'disabled':'')+'> Включить границу</label></div>').join('')+'</div><div id="visual">'+lineSVG(...t.bounds,null,a)+'</div>';
 }
 const point=r.type==='point';return '<label class="num-form" for="answer">'+(point?'Координата точки':'Твой ответ')+'<input id="answer" type="text" autocomplete="off" maxlength="2000" value="'+esc(typeof d==='string'?d:'')+'" '+(s.correct?'disabled':'')+' aria-describedby="format"></label>'+(point?'<div id="visual">'+lineSVG(...t.bounds,d,null)+'</div><p class="line-help">Нажмите на прямую или перетащите точку. Клавиатура: введите координату в поле.</p>':'')+'<p id="format" class="tiny">'+(r.type==='pairs'?'Пара: x;y. Несколько пар разделяйте вертикальной чертой |. ':r.type==='witness'||r.type==='list'||r.type==='counterexample'?'Разные числа разделяйте точкой с запятой. ':r.type==='period'?'Период — в скобках: 0,1(6). ':'')+'Можно вводить дроби 2/3, десятичные числа, sqrt(2), π, степени 10^(-3). '+(point?'Допуск 0,02.':'')+'</p>';
}
function angleSVG(angle){const xy=(a,r)=>[300+r*Math.cos(a*Math.PI/180),290-r*Math.sin(a*Math.PI/180)];let ticks='';for(let a=0;a<=180;a++){const [x,y]=xy(a,220),[u,v]=xy(a,a%10===0?201:a%5===0?207:214);ticks+='<line x1="'+x+'" y1="'+y+'" x2="'+u+'" y2="'+v+'" stroke="#8b9d91"/>';if(a%10===0){const [tx,ty]=xy(a,241);ticks+='<text x="'+tx+'" y="'+(ty+6)+'" text-anchor="middle">'+a+'</text>';}}const [x,y]=xy(angle,210);return '<svg class="angle-model" data-angle="'+angle+'" viewBox="0 0 600 330" role="img" aria-label="Транспортир со шкалой и подвижный луч"><path d="M80 290 A220 220 0 0 1 520 290 L80 290" fill="#edf4ed" stroke="#b5cdbd"/>'+ticks+'<line x1="300" y1="290" x2="530" y2="290" stroke="#143e33" stroke-width="4"/><line x1="300" y1="290" x2="'+x+'" y2="'+y+'" stroke="#136d54" stroke-width="5"/><circle cx="300" cy="290" r="6" fill="#143e33"/><circle cx="'+x+'" cy="'+y+'" r="10" class="point" fill="#136d54" stroke="white" stroke-width="3"/></svg>';}
function read(t){if(t.rule.type==='form'||t.rule.type==='construction')return Object.fromEntries([...main.querySelectorAll('[data-field]')].map(e=>[e.dataset.field,e.value]));if(t.rule.type==='angle')return {angle:Number(main.querySelector('.angle-model').dataset.angle),reading:document.getElementById('angle-reading').value};if(t.rule.type==='choice'||t.rule.type==='oneof')return [...main.querySelectorAll('.choices input:checked')].map(x=>x.value);if(t.rule.type==='order')return [...main.querySelectorAll('.order li')].map(x=>x.dataset.token);if(t.rule.type==='interval')return {low:document.getElementById('low').value,high:document.getElementById('high').value,left:document.getElementById('left').checked,right:document.getElementById('right').checked};return document.getElementById('answer').value;}
function exercise(n,pindex){
 const e=D.byNumber[n];if(!e){main.innerHTML='<a href="#catalog">← К номерам</a><section class="panel"><h1>№ '+esc(n)+' ещё не готов</h1><p>Для этого номера пока нет проверенного тренажёра. <a href="../index.html?course=makarychev9#course/makarychev9">Занятия по темам учебника</a> доступны отдельно.</p></section>';return;}
 if(!Number.isInteger(pindex)||pindex<0||pindex>=e.parts.length)pindex=0;
 const k=key(n,pindex),p=e.parts[pindex],model=p.model||e.model;
 if(!state.sessions[k]){main.innerHTML='<a href="#catalog">← Все номера</a><section class="hero"><p class="eyebrow">№ '+n+' · с. '+e.page+'</p><h1>'+esc(e.title)+'</h1><p class="lead">'+esc(p.title)+'</p></section><section class="panel featured"><h2>Как начнём?</h2><p>Можно разобрать задачу по шагам или сразу попробовать самостоятельно.</p>'+ (p.manual?'<p class="tiny">Открытое задание: расчёт или заполнение проверит программа; выбор примеров и источников обсудите с учителем. Автоматической отметки самостоятельного освоения здесь нет.</p>':'') +'<div class="row"><button id="start-learn">Разобраться по шагам</button><button id="start-check" class="quiet">Сразу самостоятельно</button>'+board(href(n,pindex))+'</div></section>';for(const mode of ['learn','check'])document.getElementById('start-'+mode).onclick=()=>{newSession(k,mode);exercise(n,pindex);};return;}
 const s=state.sessions[k],ss=steps(p,s),t=ss[s.index];current={e,p,pindex,k,s,t};
 const result=record(k);
 main.innerHTML='<a href="#catalog">← Все номера</a><div class="hero"><p class="eyebrow">№ '+n+' · пункт '+e.point+' · страница '+e.page+'</p><h1>'+esc(e.title)+'</h1><p class="lead">'+esc(p.title)+'</p><div class="parts" aria-label="Части задания">'+e.parts.map((x,i)=>{const r=state.records[key(n,i)];return '<a href="'+href(n,i)+'" class="'+(i===pindex?'active ':'')+(r&&(r.learn||r.check)?'done':'')+'" '+(i===pindex?'aria-current="page"':'')+'>'+esc(x.label||'Задание')+'</a>';}).join('')+'</div><div class="row"><div class="mode"><button id="learn" class="quiet '+(s.mode==='learn'?'active':'')+'">По шагам</button><button id="check-mode" class="quiet '+(s.mode==='check'?'active':'')+'">Самостоятельно</button></div>'+board(href(n,pindex))+'</div></div>';
 if(!t){main.innerHTML+='<section class="panel featured"><p class="success-mark" aria-hidden="true">✓</p><h2>'+ (s.mode==='learn'?'Эта часть разобрана':'Проверка завершена')+'</h2><p>'+(p.manual?'Ответ записан. Автопроверка охватывает только заполнение полей и явно указанные вычисления. Примеры, источники и интерпретацию обсудите с учителем.':result.independent?'Есть верная первая попытка без подсказок. Это результат этой задачи, а не доказательство освоения всей темы.':s.mode==='learn'?'Ты прошёл все шаги. Теперь попробуй объяснить решение своими словами и решить новую задачу по теме.':'Результат сохранён как работа со знакомой задачей или с помощью. Он не повышает показатель первого самостоятельного решения.')+'</p><div class="row">'+(pindex+1<e.parts.length?'<a class="button" href="'+href(n,pindex+1)+'">Следующая часть →</a>':D.byNumber[n+1]?'<a class="button" href="'+href(n+1)+'">К № '+(n+1)+' →</a>':'<a class="button" href="#catalog">К каталогу</a>')+'<button id="restart" class="quiet">Повторить эту часть</button></div></section>';}
 else main.innerHTML+='<div class="work"><section class="panel"><div class="step-count">'+(s.mode==='learn'?'Шаг':'Вопрос')+' '+(s.index+1)+' из '+ss.length+'</div><progress value="'+s.index+'" max="'+ss.length+'" aria-label="Выполненные шаги"></progress><h2 class="question">'+esc(t.prompt)+'</h2>'+taskFigure(p.figure)+'<form id="answer-form">'+controls(t,s)+'<div id="feedback" class="feedback '+(s.correct?'good':'')+'" role="status">'+esc(s.message)+'</div>'+(s.hint?'<div class="hint"><b>Подсказка '+s.hint+' / 2</b><p>'+esc(t.hints[s.hint-1])+'</p></div>':'')+'<div class="row actions">'+(s.correct?'<button type="button" id="next">'+(s.index+1<ss.length?'Следующий шаг →':'Завершить часть ✓')+'</button>':'<button type="submit">Проверить</button><button type="button" id="hint" class="quiet">Подсказка</button>')+'</div></form>'+(model?'<details class="explore"><summary id="open-model">Исследовать модель · помощь</summary><div id="model"></div></details>':'')+(s.index?'<details><summary>Уже выполненные шаги</summary><ol class="history">'+ss.slice(0,s.index).map(x=>'<li>'+esc(x.prompt)+'<br>'+esc(x.explain)+'</li>').join('')+'</ol></details>':'')+'</section><aside class="side"><h3>Думать, пробовать, объяснять</h3><ol><li>Прочитай, что именно нужно получить.</li><li>Сделай свой ход. Можно ошибаться.</li><li>Проверь, почему ответ подходит.</li></ol><p class="tiny">'+(p.manual?'Свободная часть требует обсуждения с учителем; автоматического зачёта освоения здесь нет.':s.mode==='learn'?'Работа по шагам считается разбором с поддержкой.':s.familiar?'Эта задача уже открывалась. Проверка будет отмечена как повторение знакомого условия.':'Первая попытка без подсказок будет отмечена отдельно.')+'</p><p><a id="basis" href="../index.html?course=makarychev9&exerciseReturn='+n+'.'+pindex+'#lesson/'+esc(p.skill)+'">Вспомнить тему и вернуться →</a></p></aside></div>';
 document.getElementById('learn').onclick=()=>{newSession(k,'learn');exercise(n,pindex);};document.getElementById('check-mode').onclick=()=>{newSession(k,'check');exercise(n,pindex);};
 if(!t){document.getElementById('restart').onclick=()=>{newSession(k,s.mode);exercise(n,pindex);};return;}
 const explore=main.querySelector('.explore');if(explore)explore.addEventListener('toggle',()=>{if(explore.open){s.assisted=true;save();if(!document.getElementById('model').children.length)root.M9Models.mount(document.getElementById('model'),model,e.number);}});
 const persistDraft=()=>{s.draft=read(t);save();};
 const form=document.getElementById('answer-form');form.oninput=()=>{persistDraft();if(t.rule.type==='form')document.getElementById('form-sketch').innerHTML=formSketch(t,s.draft);if(t.rule.type==='construction'){document.getElementById('visual').innerHTML=constructionSVG(t,s.draft);bindPointer();}if(t.rule.type==='interval')document.getElementById('visual').innerHTML=lineSVG(...t.bounds,null,s.draft);if(t.rule.type==='point'){let v=null;try{v=C.number(s.draft).value;}catch(_){}document.getElementById('visual').innerHTML=lineSVG(...t.bounds,v,null);bindPointer();}};
 form.onsubmit=ev=>{ev.preventDefault();if(s.correct)return;persistDraft();const r=C.check(t,s.draft);s.correct=r.ok;if(!r.ok&&!r.unsupported)s.mistake=true;s.message=r.message;save();exercise(n,pindex);document.getElementById('feedback').scrollIntoView({block:'nearest'});};
 document.getElementById('hint')?.addEventListener('click',()=>{persistDraft();s.assisted=true;s.hint=Math.min(2,s.hint+1);save();exercise(n,pindex);});
 document.getElementById('basis')?.addEventListener('click',()=>{persistDraft();s.assisted=true;save();});
 document.getElementById('next')?.addEventListener('click',()=>{s.index++;s.correct=false;s.hint=0;s.message='';s.draft=null;if(s.index===ss.length){result[s.mode]=true;if(s.mode==='check'&&!p.manual&&!s.assisted&&!s.mistake&&!s.familiar)result.independent=true;}save();exercise(n,pindex);main.querySelector('.step-count,h2')?.scrollIntoView({block:'nearest'});});
 for(const b of main.querySelectorAll('[data-move]'))b.onclick=()=>{const [i,direction]=b.dataset.move.split(':').map(Number),a=read(t);[a[i],a[i+direction]]=[a[i+direction],a[i]];s.draft=a;save();exercise(n,pindex);const buttons=main.querySelectorAll('[data-move="'+(i+direction)+':'+direction+'"]');buttons[0]?.focus();};
 function bindPointer(){if(!['point','construction'].includes(t.rule.type)||s.correct)return;const svg=main.querySelector('.line');let down=false;function set(ev){const q=svg.createSVGPoint();q.x=ev.clientX;q.y=ev.clientY;const pt=q.matrixTransform(svg.getScreenCTM().inverse()),[lo,hi]=t.bounds;const value=Math.round(Math.max(lo,Math.min(hi,lo+(pt.x-35)/530*(hi-lo)))*100)/100;if(t.rule.type==='construction'){document.querySelector('[data-field="point"]').value=fmt(value);s.draft=read(t);}else{s.draft=fmt(value);document.getElementById('answer').value=s.draft;}const circle=svg.querySelector('.point')||document.createElementNS('http://www.w3.org/2000/svg','circle');circle.setAttribute('class','point');circle.setAttribute('r','10');circle.setAttribute('cy','68');circle.setAttribute('cx',35+(value-lo)/(hi-lo)*530);svg.append(circle);save();}svg.onpointerdown=ev=>{down=true;svg.setPointerCapture(ev.pointerId);set(ev);};svg.onpointermove=ev=>{if(down)set(ev);};svg.onpointerup=()=>{down=false;};svg.onpointercancel=()=>{down=false;};}
 for(const button of main.querySelectorAll('[data-highlight]'))button.onclick=()=>{for(const b of main.querySelectorAll('[data-highlight]'))b.setAttribute('aria-pressed',String(b===button));for(const region of main.querySelectorAll('[data-region]'))region.classList.toggle('highlighted',region.dataset.region===button.dataset.highlight);};
 bindPointer();
 if(t.rule.type==='angle'&&!s.correct){for(const b of main.querySelectorAll('[data-rotate]'))b.onclick=()=>{const a=read(t);a.angle=Math.max(0,Math.min(180,a.angle+Number(b.dataset.rotate)));s.draft=a;save();exercise(n,pindex);main.querySelector('[data-rotate="'+b.dataset.rotate+'"]').focus();};const svg=main.querySelector('.angle-model');let drag=false;function move(ev){const point=svg.createSVGPoint();point.x=ev.clientX;point.y=ev.clientY;const pos=point.matrixTransform(svg.getScreenCTM().inverse()),angle=Math.round(Math.max(0,Math.min(180,Math.atan2(290-pos.y,pos.x-300)*180/Math.PI)));const a=read(t);a.angle=angle;s.draft=a;save();const line=svg.querySelectorAll('line');const ray=line[line.length-1],end=svg.querySelector('.point'),x=300+210*Math.cos(angle*Math.PI/180),y=290-210*Math.sin(angle*Math.PI/180);ray.setAttribute('x2',x);ray.setAttribute('y2',y);end.setAttribute('cx',x);end.setAttribute('cy',y);svg.dataset.angle=angle;}svg.onpointerdown=ev=>{drag=true;svg.setPointerCapture(ev.pointerId);move(ev);};svg.onpointermove=ev=>{if(drag)move(ev);};svg.onpointerup=()=>{drag=false;};svg.onpointercancel=()=>{drag=false;};}
}
function download(name,data){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([data],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function progress(){const records=Object.entries(state.records).filter(([,r])=>r.learn||r.check);main.innerHTML='<p class="eyebrow">Мои результаты</p><h1>Видно, что уже получается.</h1><p class="lead">Разбор с поддержкой и первая самостоятельная попытка учитываются отдельно. Повтор знакомого задания не превращается в новый самостоятельный успех.</p><section class="panel"><div class="row"><button id="export">Скачать результаты</button><button id="import-button" class="quiet">Загрузить копию</button>'+(blocked?'<button id="raw" class="quiet">Скачать исходную запись</button>':'')+'</div><p class="tiny">Копия включает черновики и шаги только этого раздела. Прежние данные курса и доски не меняются. Это файл для передачи, не облачный журнал.</p></section><section class="panel table-wrap"><table><thead><tr><th>Задание</th><th>По шагам</th><th>Проверка</th><th>Первая попытка без помощи</th></tr></thead><tbody>'+records.map(([k,r])=>{const [n,p]=k.split(':').map(Number);return '<tr><td><a href="'+href(n,p)+'">№ '+n+' · '+esc(D.byNumber[n].parts[p].label||'задание')+'</a></td><td>'+(r.learn?'✓':'—')+'</td><td>'+(r.check?'✓':'—')+'</td><td>'+(r.independent?'✓':'—')+'</td></tr>';}).join('')+'</tbody></table>'+(!records.length?'<p>Завершённых частей пока нет.</p>':'')+'</section>';document.getElementById('export').onclick=()=>download('Makarychev9-exercises-progress.json',JSON.stringify(state,null,2));document.getElementById('import-button').onclick=()=>document.getElementById('import').click();document.getElementById('raw')?.addEventListener('click',()=>download('Makarychev9-exercises-recovery.txt',localStorage.getItem(KEY)||''));}
document.getElementById('import').onchange=async function(){const file=this.files[0];if(!file)return;try{if(file.size>2e6)throw Error('Файл слишком большой.');const data=validate(JSON.parse(await file.text()));if(confirm('Заменить результаты и черновики только раздела задач Макарычева данными из выбранного файла?')){state=data;blocked=false;save();notice.textContent='Копия загружена.';progress();}}catch(e){notice.textContent=e.message;}this.value='';};
function render(){const h=location.hash.slice(1);current=null;if(h==='main'){main.focus();return;}if(h==='progress')progress();else if(/^\d+(\/\d+)?$/.test(h)){const [n,p=0]=h.split('/').map(Number);exercise(n,p);}else catalog();}
root.addEventListener('hashchange',()=>{render();main.focus({preventScroll:true});root.scrollTo(0,0);});root.addEventListener('storage',e=>{if(e.key===KEY){blocked=true;notice.textContent='Результаты изменились в другой вкладке. Обновите страницу, чтобы не перезаписать их.';}});render();
})(typeof window==='undefined'?globalThis:window);
