(function(){'use strict';
const lessons=globalThis.ProfileLessons||[],byId=new Map(lessons.map(l=>[l.id,l])),main=document.getElementById('main'),groups=[['geometry','01','Планиметрия','Научиться видеть решение на чертеже'],['vectors','02','Векторы','От перемещения — к скалярному произведению'],['trigonometry','03','Тригонометрия','Понять круг, координаты и знаки'],['algebra','04','Алгебра для экзамена','Степени, логарифмы и формулы в действии']];
let cleanup=()=>{},state;try{state=ProfileState.create(lessons,localStorage);}catch(_){state=ProfileState.create(lessons,{getItem(){throw Error();}});}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(text,action,cls='button')=>'<button type="button" class="'+cls+'" id="'+action+'">'+text+'</button>';
function save(){state.persist();warn();}
function warn(){const box=document.getElementById('storage-warning');box.hidden=!state.warning;if(state.warning)box.textContent=state.warning;}
function board(hash){if(window.self!==window.top)return '';return '<a class="button quiet board-link" href="/trainers/trainer-board.html?trainer='+encodeURIComponent('/ege-profil/start/index.html'+hash)+'">Открыть на доске</a>';}
function shell(html){cleanup();cleanup=()=>{};main.innerHTML=html;warn();const h=main.querySelector('h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}window.scrollTo(0,0);}
function status(l){const r=state.record(l.id);return r.independent.length>=2?'Две новые задачи самостоятельно':r.independent.length?'Одна новая задача самостоятельно':r.guided.length?'Есть пошаговая практика':'Начните с исследования';}
function allCompleted(){return lessons.filter(l=>state.record(l.id).independent.length>=2).length;}
function home(){
 const next=lessons.find(l=>state.record(l.id).independent.length<2)||lessons[0];
 shell('<section class="hero"><div><p class="eyebrow">ЕГЭ профиль · 2027 · первый выпуск</p><h1>Математика,<br>которую <em>понимаешь.</em></h1><p class="lead">Построй. Объясни. Реши сам. Планиметрия, векторы и алгебра — маленькими понятными шагами.</p><div class="actions"><a class="button" href="#lesson/'+next.id+'">'+(allCompleted()?'Повторить маршрут':'Мой следующий урок')+' <span aria-hidden="true">→</span></a>'+board('#home')+'</div><p class="muted">'+allCompleted()+' из '+lessons.length+' тем: две новые самостоятельные задачи.</p></div><div class="hero-art" aria-hidden="true"><svg viewBox="0 0 320 310"><defs><pattern id="grid" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M24 0H0V24" fill="none" stroke="#d8dfeb" stroke-width=".7"/></pattern></defs><rect width="320" height="310" fill="url(#grid)"/><circle cx="158" cy="150" r="104" fill="#edf3ff" stroke="#3162d3" stroke-width="2"/><path d="M22 150H295M158 280V20" stroke="#8693ae"/><path d="M158 150L232 76L232 150Z" fill="#f8af65" fill-opacity=".35" stroke="#d67b28" stroke-width="2"/><path d="M158 150L232 76" stroke="#183967" stroke-width="3"/><circle cx="232" cy="76" r="7" fill="#3162d3"/><text x="196" y="173" fill="#315fd0">cos α</text><text x="242" y="120" fill="#a74764">sin α</text><text x="25" y="287" fill="#64718c" font-size="13">одна идея → несколько задач</text></svg></div></section><section class="how"><span><b>1</b> Исследуй модель</span><span><b>2</b> Реши по шагам</span><span><b>3</b> Проверь себя</span></section><section class="route-list" aria-label="Учебный маршрут">'+groups.map(([id,n,title,sub])=>'<section class="topic-group" id="group-'+id+'"><div class="group-title"><span>'+n+'</span><div><h2>'+title+'</h2><p>'+sub+'</p></div></div><div class="lesson-grid">'+lessons.filter(l=>l.group===id).map(l=>'<a class="lesson-card" href="#lesson/'+l.id+'"><span class="position">'+position(l)+'</span><h3>'+esc(l.title)+'</h3><p>'+esc(l.summary)+'</p><span class="lesson-status">'+status(l)+' <span aria-hidden="true">↗</span></span></a>').join('')+'</div></section>').join('')+'</section><aside class="note"><b>Первый учебный выпуск, не полный курс профиля.</b> Новые задачи второй части пока не включены. Старые тренажёры и экзаменационные подборки доступны в <a href="../index.html">общем навигаторе</a>.</aside>');
}
function position(l){return typeof l.position==='number'?'ЕГЭ 2027 · №'+l.position:esc(l.position||'Основа для профиля');}
function breadcrumb(l){return '<p class="breadcrumb"><a href="#home">Маршрут</a><span>/</span>'+esc(l.title)+'</p>';}
function lesson(l){
 const active=state.data.sessions[l.id+':independent'];if(active&&!active.done){active.assisted=true;save();}
 const r=state.record(l.id),s=state.data.sessions[l.id+':guided'];
 shell(breadcrumb(l)+'<section class="lesson-head"><p class="eyebrow">'+position(l)+'</p><h1>'+esc(l.title)+'</h1><p class="lead">'+esc(l.summary)+'</p></section><div class="lesson-layout"><div><section class="panel theory"><p class="eyebrow">Сначала — смысл</p>'+l.intro+(l.why?'<p class="takeaway">'+esc(l.why)+'</p>':'')+'</section>'+(l.model?'<section class="panel model-panel"><p class="eyebrow">Лаборатория · попробуйте сами</p><div id="lab"></div><p class="small muted">Числа в лаборатории служат для исследования. В практике будет отдельное условие.</p></section>':'')+'</div><aside class="lesson-sidebar"><section class="panel start-panel"><h2>Теперь ваша очередь</h2><p>Сначала разберитесь с моделью. Затем решите по шагам или сразу проверьте себя на новом условии.</p><div class="stack">'+button(s&&!s.done?'Продолжить по шагам':'Решать по шагам','guided')+button('Проверить себя','independent','button quiet')+board('#lesson/'+l.id)+'</div><p class="small">Подсказки доступны всегда. Для отметки освоения нужны две разные новые задачи, решённые с первой попытки без помощи.</p><p class="lesson-status">'+status(l)+'</p></section>'+(l.links?.length?'<section class="panel"><h2>Ещё практика</h2><ul class="resource-list">'+l.links.map(x=>'<li><a href="'+esc(x.href)+'">'+esc(x.title)+'</a></li>').join('')+'</ul><p class="small muted">Ранее созданные материалы; нумерация внутри может относиться к 2026 году.</p></section>':'')+'</aside></div>');
 if(l.model&&ProfileModels[l.model])cleanup=ProfileModels[l.model](document.getElementById('lab'))||(()=>{});
 for(const mode of ['guided','independent'])document.getElementById(mode).onclick=()=>{state.start(l.id,mode,!!state.data.sessions[l.id+':'+mode]?.done);location.hash='practice/'+l.id+'/'+mode;};
}
function current(l,mode){const s=state.start(l.id,mode),t=l.tasks.find(t=>t.id===s.taskId);return {s,t};}
function questionInput(q,draft){return q.choices?'<fieldset class="choices"><legend class="sr-only">Выберите ответ</legend>'+q.choices.map((v,i)=>'<label><input type="radio" name="answer" value="'+esc(v)+'" '+(draft===v?'checked':'')+'><span>'+esc(v)+'</span></label>').join('')+'</fieldset>':'<label class="answer-label" for="answer">Ваш ответ<input id="answer" name="answer" type="text" autocomplete="off" inputmode="text" value="'+esc(draft)+'" placeholder="Например: 3/5 или √2/2" aria-describedby="input-note"></label><p class="small muted" id="input-note">Можно вводить дробь, десятичную запятую, √2 или sqrt(2), pi. Для произведения используйте *.</p>';}
function practice(l,mode){
 const {s,t}=current(l,mode);if(s.done){result(l,mode,s,t);return;}const q=mode==='guided'?t.steps[s.step]:{prompt:'Найдите ответ самостоятельно.',answer:t.answer,choices:t.choices,hint:t.steps[0].hint,why:t.explanation};
 const solved=mode==='guided'&&s.answers.length>s.step;
 shell(breadcrumb(l)+'<section class="practice-head"><div><p class="eyebrow">'+(mode==='guided'?'Пошаговая практика':'Самостоятельная проверка')+' · '+position(l)+'</p><h1>'+esc(l.title)+'</h1></div><a class="text-link" href="#lesson/'+l.id+'">К объяснению</a></section><div class="practice-layout"><section class="panel task-panel"><p class="task-index">Условие '+esc(t.id.split('-').slice(-1)[0])+(s.familiar?' · повтор знакомой задачи':' · новое условие')+'</p><div class="task-condition">'+t.prompt+'</div>'+(mode==='guided'?'<ol class="step-trail" aria-label="Шаги решения">'+t.steps.map((step,i)=>'<li class="'+(i<s.step?'passed':i===s.step?'current':'')+'" '+(i===s.step?'aria-current="step"':'')+'>'+(i+1)+'</li>').join('')+'</ol>':'<p class="mode-note">Подсказка поможет продолжить, но этот ответ будет отмечен как решение с помощью.</p>')+'<div class="question">'+q.prompt+'</div><form id="answer-form">'+questionInput(q,s.draft)+'<div class="actions"><button class="button" type="submit" id="submit-answer" '+(solved?'disabled':'')+'>Проверить</button>'+button('Подсказка','hint','button quiet')+'</div></form><div id="feedback" role="status" aria-live="polite" class="feedback '+(solved?'good':'')+'">'+(solved?'Верно. '+(q.why||'Можно перейти дальше.'):'')+'</div><div id="hint-box" class="hint-box" hidden></div><div class="actions">'+button(mode==='guided'&&s.step<t.steps.length-1?'Следующий шаг →':'Завершить задачу','next')+'</div></section><aside class="panel help-panel"><p class="eyebrow">Поддержка</p><h2>Застряли на шаге?</h2><p>Можно восстановить нужное правило и вернуться сюда. Введённый ответ сохранится.</p>'+button('Разобраться с основой','repair','button quiet')+'<hr><p class="small">'+(s.familiar?'Это повтор. Он полезен для тренировки, но не добавляет новое самостоятельное освоение.':'Ошибки — часть обучения. В отчёте они будут отделены от первых самостоятельных успехов.')+'</p><a href="#progress">Посмотреть мой прогресс</a></aside></div>');
 const form=document.getElementById('answer-form'),input=form.elements.answer,feed=document.getElementById('feedback'),next=document.getElementById('next');next.disabled=!solved;
 function draft(){s.draft=String(new FormData(form).get('answer')||'');save();}form.addEventListener('input',draft);form.addEventListener('change',draft);
 form.onsubmit=e=>{e.preventDefault();draft();if(!s.draft.trim()){feed.className='feedback';feed.textContent='Сначала введите или выберите ответ.';return;}const ok=ProfileCheck.check(q.answer,s.draft,q.choices);feed.className='feedback '+(ok?'good':'bad');
 if(ok){feed.innerHTML='Верно. '+(mode==='guided'?(q.why||'Переходим дальше.'):'Теперь можно завершить задачу и посмотреть объяснение.');next.disabled=false;document.getElementById('submit-answer').disabled=true;if(mode==='guided')s.answers[s.step]=s.draft;else s.answers[0]=s.draft;save();next.focus({preventScroll:true});}
 else{s.wrong=true;feed.textContent='Пока не сходится. Проверьте знак, порядок действий и условие. Можно исправить ответ или открыть подсказку.';save();}};
 document.getElementById('hint').onclick=()=>{s.assisted=true;save();const box=document.getElementById('hint-box');box.hidden=false;box.innerHTML='<b>Подсказка к текущему шагу</b><p>'+(q.hint||t.steps[0].hint)+'</p>'+(mode==='independent'?'<p>Если нужна последовательность: '+t.steps.map(x=>x.prompt).join(' → ')+'</p>':'');};
 document.getElementById('repair').onclick=()=>{s.assisted=true;save();location.hash='repair/'+l.id+'/'+mode;};
 main.querySelector('a[href="#lesson/'+l.id+'"]').onclick=()=>{s.assisted=true;save();};
 next.onclick=()=>{if(next.disabled)return;if(mode==='guided'&&s.step<t.steps.length-1){s.step++;s.draft='';save();practice(l,mode);}else{state.finish(l.id,mode,s);result(l,mode,s,t);}};
}
function repair(l,mode){const {s}=current(l,mode);s.assisted=true;save();const p=l.prereq||{title:'Проверяем основы',text:'<p>Выделите известные величины. Сформулируйте, что нужно найти, и выберите одно действие.</p>'};shell(breadcrumb(l)+'<section class="panel repair-panel"><p class="eyebrow">Короткое возвращение к основе</p><h1>'+esc(p.title)+'</h1><div class="theory">'+p.text+'</div>'+(p.href?'<p><a target="_blank" rel="noopener" href="'+esc(p.href)+'">Открыть дополнительный тренажёр в новой вкладке</a></p>':'')+'<a class="button" href="#practice/'+l.id+'/'+mode+'">Вернуться на сохранённый шаг</a><p class="small muted">Помощь отмечена. Знакомое условие можно закончить, затем получить новую задачу.</p></section>');}
function result(l,mode,s,t){const success=mode==='independent'&&!s.wrong&&!s.assisted&&!s.familiar;const idx=lessons.indexOf(l),next=lessons[idx+1];shell(breadcrumb(l)+'<section class="panel result-panel"><span class="result-symbol" aria-hidden="true">✓</span><p class="eyebrow">Задача завершена</p><h1>'+(success?'Вы решили самостоятельно.':'Разобрались — теперь закрепим.')+'</h1><p class="lead">'+(success?'Новое условие, первая попытка, без подсказок.':mode==='guided'?'Пошаговая практика завершена. Следующее новое условие поможет проверить понимание.':s.familiar?'Это повтор знакомой задачи. Он сохранён как тренировка.':'Решение с подсказкой или после ошибки сохранено как тренировка.')+'</p><div class="solution"><h2>Почему это работает</h2><div>'+t.explanation+'</div><p><b>Ответ: </b>'+esc(format(t.answer))+'</p></div><p>'+status(l)+'</p><div class="actions">'+button(mode==='guided'?'Ещё задача по шагам':'Следующая задача','another')+button(mode==='guided'?'Проверить себя':'Вернуться к объяснению','switch','button quiet')+'</div>'+(next?'<p><a href="#lesson/'+next.id+'">Следующая тема: '+esc(next.title)+' →</a></p>':'')+'<p><a href="#progress">Мой отчёт</a> · <a href="#home">Весь маршрут</a></p></section>');document.getElementById('another').onclick=()=>{state.start(l.id,mode,true);practice(l,mode);};document.getElementById('switch').onclick=()=>{if(mode==='guided'){state.start(l.id,'independent',!!state.data.sessions[l.id+':independent']?.done);location.hash='practice/'+l.id+'/independent';}else location.hash='lesson/'+l.id;};}
function format(n){return typeof n==='number'?Number(n.toFixed(8)).toLocaleString('ru-RU',{maximumFractionDigits:8}):n;}
function download(data,name,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function progress(){shell('<section class="lesson-head"><p class="eyebrow">Мой прогресс</p><h1>Что уже получается.</h1><p class="lead">'+allCompleted()+' из '+lessons.length+' тем: две разные новые задачи решены с первой попытки без помощи.</p><p>Это локальная история этого браузера. Скачанный отчёт можно передать учителю или родителю. Облачный журнал групп здесь не подключён.</p><div class="actions">'+button('Скачать отчёт','export')+(state.original?button('Скачать исходное сохранение','raw-export','button quiet'):'')+'</div></section><div class="progress-grid">'+lessons.map(l=>{const r=state.record(l.id);return '<article class="panel"><p class="position">'+position(l)+'</p><h2><a href="#lesson/'+l.id+'">'+esc(l.title)+'</a></h2><p>По шагам: '+r.guided.length+' разных задач<br>Новые самостоятельно: '+r.independent.length+' из 3<br>Завершённых попыток: '+r.attempts+'</p><progress value="'+Math.min(2,r.independent.length)+'" max="2" aria-label="'+esc(l.title)+': самостоятельное освоение"></progress></article>';}).join('')+'</div><aside class="note">Самостоятельные задачи берутся из отдельного набора. Когда все три уже открывались, начнутся повторы с явной отметкой. Они не увеличивают число новых самостоятельных успехов.</aside>');document.getElementById('export').onclick=()=>download(JSON.stringify(state.export(),null,2),'ege-profile-2027-progress.json');const raw=document.getElementById('raw-export');if(raw)raw.onclick=()=>download(state.original,'ege-profile-original-save.txt','text/plain');}
function sources(){shell('<section class="panel repair-panel"><p class="eyebrow">Содержание и источники</p><h1>Что входит в этот выпуск.</h1><p>'+lessons.length+' учебных тем, '+lessons.reduce((n,l)=>n+l.tasks.length,0)+' авторских задач. В каждой теме — объяснение, исследование, пошаговая практика и отдельные условия для самостоятельной проверки.</p><p>Планиметрия и векторы — подготовка к №1 и №2; показательные и логарифмические уравнения — к №7; тригонометрические выражения — к №8 проекта ЕГЭ 2027.</p><p><a href="https://fipi.ru/ege/demoversii-specifikacii-kodifikatory" target="_blank" rel="noopener">ФИПИ: демоверсии, спецификации, кодификаторы</a>. На дату подготовки, 2 октября 2026 года, материалы 2027 обозначены как проект. <a href="https://doc.fipi.ru/ege/demoversii-specifikacii-kodifikatory/2027/ma_11_2027.zip">Официальный архив по математике</a>.</p><p>Упражнения здесь — авторские педагогические аналоги. Они не выдаются за задания открытого банка. Этот выпуск не покрывает все типы ФИПИ и весь профильный экзамен.</p><p>Тригонометрические уравнения второй части, неравенства и параметры в новый маршрут пока не включены. Старые подборки доступны в общем навигаторе с прежней нумерацией.</p><p>Динамическая модель помогает сформулировать предположение. Обоснование опирается на свойства и формулы, а не на точность измерения рисунка.</p><a class="button" href="#home">К учебному маршруту</a></section>');}
function route(){const [page,id,mode]=location.hash.slice(1).split('/');const l=byId.get(id);if(page==='lesson'&&l)return lesson(l);if(page==='practice'&&l&&['guided','independent'].includes(mode))return practice(l,mode);if(page==='repair'&&l&&['guided','independent'].includes(mode))return repair(l,mode);if(page==='progress')return progress();if(page==='sources')return sources();home();}
window.addEventListener('hashchange',route);route();
})();
