(function(root){'use strict';
const KEY='mathexam.profileCalmPreferences.v1';
function create(A){
 const {lessons,state,main,shell,esc,format,questionInput,save}=A,byId=new Map(lessons.map(l=>[l.id,l])),D=root.ProfileCalmData;
 let warning='',blocked=false,prefs={version:1,enabled:false,examples:{},micro:{}};
 try{const raw=localStorage.getItem(KEY);if(raw){const v=JSON.parse(raw);if(v.version!==1||typeof v.enabled!=='boolean'||!v.examples||!v.micro)throw Error();prefs={version:1,enabled:v.enabled,examples:{},micro:{}};for(const [id,n]of Object.entries(v.examples))if(byId.has(id)&&Number.isInteger(n)&&n>=0&&n<15)prefs.examples[id]=n;for(const [k,vv]of Object.entries(v.micro).slice(-100))if(vv&&Array.isArray(vv.answers)&&typeof vv.draft==='string')prefs.micro[k]={answers:vv.answers.slice(0,4).map(String),draft:vv.draft.slice(0,200)};}}catch(_){blocked=true;warning='Настройки спокойного вида не удалось прочитать. Прежние данные сохранены без изменений.';}
 const ordered=D.exams.map(e=>byId.get(e.entry)).concat(lessons.filter(l=>!D.exams.some(e=>e.entry===l.id)));
 let storage;try{storage=localStorage;}catch(_){storage={getItem(){throw Error();}};}
 const checkpoint=root.ProfileCheckpoint.create(ordered,storage,state);
 function persist(){if(blocked)return;try{localStorage.setItem(KEY,JSON.stringify(prefs));}catch(_){warning='Настройки и мелкие действия сейчас сохраняются только до закрытия страницы. Основные шаги можно скачать в отчёте.';}}
 function apply(){document.body.classList.toggle('calm-view',prefs.enabled);const toggle=document.getElementById('calm-toggle');if(toggle){toggle.setAttribute('aria-pressed',String(prefs.enabled));toggle.textContent=prefs.enabled?'Спокойный вид: включён':'Спокойный вид';}}
 function setEnabled(value){prefs.enabled=value;persist();apply();}
 function bindToggle(){const toggle=document.getElementById('calm-toggle');if(toggle)toggle.onclick=()=>{setEnabled(!prefs.enabled);A.route();};apply();}
 function lessonStatus(id){const r=state.record(id);return r.independent.length?`${r.independent.length} новых условий самостоятельно`:r.guided.length?'Есть работа с опорой':'Можно начать с образца';}
 function item(id){const l=byId.get(id);if(!l)return '';return '<article class="readiness-card"><div><h3>'+esc(l.title)+'</h3><p>'+lessonStatus(id)+'</p></div><a class="button quiet" href="#lesson/'+id+'">Открыть тему</a></article>';}
 function route(number){setEnabled(true);const e=D.exams.find(e=>e.number===Number(number));if(e){
  shell('<p class="breadcrumb"><a href="#calm">← Все 13 номеров</a></p><section class="lesson-head"><p class="eyebrow">Спокойный маршрут · №'+e.number+'</p><h1>'+esc(e.title)+'</h1><p class="lead">'+esc(e.goal)+'</p><a class="button" href="#example/'+e.entry+'">Начать с разобранного образца</a></section><section class="panel"><h2>Постепенно берём решение на себя</h2><ol class="plain-steps"><li>Посмотрите один разобранный образец.</li><li>Решите другое условие маленькими шагами.</li><li>Решите с коротким планом: вычисления уже выбираете сами.</li><li>Решите новое условие без подсказок. Позже вернитесь к нему в смешанной проверке.</li></ol><p>Если стало трудно, вернитесь на одну ступень. Начинать весь курс заново не нужно.</p></section><details class="panel"><summary>Что можно вспомнить перед этим номером</summary>'+e.prerequisites.map(item).join('')+'</details>'+(e.number===8?'<details class="panel"><summary>Перед выражениями: основы тригонометрии</summary>'+D.trigFoundations.lessonIds.map(item).join('')+'</details>':'')+'<section class="panel"><h2>Все темы этого номера</h2><p>Разобранный начальный тип — только начало. Постепенно пройдите остальные темы.</p>'+e.lessonIds.map(item).join('')+'</section><a href="#checkpoint">Смешанная проверка</a>');return;}
  const snap=checkpoint.snapshot(),sum=snap.summary||{};
  shell('<section class="lesson-head"><p class="eyebrow">В своём темпе · все 13 номеров</p><h1>Просто бери и решай! Всё получится)</h1><p class="lead">Можно дольше разбирать и чаще повторять. В конце вы решаете новые задачи самостоятельно и выбираете способ решения без подсказанного названия темы.</p><a class="button" href="#readiness">Сначала проверить пробелы</a></section><div class="exam-grid full-course-grid">'+D.exams.map(e=>{const done=e.lessonIds.filter(id=>state.record(id).independent.length>=2).length;return '<a class="exam-card" data-calm-exam="'+e.number+'" href="#calm/'+e.number+'"><span class="exam-number">'+e.number+'</span><h2>'+esc(e.title)+'</h2><p>'+esc(e.goal)+'</p><span class="small">'+done+' из '+e.lessonIds.length+' тем: два новых самостоятельных условия</span><span class="exam-open">Выбрать начало →</span></a>';}).join('')+'</div><section class="panel calm-check-entry"><h2>Смешанная проверка</h2><p>По одному новому условию каждого номера, в смешанном порядке. Без таймера. Название темы не подсказывает способ. Удобный вид, пауза и рисунки остаются.</p><p>Один такой круг не проверяет все возможные типы номера. В следующем круге выбираются другие ещё не открытые условия.</p><a class="button" href="#checkpoint">'+(snap.round&&!snap.round.complete?'Продолжить проверку':'Открыть проверку')+'</a></section>'+(warning?'<p class="storage-warning" role="status">'+esc(warning)+'</p>':''));
 }
 function example(id){const l=byId.get(id);if(!l)return route();setEnabled(true);state.persist();const active=state.data.sessions[id+':independent']?state.start(id,'independent'):null;if(active&&!active.done&&!active.answers.length){active.assisted=true;}
  const t=l.tasks[0];state.data.seen[t.id]=Math.max(1,state.data.seen[t.id]||0);save();let n=Math.min(prefs.examples[id]||0,t.steps.length-1);
  shell('<p class="breadcrumb"><a href="#lesson/'+id+'">← К теме</a></p><section class="lesson-head"><p class="eyebrow">Образец · чтение решения с помощью</p><h1>'+esc(l.title)+'</h1><p>Это показ решения. Самостоятельный результат проверим на другом условии.</p></section><section class="panel"><h2>Условие</h2><div class="task-condition">'+t.prompt+'</div>'+(root.ProfileTaskModels?.[t.id]?'<div id="example-model" aria-label="Рисунок к образцу"></div>':'')+'</section><section class="panel" id="worked-example"><h2>Разобранные шаги</h2><ol class="plain-steps">'+t.steps.slice(0,n+1).map((q,i)=>'<li data-example-step="'+i+'"><p>'+q.prompt+'</p><strong>'+esc(format(q.answer))+'</strong><p>'+q.why+'</p></li>').join('')+'</ol>'+(n<t.steps.length-1?'<button class="button" id="example-next" type="button">Открыть следующий шаг →</button>':'<p>Образец разобран. Теперь попробуйте решить задачу с опорой. Знакомое условие будет отмечено как повтор.</p><button class="button" id="example-practice" type="button">Решать по шагам</button>')+'</section>');
  if(root.ProfileTaskModels?.[t.id])A.setCleanup(root.ProfileTaskModels[t.id](document.getElementById('example-model'),t,{mode:'guided',step:n,solved:true,completed:n+1,onHelp(){}})||(()=>{}));
  const next=document.getElementById('example-next');if(next)next.onclick=()=>{prefs.examples[id]=n+1;persist();example(id);};const start=document.getElementById('example-practice');if(start)start.onclick=()=>{state.start(id,'guided',true);location.hash='practice/'+id+'/guided';};
 }
 function plan(l){const e=D.exams.find(e=>e.number===l.position),rows=e?.plan||['Назовите, что нужно найти.','Выберите действие и выполните вычисление.','Проверьте результат по исходному условию.'];return '<section class="plan-support"><h2>Короткий план</h2><ol>'+rows.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ol><p class="small">Это тренировка с опорой. Подставленные числа и результаты шагов здесь не показаны.</p></section>';}
 function micro(l,t,s,mode){
  if(!prefs.enabled||mode!=='guided')return;const qs=root.ProfileCalmMicro?.steps(t,s.step)||[];if(!qs.length||s.answers.length>s.step)return;
  const panel=document.createElement('section');panel.className='micro-support';panel.innerHTML='<button type="button" class="button quiet" id="micro-start">Разбить это действие на маленькие шаги</button>';document.querySelector('.current-question').prepend(panel);
  const key=t.id+'|'+s.started+'|'+s.step;let rec=prefs.micro[key]||{answers:[],draft:''};
  // Revalidate assistance values so stale content never skips a changed question.
  let valid=0;while(valid<rec.answers.length&&qs[valid]&&root.ProfileCheck.check(qs[valid].answer,rec.answers[valid],qs[valid].choices))valid++;rec.answers=rec.answers.slice(0,valid);
  function write(){prefs.micro[key]=rec;const keys=Object.keys(prefs.micro);if(keys.length>100)delete prefs.micro[keys[0]];persist();}
  function draw(){const index=rec.answers.length;for(const element of document.querySelectorAll('.current-question > .question,.current-question > #answer-form,.current-question > #feedback,.current-question > .next-actions'))element.hidden=index<qs.length;panel.innerHTML='<h2>Одно маленькое действие</h2><ol>'+qs.slice(0,index).map((q,i)=>'<li><span>'+q.prompt+'</span> <strong>'+esc(rec.answers[i])+'</strong></li>').join('')+'</ol>'+(index<qs.length?'<p class="small">Подготовка '+(index+1)+' из '+qs.length+'</p><p id="micro-question">'+qs[index].prompt+'</p><form id="micro-form">'+(qs[index].choices?'<label for="micro-answer">Выберите ответ</label><select id="micro-answer"><option value="">Выберите…</option>'+qs[index].choices.map(v=>'<option value="'+esc(v)+'">'+esc(v)+'</option>').join('')+'</select>':'<label for="micro-answer">Ответ</label><input id="micro-answer" type="text" autocomplete="off">')+'<button class="button" type="submit">Проверить маленький шаг</button></form><p id="micro-feedback" role="status" aria-live="polite"></p>':'<p>Подготовительные действия выполнены. Теперь вернитесь к основному вопросу ниже.</p>');
   if(index>=qs.length){document.getElementById('answer')?.focus({preventScroll:true});return;}const input=panel.querySelector('#micro-answer');input.value=rec.draft;input.setAttribute('aria-describedby','micro-question');input.focus({preventScroll:true});input.oninput=()=>{rec.draft=input.value;write();};panel.querySelector('#micro-form').onsubmit=e=>{e.preventDefault();const q=qs[index],value=input.value;if(!value.trim()){panel.querySelector('#micro-feedback').textContent='Сначала введите или выберите ответ.';return;}if(!q.choices&&!Number.isFinite(root.ProfileCheck.number(value))){panel.querySelector('#micro-feedback').textContent='Не удалось прочитать число. Можно ввести дробь.';return;}if(root.ProfileCheck.check(q.answer,value,q.choices)){rec.answers.push(value);rec.draft='';write();draw();}else{panel.querySelector('#micro-feedback').textContent=q.hint||'Вернитесь к данным этого маленького шага.';}};
  }
  panel.querySelector('#micro-start').onclick=draw;if(rec.answers.length||rec.draft)draw();
 }
 function warningText(){return [warning,checkpoint.warning].filter(Boolean).map(x=>'<p class="storage-warning" role="status">'+esc(x)+'</p>').join('');}
 function check(){setEnabled(true);let c=checkpoint.current();if(!c){checkpoint.startRound();c=checkpoint.current();}if(!c){shell('<h1>Проверка недоступна</h1>'+warningText()+'<a href="#calm">К учебному маршруту</a>');return;}
  const snap=checkpoint.snapshot();if(c.complete){const rows=snap.round.items;const correct=rows.filter(r=>r.submitted&&r.correct&&!r.assisted&&!r.unavailable).length;shell('<section class="panel" id="checkpoint-result"><p class="eyebrow">Итог смешанной проверки</p><h1>Что получилось без опор.</h1><p>'+correct+' из 13 условий решены с первой попытки без помощи. Это результат этого круга, а не освоение всех типов каждого номера.</p><ul>'+rows.map(r=>'<li>№'+r.number+': '+(r.unavailable?'не было нового условия':r.assisted?'разобрано с помощью':r.correct?'самостоятельно':'нужно повторение')+' · <a href="#calm/'+r.number+'">Учебный маршрут</a></li>').join('')+'</ul><div class="actions"><button type="button" class="button" id="checkpoint-again">Новый круг с другими условиями</button><button type="button" class="button quiet" id="checkpoint-export">Скачать отчёт проверки</button></div><p>После практики вернитесь к проверке в другой день. Дата каждого круга есть в отчёте.</p></section>'+warningText());document.getElementById('checkpoint-again').onclick=()=>{checkpoint.startRound(true);check();};document.getElementById('checkpoint-export').onclick=()=>A.download(JSON.stringify(checkpoint.export(),null,2),'profile-checkpoint.json');return;}
  if(c.unavailable){shell('<section class="panel"><h1>Для №'+c.number+' новые условия закончились.</h1><p>Знакомое условие не будет выдано за новую самостоятельную проверку. Этот номер останется без результата в текущем круге.</p><button type="button" class="button" id="checkpoint-next">Продолжить круг</button><p><a href="#calm/'+c.number+'">Повторять этот номер с опорой</a></p></section>'+warningText());document.getElementById('checkpoint-next').onclick=()=>{checkpoint.next(c.token);check();};return;}
  shell('<section class="practice-head"><div><p class="eyebrow">Смешанная проверка · '+(c.position+1)+' из 13</p><h1>Задание №'+c.number+'</h1></div><button type="button" class="button quiet" id="checkpoint-pause">Сделать паузу</button></section><section class="panel condition-panel"><h2>Условие</h2><div class="task-condition">'+c.task.prompt+'</div>'+(root.ProfileTaskModels?.[c.task.id]?'<div id="checkpoint-model" aria-label="Рисунок и данные к задаче"></div>':'')+'</section><section class="panel"><form id="checkpoint-form">'+questionInput(c.task,c.draft)+'<button class="button" id="checkpoint-submit" type="submit" '+(c.submitted?'disabled':'')+'>Принять ответ</button></form><p id="checkpoint-feedback" role="status">'+(c.submitted?(c.assisted?'Ответ сохранён как работа с помощью.':c.correct?'Ответ верный. Самостоятельное условие засчитано.':'Ответ сохранён. Эту тему стоит повторить.'):'Проверяем первое решение. Если нужна помощь, можно перейти к разбору.')+'</p><div class="actions">'+(c.submitted?'<button class="button" type="button" id="checkpoint-next">Следующее задание →</button>':'')+'<button class="button quiet" type="button" id="checkpoint-help">Разобрать эту задачу</button></div></section>'+warningText());
  let modelCleanup=()=>{};if(root.ProfileTaskModels?.[c.task.id])modelCleanup=root.ProfileTaskModels[c.task.id](document.getElementById('checkpoint-model'),c.task,{mode:'independent',strict:true,step:0,solved:c.submitted,completed:c.submitted?1:0,onHelp(){const after=checkpoint.help(c.token);if(after.token!==c.token||after.submitted!==c.submitted){check();return;}document.getElementById('checkpoint-feedback').textContent=c.submitted?'Показано объяснение после принятого ответа. Результат не меняется.':'Открыта математическая помощь. Это условие сохранится как тренировка.';}})||modelCleanup;A.setCleanup(modelCleanup);
  const input=document.getElementById('answer');if(input){input.disabled=c.submitted;input.oninput=()=>{const after=checkpoint.persistDraft(input.value,c.token);if(after.token!==c.token||after.submitted!==c.submitted)check();};}
  document.getElementById('checkpoint-form').onsubmit=e=>{e.preventDefault();const shown=checkpoint.current();if(shown.token!==c.token||shown.submitted!==c.submitted){check();return;}if(c.submitted)return;const value=input?.value||'';if(!value.trim()||!Number.isFinite(root.ProfileCheck.number(value))){document.getElementById('checkpoint-feedback').textContent='Введите число, например 0,75 или 3/4. Это не считается ошибкой решения.';return;}checkpoint.submit(value,root.ProfileCheck.check,c.token);check();};
  const next=document.getElementById('checkpoint-next');if(next)next.onclick=()=>{checkpoint.next(c.token);check();};
  document.getElementById('checkpoint-help').onclick=()=>{const after=checkpoint.help(c.token);if(after.token!==c.token||after.submitted!==c.submitted){check();return;}state.remediate(c.lesson.id,c.task.id);A.setReturn('#checkpoint');location.hash='practice/'+c.lesson.id+'/guided';};
  document.getElementById('checkpoint-pause').onclick=()=>{location.hash='checkpoint-pause';};
 }
 function checkPause(){shell('<section class="panel"><h1>Можно сделать паузу.</h1><p>Условие и ваш введённый ответ сохранены. Ограничения времени нет.</p><a class="button" href="#checkpoint">Продолжить с того же места</a><p><a href="#calm">К маршруту</a></p></section>'+warningText());}
 function beforeRoute(page){if(['lesson','example','practice','repair','repair-task'].includes(page)){const s=checkpoint.snapshot();if(s.round&&!s.round.complete&&s.round.items[s.round.index]?.taskId&&!s.round.items[s.round.index]?.submitted)checkpoint.help();}}
 return {KEY,bindToggle,apply,setEnabled,enabled:()=>prefs.enabled,route,example,plan,micro,check,checkPause,beforeRoute,checkpoint};
}
root.ProfileCalmUI={create,KEY};
})(globalThis);
