const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const root=process.env.COURSE_PREVIEW_DIR;if(!root)throw Error('Set COURSE_PREVIEW_DIR to the extracted combined ZIP');const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const start='file://'+path.resolve(root,'ege-baza/index.html');
await page.goto(start);await page.click('a[href="algebra/index.html#base"]');await page.waitForSelector('#baseModel');assert((await page.locator('h1').innerText()).includes('Алгебра'));
await page.goto(start);await page.click('a[href="percent/index.html"]');await page.waitForSelector('[data-preset="125"]');
await page.goto(start);await page.click('a[href="labs/index.html"]');await page.waitForSelector('canvas');await page.click('[data-tab="plane"]');await page.click('[data-plan="1"]');for(const n of ['B','A','C'])await page.click(`[data-pick="${n}"]`);assert.equal(await page.evaluate(()=>MathExamLabs.getState().planeStep),2);
await page.goto(start);await page.click('a[href="reasoning/index.html"]');await page.waitForSelector('[data-digit]');
await page.goto(start);await page.click('a[href="work-rate/index.html"]');await page.click('#finish');assert((await page.locator('#workSummary').innerText()).includes('100%'));
for(const module of ['m01','m02']){await page.goto(start+'#module?module='+module);await page.click('.lesson a.btn');await page.waitForSelector('h1');assert(page.url().includes(module==='m01'?'/course/':'/data-course/'));await page.locator('a[href^="../../../ege-baza/index.html#"]').first().click();await page.waitForSelector('#content h1');assert(page.url().includes('/ege-baza/index.html#'));}
assert.deepEqual(errors,[]);await browser.close();console.log('ASSEMBLED_PREVIEW_BROWSER_OK: archive entry links, both old modules, new sections, WebGL and perpendicular construction.');})().catch(e=>{console.error(e);process.exit(1);});
