const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path');const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||undefined,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const errors=[],page=await browser.newPage({viewport:{width:1280,height:900}});page.on('pageerror',e=>errors.push(e.message));const url='file://'+path.resolve(__dirname,'../ege-baza/labs/index.html');await page.goto(url);await page.waitForSelector('canvas');
 await page.evaluate(()=>localStorage.setItem('mathExamCourseProgress.v1','{"untouched":true}'));
 const move=async(id,value)=>page.locator(id).evaluate((el,v)=>{el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));},String(value));
 await move('#solidParameter',100);assert((await page.locator('#solidMeaning').innerText()).includes('Вся деталь'));
 await page.selectOption('#solidMode','cone');await move('#solidParameter',50);assert((await page.locator('#solidFacts').innerText()).includes('0,125'));
 await page.locator('#solidAnswer').fill('8');await page.click('#solidAnswerCheck');assert((await page.locator('#solidFeedback').innerText()).includes('Верно'));
 await page.click('#animateSolid');await page.waitForTimeout(100);await page.click('#animateSolid');const paused=await page.evaluate(()=>MathExamLabs.getState().solidValue);await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>MathExamLabs.getState().solidValue),paused);
 await page.click('[data-tab="plane"]');await page.click('[data-pick="A"]');await page.click('[data-pick="C"]');assert.equal(await page.evaluate(()=>MathExamLabs.getState().planeStep),1);await page.click('[data-pick="B"]');await page.click('[data-pick="M"]');await page.click('[data-reason="1"]');await page.fill('#planeAnswer','8');await page.click('#planeAnswerCheck');await page.fill('#planeAnswer','48');await page.click('#planeAnswerCheck');assert.equal(await page.evaluate(()=>MathExamLabs.getState().planeStep),5);
 await page.selectOption('#planeMode','circle');await page.click('[data-pick="A"]');await page.click('[data-pick="C"]');await page.click('[data-pick="B"]');await page.click('[data-pick="C"]');await page.click('[data-reason="0"]');await page.click('[data-hyp="AB"]');await page.fill('#planeAnswer','8');await page.click('#planeAnswerCheck');assert.equal(await page.evaluate(()=>MathExamLabs.getState().planeStep),5);
 await page.click('[data-tab="trig"]');await page.click('[data-jump="750"]');assert((await page.locator('#trigFacts').innerText()).includes('1/2'));await page.click('[data-jump="90"]');await page.check('#showTan');assert((await page.locator('#tanMeaning').innerText()).includes('не определён'));await page.locator('#angle').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>MathExamLabs.getState().angle),91);
 await page.click('[data-tab="ineq"]');const domains=[0,0,1,1,1,2],bounds=['-2','-2;3','-2;3','-2;3','1;5','-1'],zones=[[0],[1],[0,2],[0,2],[1],[0]],ends=[[0],[0,1],[],[],[1],[0]];
 for(let i=0;i<6;i++){await page.selectOption('#ineqCase',String(i));await page.click(`[data-domain="${domains[i]}"]`);await page.fill('#boundaries',bounds[i]);await page.click('#checkBounds');for(const z of zones[i])await page.click(`[data-zone-button="${z}"]`);for(const e of ends[i])await page.click(`[data-end-button="${e}"]`);await page.click('#checkIntervals');assert((await page.locator('#ineqFeedback').innerText()).startsWith('Верно'),`case ${i}`);}
 // A denominator root must remain excluded even with a non-strict inequality.
 await page.selectOption('#ineqCase','3');await page.click('[data-domain="1"]');await page.fill('#boundaries','-2;3');await page.click('#checkBounds');await page.click('[data-end-button="0"]');await page.click('#checkIntervals');assert((await page.locator('#ineqFeedback').innerText()).includes('не определено'));
 // Expected answers calculated independently of the application bank.
 const keys={stereo:[90,1500,135,5],plane:[108,24,{choice:1},12],trig:[9,{choice:1},{choice:0},{choice:3}],ineq:[{choice:1},{choice:1},{choice:0},{choice:1},3124,3214]};
 for(const [tab,key] of Object.entries(keys)){await page.click(`[data-tab="${tab}"]`);await page.click('#openQuiz');await page.click('#submitQuiz');assert((await page.locator('#quizError').innerText()).length>0);for(const a of key){if(typeof a==='object')await page.click(`[data-answer="${a.choice}"]`);else await page.fill('#quizNumber',String(a));await page.click('#submitQuiz');}assert.equal(await page.locator('#quiz h2').innerText(),`${key.length} из ${key.length}`);await page.click('#finishQuiz');}
 await page.click('#openQuiz');await page.click('#backQuiz');await page.click('#openQuiz');for(let i=0;i<6;i++)await page.click('#skipQuiz');assert((await page.locator('#quiz').innerText()).includes('Учебная попытка'));await page.click('#finishQuiz');
 const downloadPromise=page.waitForEvent('download');await page.click('#report');const download=await downloadPromise;assert.equal(download.suggestedFilename(),'MathExam_Labs_Report.txt');
 const out=process.env.LABS_SCREENSHOT_DIR;if(out)fs.mkdirSync(out,{recursive:true});
 for(const width of [1280,768,360]){await page.setViewportSize({width,height:900});for(const tab of Object.keys(keys)){await page.click(`[data-tab="${tab}"]`);if(tab==='stereo'){await page.selectOption('#solidMode','water');await move('#solidParameter',100);}if(tab==='plane'){await page.selectOption('#planeMode','median');await page.click('[data-pick="A"]');await page.click('[data-pick="C"]');await page.click('[data-pick="B"]');await page.click('[data-pick="M"]');}if(tab==='trig')await page.click('[data-jump="150"]');if(tab==='ineq'){await page.selectOption('#ineqCase','4');await page.click('[data-domain="1"]');await page.fill('#boundaries','1;5');await page.click('#checkBounds');await page.click('[data-zone-button="1"]');await page.click('[data-end-button="1"]');}assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`overflow ${tab}/${width}`);if(out)await page.screenshot({path:path.join(out,`${tab}-${width}.png`),fullPage:true});}}
 assert.equal(await page.evaluate(()=>localStorage.getItem('mathExamCourseProgress.v1')),'{"untouched":true}');assert.deepEqual(errors,[]);
 // Touch-enabled context checks tap construction, and a pointer drag on the 3D canvas.
 const touch=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const p=await touch.newPage();await p.goto(url);await p.waitForSelector('canvas');await p.locator('[data-tab="plane"]').tap();await p.locator('[data-pick="A"]').tap();await p.locator('[data-pick="C"]').tap();assert.equal(await p.evaluate(()=>MathExamLabs.getState().planeStep),1);await p.locator('[data-tab="stereo"]').tap();const bb=await p.locator('canvas').boundingBox();await p.mouse.move(bb.x+80,bb.y+80);await p.mouse.down();await p.mouse.move(bb.x+150,bb.y+100,{steps:5});await p.mouse.up();
 await touch.close();await browser.close();console.log('PASS: real Chromium/WebGL, 2 solid models, pause, both construction paths, keyboard circle control, all 6 inequality builders, all 18 independent answers, assistance/skips, report download, 3 widths × 4 labs, touch taps, storage isolation.');
})().catch(e=>{console.error(e);process.exit(1);});
