const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {answerKeys,percentKeys}=require('./ege-baza-algebra-percent.test.cjs');
(async()=>{
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const root='file://'+path.resolve(__dirname,'../ege-baza/')+'/';
const move=async(id,value)=>page.locator(id).evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));},String(value));
const algebraAnswer=async(a,quiz=false)=>{const prefix=quiz?'quizInput':'practiceInput';if(typeof a==='number')await page.click(`#${prefix} [data-value="${a}"]`);else await page.fill(`#${prefix}Field`,a);await page.click(quiz?'#quizSubmit':'#practiceCheck');};
await page.goto(root+'algebra/index.html');await page.waitForSelector('#functionGraph');
await page.evaluate(()=>localStorage.setItem('mathExamCourseProgress.v1','{"sentinel":1}'));
const guided={exp:[[0,0,0],[1,1,0],[1,0,1],[0,2]],log:[[1,0,1],[2,0,2],[0,1,2],[1,1,0,2]]};
for(const [route,keys] of Object.entries(guided)){await page.click(`[data-route="${route}"]`);for(let i=0;i<keys.length;i++){await page.selectOption('#lessonSelect',String(i));for(const a of keys[i])await page.click(`[data-lesson-answer="${a}"]`);assert(await page.locator('#taskGraph').isVisible());}}
// Virtual learner 1: a fraction gap blocks the inequality; return must preserve exact step and decreasing base.
await page.click('[data-route="exp"]');await page.selectOption('#lessonSelect','1');await page.click('[data-base="0.5"]');await page.click('[data-lesson-answer="1"]');await page.click('#prerequisite');assert.equal(await page.evaluate(()=>MathExamAlgebra.getState().skill),'fractions');await algebraAnswer('2/5');assert((await page.locator('#practiceFeedback').innerText()).includes('Пока'));await algebraAnswer('5/6');await page.click('#returnTask');assert.deepEqual(await page.evaluate(()=>{const s=MathExamAlgebra.getState();return [s.route,s.lesson.exp.index,s.lesson.exp.step,s.base];}),['exp',1,1,.5]);
await page.click('[data-route="base"]');
for(const [skill,key] of Object.entries(answerKeys)){await page.click(`[data-skill="${skill}"]`);if(skill==='fractions')await page.click('#practiceNext');const start=skill==='fractions'?1:0;for(let i=start;i<6;i++){await algebraAnswer(key[i]);assert((await page.locator('#practiceFeedback').innerText()).startsWith('Верно'),skill+' '+i);if(i<5)await page.click('#practiceNext');}}
// Models: division by zero, fraction reduction, equal operations, place carry.
await page.click('[data-skill="fractions"]');await page.selectOption('#fractionB','0');await page.selectOption('#fractionOp','/');assert((await page.locator('#fractionFormula').innerText()).includes('не определено'));
await page.click('[data-skill="divisibility"]');await page.click('#practiceNext');await page.click('#practiceNext');await page.click('#practiceNext');await algebraAnswer('18/24');assert((await page.locator('#practiceFeedback').innerText()).includes('Пока'));await algebraAnswer('3/4');assert((await page.locator('#practiceFeedback').innerText()).startsWith('Верно'));
await page.click('[data-skill="equations"]');await page.click('#equationApply');assert((await page.locator('#equationModel').innerText()).includes('(2)x + (0) = 8'));await page.selectOption('#equationOp','/');await page.fill('#equationValue','2');await page.click('#equationApply');assert((await page.locator('#equationModel').innerText()).includes('(1)x + (0) = 4'));await page.fill('#equationValue','0');await page.click('#equationApply');assert((await page.locator('#equationFeedback').innerText()).includes('ноль'));
await page.click('#diagnostic');await page.click('#quizSubmit');assert((await page.locator('#quizError').innerText()).length);for(const key of Object.values(answerKeys))for(const a of key.slice(6))await algebraAnswer(a,true);assert.equal(await page.locator('#screen h2').innerText(),'28 из 28');await page.click('#quizFinish');
for(const [route,answers] of Object.entries({exp:['6',1,'3/2',0],log:['13',1,1,'9']})){await page.click(`[data-route="${route}"]`);await page.click('#functionCheck');for(const a of answers)await algebraAnswer(a,true);assert.equal(await page.locator('#screen h2').innerText(),'4 из 4');await page.click('#quizFinish');}
// Virtual learner 2: guesses/skips and looks at explanations; must not acquire independent credit.
await page.click('#diagnostic');await page.click('#quizBack');await page.click('#diagnostic');for(let i=0;i<28;i++)await page.click('#quizSkip');assert((await page.locator('#screen').innerText()).includes('УЧЕБНАЯ'));assert.equal(await page.evaluate(()=>MathExamAlgebra.getState().records.at(-1).independent),false);
const down=page.waitForEvent('download');await page.click('#download');assert.equal((await down).suggestedFilename(),'MathExam_Algebra_Report.txt');
assert.equal(await page.evaluate(()=>localStorage.getItem('mathExamCourseProgress.v1')),'{"sentinel":1}');
await page.goto(root+'percent/index.html');await page.waitForSelector('[data-model="shop"]');
const pctAnswer=async(a)=>{if(typeof a==='number')await page.click(`[data-choice="${a}"]`);else await page.fill('#number',a);await page.click('#submit');};
// Virtual learner 3: confuses the old and new base, changes model, uses a prerequisite, and resumes.
await page.click('[data-route="lessons"]');await page.selectOption('#lessonSelect','8');await pctAnswer(0);assert((await page.locator('#feedback').innerText()).includes('Проверьте'));await pctAnswer(1);await page.click('#foundation');await pctAnswer('10');await page.click('#back');assert((await page.locator('#screen').innerText()).includes('Шаг 2 из 3'));
await page.click('[data-route="models"]');await page.click('[data-model="compare"]');assert((await page.locator('#meaning').innerText()).includes('50%'));await page.selectOption('#base','A');assert((await page.locator('#meaning').innerText()).includes('33,333'));
await page.click('[data-model="shop"]');assert((await page.locator('#meaning').innerText()).includes('960'));await page.click('#swap');assert((await page.locator('#meaning').innerText()).includes('960'));
await page.click('[data-model="mix"]');await page.selectOption('#mixMode','evaporate');await move('#water',300);assert((await page.locator('#meaning').innerText()).includes('Проверьте условие'));await page.selectOption('#mixMode','water');await move('#water',100);assert((await page.locator('#meaning').innerText()).includes('10% соли'));
await page.click('[data-route="lessons"]');for(let i=0;i<percentKeys.length;i++){await page.selectOption('#lessonSelect',String(i));await page.click('#resetLesson');for(const a of percentKeys[i])await pctAnswer(a);assert((await page.locator('#screen').innerText()).includes('Решение построено'),'percent '+i);}
await page.click('[data-route="clinic"]');for(let i=0;i<6;i++){await pctAnswer(0);assert((await page.locator('#feedback').innerText()).startsWith('Верно'));await page.click('#back');}
// Virtual learner 4: competent learner on previously unseen transfer items, all independently calculated answers.
await page.click('[data-route="check"]');const key=['63','120','35','85','100/3','36','224','12','2000','1440','200/3','50','12','16','16','300','172.8','20','300','7',1,1,'60',1];for(const a of key)await pctAnswer(a);assert.equal(await page.locator('#screen h2').innerText(),'24 из 24');assert.equal(await page.evaluate(()=>MathExamPercent.getState().records.at(-1).independent),true);
const pd=page.waitForEvent('download');await page.click('#report');assert.equal((await pd).suggestedFilename(),'MathExam_Percent_Report.txt');
// Virtual learner 5: small screen, keyboard and touch. All model states must remain within viewport.
const out=process.env.COURSE_SCREENSHOT_DIR;if(out)fs.mkdirSync(out,{recursive:true});
for(const width of [1280,768,360]){await page.setViewportSize({width,height:900});await page.click('[data-route="models"]');for(const model of ['hundred','compare','ratio','shop','mix','growth']){await page.click(`[data-model="${model}"]`);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`percent overflow ${model} ${width}`);if(out&&(width===360||model==='hundred'))await page.screenshot({path:path.join(out,`percent-${model}-${width}.png`),fullPage:true});}}
await page.goto(root+'algebra/index.html');for(const width of [1280,768,360]){await page.setViewportSize({width,height:900});for(const section of ['exp','log','base']){await page.click(`[data-route="${section}"]`);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`algebra ${section} ${width}`);if(section==='base')for(const skill of Object.keys(answerKeys)){if(width<=780)await page.selectOption('#mobileSkill',skill);else await page.click(`[data-skill="${skill}"]`);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`base overflow ${skill} ${width}`);}if(out)await page.screenshot({path:path.join(out,`algebra-${section}-${width}.png`),fullPage:true});}}
const touch=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const p=await touch.newPage();await p.goto(root+'percent/index.html');await p.locator('[data-preset="125"]').tap();assert.equal(await p.evaluate(()=>MathExamPercent.getState().p),125);await p.locator('#p').focus();await p.keyboard.press('ArrowRight');assert.equal(await p.evaluate(()=>MathExamPercent.getState().p),126);await touch.close();
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: 84 foundation tasks, 36 algebra checks, 8 guided function tasks, 17 percentage lessons, 24 percentage checks, 6 error clinics, 5 virtual-learner scenarios, reports, 3 widths, keyboard/touch and storage isolation.');
})().catch(e=>{console.error(e);process.exit(1);});
