const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const ROOT=path.resolve(__dirname,'..'),OUT=process.env.BROWSER_ARTIFACTS_DIR;
const server=http.createServer((req,res)=>{let file;try{file=path.resolve(ROOT,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(ROOT+path.sep))throw Error();if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.json':'application/json','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch(e){res.writeHead(404);res.end('Not found');}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,base=origin+'/ege-baza/path/index.html';const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
 try{const page=await browser.newPage({viewport:{width:1280,height:900},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);assert.equal(await page.locator('#cards>.card').count(),21);await page.locator('#search').fill('скидк');assert((await page.locator('#cards').innerText()).includes('скидк'));await page.locator('#search').fill('');
 const ids=await page.evaluate(()=>PathData.practice.catalog.map(m=>m.id));
 for(const id of ids){await page.goto(base+'#lesson='+id);await page.locator('[data-stage="1"]').click();await page.waitForSelector('#model');assert((await page.locator('#model').innerText()).trim().length>0,id);await page.locator('[data-stage="3"]').click();assert(await page.locator('#answer').isVisible());}
 // A keyboard answer survives reload, the first wrong attempt is recorded,
 // and remediation returns to the same task rather than to the course homepage.
 await page.goto(base+'#lesson=practice-percent-whole');await page.locator('[data-stage="3"]').click();await page.locator('#new').click();const before=await page.evaluate(()=>{const l=PathCourse.state().lessons['practice-percent-whole'];return {seed:l.seed,independent:l.independent};});
 await page.locator('#answer').fill('17');await page.reload();assert.equal(await page.locator('#answer').inputValue(),'17');await page.locator('#answer').press('Enter');await page.waitForSelector('#ege-remediation a');await page.locator('#ege-remediation a').click();await page.waitForSelector('#ege-return a');await page.locator('#ege-return a').click();await page.waitForSelector('#answer');assert.equal(await page.evaluate(()=>PathCourse.state().lessons['practice-percent-whole'].seed),before.seed);
 const answer=await page.evaluate(()=>PathData.task('practice-percent-whole',PathCourse.state().lessons['practice-percent-whole'].seed).answer);await page.locator('#answer').fill(String(answer));await page.locator('#answer').press('Enter');assert.equal(await page.evaluate(()=>PathCourse.state().lessons['practice-percent-whole'].independent),before.independent);
 // Independent matching requires all four entries and does not accept prefixes.
 await page.goto(base+'#lesson=practice-inequality-match');await page.locator('[data-stage="3"]').click();await page.locator('#answer').fill('12');await page.locator('#answer').press('Enter');assert((await page.locator('#feedback').innerText()).includes('неверно'));
 // Visual and overflow checks: document fits, wide tables may scroll locally.
 if(OUT)fs.mkdirSync(OUT,{recursive:true});
 for(const width of [360,768,1280]){await page.setViewportSize({width,height:900});for(const id of ['practice-delivery','practice-grid-cut','practice-graph-match','practice-number-match','practice-percent-part','practice-right-ratio','box']){await page.goto(base+'#lesson='+id);await page.locator('[data-stage="1"]').click();const sizes=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,view:innerWidth}));assert(sizes.scroll<=sizes.view+1,`${id}: horizontal overflow at ${width}: ${JSON.stringify(sizes)}`);if(OUT&&((width===360&&id==='practice-delivery')||(width===768&&id==='practice-graph-match')||(width===1280&&id==='practice-grid-cut')))await page.screenshot({path:path.join(OUT,`${id}-${width}.png`),fullPage:true});}}
 // Figure construction and a keyboard-operable interactive fraction model.
 await page.goto(base+'#lesson=practice-grid-cut');await page.locator('[data-stage="1"]').click();await page.locator('#auxRect').click();assert((await page.locator('#constructionRead').innerText()).includes('вычесть'));
 await page.goto(base+'#lesson=practice-fraction-percent');await page.locator('[data-stage="1"]').click();const n=await page.evaluate(()=>{let l=PathCourse.state().lessons['practice-fraction-percent'];return PathData.task('practice-fraction-percent',l.seed).model.fractions[0][0];});for(let i=0;i<n;i++){await page.locator(`[data-share="${i}"]`).focus();await page.keyboard.press('Space');}await page.locator('#checkShares').click();assert((await page.locator('#modelFeedback').innerText()).includes('верно'));
 // The board catalog contains every new family and the opening query is correct.
 const catalog=await (await page.request.get(origin+'/trainers/board-picker-data.json')).json();for(const id of ids)assert(catalog.entries.some(x=>x.href==='/ege-baza/path/index.html#lesson='+id));const board=page.locator('a[href*="trainer-board.html"]');assert((await board.getAttribute('href')).includes('trainer='));
 // Exam representations, completion and export affordance in a real browser.
 await page.goto(base+'#exam');await page.locator('#start').click();for(let i=0;i<21;i++){const t=await page.evaluate(()=>{const r=PathCourse.state().active;return PathData.task(r.ids[r.i],r.seed+r.i);});assert.equal(t.pos,i+1);await page.locator('#answer').fill(String(t.answer));await page.locator('#answer').press('Enter');}await page.waitForSelector('#export');assert((await page.locator('#main').innerText()).includes('21/21'));assert.deepEqual(errors,[]);
 console.log('EGE_BAZA_PRACTICE_BROWSER_OK: Chromium; 75 lesson models; 360/768/1280px; keyboard; exact remediation return; reload; matching; full 21-task exam; board catalog; no page errors.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server.close());
