const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');const {keys,checks}=require('./ege-baza-reasoning.test.cjs');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const p=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file://'+path.resolve(__dirname,'../ege-baza/reasoning/index.html'));
const answer=async a=>{if(typeof a==='number')await p.click(`[data-choice="${a}"]`);else await p.fill('#number',a);await p.click('#submit');};const move=async(id,v)=>p.locator(id).evaluate((el,v)=>{el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));},String(v));
for(let i=0;i<keys.length;i++){await p.selectOption('#lesson',String(i));if(i===0){await answer(1);assert((await p.locator('#feedback').innerText()).includes('Проверьте'));}for(let j=0;j<keys[i].length;j++){if(i===4&&j===3){await answer('7.2');assert((await p.locator('#feedback').innerText()).includes('Проверьте'));}if(i===8&&j===1){await answer(0);assert((await p.locator('#feedback').innerText()).includes('Пропуски')||(await p.locator('#feedback').innerText()).includes('пропуски'));}await answer(keys[i][j]);}assert((await p.locator('#steps').innerText()).includes('Рассуждение построено'),'lesson '+i);}
await p.selectOption('#lesson','0');for(const [i,v] of [1,9,3,5].entries())await p.selectOption(`[data-digit="${i}"]`,String(v));assert.equal(await p.locator('.constraint.bad').count(),0);
await p.selectOption('#lesson','3');for(const i of [2,6,7])await p.click(`[data-strike="${i}"]`);assert((await p.locator('#strikeInfo').innerText()).includes('Все условия'));await p.click('[data-strike="2"]');assert((await p.locator('#strikeInfo').innerText()).includes('Нужны'));
await p.selectOption('#lesson','4');await p.click('#turn');assert((await p.locator('#roadInfo').innerText()).includes('6 км'));await p.click('#meet');assert((await p.locator('#roadInfo').innerText()).includes('4,8'));await p.click('#play');await p.waitForTimeout(120);await p.click('#play');const t=await p.evaluate(()=>MathExamReasoning.getState().time);await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>MathExamReasoning.getState().time),t);await p.click('#play');await p.selectOption('#lesson','5');assert.equal(await p.evaluate(()=>MathExamReasoning.getState().animation),0);
assert((await p.locator('#avgInfo').innerText()).includes('72'));await p.selectOption('#lesson','8');await move('#wrong',1);assert((await p.locator('#scoreInfo').innerText()).includes('дробным'));await move('#wrong',7);assert((await p.locator('#scoreInfo').innerText()).includes('больше двадцати'));await move('#wrong',3);assert((await p.locator('#scoreInfo').innerText()).includes('✓'));await p.click('#enumerate');assert.equal(await p.locator('#allScores tr').count(),21);
await p.selectOption('#lesson','9');await move('#cutX',7);await move('#cutY',3);assert((await p.locator('#rectInfo').innerText()).includes('= 42'));await p.click('#resetModel');assert((await p.locator('#rectInfo').innerText()).includes('22 + 20 = 26 + 16'));
await p.selectOption('#lesson','10');await p.click('#construct');assert((await p.locator('#constructed').innerText()).includes('Сначала'));await move('#rowN',16);await p.click('#construct');assert.equal(await p.locator('#constructed tr').count(),18);
await p.selectOption('#lesson','11');await p.click('#viaD');assert((await p.locator('#ringInfo').innerText()).includes('80 км'));
await p.click('#check');await p.click('#submit');assert((await p.locator('#feedback').innerText()).includes('Введите'));for(const a of checks)await answer(a);assert.equal(await p.locator('#screen h2').innerText(),'12 из 12');await p.click('#finish');await p.click('#check');await p.click('#back');await p.click('#check');for(let i=0;i<12;i++)await p.click('#skip');assert.equal(await p.evaluate(()=>MathExamReasoning.getState().records.at(-1).independent),false);
const dl=p.waitForEvent('download');await p.click('#report');assert.equal((await dl).suggestedFilename(),'MathExam_19_21_Report.txt');
const out=process.env.COURSE_SCREENSHOT_DIR;if(out)fs.mkdirSync(out,{recursive:true});await p.click('#learn');for(const width of [1280,768,360]){await p.setViewportSize({width,height:900});for(let i=0;i<12;i++){await p.selectOption('#lesson',String(i));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+width+' '+i);if(out&&[0,4,9,10].includes(i))await p.screenshot({path:path.join(out,`reasoning-${i}-${width}.png`),fullPage:true});}}
assert.deepEqual(errors,[]);await browser.close();console.log('REASONING_BROWSER_OK: 12 guided scenarios + 12 check items, actual digit/strike construction, moving timeline/pause, integer elimination, table construction, 3 viewport widths, assistance and report.');})().catch(e=>{console.error(e);process.exit(1);});
