'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'..'),express=require(path.join(ROOT,'board-server/node_modules/express'));
const {LearningStore}=require(path.join(ROOT,'board-server/learning-store'));
const {createLearningApi}=require(path.join(ROOT,'board-server/learning-api'));
const {createLearningRunsRouter}=require(path.join(ROOT,'board-server/learning-runs'));
const contracts=require(path.join(ROOT,'board-server/learning-contracts'));
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'learning-exam-browser-')),store=new LearningStore({filePath:path.join(dir,'learning.sqlite'),contracts});
const teacher=store.bootstrap({name:'Преподаватель',login:'teacher'}).account,invitation=store.createStudent(teacher,{name:'Ученик',login:'learner'}),student=store.activate(invitation.invitationToken,'scrypt1:'+('0'.repeat(32))+':'+('0'.repeat(64))).account;
const app=express();app.use(express.json({limit:'200kb'}));
const fixture=`<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/learning/style.css"><link rel="stylesheet" href="/learning/exam.css"><link rel="stylesheet" href="/learning/references.css"><script src="/ege-baza/path/data.js"></script><script src="/ege-baza/path/practice.js"></script><script src="/ege-baza/path/equation-practice.js"></script><script src="/ege-baza/path/practice-view.js"></script><script src="/learning/references.js"></script><script src="/learning/exam.js"></script><body><div id="notice" role="status"></div><main id="main"></main><script>
window.session=null;window.cleanup=null;
window.api=async(path,options={})=>{const r=await fetch('/api/learning'+path,{...options,credentials:'same-origin',headers:{'Content-Type':'application/json',...(session?{'x-csrf-token':session.csrfToken}:{}),...options.headers}});const body=await r.json();if(!r.ok)throw Object.assign(Error(body.error),{status:r.status,code:body.error});return body;};
window.mountRun=async()=>{session=await api('/session');cleanup?.destroy();cleanup=LearningExam.mount(document.getElementById('main'),{id:new URLSearchParams(location.hash.slice(1)).get('run'),account:session.account,api,navigate:hash=>location.hash=hash,notice:(text)=>document.getElementById('notice').textContent=text});};addEventListener('hashchange',mountRun);mountRun();
</script></body></html>`;
(async()=>{
 const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));}),origin='http://127.0.0.1:'+server.address().port;
 const learning=createLearningApi({store,publicOrigin:origin,secureCookies:false});app.use('/api/learning',learning.router,createLearningRunsRouter(learning).router);app.get('/fixture',(_q,res)=>res.type('html').send(fixture));app.use(express.static(ROOT));
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});
 const errors=[];async function client(){const session=store.createSession(student.id),context=await browser.newContext({viewport:{width:1280,height:1000},acceptDownloads:true});await context.addCookies([{name:'mathexam_learning_local',value:session.sessionToken,url:origin,httpOnly:true,sameSite:'Strict'}]);const page=await context.newPage();page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE_ERROR',e.message);});return{page,context};}
 try{
  const a=await client(),p=a.page;await p.goto(origin+'/fixture');await p.waitForFunction(()=>document.getElementById('main').textContent.includes('21 задание')||document.getElementById('main').textContent.includes('недоступна'));assert((await p.locator('#main').innerText()).includes('21 задание'),await p.locator('body').innerText());await p.locator('[data-start=exam]').click();await p.waitForSelector('#exam-answer');const runId=new URLSearchParams(p.url().split('#')[1]).get('run');assert(runId);
  const get=()=>p.evaluate(id=>api('/runs/'+id),runId);let run=await get();assert.equal(run.questions.length,21);assert.deepEqual(run.questions.map(q=>q.position),Array.from({length:21},(_,i)=>i+1));assert.equal(run.result,null);for(const q of run.questions){for(const key of ['answer','steps','solutions','params','model','rule'])assert(!Object.hasOwn(q.taskSpec.task,key),'private answer data '+key);}
  assert.equal(await p.locator('[data-reference-level]').count(),0,'no contextual help in exam');await p.getByRole('button',{name:'Справочный лист ФИПИ',exact:true}).click();assert.equal(await p.locator('dialog[open] img').count(),4);await p.getByRole('button',{name:'Закрыть',exact:true}).click();
  if(process.env.BROWSER_ARTIFACTS_DIR){fs.mkdirSync(process.env.BROWSER_ARTIFACTS_DIR,{recursive:true});await p.screenshot({path:path.join(process.env.BROWSER_ARTIFACTS_DIR,'learning-exam-question.png'),fullPage:true});}
  const pinned=run.questions.map(q=>q.taskSpec.task.q);
  // Lose an accepted response: retry must not duplicate the answer action.
  let lost=false,lostOp;await p.route('**/api/learning/runs/*/actions',async route=>{const body=route.request().postDataJSON();if(!lost&&body.type==='answer'){lost=true;lostOp=body.opId;await route.fetch();await route.abort('failed');}else await route.continue();});
  await p.locator('#exam-answer').fill('12,5');await p.waitForFunction(()=>document.querySelector('#exam-save').textContent.startsWith('Все ответы сохранены'),null,{timeout:20000});assert(lost);run=await get();assert.equal(run.version,1);assert.equal(run.questions[0].answer,'12,5');assert.equal(store.row('SELECT COUNT(*) AS n FROM learning_run_operations WHERE op_id=?',lostOp).n,1);await p.unroute('**/api/learning/runs/*/actions');
  await p.locator('#exam-next').click();await p.waitForFunction(()=>document.querySelector('[data-question="1"]').getAttribute('aria-current')==='step');await p.locator('#exam-answer').fill('7/3');await p.waitForFunction(()=>document.querySelector('#exam-save').textContent.startsWith('Все ответы сохранены'));await p.reload();await p.waitForSelector('#exam-answer');assert.equal(await p.locator('#exam-answer').inputValue(),'7/3');assert.deepEqual((await get()).questions.map(q=>q.taskSpec.task.q),pinned);
  // Leaving the route immediately after typing still drains the bound draft.
  await p.locator('#exam-answer').fill('route-away');await p.evaluate(()=>location.hash='exam');
  await p.waitForFunction(async id=>(await api('/runs/'+id)).questions[1].answer==='route-away',runId);
  await p.goto(origin+'/fixture#run='+runId);await p.waitForSelector('#exam-answer');assert.equal(await p.locator('#exam-answer').inputValue(),'route-away');await p.locator('#exam-answer').fill('7/3');await p.waitForFunction(()=>document.querySelector('#exam-save').textContent.startsWith('Все ответы сохранены'));
  // An old mount's delayed ACK must not erase a new mount's recovery queue.
  let releaseOld,releaseNew,oldCommitted=false,newHeld=false;
  const waitOld=new Promise(resolve=>releaseOld=resolve),waitNew=new Promise(resolve=>releaseNew=resolve);
  await p.route('**/api/learning/runs/*/actions',async route=>{const body=route.request().postDataJSON();if(body.type==='answer'&&body.payload.answer==='owner-old'&&!oldCommitted){const response=await route.fetch();oldCommitted=true;await waitOld;await route.fulfill({response});}else if(body.type==='answer'&&body.payload.answer==='owner-new'){newHeld=true;await waitNew;await route.continue();}else await route.continue();});
  await p.locator('#exam-answer').fill('owner-old');for(let i=0;i<100&&!oldCommitted;i++)await new Promise(r=>setTimeout(r,20));assert(oldCommitted);await p.evaluate(()=>location.hash='exam');await p.waitForSelector('[data-start=exam]');await p.evaluate(id=>location.hash='run='+id,runId);await p.waitForSelector('#exam-answer');await p.waitForFunction(()=>document.querySelector('#exam-save').textContent.startsWith('Все ответы сохранены'));
  await p.locator('#exam-answer').fill('owner-new');for(let i=0;i<100&&!newHeld;i++)await new Promise(r=>setTimeout(r,20));assert(newHeld);releaseOld();await p.waitForTimeout(100);
  assert(await p.evaluate(id=>{const saved=JSON.parse(sessionStorage.getItem('mathexam.learning.exam.'+session.account.id+'.'+id));return saved.queue.some(op=>op.payload.answer==='owner-new');},runId),'old ACK preserves newer mount recovery copy');releaseNew();await p.waitForFunction(()=>document.querySelector('#exam-save').textContent.startsWith('Все ответы сохранены'));await p.unroute('**/api/learning/runs/*/actions');await p.locator('#exam-answer').fill('7/3');await p.waitForFunction(()=>document.querySelector('#exam-save').textContent.startsWith('Все ответы сохранены'));
  const b=await client();await b.page.goto(origin+'/fixture#run='+runId);await b.page.waitForSelector('#exam-answer');assert.equal(await b.page.locator('#exam-answer').inputValue(),'7/3','same work on second device');
  // Old-device writes are never rebased over newer work.
  let release,held=false;const hold=new Promise(resolve=>release=resolve);await p.route('**/api/learning/runs/*/actions',async route=>{const body=route.request().postDataJSON();if(body.type==='answer'&&body.payload.answer==='old-device'){held=true;await hold;}await route.continue();});await p.locator('#exam-answer').fill('old-device');for(let i=0;i<30&&!held;i++)await new Promise(r=>setTimeout(r,30));assert(held);await b.page.locator('#exam-answer').fill('new-device');await b.page.waitForFunction(()=>document.querySelector('#exam-save').textContent.startsWith('Все ответы сохранены'));release();await p.waitForSelector('#exam-resume-server');assert.equal(await p.locator('#exam-answer').inputValue(),'new-device');assert.equal((await get()).questions[1].answer,'new-device');const downloadEvent=p.waitForEvent('download');await p.locator('#exam-download').click();const file=await(await downloadEvent).path(),backup=JSON.parse(fs.readFileSync(file,'utf8'));assert(backup.rejected.some(op=>op.payload.answer==='old-device'));await p.locator('#exam-resume-server').click();await p.unroute('**/api/learning/runs/*/actions');
  // Finish with one exact answer and twenty omissions; empty answers stay visible.
  await b.context.close();await p.locator('[data-question="0"]').click();await p.waitForFunction(()=>document.querySelector('#exam-save').textContent.startsWith('Все ответы сохранены'));run=await get();const full=JSON.parse(store.row('SELECT task_json FROM attempts WHERE id=?',run.questions[0].attemptId).task_json).task;await p.locator('#exam-answer').fill(String(full.answer));await p.waitForFunction(()=>document.querySelector('#exam-save').textContent.startsWith('Все ответы сохранены'));await p.locator('[data-question="1"]').click();await p.locator('#exam-answer').fill('');await p.waitForFunction(()=>document.querySelector('#exam-save').textContent.startsWith('Все ответы сохранены'));
  await p.locator('#exam-finish').click();await p.waitForFunction(()=>!document.querySelector('[data-finish-confirm]').disabled);await p.locator('[data-finish-confirm]').click();await p.waitForSelector('#exam-results');run=await get();assert.equal(run.result.correct,1);assert.equal(run.result.answered,1);assert.equal(run.result.total,21);assert.equal(await p.locator('.exam-result').count(),21);assert.equal(await p.locator('#exam-answer').count(),0);await p.reload();await p.waitForSelector('#exam-results');assert.equal((await get()).result.correct,1);
  await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile no page overflow');await p.locator('.exam-result').first().locator('summary').click();assert((await p.locator('.exam-result').first().innerText()).includes('Правильный ответ'));const oldQuestion=run.questions[0].taskSpec.task.q;await p.locator('[data-practice="0"]').click();await p.waitForURL('**#attempt=*');const attemptId=new URLSearchParams(p.url().split('#')[1]).get('attempt');const attempt=store.row('SELECT task_json FROM attempts WHERE id=?',attemptId);assert.notEqual(JSON.parse(attempt.task_json).task.q,oldQuestion,'fresh remediation condition');
  // Report semantics never turn cancelled or assisted work into mastery.
  await p.goto(origin+'/fixture#run='+runId);await p.waitForSelector('#exam-results');
  await p.evaluate(async id=>{const value=await api('/runs/'+id);value.result.cancelled=true;value.result.byPosition=[];cleanup.destroy();cleanup=LearningExam.mount(document.getElementById('main'),{id,account:session.account,api:async()=>value,navigate:()=>{},notice:()=>{}});},runId);
  await p.waitForSelector('#exam-results h2');assert.match(await p.locator('#exam-results').innerText(),/Прогресс начат заново/);assert.doesNotMatch(await p.locator('#exam-results').innerText(),/Все задания этого варианта решены/);assert.equal(await p.locator('.exam-result-number').count(),0);
  await p.evaluate(async id=>{const value=await api('/runs/'+id);value.result.assisted=true;value.result.byPosition[0].outcome='hinted';cleanup.destroy();cleanup=LearningExam.mount(document.getElementById('main'),{id,account:session.account,api:async()=>value,navigate:()=>{},notice:()=>{}});},runId);
  await p.waitForSelector('.exam-result');assert.match(await p.locator('#exam-results').innerText(),/получена помощь/);assert.match(await p.locator('.exam-result').first().innerText(),/Решено с подсказкой/);
  assert.deepEqual(errors,[]);console.log('LEARNING_EXAM_BROWSER_OK: 21 pinned positions, no prefinish keys/hints, full reference, autosave/reload/two devices, lost ACK idempotency, stale-device quarantine/export, route-away draft drain, old-mount ACK race, cancelled/assisted report semantics, atomic explicit finish, 21-result report, fresh analogue, mobile.');
 }finally{await browser.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));store.close();fs.rmSync(dir,{recursive:true,force:true});}
})().catch(error=>{console.error(error.stack||error);process.exitCode=1;});
