'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),D=require('../school/m9-exercises/data');
const root=path.resolve(__dirname,'..'),server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(!f.startsWith(root+path.sep))return res.writeHead(403).end();try{if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.json')?'application/json':'text/html');res.end(fs.readFileSync(f));}catch(_){res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,base=origin+'/school/m9-exercises/index.html';const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,headless:true,args:['--no-sandbox']});try{
const page=await browser.newPage({viewport:{width:1280,height:900}});page.setDefaultTimeout(10000);let errors=[];page.on('pageerror',e=>errors.push(e.message));
async function go(n,p=0,mode='learn'){await page.goto(base+'#'+n+'/'+p);await page.locator('h1').waitFor();if(await page.locator('#start-'+mode).count())await page.locator('#start-'+mode).click();}
async function answer(s){const r=s.rule;if(r.type==='angle'){await page.locator('.angle-model').scrollIntoViewIfNeeded();const a=JSON.parse(s.example),xy=await page.locator('.angle-model').evaluate((svg,a)=>{const p=svg.createSVGPoint();p.x=300+210*Math.cos(a*Math.PI/180);p.y=290-210*Math.sin(a*Math.PI/180);const q=p.matrixTransform(svg.getScreenCTM());return {x:q.x,y:q.y};},a.angle);await page.mouse.click(xy.x,xy.y);await page.locator('#angle-reading').fill(a.reading);}else if(r.type==='choice'){for(const v of s.example)await page.locator('.choices input').filter({visible:true}).evaluateAll((els,value)=>{const e=els.find(e=>e.value===value);e.click();},v);}else if(r.type==='order'){for(let target=0;target<s.example.length;target++){for(;;){const order=await page.locator('.order li').evaluateAll(a=>a.map(e=>e.dataset.token));const index=order.indexOf(s.example[target]);if(index===target)break;await page.locator('[data-move="'+index+':-1"]').click();}}}else if(r.type==='interval'){const a=JSON.parse(s.example);await page.locator('#low').selectOption(a.low);await page.locator('#high').selectOption(a.high);await page.locator('#left').setChecked(a.left);await page.locator('#right').setChecked(a.right);}else await page.locator('#answer').fill(s.example);
await page.locator('#answer-form button[type=submit]').click();assert.equal(await page.locator('.feedback.good').count(),1,s.prompt+' '+await page.locator('#feedback').innerText());await page.locator('#next').click();}
await page.goto(base);assert.equal(await page.locator('.task-card').count(),53);await page.locator('#number').fill('891');await page.locator('#find button').click();assert.match(await page.locator('#find-result').innerText(),/ещё не готов/);
// A fresh, direct independent attempt is possible without viewing worked hints.
await go(21,0,'check');for(const s of D.byNumber[21].parts[0].steps.filter(s=>s.final))await answer(s);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(M9ExerciseState.KEY)).records['21:0'].independent),true);
let parts=0;for(const e of D.exercises)for(let p=0;p<e.parts.length;p++){await go(e.number,p);if(await page.locator('#learn').count())await page.locator('#learn').click();for(const s of e.parts[p].steps)await answer(s);parts++;if(parts%36===0)console.log('Guided parts',parts);}
assert.equal(await page.evaluate(()=>Object.values(JSON.parse(localStorage.getItem(M9ExerciseState.KEY)).records).filter(r=>r.learn).length),177);
// A number does not count completed merely from opening it. Hints and known tasks do not create fresh mastery.
await go(1,0);await page.locator('#check-mode').click();await page.locator('#hint').click();await page.locator('#hint').click();await page.locator('#answer').fill(D.byNumber[1].parts[0].steps.at(-1).example);await page.locator('#answer-form button[type=submit]').click();await page.locator('#next').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(M9ExerciseState.KEY)).records['1:0'].independent),false);
await go(20,0);await page.locator('#learn').click();await page.locator('#answer').fill('мой черновик');await page.locator('#basis').click();await page.locator('a').filter({hasText:'Вернуться к задаче и сохранённому шагу'}).click();assert.equal(await page.locator('#answer').inputValue(),'мой черновик');await page.reload();assert.equal(await page.locator('#answer').inputValue(),'мой черновик');
await go(14,0);await page.locator('#learn').click();await answer(D.byNumber[14].parts[0].steps[0]);await page.locator('.line').scrollIntoViewIfNeeded();const xy=await page.locator('.line').evaluate(svg=>{const p=svg.createSVGPoint();p.x=35+(2.65+4)/9*530;p.y=68;const a=p.matrixTransform(svg.getScreenCTM());return {x:a.x,y:a.y};});await page.mouse.click(xy.x,xy.y);assert.equal(await page.locator('#answer').inputValue(),'2,65');await page.locator('#answer-form button[type=submit]').click();assert.equal(await page.locator('.feedback.good').count(),1);
await page.evaluate(()=>{localStorage.setItem('mathexam.workshop.v1','legacy-sentinel');localStorage.setItem('mathexam.trainerBoard.v1','board-sentinel');});
await page.goto(base+'#progress');const wait=page.waitForEvent('download');await page.locator('#export').click();const dl=await wait;const data=JSON.parse(fs.readFileSync(await dl.path(),'utf8'));assert(data.records['21:0'].independent);assert.equal(await page.evaluate(()=>localStorage.getItem('mathexam.workshop.v1')),'legacy-sentinel');
// Responsive, zoom and keyboard. No WebGL or animations are required.
fs.mkdirSync('/tmp/m9-exercise-shots',{recursive:true});for(const n of [0,2,10,14,19,21,45]){if(n===0)await page.goto(base+'#catalog');else{await go(n);await page.locator('#learn').click();if(n===14||n===19)await answer(D.byNumber[n].parts[0].steps[0]);}for(const width of [360,768,1280]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+n+' '+width);if(width===360)await page.screenshot({path:'/tmp/m9-exercise-shots/'+n+'.png',fullPage:true});}}
await page.setViewportSize({width:360,height:900});await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>document.body.style.zoom='2');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.evaluate(()=>document.body.style.zoom='1');
await go(45);await page.locator('#learn').click();await page.locator('[data-rotate="-5"]').focus();await page.keyboard.press('Enter');await page.locator('#angle-reading').fill('85');await page.locator('#answer-form button[type=submit]').click();assert.equal(await page.locator('.feedback.good').count(),1);
await go(19);await page.locator('#learn').click();await answer(D.byNumber[19].parts[0].steps[0]);await page.locator('#low').focus();await page.keyboard.press('Home');await page.keyboard.press('Tab');assert.equal(await page.locator('#low').inputValue(),'-inf');
await page.route('**/api/trainer-registry',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({schemaVersion:1,digest:'a'.repeat(64),trainers:[]})}));await page.goto(origin+'/trainers/trainer-board.html?trainer='+encodeURIComponent('/school/m9-exercises/index.html#20/0'));await page.frameLocator('#trainerFrame').locator('h1').waitFor();assert.match(await page.frameLocator('#trainerFrame').locator('h1').innerText(),/область корня/);assert.equal(await page.frameLocator('#trainerFrame').locator('a[href*="trainer-board.html?trainer="]').count(),0);
const corrupt=await browser.newPage();await corrupt.goto(base);await corrupt.evaluate(()=>localStorage.setItem(M9ExerciseState.KEY,'{broken'));await corrupt.reload();assert.match(await corrupt.locator('#notice').innerText(),/не перезаписаны/);await corrupt.goto(base+'#3/0');await corrupt.locator('#start-learn').click();await corrupt.locator('#hint').click();assert.equal(await corrupt.evaluate(()=>localStorage.getItem(M9ExerciseState.KEY)),'{broken');await corrupt.close();
assert.deepEqual(errors,[]);console.log('PASS browser: 177 full guided parts; independent first attempt; known/hinted task; draft reload and course return; pointer and keyboard; mobile/tablet/desktop/zoom; data export, old-key preservation, corruption; board iframe.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
