'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const lessons=['preparation','chapter4','chapter5','chapter6a','chapter6b'].flatMap(n=>require('../ege-profil/circle/'+n));const tasks=lessons.flatMap(l=>l.tasks),check=require('../ege-profil/circle/checks'),state=require('../ege-profil/circle/state');
assert.equal(lessons.length,33);assert.equal(new Set(lessons.map(l=>l.id)).size,lessons.length);assert.equal(tasks.length,295);assert.equal(new Set(tasks.map(t=>t.id)).size,tasks.length);
const numbers=new Set(tasks.filter(t=>/^\d/.test(t.book)).map(t=>t.book));for(const[ch,count]of [[4,20],[5,14],[6,41]])for(let n=1;n<=count;n++)assert(numbers.has(`${ch}.${n}`));assert.equal(numbers.size,75);
let steps=0,fields=0;for(const l of lessons){assert([0,4,5,6].includes(l.chapter),l.id);assert(l.intro.length>250);for(const t of l.tasks){assert(t.steps.length>=2,t.id);steps+=t.steps.length;for(const q of [...t.steps,t]){assert(q.fields.length,t.id);assert.equal(new Set(q.fields.map(f=>f.id)).size,q.fields.length);for(const f of q.fields){fields++;assert(['number','point','choice','multi','order'].includes(f.kind),t.id);if(['number','point'].includes(f.kind)){assert(Number.isFinite(f.expected),t.id);assert(check.check(f,String(f.expected)),t.id);assert(!check.check(f,''));assert(!check.check(f,'NaN'));}else{assert(new Set(f.options.map(o=>o.value)).size===f.options.length,t.id);const a=Array.isArray(f.expected)?f.expected:[f.expected];assert(a.every(x=>f.options.some(o=>o.value===x)),t.id);assert(check.check(f,f.expected),t.id);assert(!check.check(f,'unknown'));}if(f.kind==='point'){assert(check.check(f,f.expected+12*Math.PI));assert(!check.check(f,f.expected+0.1));}}}}}
assert(check.check({kind:'number',expected:Math.sqrt(3)/2},'√3/2'));assert(check.check({kind:'number',expected:2*Math.PI/3},'2*pi/3'));assert(Number.isNaN(check.number('alert(1)')));assert(Number.isNaN(check.number('1/0')));
assert(check.check({kind:'multi',expected:[]},[]));assert(!check.check({kind:'multi',expected:['a']},['a','a']));assert(!check.check({kind:'order',expected:['a','b']},['b','a']));
const mem=new Map([['legacy.student','keep']]);const storage={getItem:k=>mem.get(k)||null,setItem:(k,v)=>mem.set(k,v)};let s=state.create(lessons,storage),id=tasks[0].id;
let a=s.start(id,'independent');s.finish(a);assert(s.data.records[id].independent);a=s.start(id,'independent',true);assert(a.familiar);s.finish(a);
for(const [index,flag]of [[1,'wrong'],[2,'assisted']]){a=s.start(tasks[index].id,'independent');a[flag]=true;s.finish(a);assert(!s.data.records[a.taskId].independent);}
a=s.start(tasks[3].id,'guided');a.draft={answer:'sqrt(2)/2',order:['a','c']};a.step=1;s.save();s=state.create(lessons,storage);assert.deepEqual(s.data.sessions[tasks[3].id+':guided'].draft,{answer:'sqrt(2)/2',order:['a','c']});s.finish(s.data.sessions[tasks[3].id+':guided']);a=s.start(tasks[3].id,'independent');assert(a.familiar);
const tab=state.create(lessons,storage);a=tab.start(tasks[4].id,'independent');tab.finish(a);s.save();assert(JSON.parse(mem.get(state.KEY)).records[tasks[4].id].independent);assert.equal(mem.get('legacy.student'),'keep');
const tabA=state.create(lessons,storage),tabB=state.create(lessons,storage);const draftA=tabA.start(tasks[5].id,'guided');draftA.draft={answer:'3/7'};tabA.save();const draftB=tabB.start(tasks[6].id,'guided');draftB.draft={answer:'pi/3'};tabB.save();tabA.save();const stored=JSON.parse(mem.get(state.KEY));assert.equal(stored.sessions[tasks[5].id+':guided'].draft.answer,'3/7');assert.equal(stored.sessions[tasks[6].id+':guided'].draft.answer,'pi/3');
const bad='{broken';mem.set(state.KEY,bad);s.save();assert.equal(mem.get(state.KEY),bad);assert(s.warning);assert.equal(s.original,bad);const fresh=state.create(lessons,storage);fresh.start(id,'guided');assert.equal(mem.get(state.KEY),bad);assert(fresh.warning);
const future=JSON.stringify({version:7,seen:{},records:{},sessions:{}});mem.set(state.KEY,future);const f=state.create(lessons,storage);f.start(id,'guided');assert.equal(mem.get(state.KEY),future);assert(f.warning);assert.equal(f.export().storage,'local-browser');
for(const file of ['index.html','app.js','style.css','state.js','checks.js','models.js'])assert(fs.statSync(path.join(__dirname,'../ege-profil/circle',file)).size>100);
console.log(JSON.stringify({gate:'MORD_CIRCLE_STRUCTURE_STATE_OK',lessons:lessons.length,bookNumbers:numbers.size,bookParts:tasks.length-6,preparation:6,tasks:tasks.length,guidedSteps:steps,fields,oldData:true,corruptionPreserved:true,otherTabSuccesses:true}));
