'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const lessons=['preparation','chapter4','chapter5','chapter6a','chapter6b'].flatMap(n=>require('../ege-profil/circle/'+n));
const root=path.resolve(__dirname,'..'),KEY='mathexam.mordkovichCircle.v1';
const server=http.createServer((req,res)=>{try{const p0=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(!p0.startsWith(root+path.sep))return res.writeHead(403).end();const p=fs.statSync(p0).isDirectory()?path.join(p0,'index.html'):p0;res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.json')?'application/json':'text/html');res.end(fs.readFileSync(p));}catch(_){res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,base=origin+'/ege-profil/circle/index.html';const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,headless:true,args:['--no-sandbox']});let errors=[],tasks=0,questions=0;
try{const context=await browser.newContext();
async function fill(page,fields){for(const f of fields){if(f.kind==='number')await page.locator('#field-'+f.id).fill(String(f.expected));else if(f.kind==='point'){await page.locator('[data-angle-input]').fill(String(f.expected));await page.locator('[data-apply-angle]').click();await page.locator('[data-capture="'+f.id+'"]').click();}else if(f.kind==='choice')await page.locator(`input[name="${f.id}"][value="${f.expected}"]`).check();else if(f.kind==='multi'){if(!f.expected.length)await page.locator(`input[name="${f.id}"][value="__none"]`).check();else for(const value of f.expected)await page.locator(`input[name="${f.id}"][value="${value}"]`).check();}else if(f.kind==='order')for(const value of f.expected)await page.locator(`[data-add="${f.id}"][data-value="${value}"]`).click();}
 await page.locator('#check').click();assert.equal(await page.locator('#feedback.good').count(),1,page.url()+' :: '+await page.locator('#feedback').innerText());await page.locator('#next').click();questions++;}
// Three real browser pages exercise separate topics concurrently, sharing the same progress store.
const smokeOnly=process.argv.includes("--smoke-only");if(!smokeOnly){
await Promise.all([0,1,2].map(async worker=>{const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));await page.goto(base);for(let li=worker;li<lessons.length;li+=3){const l=lessons[li];for(const t of l.tasks){await page.goto(base+'#task/'+t.id+'/guided');for(const q of [...t.steps,t])await fill(page,q.fields);assert.equal(await page.locator('.result-panel').count(),1,t.id+' guided');await page.goto(base+'#task/'+t.id+'/independent');await fill(page,t.fields);assert.equal(await page.locator('.result-panel').count(),1,t.id+' independent');tasks++;}console.log('Completed',l.id,l.tasks.length);}}));
assert.equal(tasks,295);
}
const ctx=await browser.newContext(),page=await ctx.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
await page.goto(base);assert.equal(await page.locator('.lesson-card').count(),33);await page.evaluate(()=>localStorage.setItem('mathExamCourseProgress.v1','legacy-preserved'));
await page.locator('#book-number').fill('4.19');await page.locator('#jump-form button').click();await page.locator('.task-card').first().waitFor();assert.equal(await page.locator('.task-card').count(),4);
// Wrong answer + assistance + remediation + draft reload; these never become fresh success.
await page.goto(base+'#task/prep-radius/independent');await page.locator('#field-diameter').fill('3');await page.locator('#check').click();assert.equal(await page.locator('#feedback.bad').count(),1);await page.locator('#hint').click();await page.locator('#field-diameter').fill('2');await page.getByRole('link',{name:'К объяснению и обратно',exact:true}).click();await page.getByRole('link',{name:'Вернуться на сохранённый шаг'}).click();assert.equal(await page.locator('#field-diameter').inputValue(),'2');await page.reload();assert.equal(await page.locator('#field-diameter').inputValue(),'2');await fill(page,lessons[0].tasks[0].fields);assert.equal(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)).records['prep-radius'].independent,KEY),false);
await page.goto(base+'#task/prep-quarter/independent');await fill(page,lessons[0].tasks[1].fields);assert.equal(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)).records['prep-quarter'].independent,KEY),true);await page.reload();assert.equal(await page.locator('.result-panel').count(),1);await page.locator('#repeat').click();assert.match(await page.locator('.practice-head').innerText(),/знакомая/i);
// All six models, narrow/tablet/desktop, keyboard, finite input and no automatic animation.
fs.mkdirSync('/tmp/mord-circle-shots',{recursive:true});for(const l of lessons){await page.goto(base+'#lesson/'+l.id);await page.locator('#lab [data-circle-svg]').waitFor();for(const width of [360,768,1280]){await page.setViewportSize({width,height:900});if(!(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1))){console.log(await page.locator('main *').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,14).map(e=>({tag:e.tagName,class:e.className,width:e.getBoundingClientRect().width,text:e.textContent.slice(0,90)}))));await page.screenshot({path:'/tmp/mord-circle-overflow.png',fullPage:true});throw Error('overflow '+l.id+' '+width);}}await page.locator('[data-circle-svg]').focus();const old=await page.locator('[data-angle-input]').inputValue();await page.keyboard.press('ArrowRight');assert.notEqual(await page.locator('[data-angle-input]').inputValue(),old);}
await page.goto(base+'#lesson/before-radians');await page.setViewportSize({width:360,height:900});await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>document.body.style.zoom='2');if(!(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1))){console.log(await page.locator('body *').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,20).map(e=>({tag:e.tagName,class:e.className,width:e.getBoundingClientRect().width,text:e.textContent.slice(0,70)}))));throw Error('200% zoom overflow');}await page.evaluate(()=>document.body.style.zoom='1');await page.screenshot({path:'/tmp/mord-circle-shots/mobile.png',fullPage:true});
await page.setViewportSize({width:1280,height:900});await page.goto(base+'#home');await page.screenshot({path:'/tmp/mord-circle-shots/home.png',fullPage:true});await page.goto(base+'#lesson/m5-abscissa-inequalities');await page.screenshot({path:'/tmp/mord-circle-shots/inequalities.png',fullPage:true});
await page.goto(base+'#progress');const download=page.waitForEvent('download');await page.locator('#export').click();const exported=JSON.parse(fs.readFileSync(await(await download).path(),'utf8'));assert.equal(exported.storage,'local-browser');assert(exported.records['prep-quarter'].independent);assert(!exported.records['prep-radius'].independent);
await page.route('**/api/trainer-registry',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({schemaVersion:1,digest:'a'.repeat(64),trainers:[]})}));await page.goto(origin+'/trainers/trainer-board.html?trainer='+encodeURIComponent('/ege-profil/circle/index.html#lesson/before-circle'));await page.frameLocator('#trainerFrame').locator('h1').waitFor();assert.match(await page.frameLocator('#trainerFrame').locator('h1').innerText(),/единичной/);assert.equal(await page.frameLocator('#trainerFrame').locator('.board-link').count(),0);
await page.goto(base);assert.equal(await page.evaluate(()=>localStorage.getItem('mathExamCourseProgress.v1')),'legacy-preserved');await page.evaluate(k=>localStorage.setItem(k,'{broken'),KEY);await page.reload();assert(await page.locator('#storage-warning').isVisible());await page.goto(base+'#task/prep-radius/guided');assert.equal(await page.evaluate(k=>localStorage.getItem(k),KEY),'{broken');
assert.deepEqual(errors,[]);console.log(JSON.stringify({gate:smokeOnly?'MORD_CIRCLE_SMOKE_OK':'MORD_CIRCLE_BROWSER_OK',tasks,bothModes:true,questions,responsive:[360,768,1280],keyboard:true,zoom:true,reducedMotion:true,board:true,corruptionPreserved:true,errors}));await ctx.close();await context.close();
}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
