'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const D=[...require('../ege-profil/start/geometry-data'),...require('../ege-profil/start/algebra-data')],root=path.resolve(__dirname,'..'),KEY='mathexam.profileStart2027.v1';
const server=http.createServer((req,res)=>{let p;try{p=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(!p.startsWith(root+path.sep))return res.writeHead(403).end();if(fs.statSync(p).isDirectory())p=path.join(p,'index.html');res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.json')?'application/json':'text/html');res.end(fs.readFileSync(p));}catch(_){res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,base=origin+'/ege-profil/start/index.html';const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,headless:true,args:['--no-sandbox']});try{
const context=await browser.newContext(),page=await context.newPage();page.setDefaultTimeout(12000);let errors=[];page.on('pageerror',e=>errors.push(e.message));
async function open(l,mode){await page.goto(base+'#lesson/'+l.id);await page.locator('#'+mode).click();await page.locator('#answer-form').waitFor();}
async function answer(q){if(q.choices){const inputs=page.locator('.choices input');const vals=await inputs.evaluateAll(es=>es.map(e=>e.value));const index=vals.indexOf(String(q.answer));assert(index>=0,'choice '+q.answer);await inputs.nth(index).check();}else await page.locator('#answer').fill(String(q.answer));await page.locator('#submit-answer').click();assert.equal(await page.locator('.feedback.good').count(),1,await page.locator('#feedback').innerText());await page.locator('#next').click();}
await page.goto(base);assert.equal(await page.locator('.lesson-card').count(),12 + require('../ege-profil/start/stereo-data').length);assert.equal(await page.locator('a[href="../trigonometry/index.html"]').count(),1);await page.evaluate(()=>localStorage.setItem('mathExamCourseProgress.v1','legacy-preserved'));
let tasks=0,steps=0;for(const l of D){for(const mode of ['guided','independent']){await open(l,mode);for(let index=0;index<3;index++){
 const taskId=await page.evaluate(({key,id,mode})=>JSON.parse(localStorage.getItem(key)).sessions[id+':'+mode].taskId,{key:KEY,id:l.id,mode});const t=l.tasks.find(t=>t.id===taskId);assert(t);for(const q of mode==='guided'?t.steps:[{answer:t.answer,choices:t.choices}]){await answer(q);steps++;}assert.equal(await page.locator('.result-panel').count(),1);tasks++;if(index<2)await page.locator('#another').click();
 }}console.log('Completed',l.id);}
assert.equal(tasks,108);assert.equal(await page.evaluate(key=>Object.values(JSON.parse(localStorage.getItem(key)).records).filter(r=>r.independent.length===3).length,KEY),18);
// Repetition, errors, help and recovery are tested in a fresh learner context.
const fresh=await browser.newContext();const learner=await fresh.newPage();learner.on('pageerror',e=>errors.push(e.message));const l=D[0];
await learner.goto(base+'#lesson/'+l.id);await learner.locator('#independent').click();let t=l.tasks[3];await learner.locator('#answer').fill(String(t.answer+17));await learner.locator('#submit-answer').click();assert.equal(await learner.locator('.feedback.bad').count(),1);await learner.locator('#hint').click();await learner.locator('#answer').fill('3/5');await learner.locator('.support-details summary').click();await learner.locator('#repair').click();await learner.getByRole('link',{name:'Вернуться на сохранённый шаг'}).click();assert.equal(await learner.locator('#answer').inputValue(),'3/5');await learner.reload();assert.equal(await learner.locator('#answer').inputValue(),'3/5');await learner.locator('#answer').fill(String(t.answer));await learner.locator('#submit-answer').click();await learner.locator('#next').click();assert.equal(await learner.evaluate(({key,id})=>JSON.parse(localStorage.getItem(key)).records[id].independent.length,{key:KEY,id:l.id}),0);await learner.reload();assert.equal(await learner.locator('.result-panel').count(),1,'completed session survives reload');
await learner.goto(base+'#progress');const download=learner.waitForEvent('download');await learner.locator('#export').click();const exported=JSON.parse(fs.readFileSync(await(await download).path(),'utf8'));assert.equal(exported.storage,'local-browser');assert.equal(exported.records[l.id].independent.length,0);
// All labs must mount, accept keyboard control, reflow, and survive reduced motion.
fs.mkdirSync('/tmp/profile-start-shots',{recursive:true});for(const l of D){await page.goto(base+'#lesson/'+l.id);await page.locator('#explore-lab summary').click();await page.locator('#lab svg').first().waitFor();for(const width of [360,768,1280]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+l.id+' '+width);}const control=page.locator('#lab input[type=range]').first();if(await control.count()){await control.focus();const before=await control.inputValue();await page.keyboard.press('ArrowRight');assert.notEqual(await control.inputValue(),before,'keyboard lab '+l.id);}}
await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:360,height:900});await page.evaluate(()=>document.body.style.zoom='2');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'zoom reflow');await page.evaluate(()=>document.body.style.zoom='1');await page.screenshot({path:'/tmp/profile-start-shots/mobile.png',fullPage:true});
await page.setViewportSize({width:1280,height:900});await page.goto(base+'#home');await page.screenshot({path:'/tmp/profile-start-shots/home.png',fullPage:true});
await page.route('**/api/trainer-registry',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({schemaVersion:1,digest:'a'.repeat(64),trainers:[]})}));await page.goto(origin+'/trainers/trainer-board.html?trainer='+encodeURIComponent('/ege-profil/start/index.html#lesson/'+l.id));await page.frameLocator('#trainerFrame').locator('h1').waitFor();assert.equal(await page.frameLocator('#trainerFrame').locator('h1').innerText(),l.title);assert.equal(await page.frameLocator('#trainerFrame').locator('.board-link').count(),0);
await page.goto(base);assert.equal(await page.evaluate(()=>localStorage.getItem('mathExamCourseProgress.v1')),'legacy-preserved');await page.evaluate(key=>localStorage.setItem(key,'{broken'),KEY);await page.reload();assert(await page.locator('#storage-warning').isVisible());await page.goto(base+'#lesson/'+l.id);await page.locator('#guided').click();assert.equal(await page.evaluate(key=>localStorage.getItem(key),KEY),'{broken');
assert.deepEqual(errors,[]);console.log(JSON.stringify({gate:'PROFILE_START_BROWSER_OK',tasks,checkedAnswers:steps,responsive:[360,768,1280],keyboard:true,reducedMotion:true,zoom:true,board:true,corruptionPreserved:true,errors}));
await fresh.close();await context.close();
}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
