'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const D=require('../ege-profil/learning/data'),R=require('../ege-profil/learning/route');
const start=[...require('../ege-profil/start/geometry-data'),...require('../ege-profil/start/algebra-data')],circle=['preparation','chapter4','chapter5','chapter6a','chapter6b'].flatMap(n=>require('../ege-profil/circle/'+n));
const root=path.resolve(__dirname,'..'),pk='mathexam.profileStart2027.v1',mk='mathexam.mordkovichCircle.v1';
const server=http.createServer((req,res)=>{try{let p=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(!p.startsWith(root+path.sep))return res.writeHead(403).end();if(fs.statSync(p).isDirectory())p=path.join(p,'index.html');res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.json')?'application/json':'text/html');res.end(fs.readFileSync(p));}catch(_){res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,headless:true,args:['--no-sandbox']});let completed=0;const errors=[];
try{const page=await browser.newPage({viewport:{width:1280,height:900}});page.on('pageerror',e=>errors.push(e.message));
await page.goto(origin+D.routes.lesson.path);assert.equal(await page.locator('.route-card').count(),6);assert.equal(await page.locator('.teaching-prompts li').count(),18);assert.equal(await page.locator('#homework-link').inputValue(),origin+D.routes.homework.path);
await page.locator('.route-card').first().getByRole('link',{name:'Обсудить и исследовать'}).click();await page.locator('#route-context').waitFor();assert.match(await page.locator('#route-context').innerText(),/Урок с репетитором/);await page.locator('#route-context summary').click();assert.match(await page.locator('#route-context').innerText(),/гипотенуза/);
async function startAnswer(q){if(q.choices)await page.locator('input[name=answer]').filter({visible:true}).evaluateAll((es,answer)=>{const el=es.find(e=>e.value===String(answer));if(!el)throw Error();el.click();},q.answer);else await page.locator('#answer').fill(String(q.answer));await page.locator('#submit-answer').click();assert.equal(await page.locator('#feedback.good').count(),1);await page.locator('#next').click();}
async function circleAnswer(q){for(const f of q.fields){if(f.kind==='number')await page.locator('#field-'+f.id).fill(String(f.expected));else if(f.kind==='point'){await page.locator('[data-angle-input]').fill(String(f.expected));await page.locator('[data-apply-angle]').click();await page.locator('[data-capture="'+f.id+'"]').click();}else if(f.kind==='choice')await page.locator('input[name="'+f.id+'"][value="'+f.expected+'"]').check();else throw Error('Unexpected assigned field '+f.kind);}await page.locator('#check').click();assert.equal(await page.locator('#feedback.good').count(),1,await page.locator('#feedback').innerText());await page.locator('#next').click();}
// Tutor completes a guided example. This alone must not mark homework complete.
await page.locator('#route-context').getByRole('link',{name:'По шагам',exact:true}).click();await page.locator('#answer-form').waitFor();let l=start.find(l=>l.id==='geo-right');for(const q of l.tasks[0].steps)await startAnswer(q);await page.locator('.result-panel').waitFor();
await page.goto(origin+D.routes.homework.path+'#report');assert.match(await page.locator('.route-card').first().innerText(),/не завершена/);
for(const id of R.ids(D.routes.homework)){
 const d=D.lessons[id];await page.goto(origin+R.link('homework',id,'independent'));
 if(d.engine==='start'){await page.locator('#answer-form').waitFor();const taskId=await page.evaluate(({key,id})=>JSON.parse(localStorage.getItem(key)).sessions[id+':independent'].taskId,{key:pk,id});const t=start.find(l=>l.id===id).tasks.find(t=>t.id===taskId);await startAnswer(t);}
 else{await page.locator('#answer-form').waitFor();const t=circle.find(l=>l.id===id).tasks.find(t=>t.id===d.homeIndependent);await circleAnswer(t);}
 await page.locator('.result-panel').waitFor();assert.match(await page.locator('#route-context').innerText(),/Домашка/);completed++;
}
await page.goto(origin+D.routes.homework.path+'#report');assert.equal(await page.getByText('Есть новый самостоятельный успех',{exact:true}).count(),6);const download=page.waitForEvent('download');await page.locator('#export-text').click();const report=fs.readFileSync(await(await download).path(),'utf8');assert(report.includes('Скалярное произведение'));assert(report.includes('Число превращается в путь'));
await page.goto(origin+D.routes.trigonometry.path);assert.equal(await page.locator('.route-card').count(),39);await page.goto(origin+D.routes.trigonometry.path+'#exam');assert.match(await page.locator('#exam').innerText(),/двойного угла/);
// Pointer, slider, keyboard and exact typed angles; free drag remains explicit.
await page.goto(origin+R.link('homework','before-radians'));await page.locator('[data-angle-snap]').waitFor();assert.equal(await page.locator('[data-angle-snap]').inputValue(),'12');
const svg=page.locator('[data-circle-svg]');await svg.scrollIntoViewIfNeeded();const b=await svg.boundingBox();const xy=a=>({x:b.x+(230+130*Math.cos(a))/480*b.width,y:b.y+(190-130*Math.sin(a))/385*b.height});
let p=xy(.27);await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.up();assert.equal(await page.locator('[data-angle-input]').inputValue(),'π/12');
await svg.focus();await page.keyboard.press('Home');await page.keyboard.press('ArrowLeft');assert.equal(await page.locator('[data-angle-input]').inputValue(),'−π/12');
await svg.focus();await page.keyboard.press('Home');p=xy(0);await page.mouse.move(p.x,p.y);await page.mouse.down();for(let i=1;i<=30;i++){p=xy(-i*Math.PI/12);await page.mouse.move(p.x,p.y);}await page.mouse.up();assert.equal(await page.locator('[data-angle-input]').inputValue(),'−5π/2');
await page.locator('[data-angle-snap]').selectOption('0');p=xy(-2.0777);await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.up();assert.match(await page.locator('[data-angle-input]').inputValue(),/,\d+π/);
await page.locator('[data-angle-snap]').selectOption('12');assert(!((await page.locator('[data-angle-input]').inputValue()).includes(',')));
await page.locator('[data-angle-input]').fill('π/7');await page.locator('[data-angle-input]').press('Enter');assert.equal(await page.locator('[data-angle-input]').inputValue(),'π/7');await page.locator('[data-angle-range]').focus();await page.keyboard.press('ArrowRight');assert(!((await page.locator('[data-angle-input]').inputValue()).includes(',')));
// Responsive dashboards, context ribbon and 200% zoom.
for(const url of [D.routes.lesson.path,D.routes.homework.path,D.routes.trigonometry.path,R.link('homework','before-radians')])for(const width of [360,768,1280]){await page.setViewportSize({width,height:900});await page.goto(origin+url);await page.locator('h1').waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+url+' '+width);}
await page.setViewportSize({width:360,height:900});await page.goto(origin+D.routes.lesson.path);await page.evaluate(()=>document.body.style.zoom='2');if(!(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)))console.log(await page.locator('body *').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().right>innerWidth+1).map(e=>({tag:e.tagName,cls:e.className,w:e.getBoundingClientRect().width,text:e.textContent.slice(0,70)}))));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.evaluate(()=>document.body.style.zoom='1');
await page.goto(origin+'/trainers/trainer-board.html?trainer='+encodeURIComponent(D.routes.lesson.path));const frame=page.frameLocator('#trainerFrame');await frame.getByRole('heading',{name:D.routes.lesson.title,exact:true}).waitFor();await frame.locator('.route-card').first().getByRole('link',{name:'Обсудить и исследовать'}).click();await frame.locator('#route-context').waitFor();
// Corrupt saved data is read-only and visibly incomplete, never a success.
await page.goto(origin+D.routes.homework.path);await page.evaluate(({pk,mk})=>{localStorage.setItem(pk,'{broken');localStorage.setItem(mk,'{broken');},{pk,mk});await page.reload();assert(await page.locator('.warning').isVisible());assert.equal(await page.evaluate(k=>localStorage.getItem(k),pk),'{broken');assert.equal(await page.locator('.task-status').filter({hasText:'самостоятельный успех'}).count(),0);
assert.deepEqual(errors,[]);console.log(JSON.stringify({gate:'PROFILE_ROUTE_BROWSER_OK',homeworkChecks:completed,tutorGuided:true,report:true,board:true,snapPointer:true,negativeTurns:true,freeMode:true,typedPi:true,responsive:[360,768,1280],zoom:true,corruptionPreserved:true,errors}));
}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
