'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..'),shots=process.env.V6_SHOTS||'/tmp/vilenkin-full-shots';fs.mkdirSync(shots,{recursive:true});
const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(!f.startsWith(root+path.sep))return res.writeHead(403).end();try{if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.json')?'application/json':'text/html');res.end(fs.readFileSync(f));}catch(_){res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,base=origin+'/school/index.html?course=vilenkin6';const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,headless:true,args:['--no-sandbox']});try{
const page=await browser.newPage({viewport:{width:1280,height:900}});page.setDefaultTimeout(9000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
const go=async(route)=>{await page.goto(base+'#'+route);await page.locator('h1').waitFor();};
const answerFor=()=>page.evaluate(()=>{const s=JSON.parse(localStorage.getItem(WorkshopState.KEY)),t=WorkshopMath.generate(s.last.skill,s.last.seed),fmt=a=>Array.isArray(a)?a.map(fmt).join(';'):typeof a==='object'?WorkshopMath.fmt(a):String(a);return t.answerFormat==='prime-factors'?t.answer.join('*'):fmt(t.answer);});
await go('course/vilenkin6');assert.equal(await page.locator('.v6-unit-card').count(),46);await page.locator('#v6-search').fill('процент');assert(await page.locator('#v6-search-results a').count()>5);await page.locator('a[href="#v6-unit/2"]').click();await page.locator('.skill-row').first().waitFor();assert.equal(await page.locator('.skill-row').count(),11);
const ids=await page.evaluate(()=>WorkshopCurriculum.pathById.vilenkin6.ids);await page.evaluate(()=>{localStorage.setItem('legacy-sentinel','keep');const s=WorkshopState.blank();WorkshopState.result(s,{skill:'v6-02',mode:'check',correct:true,attempt:1,assisted:false,exposed:false,time:1,fingerprint:'old'});WorkshopState.save(localStorage,s);});await page.reload();await page.locator('h1').waitFor();
for(const [index,id]of ids.entries()){
 await go('lesson/'+id);await page.locator('.v6-lab').waitFor();assert.equal(await page.locator('.v6-worked li').count(),3,id+' example');
 const answers=await page.evaluate(id=>{const t=WorkshopMath.generate(id,0),fmt=a=>Array.isArray(a)?a.map(fmt).join(';'):typeof a==='object'?WorkshopMath.fmt(a):String(a);return [...t.steps,t].map(s=>s.answerFormat==='prime-factors'?s.answer.join('*'):fmt(s.answer));},id);
 for(const [i,a]of answers.entries()){await page.locator('#answer').fill(a);await page.locator('#answer-form button').click();assert.equal(await page.locator('.feedback.error').count(),0,id+' step '+i);if(i<answers.length-1)await page.locator('[data-cmd=next]').click();}
 if((index+1)%40===0)console.log('Vilenkin full browser guided flows',index+1);
}
const field=async(key,val)=>{await page.locator('#model [data-field='+key+']').evaluate((e,v)=>e.value=String(v),val);await page.locator('#model [data-field='+key+']').dispatchEvent('input');};
const modelAnswer=async(a)=>{if(a!==null)await page.locator('#v6-prediction').fill(String(a));await page.locator('.v6-model-check button').click();assert.match(await page.locator('.v6-result').innerText(),/^Верно/);};
await go('lesson/v6f-percent-small');await field('total',800);await field('p',.5);await modelAnswer(4);await field('p',150);await modelAnswer(1200);await page.locator('[data-adjust=p][data-delta="-1"]').click();assert.equal(await page.locator('[data-field=p]').inputValue(),'149.5');
await go('lesson/v6f-like-recognize');await field('group',1);assert.match(await page.locator('#model svg').textContent(),/y/);const algebraValue=await page.evaluate(()=>{const d=WorkshopMath.generate('v6f-like-recognize',0).data;return (d.a-d.c)*d.x+d.a+d.b;});await modelAnswer(algebraValue);
await go('lesson/v6f-motion-meeting');await field('time',0);let positions=await page.locator('#model svg circle').evaluateAll(es=>es.map(e=>Number(e.getAttribute('cx'))));assert(positions[0]<positions[1],'initial separation must be visible');const meetingTime=await page.evaluate(()=>{const d=WorkshopMath.generate('v6f-motion-meeting',0).data;return d.distance/(d.fast+d.slow);});await field('time',meetingTime);positions=await page.locator('#model svg circle').evaluateAll(es=>es.map(e=>Number(e.getAttribute('cx'))));assert(Math.abs(positions[0]-positions[1])<1e-8,'meeting positions must coincide');await modelAnswer(0);
await go('lesson/v6f-fraction-add');const denominators=await page.evaluate(()=>{const d=WorkshopMath.generate('v6f-fraction-add',0).data;return d.u.d*d.w.d/WorkshopMath.gcd(d.u.d,d.w.d);});await field('den',denominators);await modelAnswer('да');
await go('lesson/v6f-absolute-roots');const roots=await page.evaluate(()=>WorkshopMath.generate('v6f-absolute-roots',0).answer);await page.locator('[data-cmd=mode][data-value=practice]').click();const reversed=await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem(WorkshopState.KEY));return WorkshopMath.generate(s.last.skill,s.last.seed).answer.reverse().join(';');});await page.locator('#answer').fill(reversed);await page.locator('#answer-form button').click();assert.equal(await page.locator('.feedback.error').count(),0);
await go('lesson/v6f-equation-both');const eq=await page.evaluate(()=>WorkshopMath.generate('v6f-equation-both',0).data);const operation=async(op,v)=>{await page.locator('#v6-op').selectOption(op);await page.locator('#v6-operand').fill(String(v));await page.locator('[data-eq=apply]').click();};await operation('x',-eq.C);await operation('constant',-eq.B);await operation('divide',eq.A-eq.C);assert.match(await page.locator('.v6-result').innerText(),/Получено x/);await operation('divide',0);assert.match(await page.locator('.v6-result').innerText(),/недопустимо/);await page.locator('[data-eq=undo]').click();assert.equal(await page.locator('.v6-eq-history li').count(),2);
await go('lesson/v6f-symmetry-line');const point=await page.evaluate(()=>WorkshopMath.generate('v6f-symmetry-line',0).data.target);await field('x',point[0]);await field('y',point[1]);await modelAnswer(null);const dot=page.locator('[data-v6-drag]');await dot.focus();await dot.press('ArrowRight');assert.equal(await page.locator('[data-field=x]').inputValue(),String(point[0]+1));await page.locator('[data-v6-drag]').press('ArrowLeft');await modelAnswer(null);
await go('lesson/v6f-percent-reverse');await page.locator('#answer').fill('черновик 80');await page.locator('[data-cmd=prerequisite][data-value=v6f-percent-whole]').click();await page.locator('[data-cmd=return]').click();assert.equal(await page.locator('#answer').inputValue(),'черновик 80');
await page.locator('[data-cmd=mode][data-value=check]').click();assert.equal(await page.locator('#model').count(),0);for(let i=0;i<3;i++)await page.locator('[data-cmd=hint]').click();assert.match(await page.locator('#help').innerText(),/Подсказка 3 из 3/);await page.locator('#answer').fill(await answerFor());await page.locator('#answer-form button').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(WorkshopState.KEY)).skills['v6f-percent-reverse'].checks.length),0);
await go('lesson/v6f-percent-whole');await page.locator('[data-cmd=mode][data-value=check]').click();const errorValue=await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem(WorkshopState.KEY)),t=WorkshopMath.generate(s.last.skill,s.last.seed);return WorkshopMath.fmt(t.errors[0].value);});await page.locator('#answer').fill(errorValue);await page.locator('#answer-form button').click();assert.match(await page.locator('.feedback.error').innerText(),/восстановить целое/);assert(await page.locator('[data-cmd=prerequisite][data-value=v6f-percent-part]').count()>0);
await go('lesson/v6f-equation-inverse');await page.locator('[data-cmd=mode][data-value=check]').click();for(let i=0;i<3;i++){await page.locator('#answer').fill(await answerFor());await page.locator('#answer-form button').click();await page.locator('[data-cmd=next]').click();}await page.waitForFunction(()=>document.querySelector('h1')?.textContent.includes('прогресс'));assert.match(await page.locator('h1').innerText(),/прогресс/);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(WorkshopState.KEY)).skills['v6f-equation-inverse'].checks.length),3);
for(const width of [360,768,1280]){await page.setViewportSize({width,height:900});for(const key of ['percent-small','triangle-sum','symmetry-axis','equation-fractions','graph-journey','project-garden','mixed-multiply']){await go('lesson/v6f-'+key);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),key+' overflow '+width);}await page.locator('#model').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(shots,'model-'+width+'.png')});await go('course/vilenkin6');await page.screenshot({path:path.join(shots,'course-'+width+'.png')});}
await page.emulateMedia({reducedMotion:'reduce'});await go('lesson/v6f-symmetry-axis');await page.evaluate(()=>document.body.style.zoom='2');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.evaluate(()=>document.body.style.zoom='1');assert.equal(await page.evaluate(()=>localStorage.getItem('legacy-sentinel')),'keep');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(WorkshopState.KEY)).skills['v6-02'].checks.length),1);
await page.route('**/api/trainer-registry',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({schemaVersion:1,digest:'a'.repeat(64),trainers:[]})}));await page.goto(origin+'/trainers/trainer-board.html?trainer='+encodeURIComponent('/school/index.html?course=vilenkin6#lesson/v6f-percent-small'));await page.frameLocator('#trainerFrame').locator('.v6-lab').waitFor();assert.match(await page.frameLocator('#trainerFrame').locator('h1').innerText(),/проценты/);assert.equal(await page.frameLocator('#trainerFrame').locator('a[href*="trainer-board.html?trainer="]').count(),0);
assert.deepEqual(errors,[]);console.log('PASS 194 guided lesson flows; editable models; reverse root order; valid equation operations; hints/errors/return; 3 independent tasks; local legacy data; phone/tablet/desktop/zoom; embedded board.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
