'use strict';
// Independent numeric checks use raw conditions, enumeration, and substitution.
const assert=require('node:assert/strict'),fs=require('node:fs');
const C=require('../school/curriculum'),M=require('../school/math'),S=require('../school/state');
require('../school/algebra7').install(C,M);require('../school/secondary').install(C,M);require('../school/core-content').install(C);require('../school/core-math').install(M);require('../school/paths').install(C);
const E=require('../school/editions-content');E.install(C);require('../school/editions-math').install(M);
const legacy=C.lessons.map(l=>l.id);require('../school/vilenkin6-lessons').install(C,E);require('../school/vilenkin6-math').install(M);const V=require('../school/vilenkin6-models');
const n=x=>Array.isArray(x)?x.map(n):x&&typeof x==='object'?x.n/x.d:x,fmt=x=>Array.isArray(x)?x.map(fmt).join(';'):typeof x==='object'?M.fmt(x):String(x),close=(a,b)=>{if(Array.isArray(a))return assert.deepEqual(a,b);if(typeof b==='string')return assert.equal(a,b);assert(Math.abs(a-b)<1e-7,`${a} != ${b}`);},gcd=(a,b)=>b?gcd(b,a%b):a,lcm=(a,b)=>a*b/gcd(a,b),range=(a,b)=>Array.from({length:b-a+1},(_,i)=>i+a),yn=z=>z?'да':'нет';
const evalExpr=(expr,x,y=1)=>Function('return ('+expr.replace(/−/g,'-').replace(/·/g,'*').replace(/,/g,'.').replace(/x/g,'('+x+')').replace(/y/g,'('+y+')').replace(/(\d|\))\(/g,'$1*(')+')')();
function oracle(k,d,z,t){const {a,b,c,v}=d,u=n(d.u),w=n(d.w),x=d.x,y=d.y,p=n(d.percent);
 switch(k){
 case 'mean-share':case 'mean-calculate':case 'mean-weighted':close(z*d.values.length,d.values.reduce((s,n)=>s+n,0));return;
 case 'mean-missing':close(z+d.values.slice(0,-1).reduce((s,n)=>s+n,0),n(d.mean)*d.values.length);return;
 case 'percent-meaning':close(z*100,d.total);return;
 case 'percent-convert':close(z,d.direction?p:p/100);return;
 case 'percent-common':case 'percent-part':case 'percent-small':case 'proportion-percent':close(z*100,d.total*p);return;
 case 'percent-whole':close(z*p/100,n(d.part));return;
 case 'percent-ratio':close(z*d.total/100,n(d.part));return;
 case 'percent-discount':close(z+n(d.part),d.total);return;
 case 'percent-increase':close(z-n(d.part),d.total);return;
 case 'percent-reverse':close(z*(1-p/100),n(d.after));return;
 case 'percent-chain':close(z,d.total*(1+d.p1/100)*(1-d.p2/100));return;
 case 'pie-read':close(z/d.total,p/100);return;
 case 'pie-angle':close(z/360,p/100);return;
 case 'pie-build':close(z/360+(p+d.p2)/100,1);return;
 case 'triangle-sides':close(z,['равносторонний','равнобедренный','разносторонний'][new Set(d.lengths).size-1]);return;
 case 'triangle-exists':{const s=d.lengths.slice().sort((a,b)=>a-b);close(z,yn(s[0]+s[1]>s[2]));return;}
 case 'triangle-angles':close(z,d.angles.some(x=>x>90)?'тупоугольный':d.angles.includes(90)?'прямоугольный':'остроугольный');return;
 case 'triangle-sum':close(z+d.angles[0]+d.angles[1],180);return;
 case 'triangle-isosceles':close(z*2+d.angles[0],180);return;
 case 'sets-members':close(z,new Set(d.list).size);return;
 case 'sets-union':close(z,new Set([...d.A,...d.B]).size);return;
 case 'sets-intersection':close(z,d.A.filter(x=>d.B.includes(x)).length);return;
 case 'sets-count':close(z,d.onlyA+d.onlyB+d.both);return;
 case 'sets-subset':close(z,yn(d.B.every(x=>d.A.includes(x))));return;
 case 'prime-test':{const ds=range(1,d.n).filter(x=>d.n%x===0);close(z,ds.length===1?'ни то ни другое':ds.length===2?'простое':'составное');return;}
 case 'divisibility':close(z,yn(d.n%d.divisor===0));return;
 case 'prime-factor':close(z.reduce((a,b)=>a*b,1),d.n);z.forEach(p=>assert.equal(range(1,p).filter(x=>p%x===0).length,2));return;
 case 'prime-repair':close(z*d.shown.reduce((a,b)=>a*b,1),d.n);return;
 case 'gcd-list':case 'gcd-primes':case 'gcd-packs':close(z,Math.max(...range(1,Math.min(x,y)).filter(n=>x%n===0&&y%n===0)));return;
 case 'coprime':close(z,yn(range(2,Math.min(x,y)).every(n=>x%n||y%n)));return;
 case 'lcm-find':case 'lcm-primes':case 'lcm-events':{let ans=Math.max(x,y);while(ans%x||ans%y)ans++;close(z,ans);return;}
 case 'fraction-equivalent':case 'fraction-convert':close(z/d.den,u);return;
 case 'fraction-lcd':close(z,lcm(d.u.d,d.w.d));return;
 case 'fraction-compare':case 'negative-compare':case 'negative-fractions':close(z,u<w?'<':u>w?'>':'=');return;
 case 'fraction-add':case 'fraction-decimal':case 'mixed-add':close(z,u+w);return;
 case 'fraction-subtract':case 'mixed-subtract':case 'mixed-borrow':case 'whole-minus-fraction':close(z+w,u);return;
 case 'fraction-brackets':close(z+u+w,n(d.outer));return;
 case 'mixed-convert':case 'rational-decimal':close(z,u);return;
 case 'fraction-times-int':case 'fraction-multiply':case 'fraction-cancel':case 'mixed-multiply':case 'fraction-area':close(z,u*w);return;
 case 'fraction-part':close(z/d.total,u);return;
 case 'fraction-remain':close(z/d.total+u,1);return;
 case 'fraction-of-remainder':close(z+n(d.first)*w+d.total*u,d.total);return;
 case 'fraction-volume':close(z,d.length*n(d.width)*n(d.height));return;
 case 'distribute-add':case 'distribute-factor':case 'properties-factor':close(z,d.outer*d.x+d.outer*d.y);return;
 case 'distribute-sub':close(z+d.outer*d.y,d.outer*d.x);return;
 case 'distribute-fractions':close(z,d.outer*(u+w));return;
 case 'reciprocal':close(z*u,1);return;
 case 'fraction-divide-int':case 'fraction-divide':case 'mixed-divide':case 'fraction-unit-rate':case 'fraction-unknown':close(z*w,u);return;
 case 'whole-from-fraction':case 'whole-from-remainder':case 'whole-two-parts':close(z*n(d.share),n(d.known));return;
 case 'fraction-bar':close(z*(w+1),u+w);return;
 case 'fraction-order':close(z*w,u*d.factor);return;
 case 'fraction-complex':close(z*(1+u),1);return;
 case 'ratio-units':close(z*d.meters*100,d.cm);return;
 case 'ratio-reduce':close(z[0]/z[1],x/y);assert.equal(gcd(...z),1);return;
 case 'ratio-split':close(z+(z/d.parts[0])*d.parts[1],d.total);return;
 case 'ratio-difference':close(z/d.parts[0]*d.parts[1]-z,d.difference);return;
 case 'proportion-check':close(z,yn(a*y===b*x));return;
 case 'proportion-missing':close(z/d.den,a/b);return;
 case 'proportion-recipe':case 'direct':close(z/d.newN,d.total/d.old);return;
 case 'proportion-choice':{const ratios=d.rows.map(([x,y])=>y/x),products=d.rows.map(([x,y])=>x*y);close(z,new Set(ratios).size===1?'прямая':new Set(products).size===1?'обратная':'ни та ни другая');return;}
 case 'inverse':case 'work-gardens':case 'review-ratios':close(z*d.newWorkers/d.newGardens,d.workers*d.days/d.gardens);return;
 case 'joint-work':close(z/d.t1+z/d.t2,1);return;
 case 'motion-meeting':close(z*(d.meeting?d.fast+d.slow:d.fast-d.slow),d.distance);return;
 case 'scale-real':close(z*100000,d.map*d.scale);return;
 case 'scale-map':close(z*d.scale,d.real);return;
 case 'scale-find':close(z*d.map,d.real);return;
 case 'symmetry-axis':close(z,d.axis==='x'?[x,-y]:[-x,y]);return;
 case 'symmetry-center':close(z,[-x,-y]);return;
 case 'symmetry-line':close((z[0]+x)/2,d.center);close(z[1],y);return;
 case 'symmetry-polygon':close(z,[-x,y]);return;
 case 'circle-radius':case 'circle-inverse':close(z,d.radius);return;
 case 'circle-length':close(z/(2*d.radius),3.14);return;
 case 'circle-area':close(z/(d.radius**2),3.14);return;
 case 'sphere-solids':close(z,d.radius*2);return;
 case 'signed-context':case 'signed-scale':close(z,y);return;
 case 'signed-order':close(z,Math.min(...d.values));return;
 case 'opposite':case 'minus-minus':case 'opposite-equation':close(z+x,0);return;
 case 'absolute':close(z,Math.abs(n(d.value)));return;
 case 'absolute-roots':assert.deepEqual(new Set(z),new Set([-a,a]));return;
 case 'absolute-shift':z.forEach(x=>close(Math.abs(x-d.center),a));assert.equal(new Set(z).size,2);return;
 case 'distance-points':close(z,Math.abs(x-y));return;
 case 'integers-between':close(z,range(d.left,d.right).filter(x=>(d.include?x>=d.left:x>d.left)&&x<d.right).length);return;
 case 'line-positive':case 'line-negative':case 'change-final':close(z,d.start+d.move);return;
 case 'line-chain':close(z,d.start+d.m1+d.m2);return;
 case 'change':close(z+d.start,d.end);return;
 case 'change-start':close(z+d.move,d.end);return;
 case 'negative-add':case 'negative-decimal-add':case 'negative-fraction-add':case 'mixed-sign-add':case 'mixed-sign-decimal':case 'mixed-sign-fractions':close(z,u+w);return;
 case 'cancel-pairs':case 'properties-group':close(z,d.values.reduce((s,n)=>s+n,0));return;
 case 'subtract-rule':case 'subtract-negative':case 'subtract-fractions':close(z+w,u);return;
 case 'subtract-chain':close(z,-a+b+c-(a+b));return;
 case 'multiply-sign':case 'multiply-decimal':case 'multiply-fractions':close(z,u*w);return;
 case 'multiply-many':close(z,d.values.reduce((a,b)=>a*b,1));return;
 case 'divide-sign':case 'divide-decimal':case 'divide-fractions':close(z*w,u);return;
 case 'divide-unknown':close(d.dividend/z,d.quotient);return;
 case 'rational-finite':{let den=d.u.d;while(den%2===0)den/=2;while(den%5===0)den/=5;close(z,yn(den===1));return;}
 case 'rational-period':close(z,Math.floor(100/d.den)%10);return;
 case 'properties-product':close(z,-.25*a*4);return;
 case 'properties-order':close(z,-a*a+b*b);return;
 case 'brackets-plus':case 'brackets-minus':case 'brackets-factor':case 'brackets-nested':case 'like-combine':case 'like-after-brackets':close(z,evalExpr(d.expr,d.x));return;
 case 'coefficient-read':case 'coefficient-product':case 'coefficient-fraction':close(z,evalExpr(d.expr,1));return;
 case 'like-recognize':close(z,2);return;
 case 'like-two-letters':close(z[0],evalExpr(d.expr,1,0));close(z[1],evalExpr(d.expr,0,1));return;
 case 'equation-inverse':case 'equation-both':case 'equation-brackets':case 'equation-fractions':case 'equation-decimals':case 'equation-parts':case 'equation-motion':case 'equation-transfer':case 'equation-mixture':case 'review-equations':{const [left,right]=d.expr.split('=');close(evalExpr(left,z),evalExpr(right,z));return;}
 case 'equation-special':close(z,d.B===d.D?'любое число':'нет');return;
 case 'perpendicular-angle':close(z-d.angle,90);return;
 case 'perpendicular-build':close(z[0],x);close(z[1],d.baseY);return;
 case 'perpendicular-distance':close(z,Math.abs(y-d.baseY));return;
 case 'parallel-definition':close(z,yn(d.dx*d.dy2===d.dy*d.dx2));return;
 case 'parallel-build':case 'parallel-grid':close(z,[x+d.dx,y+d.dy]);return;
 case 'coordinates-read':case 'coordinates-place':close(z,[x,y]);return;
 case 'coordinates-axis':close(z,x===0?'y':y===0?'x':'ни одной');return;
 case 'coordinates-rectangle':close(z,[d.rectangle[0],d.rectangle[1]+d.rectangle[3]]);return;
 case 'coordinates-polygon':close(z,d.rectangle[2]*d.rectangle[3]);return;
 case 'review-geometry':close(z,2*(d.rectangle[2]+d.rectangle[3]));return;
 case 'graph-read':close(z,d.values[d.index]);return;
 case 'graph-build':close(z,[d.times[d.index],d.values[d.index]]);return;
 case 'graph-journey':close(z,d.values.slice(1).reduce((s,x,i)=>s+Math.abs(x-d.values[i]),0));return;
 case 'graph-speed':close(z,(d.values[1]-d.values[0])/(d.times[1]-d.times[0]));return;
 case 'graph-temperature':close(z,Math.max(...d.values)-Math.min(...d.values));return;
 case 'review-numbers':close(z,d.total*p/100);return;
 case 'review-fractions':close(z*n(d.divisor),u+w);return;
 case 'review-signed':close(z,-a+b*c);return;
 case 'project-budget':close(z-d.delivery,d.total*p/100);return;
 case 'project-garden':close(z*d.den,d.length*d.width*(d.scale/100)**2);return;
 case 'project-route':close(z*(d.t1+d.t2+n(d.stop)),d.s1*d.t1+d.s2*d.t2);return;
 default:throw Error('Oracle missing '+k);
 }
}
let tasks=0,frames=0;const ids=C.pathById.vilenkin6.ids;assert.equal(ids.length,194);assert.equal(new Set(ids).size,194);assert.equal(C.pathById.vilenkin6.units.length,46);legacy.forEach(id=>assert(C.byId[id]));
for(const id of ids){const l=C.byId[id];assert(l.worked.length>=3,id+' worked example');assert(l.worked.every(x=>x.length>3),id+' empty example');[...l.requires,...l.related,l.next].filter(Boolean).forEach(id=>assert(C.byId[id]));const fingerprints=new Set();
 for(let seed=0;seed<120;seed++){const t=M.generate(id,seed);try{oracle(l.fullKey,t.data,n(t.answer),t);}catch(e){throw Error(id+' seed '+seed+': '+e.message,{cause:e});}assert(t.steps.length>=2);for(const target of [t,...t.steps])assert(M.accepts(target.answerFormat==='prime-factors'?target.answer.join('*'):fmt(target.answer),target),id+' answer enterable');if(t.answerFormat==='unordered')assert(M.accepts(t.answer.slice().reverse().map(fmt).join(';'),t));fingerprints.add(S.fingerprint(id,t));tasks++;
 if(seed<3&&t.model.family!=='equation'){const fields=V.spec(t.model),p=Object.fromEntries(fields.map(f=>[f.key,f.value]));fields.forEach(f=>{assert(f.min<=f.value&&f.value<=f.max,id+' range');});for(const field of [null,...fields])for(const edge of ['min','max']){const ps={...p};if(field)ps[field.key]=field[edge];const r=V.investigate(t.model,ps);assert(!/NaN|Infinity|undefined/.test(JSON.stringify(r)),id+' finite model');assert(r.caption.length>30&&r.question);frames++;}}
 }
 assert(fingerprints.size>=3,id+' needs fresh variants');
}
const state=S.blank();for(const id of [legacy[0],...ids.slice(0,4)])S.result(state,{skill:id,mode:'check',correct:true,attempt:1,assisted:false,exposed:false,time:1,fingerprint:'unique-'+id});const storage={getItem:()=>JSON.stringify(state)};assert(!S.load(storage,C.lessons.map(l=>l.id)).warning);assert.equal(S.load(storage,C.lessons.map(l=>l.id)).state.skills[legacy[0]].checks.length,1);
const board=JSON.parse(fs.readFileSync('trainers/board-picker-data.json'));for(const id of ids)assert(board.entries.some(e=>e.href.endsWith('#lesson/'+id)),id+' board link');
console.log(`PASS ${tasks} independently checked tasks, ${frames} model boundary frames, 194 lesson maps, alternate-root order, legacy state and board links.`);
