'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..'),shots=process.env.M9_SHOTS||'/tmp/makarychev9-shots';fs.mkdirSync(shots,{recursive:true});
const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(!f.startsWith(root+path.sep))return res.writeHead(403).end();try{if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.json')?'application/json':'text/html');res.end(fs.readFileSync(f));}catch(_){res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,base=origin+'/school/index.html?course=makarychev9';const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,headless:true,args:['--no-sandbox']});try{
const page=await browser.newPage({viewport:{width:1280,height:900}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
const go=async(route)=>{await page.goto(base+'#'+route);await page.locator('h1').waitFor();};
const answerFor=()=>page.evaluate(()=>{const s=JSON.parse(localStorage.getItem(WorkshopState.KEY)),t=WorkshopMath.generate(s.last.skill,s.last.seed),fmt=a=>Array.isArray(a)?a.map(fmt).join(';'):typeof a==='object'?WorkshopMath.fmt(a):String(a);return t.answerFormat==='m9-pairs'?t.answer.map(p=>'('+p.map(fmt).join(';')+')').join(';'):fmt(t.answer);});
await go('course/makarychev9');assert.equal(await page.locator('.m9-unit-card').count(),31);assert.equal(await page.locator('.m9-unit-card .warm').count(),5);assert.match(await page.locator('main').innerText(),/2023/);await page.locator('#m9-search').fill('пункт 17');assert.equal(await page.locator('#m9-search-results a').count(),3);await page.screenshot({path:path.join(shots,'course-desktop.png'),fullPage:true});
await go('m9-unit/10');assert.equal(await page.locator('.skill-row').count(),3);await page.locator('summary').click();await page.locator('a[href="#lesson/m9-10"]').click();await page.locator('h1').waitFor();assert.match(page.url(),/lesson\/m9-10/);
const ids=await page.evaluate(()=>WorkshopCurriculum.pathById.makarychev9.ids);
for(const [index,id] of ids.entries()){
 await go('lesson/'+id);await page.locator('.m9-lab svg').waitFor();assert.equal(await page.locator('.v6-worked li').count(),3,id);
 const answers=await page.evaluate(id=>{const t=WorkshopMath.generate(id,0),fmt=a=>Array.isArray(a)?a.map(fmt).join(';'):typeof a==='object'?WorkshopMath.fmt(a):String(a);return [...t.steps,t].map(s=>s.answerFormat==='m9-pairs'?s.answer.map(p=>'('+p.map(fmt).join(';')+')').join(';'):fmt(s.answer));},id);
 for(const [i,a] of answers.entries()){await page.locator('#answer').fill(a);await page.locator('#answer-form button').click();assert.equal(await page.locator('.feedback.error').count(),0,id+' step '+i);if(i<answers.length-1)await page.locator('[data-cmd=next]').click();}
 if((index+1)%25===0)console.log('M9 guided flows',index+1);
}
async function change(key,value){await page.locator('[data-param='+key+']').fill(String(value));await page.locator('[data-param='+key+']').dispatchEvent('change');}
await go('lesson/m9f-shift-vertex');const target=await page.evaluate(()=>{const d=WorkshopMath.generate('m9f-shift-vertex',0).data;return {a:d.sgn*d.c,h:d.h,k:d.b};});await page.locator('[data-lab-action=graph-check]').click();assert(!await page.locator('.m9-status').evaluate(e=>e.classList.contains('good')));for(const [k,v] of Object.entries(target))await change(k,v);await page.locator('[data-lab-action=graph-check]').click();assert.match(await page.locator('.m9-status').innerText(),/Построение верно/);
await page.locator('[data-lab-action=target]').click();assert.equal(await page.locator('.m9-target').count(),2);const oldMission=await page.locator('.m9-mission p').first().innerText();await page.locator('[data-lab-action=new-mission]').click();assert.notEqual(await page.locator('.m9-mission p').first().innerText(),oldMission);
// Pointer construction and keyboard use the same state.
await page.locator('.m9-coordinate').scrollIntoViewIfNeeded();const positions=await page.locator('.m9-coordinate').evaluate(svg=>[[300,260],[240,220]].map(([x,y])=>{const pt=svg.createSVGPoint();pt.x=x;pt.y=y;const out=pt.matrixTransform(svg.getScreenCTM());return {x:out.x,y:out.y};}));await page.mouse.move(positions[0].x,positions[0].y);await page.mouse.down();await page.mouse.move(positions[1].x,positions[1].y);assert.equal(await page.locator('[data-param=h]').inputValue(),'-3');assert.equal(await page.locator('[data-param=k]').inputValue(),'2');await page.mouse.up();await page.mouse.click(positions[0].x,positions[0].y);assert.equal(await page.locator('[data-param=h]').inputValue(),'0');assert.equal(await page.locator('[data-param=k]').inputValue(),'0');await page.locator('[data-param=h]').focus();await page.keyboard.press('ArrowUp');await page.keyboard.press('Tab');assert.equal(await page.locator('[data-param=h]').inputValue(),'1');
await page.locator('[data-param=type]').selectOption('inverse');await change('x',1);assert.match(await page.locator('.m9-canvas').innerText(),/не определено/);
await go('lesson/m9f-interval-rational');await page.locator('[data-param=type]').selectOption('quotient');await page.locator('[data-interval="0"]').click();await page.locator('[data-interval="2"]').click();await page.locator('[data-end="0"]').check();await page.locator('[data-end="1"]').check();await page.locator('[data-lab-action=sign-check]').click();assert.match(await page.locator('.m9-status').innerText(),/нуль знаменателя/);await page.locator('[data-end="1"]').uncheck();await page.locator('[data-lab-action=sign-check]').click();assert.match(await page.locator('.m9-status').innerText(),/Верно/);
await page.locator('[data-lab-action=show-graph]').click();assert.equal(await page.locator('.m9-coordinate').count(),1);
await page.locator('[data-param=type]').selectOption('even');await page.locator('[data-interval="2"]').click();await page.locator('[data-end="0"]').check();await page.locator('[data-end="1"]').check();await page.locator('[data-lab-action=sign-check]').click();assert.match(await page.locator('.m9-status').innerText(),/Верно/);
await go('lesson/m9f-system-circle');await page.locator('[data-param=type]').selectOption('circle');await change('x',4);await change('y',3);await page.locator('[data-lab-action=system-check]').click();assert.match(await page.locator('.m9-status').innerText(),/^Подходит/);await change('x',-4);await page.locator('[data-lab-action=system-check]').click();assert.match(await page.locator('.m9-status').innerText(),/^Подходит/);
await go('lesson/m9f-geometric-alternating');await page.locator('[data-param=type]').selectOption('geometric');await change('change',-1);await change('count',5);await page.locator('[data-sum]').fill('2');await page.locator('[data-lab-action=sum-check]').click();assert.match(await page.locator('.m9-status').innerText(),/Сумма верна/);
await go('lesson/m9f-absolute-error');await page.locator('[data-error]').fill('-1');await page.locator('[data-lab-action=error-check]').click();assert.match(await page.locator('.m9-status').innerText(),/не может быть отрицательным/);await page.locator('[data-error]').fill('1');await page.locator('[data-lab-action=error-check]').click();assert.match(await page.locator('.m9-status').innerText(),/Верно/);
// Preserve draft and exact session on a prerequisite detour.
await go('lesson/m9f-rational-solve');await page.locator('#answer').fill('мой шаг');await page.locator('[data-cmd=prerequisite][data-value=core-rational-equation]').click();await page.locator('[data-cmd=return]').click();assert.equal(await page.locator('#answer').inputValue(),'мой шаг');
await page.locator('[data-cmd=hint]').click();await page.locator('[data-cmd=hint]').click();await page.locator('[data-cmd=hint]').click();assert.match(await page.locator('#help').innerText(),/Подсказка 3 из 3/);
// New independent checks count; viewing a lab and hints do not.
await page.locator('[data-cmd=mode][data-value=check]').click();for(let i=0;i<3;i++){await page.locator('#answer').fill(await answerFor());await page.locator('#answer-form button').click();assert.equal(await page.locator('.feedback.error').count(),0);await page.locator('[data-cmd=next]').click();}assert(await page.evaluate(()=>JSON.parse(localStorage.getItem(WorkshopState.KEY)).skills['m9f-rational-solve'].checks.length>=2));
await page.evaluate(()=>{localStorage.setItem('m9-sentinel','keep');const s=JSON.parse(localStorage.getItem(WorkshopState.KEY));WorkshopState.result(s,{skill:'m9-01',mode:'check',correct:true,attempt:1,assisted:false,exposed:false,time:1,fingerprint:'legacy'});WorkshopState.save(localStorage,s);});await page.reload();await page.locator('h1').waitFor();
for(const route of ['course/makarychev9','lesson/m9f-shift-vertex','lesson/m9f-interval-even','lesson/m9f-system-circle','lesson/m9f-geometric-sum']){await go(route);for(const width of [360,768,1280]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),route+' width '+width);if(width===360)await page.screenshot({path:path.join(shots,route.split('/').at(-1)+'-360.png'),fullPage:true});}}
await page.setViewportSize({width:360,height:900});await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>document.body.style.zoom='2');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.evaluate(()=>document.body.style.zoom='1');assert.equal(await page.evaluate(()=>localStorage.getItem('m9-sentinel')),'keep');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(WorkshopState.KEY)).skills['m9-01'].checks.length),1);
await go('progress');const downloadPromise=page.waitForEvent('download');await page.locator('[data-cmd=backup]').click();const download=await downloadPromise;const exported=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(exported.skills['m9-01'].checks.length,1);
await page.route('**/api/trainer-registry',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({schemaVersion:1,digest:'a'.repeat(64),trainers:[]})}));await page.goto(origin+'/trainers/trainer-board.html?trainer='+encodeURIComponent('/school/index.html?course=makarychev9#lesson/m9f-shift-vertex'));await page.frameLocator('#trainerFrame').locator('.m9-lab').waitFor();assert.equal(await page.frameLocator('#trainerFrame').locator('a[href*="trainer-board.html?trainer="]').count(),0);await page.waitForFunction(()=>document.querySelector('#pickerGroup').options.length>3);await page.locator('#chooseTrainer').click();await page.locator('[data-course-picker="Макарычев · 9 класс"]').click();await page.locator('#pickerSearch').fill('Собери');await page.locator('#pickerSearch').fill('Чётная кратность');assert.equal(await page.locator('.picker-item').count(),1);await page.locator('.picker-item').click();await page.frameLocator('#trainerFrame').locator('.m9-lab').waitFor();assert.match(await page.frameLocator('#trainerFrame').locator('h1').innerText(),/Чётная кратность/);
assert.deepEqual(errors,[]);console.log('PASS M9 real Chromium: 93 guided flows; all five lab missions; pointer/keyboard; interval endpoints and even roots; hyperbola undefined point; three hints; prerequisite return; independent progress; old data and backup; mobile/tablet/desktop/zoom; board launch.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
