'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),C=require('../school/curriculum'),M=require('../school/math'),S=require('../school/state');
require('../school/algebra7').install(C,M);require('../school/secondary').install(C,M);require('../school/core-content').install(C);require('../school/core-math').install(M);require('../school/paths').install(C);const E=require('../school/editions-content');E.install(C);require('../school/editions-math').install(M);const V6=require('../school/vilenkin6-lessons');V6.install(C,E);require('../school/vilenkin6-math').install(M);
const oldIds=C.lessons.map(x=>x.id),oldGenerate=M.generate,V5=require('../school/vilenkin5-lessons'),P=V5.install(C,V6);require('../school/vilenkin5-math').install(M,C);const Lab=require('../school/vilenkin5-models');
const n=x=>Array.isArray(x)?x.map(n):x&&typeof x==='object'?x.n/x.d:x,fmt=x=>Array.isArray(x)?x.map(fmt).join(';'):typeof x==='object'?M.fmt(x):String(x),same=(a,b)=>{if(typeof a==='number'&&typeof b==='number')assert(Math.abs(a-b)<1e-8,`${a} != ${b}`);else assert.deepEqual(a,b);},range=k=>Array.from({length:k},(_,i)=>i),yes=b=>b?'да':'нет';
function oracle(k,t){const d=t.data,{a,b,c}=d,z=n(t.answer),x=n(d.x),y=n(d.y);
 if(d.sharedKey){assert.deepEqual(t.answer,oldGenerate('v6f-'+d.sharedKey,t._seed).answer);return;}
 switch(k){
 case 'table-read':same(z,d.values[d.i]);break;case 'table-total':same(z,d.values[2]);break;case 'chart-read':same(z,d.height*d.step);break;case 'chart-difference':same(z+d.second,d.first);break;
 case 'place-value':same(z,Number(String(d.n)[d.pos])*10**(3-d.pos));break;case 'place-build':same(z,a*1000+b*10+c);break;case 'place-neighbors':same(z,[d.center-1,d.center+1]);break;
 case 'segment-length':same(z+d.start,d.end);break;case 'broken-length':same(z,d.sides.reduce((s,n)=>s+n,0));break;case 'length-units':same(z-100*a,b);break;case 'scale-step':same(z*d.intervals+d.start,d.end);break;case 'scale-point':same(z/c,a);break;case 'natural-between':same(z,range(d.high).filter(v=>v>d.low).length);break;
 case 'line-ray':same(z,{отрезок:2,луч:1,прямая:0}[d.kind]);break;case 'angle-parts':same(z,d.names[1]);break;case 'circle-shapes':same(z,['окружность','круг','шар','цилиндр'][d.i]);break;case 'natural-compare':same(z,x>y?'>':x<y?'<':'=');break;
 case 'natural-add':same(z-y,x);break;case 'add-smart':same(z-y,d.first+d.last);break;case 'sum-change':same(z-y,x);break;case 'natural-subtract':same(z+y,x);break;case 'subtract-sum':same(z+y+c,x);break;case 'difference-change':same(z+y,x);break;
 case 'expression-value':same((z-c)/b,a);break;case 'expression-story':same(z-c*10,a*d.price);break;case 'equation-add':same(z+b,x+b);break;case 'equation-sub':same(d.sw?z-b:x+b-z,d.sw?x-b:b);break;case 'equation-story':same(z-a,b*10);break;
 case 'natural-multiply':same(z,x*y);break;case 'multiply-column':same(z,x*y);break;case 'division-share':case 'division-measure':case 'division-column':same(z*d.divisor,d.total);break;
 case 'remainder-find':same(z[0]*d.divisor+z[1],d.total);assert(z[1]>=0&&z[1]<d.divisor);break;case 'remainder-pack':assert(z*d.divisor>=d.total&&(z-1)*d.divisor<d.total);break;
 case 'order-brackets':same(z+a*(b+c),d.start);break;case 'order-equal':same(z*b,a*b*c);break;case 'power-read':same(z,Array(d.pow).fill(d.base).reduce((s,v)=>s*v,1));break;case 'power-order':same((z-c)/a,b*b);break;case 'calculator-order':same(z-a,b*c);break;
 case 'divisors-all':same(z,range(d.n).map(i=>i+1).filter(i=>d.n%i===0));break;case 'divisibility-digit':same(z,range(10).filter(i=>(d.tens*10+i)%d.divisor===0));break;
 case 'formula-distance':same(z/d.time,d.speed);break;case 'formula-perimeter':same(z,a+b+a+b);break;case 'area-grid':same(z,range(a).reduce(s=>s+b,0));break;case 'area-missing':same(z*a,a*b);break;case 'area-cut':same(z+a*b,x*y);break;case 'area-units':same(z/a,d.unit==='м²'?100*100:10*10);break;case 'land-units':same(z/100,a*100+b);break;
 case 'solid-elements':same(z,[a,a,a,a,b,b,b,b,c,c,c,c].reduce((s,n)=>s+n,0));break;case 'solid-surface':same(z,a*b+a*b+a*c+a*c+b*c+b*c);break;case 'volume-layers':same(z,range(c).reduce(s=>s+a*b,0));break;case 'volume-litres':same(z-b*25,a*1000);break;case 'circle-radius':same(d.reverse?z*2:z/2,d.reverse?a*2:a);break;
 case 'fraction-parts':same(z*d.den,d.n);break;case 'fraction-line':same(z*d.den,d.num);break;case 'fraction-same-compare':same(z,d.n>d.m?'>':d.n<d.m?'<':'=');break;case 'fraction-unit-compare':same(z,1/d.den>1/d.other?'>':'<');break;case 'fraction-kind':same(z,d.num/d.den<1?'правильная':'неправильная');break;
 case 'fraction-same-add':same(z*d.den,d.n+d.m);break;case 'fraction-same-sub':same(z*d.den+d.m,d.n);break;case 'fraction-sharing':same(z*d.den,a);break;case 'mixed-extract':same(z[0]*d.den+z[1],d.num);assert(z[1]<d.den);break;case 'fraction-reduce':case 'fraction-reduce-check':same(z*d.den,d.num);break;
 case 'decimal-place':same(z*1000,c);break;case 'decimal-fraction':same(z*d.scale,d.num);break;case 'decimal-zeros':same(z,'да');break;case 'decimal-compare':same(z,x>y?'>':x<y?'<':'=');break;case 'decimal-between':same(z-n(d.left),n(d.right)-z);break;
 case 'decimal-add':case 'decimal-carry':case 'decimal-subtract':case 'decimal-borrow':case 'decimal-money':case 'decimal-times-int':case 'decimal-times-ten':case 'decimal-divide-int':case 'decimal-divide-zero':case 'decimal-divide-ten':case 'decimal-multiply':case 'decimal-small-product':case 'decimal-area':case 'decimal-divide':case 'decimal-portion':case 'decimal-reverse':case 'project-recipe':
  if(d.op==='add')same(z-y,x);else if(d.op==='subtract')same(z+y,x);else if(d.op==='multiply')same(z/y,x);else same(z*y,x);break;
 case 'round-decimal':case 'round-carry':{const step=10**-d.places,v=d.raw/d.scale;same(z/step,Number((BigInt(d.raw)*BigInt(10**d.places)*2n+BigInt(d.scale))/(BigInt(d.scale)*2n)));assert(Math.abs(v-z)<=step/2+1e-9);break;}
 case 'angle-kind':same(z,d.deg===180?'развёрнутый':d.deg===90?'прямой':d.deg<90?'острый':'тупой');break;case 'angle-measure':same(z+d.start,d.end);break;case 'angle-build':same(z-d.start,a*10);break;case 'angle-sum':same(z+d.first,d.total);break;
 case 'project-room':assert(z*n(d.cover)>=x*y&&(z-1)*n(d.cover)<x*y);break;
 default:throw Error('Missing independent oracle '+k);
 }
}
assert.equal(P.units.length,53);assert.equal(P.ids.length,132);assert(P.units.every(x=>x.ids.length));assert.equal(new Set(C.lessons.map(l=>l.id)).size,C.lessons.length);assert(oldIds.every(id=>C.byId[id]));
const visiting=new Set(),done=new Set();function visit(id){assert(C.byId[id],id);assert(!visiting.has(id),'Prerequisite cycle '+id);if(done.has(id))return;visiting.add(id);C.byId[id].requires.forEach(visit);visiting.delete(id);done.add(id);}C.lessons.forEach(l=>visit(l.id));
let count=0;for(const id of P.ids){const l=C.byId[id];assert.equal(l.worked.length,3,id);assert(l.explanation.length>40&&l.misconception&&l.reflect.length>=2);for(const r of [...l.requires,...l.related])assert(C.byId[r],r);for(let seed=0;seed<120;seed++){
 const t=M.generate(id,seed);t._seed=seed;oracle(l.fullKey,t);assert(t.steps.length>=2,id);for(const s of [...t.steps,t]){const text=s.answerFormat==='prime-factors'?s.answer.join('*'):s.answerFormat==='decimal'?String(n(s.answer)).includes('.')?String(n(s.answer)):n(s.answer)+'.0':fmt(s.answer);assert(M.accepts(text,s),id+' rejects its valid answer '+text);assert(!M.accepts('не знаю',s),id);assert(!/NaN|Infinity|undefined/.test(s.prompt));}count++;
}}
// Cross-class links preserve a one-way prerequisite graph and two-way optional navigation.
for(const l of C.lessons.filter(l=>l.foundation5)){assert(l.requires.includes(l.foundation5));assert(C.byId[l.foundation5].related.includes(l.id));}
assert(C.lessons.filter(l=>l.foundation5).length>=25);
// Independent operation invariants across legal lab boundaries, including non-integer quotient and improper fractions.
let frames=0;for(const op of ['add','subtract','multiply','divide','compare','parts','equivalent'])for(const ad of [2,3,7,12])for(const bd of [2,5,12])for(const an of [0,1,12,24])for(const bn of [1,4,24]){const s=Lab.fractionState({op,an,ad,bn,bd},M);assert(s.common%ad===0&&s.common%bd===0);const a=an/ad,b=bn/bd;const expected={add:a+b,subtract:a-b,multiply:a*b,divide:a/b,compare:a>b?'>':a<b?'<':'=',parts:a,equivalent:a}[op];same(n(s.answer),expected);frames++;}
for(const op of ['add','subtract','multiply','divide'])for(const ac of [0,1,68,100,999])for(const bc of [1,25,100,999]){const s=Lab.decimalState({op,ac,bc},M);same(n(s.answer),{add:(ac+bc)/100,subtract:(ac-bc)/100,multiply:ac*bc/10000,divide:ac/bc}[op]);frames++;}
for(let divisor=2;divisor<10;divisor++)for(const value of [612,803,1005,4096]){const rows=Lab.divisionRows(value,divisor);rows.forEach(r=>{assert(r.remainder>=0&&r.remainder<divisor);same(r.product+r.remainder,r.current);});same(Number(rows.map(r=>r.q).join(''))*divisor+rows.at(-1).remainder,value);}
const state=S.blank();S.result(state,{skill:'v6f-fraction-add',mode:'check',correct:true,attempt:1,assisted:false,exposed:false,time:1,fingerprint:'old'});const mem={raw:JSON.stringify(state),getItem(){return this.raw;},setItem(k,v){this.raw=v;}};const restored=S.load(mem,C.lessons.map(x=>x.id));assert(!restored.blocked);assert.equal(restored.state.skills['v6f-fraction-add'].checks.length,1);
const board=JSON.parse(fs.readFileSync('trainers/board-picker-data.json'));assert.equal(board.entries.filter(x=>x.group==='Виленкин · 5 класс').length,P.ids.length+1);assert.equal(board.entries.filter(x=>x.group==='Виленкин · 6 класс').length,239);
console.log(`PASS Vilenkin 5: ${count} independent task checks, ${frames} lab boundaries, ${P.ids.length} lessons, 51 textbook points, cross-class DAG, legacy progress, board links.`);
