// Real browser regression scenarios; simulated pupils, not a real-pupil study.
const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..'),shots=process.env.EDITION_SHOTS||'/tmp/edition-checks';fs.mkdirSync(shots,{recursive:true});
const server=http.createServer((req,res)=>{let file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.json')?'application/json':'text/html');res.end(req.method==='HEAD'?'':fs.readFileSync(file));}catch(_){res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,base=origin+'/school/index.html';const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,headless:true,args:['--no-sandbox']});
try{const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));
const go=async(h,course='')=>{await page.goto(base+(course?'?course='+course:'')+'#'+h);await page.locator('h1').waitFor();};
await go('course/vilenkin6');assert.equal(await page.locator('.skill-row').count(),44);await go('course/makarychev9');assert.equal(await page.locator('.skill-row').count(),31);
await page.evaluate(()=>{const state=WorkshopState.blank();WorkshopState.result(state,{skill:'fraction',mode:'check',correct:true,attempt:1,assisted:false,exposed:false,time:1,fingerprint:'legacy'});WorkshopState.save(localStorage,state);localStorage.setItem('legacy-sentinel','preserve');});
const ids=await page.evaluate(()=>WorkshopCurriculum.lessons.filter(l=>l.edition).map(l=>l.id));
for(const [idx,id] of ids.entries()){
 await go('lesson/'+id,id.startsWith('v6')?'vilenkin6':'makarychev9');await page.locator('#model svg').waitFor();
 assert.equal(await page.locator('.alg-theory h2').count(),3);
 const sliders=page.locator('#model input[type=range]');if(await sliders.count()){const el=sliders.first(),before=await el.inputValue();await el.focus();await el.press(Number(before)>=Number(await el.getAttribute('max'))?'ArrowLeft':'ArrowRight');assert.notEqual(await el.inputValue(),before,id+' keyboard');}
 const answers=await page.evaluate(id=>{const t=WorkshopMath.generate(id,0);const fmt=a=>Array.isArray(a)?a.map(fmt).join(';'):typeof a==='object'?WorkshopMath.fmt(a):String(a);return [...t.steps,t].map(s=>s.answerFormat==='prime-factors'?s.answer.join('*'):fmt(s.answer));},id);
 for(const [i,a] of answers.entries()){await page.locator('#answer').fill(a);await page.locator('#answer-form button').click();assert.equal(await page.locator('.feedback.error').count(),0,id+' step '+i);if(i<answers.length-1)await page.locator('[data-cmd=next]').click();}
 if((idx+1)%15===0)console.log('browser lessons',idx+1);
}
await go('lesson/v6-22','vilenkin6');const model=await page.evaluate(()=>WorkshopMath.generate('v6-22',0).model);await page.locator('#model [data-field=x]').evaluate((el,v)=>el.value=String(v),-model.x);await page.locator('#model [data-field=x]').dispatchEvent('input');await page.locator('#model [data-field=y]').evaluate((el,v)=>el.value=String(v),model.y);await page.locator('#model [data-field=y]').dispatchEvent('input');await page.locator('#model .edition-predict button').click();assert.match(await page.locator('.edition-feedback').innerText(),/Получилось/);
await page.locator('#answer').fill('мой ход');await page.locator('[data-cmd=prerequisite]').first().click();await page.locator('[data-cmd=return]').click();assert.equal(await page.locator('#answer').inputValue(),'мой ход');
await go('lesson/m9-14','makarychev9');await page.locator('[data-cmd=mode][data-value=check]').click();const answer=()=>page.evaluate(()=>{const state=JSON.parse(localStorage.getItem(WorkshopState.KEY)),t=WorkshopMath.generate(state.last.skill,state.last.seed);return String(t.answer);});await page.locator('[data-cmd=hint]').click();await page.locator('#answer').fill(await answer());await page.locator('#answer-form button').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(WorkshopState.KEY)).skills['m9-14'].checks.length),0);
await page.locator('[data-cmd=mode][data-value=check]').click();for(let i=0;i<3;i++){await page.locator('#answer').fill(await answer());await page.locator('#answer-form button').click();await page.locator('[data-cmd=next]').click();}await page.waitForFunction(()=>document.querySelector('h1')?.textContent.includes('прогресс'));assert.match(await page.locator('h1').innerText(),/прогресс/);
for(const width of [360,768,1280]){await page.setViewportSize({width,height:900});for(const id of ['v6-12','v6-22','m9-11','m9-24','m9-31']){await go('lesson/'+id,id.startsWith('v6')?'vilenkin6':'makarychev9');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),width+' '+id);}await page.screenshot({path:path.join(shots,'course-'+width+'.png'),fullPage:true});}
await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>document.body.style.zoom='2');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.evaluate(()=>document.body.style.zoom='1');
assert.equal(await page.evaluate(()=>localStorage.getItem('legacy-sentinel')),'preserve');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(WorkshopState.KEY)).skills.fraction.checks.length),1);
await page.setViewportSize({width:1280,height:900});await page.route('**/api/trainer-registry',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({schemaVersion:1,digest:'a'.repeat(64),trainers:[]})}));
await page.goto(origin+'/trainers/trainer-board.html');await page.waitForFunction(()=>document.querySelector('#pickerGroup').options.length>3);await page.locator('[data-course-picker="Виленкин · 6 класс"]').click();assert.equal(await page.locator('.picker-item').count(),45);await page.locator('#pickerSearch').fill('Симметрия');await page.locator('.picker-item').click();const frame=page.frameLocator('#trainerFrame');await frame.locator('.edition-lab').waitFor();assert.match(await frame.locator('h1').innerText(),/симметрия/i);assert.equal(await frame.locator('a[href*="trainer-board.html?trainer="]').count(),0);
await page.locator('#expandTrainer').click();await page.locator('#expandTrainer').click();await page.locator('#boardLayout').selectOption('trainer');
await page.locator('#focusBoard').click();const rect=await page.locator('#canvas').boundingBox();await page.mouse.move(rect.x+40,rect.y+40);await page.mouse.down();await page.mouse.move(rect.x+100,rect.y+90,{steps:5});await page.mouse.up();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('mathexam.trainerBoard.v1')).pages[0].strokes.length>0);const strokes=await page.evaluate(()=>JSON.parse(localStorage.getItem('mathexam.trainerBoard.v1')).pages[0].strokes);
await page.locator('[data-course-picker="Макарычев · 9 класс"]').click();await page.locator('#pickerSearch').fill('Сдвиги');await page.locator('.picker-item').click();await frame.locator('.edition-lab').waitFor();assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('mathexam.trainerBoard.v1')).pages[0].strokes),strokes);
for(const width of [360,768,1280]){await page.setViewportSize({width,height:900});await page.locator('#expandTrainer').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(shots,'board-'+width+'.png')});await page.locator('#expandTrainer').click();}
assert.deepEqual(errors,[]);console.log('PASS 75 complete lesson step flows; model construction; help vs independent; prerequisites; 360/768/1280, keyboard, zoom; board course search/open/switch, expansion and drawings retained.');
}finally{await browser.close();server.closeAllConnections();server.close();}})().catch(e=>{console.error(e);server.closeAllConnections();server.close();process.exitCode=1;});
