'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..'),shots=process.env.V5_SHOTS||'/tmp/vilenkin5-full-shots';fs.mkdirSync(shots,{recursive:true});
const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(!f.startsWith(root+path.sep))return res.writeHead(403).end();try{if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.json')?'application/json':'text/html');res.end(fs.readFileSync(f));}catch(_){res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,base=origin+'/school/index.html?course=vilenkin5';const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,headless:true,args:['--no-sandbox']});try{
const page=await browser.newPage({viewport:{width:1280,height:900}});page.setDefaultTimeout(9000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
const go=async(route)=>{await page.goto(base+'#'+route);await page.locator('h1').waitFor();};
const answerFor=()=>page.evaluate(()=>{const s=JSON.parse(localStorage.getItem(WorkshopState.KEY)),t=WorkshopMath.generate(s.last.skill,s.last.seed),fmt=a=>Array.isArray(a)?a.map(fmt).join(';'):typeof a==='object'?WorkshopMath.fmt(a):String(a);return t.answerFormat==='prime-factors'?t.answer.join('*'):fmt(t.answer);});
await go('course/vilenkin5');assert.equal(await page.locator('.v5-unit-card').count(),53);assert.equal(await page.locator('.v5-fraction-links a').count(),8);assert.equal(await page.locator('.v5-achievement.unlocked').count(),0);await page.locator('#v5-search').fill('запят');assert(await page.locator('#v5-search-results a').count()>3);
const ids=await page.evaluate(()=>WorkshopCurriculum.pathById.vilenkin5.ids);
for(const [index,id]of ids.entries()){
 await go('lesson/'+id);await page.locator('#model svg, #model table, #model .v5-place, #model .v5-equivalence').first().waitFor();assert.equal(await page.locator('.v6-worked li').count(),3,id+' theory');
 const answers=await page.evaluate(id=>{const t=WorkshopMath.generate(id,0),fmt=a=>Array.isArray(a)?a.map(fmt).join(';'):typeof a==='object'?WorkshopMath.fmt(a):String(a);return [...t.steps,t].map(s=>s.answerFormat==='prime-factors'?s.answer.join('*'):s.answerFormat==='decimal'?(Number.isInteger(typeof s.answer==='object'?s.answer.n/s.answer.d:s.answer)?(typeof s.answer==='object'?s.answer.n/s.answer.d:s.answer)+'.0':fmt(s.answer)):fmt(s.answer));},id);
 for(const [i,a]of answers.entries()){await page.locator('#answer').fill(a);await page.locator('#answer-form button').click();assert.equal(await page.locator('.feedback.error').count(),0,id+' step '+i);if(i<answers.length-1)await page.locator('[data-cmd=next]').click();}
 if((index+1)%30===0)console.log('V5 guided flows',index+1);
}
async function change(key,value){await page.locator('[data-param='+key+']').fill(String(value));await page.locator('[data-param='+key+']').dispatchEvent('change');}
await go('lesson/v5f-fraction-add');await page.locator('[data-param=partition]').fill('5');await page.locator('[data-action=partition]').click();assert.match(await page.locator('.v5-feedback').innerText(),/оба знаменателя/);await page.locator('[data-param=partition]').fill('12');await page.locator('[data-action=partition]').click();await page.locator('[data-action=combine]').click();await page.getByLabel('Ответ в лаборатории').fill('11/12');await page.locator('.v5-lab-form button').click();assert.match(await page.locator('.v5-feedback').innerText(),/Верно/);
await change('an',1);await change('ad',2);await change('bn',1);await change('bd',2);await page.locator('[data-action=mission-check]').click();assert.match(await page.locator('.v5-feedback').innerText(),/Миссия выполнена/);
await go('lesson/v5f-fraction-multiply');await page.locator('[data-action=combine]').click();await page.locator('[data-action=mission-check]').click();assert.match(await page.locator('.v5-feedback').innerText(),/Миссия выполнена/);
await go('lesson/v5f-fraction-divide');await change('an',1);await change('ad',2);await change('bn',3);await change('bd',4);await page.locator('[data-action=portion]').click();assert.match(await page.locator('.v5-feedback').innerText(),/не помещается/);await page.locator('[data-action=partial]').click();await page.getByLabel('Ответ в лаборатории').fill('2/3');await page.locator('.v5-lab-form button').click();assert.match(await page.locator('.v5-feedback').innerText(),/Верно/);
await go('lesson/v5f-decimal-borrow');await page.locator('[data-action=exchange-whole]').click();await page.locator('[data-action=exchange-tenth]').click();assert.deepEqual(await page.locator('tbody tr').last().locator('td').allTextContents(),['Первое после разменов (3)','2','9','10']);await page.getByLabel('Ответ в лаборатории').fill('2,52');await page.locator('.v5-lab-form button').click();assert.match(await page.locator('.v5-feedback').innerText(),/Верно/);
await go('lesson/v5f-decimal-divide');await change('factor',100);assert.match(await page.locator('.v5-equivalence').innerText(),/150 : 25/);await page.getByLabel('Ответ в лаборатории').fill('6');await page.locator('.v5-lab-form button').click();assert.match(await page.locator('.v5-feedback').innerText(),/Верно/);
await go('lesson/v5f-angle-build');await page.locator('[data-param=angle]').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('[data-param=angle]').inputValue(),'31');await page.keyboard.press('ArrowRight');assert.equal(await page.locator('[data-param=angle]').inputValue(),'32');
// Sixth -> fifth -> same original step and draft. Assistance must not count as independence.
await page.goto(origin+'/school/index.html?course=vilenkin6#lesson/v6f-fraction-add');await page.locator('#answer').fill('мой ход');await page.locator('[data-cmd=prerequisite][data-value=v5f-fraction-add]').click();assert.match(await page.locator('h1').innerText(),/дроб/);await page.locator('[data-cmd=return]').click();assert.equal(await page.locator('#answer').inputValue(),'мой ход');assert.match(page.url(),/v6f-fraction-add/);
await go('lesson/v5f-decimal-add');await page.locator('[data-cmd=hint]').click();await page.locator('[data-cmd=hint]').click();assert.match(await page.locator('#help').innerText(),/Подсказка 2 из 3/);
await page.locator('[data-cmd=mode][data-value=check]').click();for(let i=0;i<3;i++){await page.locator('#answer').fill(await answerFor());await page.locator('#answer-form button').click();assert.equal(await page.locator('.feedback.error').count(),0);await page.locator('[data-cmd=next]').click();}
await go('course/vilenkin5');assert.equal(await page.locator('.v5-achievement.unlocked').count(),1);
// A sentinel and older V6 record survive navigation and reload.
await page.evaluate(()=>{localStorage.setItem('v5-sentinel','keep');const state=JSON.parse(localStorage.getItem(WorkshopState.KEY));WorkshopState.result(state,{skill:'v6f-fraction-add',mode:'check',correct:true,attempt:1,assisted:false,exposed:false,time:1,fingerprint:'v6-previous'});WorkshopState.save(localStorage,state);});await page.reload();await page.locator('h1').waitFor();await go('lesson/v5f-fraction-subtract');
for(const width of [360,768,1280]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(shots,'fraction-'+width+'.png'),fullPage:true});}
await page.setViewportSize({width:360,height:900});await go('lesson/v5f-decimal-borrow');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(shots,'decimal-360.png'),fullPage:true});await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>document.body.style.zoom='2');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.evaluate(()=>document.body.style.zoom='1');assert.equal(await page.evaluate(()=>localStorage.getItem('v5-sentinel')),'keep');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(WorkshopState.KEY)).skills['v6f-fraction-add'].checks.length),1);
await page.route('**/api/trainer-registry',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({schemaVersion:1,digest:'a'.repeat(64),trainers:[]})}));await page.goto(origin+'/trainers/trainer-board.html?trainer='+encodeURIComponent('/school/index.html?course=vilenkin5#lesson/v5f-fraction-divide'));await page.frameLocator('#trainerFrame').locator('.v5-lab').waitFor();assert.equal(await page.frameLocator('#trainerFrame').locator('a[href*="trainer-board.html?trainer="]').count(),0);
await page.waitForFunction(()=>document.querySelector('#pickerGroup').options.length>3);await page.locator('#chooseTrainer').click();await page.locator('[data-course-picker="Виленкин · 5 класс"]').click();assert.equal(await page.locator('.picker-item').count(),60);assert.match(await page.locator('#pickerCount').innerText(),/135/);await page.locator('#pickerMore').click();assert.equal(await page.locator('.picker-item').count(),120);await page.locator('#pickerSearch').fill('Убираем запятую');await page.locator('.picker-item').click();await page.frameLocator('#trainerFrame').locator('.v5-lab').waitFor();assert.match(await page.frameLocator('#trainerFrame').locator('h1').innerText(),/Убираем запятую/);
assert.deepEqual(errors,[]);console.log('PASS V5 real Chromium: 134 guided flows, fraction missions and partition, fractional portions, decimal exchange and rescaling, keyboard, sixth/fifth return, hints and honest achievement, old progress, mobile/zoom, board iframe.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
