(function(root){
'use strict';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=(x,y,s)=>`<text x="${x}" y="${y}" text-anchor="middle">${esc(s)}</text>`;
const line=(x,y,X,Y,color='#315d65',dash='')=>`<line x1="${x}" y1="${y}" x2="${X}" y2="${Y}" stroke="${color}" stroke-width="2" ${dash?'stroke-dasharray="6 5"':''}/>`;
const dot=(x,y,label,color='#e69e5a')=>`<circle cx="${x}" cy="${y}" r="7" fill="${color}"/>`+text(x,y-14,label);
function spec(m){
 if(m.family==='coordinates')return [{key:'x',label:'Координата x точки B',min:-12,max:12,value:0},{key:'y',label:'Координата y точки B',min:-12,max:12,value:0}];
 if(m.family==='lines')return [{key:'angle',label:'Направление подвижной прямой, градусы',min:0,max:180,value:70}];
 if(['region','plane'].includes(m.family))return [{key:'x',label:'Координата x пробной точки',min:-10,max:10,value:m.x||0},{key:'y',label:'Координата y пробной точки',min:-10,max:10,value:m.y||0}];
 if(m.family==='factors')return [{key:'divisor',label:'Пробный делитель',min:2,max:20,value:2}];
 if(m.family==='sequence')return [{key:'n',label:'Число показанных членов',min:1,max:8,value:4}];
 if(m.family==='induction')return [{key:'n',label:'Сторона квадрата',min:1,max:8,value:3}];
 if(m.family==='packages')return [{key:'n',label:'Число упаковок',min:0,max:12,value:1}];
 if(m.family==='balance')return [{key:'move',label:'Прибавить к обеим частям',min:-15,max:15,value:0}];
 if(m.family==='parabola'||m.family==='hyperbola')return [{key:'h',label:'Горизонтальный сдвиг h',min:-6,max:6,value:Math.max(-6,Math.min(6,m.h))},{key:'x',label:'Пробное значение x',min:-8,max:8,value:0}];
 if(m.family==='approx')return [{key:'delta',label:'Допустимая абсолютная погрешность',min:0,max:10,value:m.b}];
 if(m.family==='journey')return [{key:'t',label:'Время наблюдения',min:0,max:m.points[m.points.length-1][0],step:.5,value:1}];
 return [{key:'x',label:'Пробное значение x',min:-10,max:10,value:1}];
}
function investigate(m,p){
 let body='',caption='',question='',target,construct=false;
 const range=15,X=x=>280+x*13,Y=y=>170-y*13;
 const axes=()=>{let s='';for(let i=-10;i<=10;i+=2){s+=line(X(i),Y(-10),X(i),Y(10),'#dce9e8')+line(X(-10),Y(i),X(10),Y(i),'#dce9e8');if(i)s+=text(X(i),Y(0)+18,i);}return s+line(X(-11),Y(0),X(11),Y(0))+line(X(0),Y(-11),X(0),Y(11))+text(X(11),Y(0)-8,'x')+text(X(0)+12,Y(11),'y');};
 const graph=(f,color='#137f76')=>{let s='',segment=[];function flush(){if(segment.length>1)s+=`<polyline fill="none" stroke="${color}" stroke-width="3" points="${segment.join(' ')}"/>`;segment=[];}for(let i=-200;i<=200;i++){let x=i/20,y=f(x);if(!Number.isFinite(y)||Math.abs(y)>11){flush();continue;}segment.push(X(x)+','+Y(y));}flush();return s;};
 const v=p.x||0;
 switch(m.family){
 case 'coordinates':{body=axes()+dot(X(m.x),Y(m.y),'A')+dot(X(p.x),Y(p.y),'B','#137f76');let t;if(m.reflect!==undefined){t=m.reflect===0?[-m.x,m.y]:m.reflect===1?[m.x,-m.y]:[-m.x,-m.y];caption='Построй отражение A относительно '+['оси y','оси x','начала координат'][m.reflect]+'.';}else{t=[m.x+m.dx,m.y+m.dy];caption=`Перемести A на ${m.dx} вправо и ${-m.dy} вниз.`;}question='Передвинь B ползунками, стрелками или перетаскиванием на сетке и проверь построение.';target=t;construct=true;break;}
 case 'lines':{const draw=(angle,color)=>{let r=angle*Math.PI/180;return line(280-130*Math.cos(r),170+130*Math.sin(r),280+130*Math.cos(r),170-130*Math.sin(r),color);};body=draw(35,'#e69e5a')+draw(p.angle,'#137f76')+text(280,310,`Оранжевая: 35° · Зелёная: ${p.angle}°`);caption=m.parallel?'Направления параллельных прямых совпадают. На чертеже они наложатся; для разных прямых нужен ещё сдвиг.':'Построй прямую, перпендикулярную оранжевой. Разность направлений должна быть 90°.';question=m.parallel?'Выбери направление параллельной прямой.':'Поверни зелёную прямую до прямого угла.';target=m.parallel?35:125;construct=true;break;}
 case 'factors':{const d=p.divisor,whole=Math.floor(m.value/d),rem=m.value%d;body=text(280,90,`${m.value} = ${d} · ${whole} + ${rem}`);for(let i=0;i<Math.min(d,20);i++)body+=`<rect x="${45+i*23}" y="135" width="19" height="50" fill="#78bfb2"/>`;body+=text(280,230,`Полных групп: ${whole} · Остаток: ${rem}`);caption='Меняй делитель. Делитель числа — тот, при котором остаток равен нулю. Затем ищи простые делители.';question=`Делится ли ${m.value} на ${d} без остатка? Да или нет.`;target=rem===0?'да':'нет';break;}
 case 'balance':{const a=m.a,b=m.b,x=m.x,left=a*x+b+p.move,right=a*x+b+p.move;body=line(95,210,465,210)+`<path d="M260 280 L280 210 L300 280 Z" fill="#88beb7"/>`+text(160,140,`${a}x ${b>=0?'+':''}${b} ${p.move>=0?'+':''}${p.move}`)+text(400,140,`${a*x+b} ${p.move>=0?'+':''}${p.move}`)+text(280,65,'Одинаковое действие сохраняет равенство')+text(280,315,`Для x=${x}: ${left} = ${right}`);caption='Подбери одно действие для обеих чаш, чтобы свободный член слева исчез. Значение x при этом не меняется.';question='Сколько нужно прибавить к обеим частям?';target=-b;break;}
 case 'sequence':{const values=Array.from({length:p.n},(_,i)=>m.geometric?m.start*m.ratio**i:m.start+i*m.diff),max=Math.max(1,...values.map(Math.abs));values.forEach((y,i)=>{const h=Math.abs(y)/max*95;body+=`<rect x="${40+i*62}" y="${y>=0?170-h:170}" width="40" height="${Math.max(1,h)}" fill="${i===p.n-1?'#e69e5a':'#77beb0'}"/>`+text(60+i*62,300,i+1)+text(60+i*62,y>=0?160-h:185+h,y);});body+=line(35,170,535,170);caption=m.geometric?`Первый член ${m.start}, множитель q=${m.ratio}.`:`Первый член ${m.start}, разность d=${m.diff}.`;question=m.sum?'Найди сумму показанных членов.':'Каким будет следующий член?';target=m.sum?values.reduce((a,b)=>a+b,0):m.geometric?values.at(-1)*m.ratio:values.at(-1)+m.diff;break;}
 case 'induction':{const n=p.n,s=24;for(let i=0;i<n;i++)for(let j=0;j<n;j++)body+=`<rect x="${170+i*s}" y="${50+j*s}" width="22" height="22" fill="${i===n-1||j===n-1?'#e69e5a':'#78bfb2'}"/>`;caption=`К квадрату (${n-1})² добавили L-образную рамку. Получился квадрат ${n}².`;question='Сколько клеток в оранжевой рамке?';target=2*n-1;break;}
 case 'packages':{const total=p.n*m.b;body=text(280,80,`Нужно ${m.a} м²`) +text(280,125,`${p.n} упаковок покрывают ${total} м²`);for(let i=0;i<p.n;i++)body+=`<rect x="${35+i*42}" y="180" width="36" height="45" fill="${total>=m.a?'#78bfb2':'#e69e5a'}"/>`;caption='Упаковки неделимы. Найди первое целое число упаковок, при котором покрытия достаточно.';question='Минимальное число упаковок?';target=Math.ceil(m.a/m.b);break;}
 case 'approx':{const center=m.a,delta=p.delta;body=line(50,170,510,170)+line(130,160,430,160,'#137f76')+dot(130,170,center-delta)+dot(430,170,center+delta)+dot(280,170,center,'#137f76');caption=`Приближение ${center} с допустимой ошибкой ${delta}: точное значение лежит в [${center-delta}; ${center+delta}]. При δ=0 интервал превращается в точку (схематически показаны его концы).`;question='Какова длина допустимого интервала?';target=2*delta;break;}
 case 'journey':{const pts=m.points,maxT=pts.at(-1)[0],maxY=Math.max(...pts.map(z=>z[1])),tx=t=>50+t/maxT*460,yy=y=>280-y/Math.max(1,maxY)*220;body=line(50,280,520,280)+line(50,280,50,45);let points=pts.map(z=>tx(z[0])+','+yy(z[1])).join(' ');body+=`<polyline points="${points}" fill="none" stroke="#137f76" stroke-width="3"/>`;pts.forEach(z=>{body+=text(tx(z[0]),303,z[0])+text(tx(z[0]),yy(z[1])-12,z[1]);});let i=Math.max(1,pts.findIndex(z=>z[0]>=p.t));if(i===0)i=1;if(p.t>=maxT)i=pts.length-1;const before=pts[i-1],after=pts[i],y=before[1]+(after[1]-before[1])*(p.t-before[0])/(after[0]-before[0]);body+=dot(tx(p.t),yy(y),'');caption='По горизонтали — время, по вертикали — пройденный путь. Перемещай точку по графику.';question='Какой путь соответствует выбранному времени?';target=y;break;}
 case 'radical':{body=line(50,180,510,180);let a=Math.floor(Math.sqrt(m.rad)),lo=a*a,hi=(a+1)**2;body+=dot(130,180,a)+dot(430,180,a+1)+dot(130+(Math.sqrt(m.rad)-a)*300,180,'√'+m.rad,'#137f76')+text(280,270,`${lo} ≤ ${m.rad} < ${hi}`);caption='Квадраты соседних целых чисел ограничивают корень между ними.';question=`Наибольшее целое, не превосходящее √${m.rad}?`;target=a;break;}
 case 'powers':{const e=m.b+v;body=text(280,110,`${m.a} · 10^${e}`)+text(280,180,(m.a*10**e).toPrecision(6));caption='Увеличение показателя на 1 увеличивает значение в 10 раз. Отрицательный показатель означает деление.';question='Во сколько раз изменится значение при увеличении показателя на 2?';target=100;break;}
 case 'parity':{const f=x=>m.v===0?m.a*x*x+m.b:m.v===1?m.a*x*x*x-m.b*x:m.a*x*x+m.b*x;body=axes()+graph(f)+(Math.abs(f(v))<=10?dot(X(v),Y(f(v)),'x'):'')+(Math.abs(f(-v))<=10?dot(X(-v),Y(f(-v)),'−x','#137f76'):'');caption='Точки могут выходить за видимое окно. Сравни f(x) и f(−x): симметрию нужно обосновать формулой для всех x.';question=`Чему равно f(−${v})?`;target=f(-v);break;}
 case 'parabola':case 'hyperbola':{const hyper=m.family==='hyperbola',f=x=>hyper?m.a/(x-p.h)+m.k:m.a*(x-p.h)**2+m.k;body=axes()+graph(f);if(hyper)body+=line(X(p.h),Y(-10),X(p.h),Y(10),'#e69e5a',true)+line(X(-10),Y(m.k),X(10),Y(m.k),'#e69e5a',true);else body+=dot(X(p.h),Y(m.k),'Вершина');caption=hyper?`y=${m.a}/(x−(${p.h}))+${m.k}. Пунктир — асимптоты.`:`y=${m.a}(x−(${p.h}))²+${m.k}. Меняй h и следи за вершиной.`;question=`Чему равно y при x=${v}? При запрещённом x введи нет.`;target=hyper&&v===p.h?'нет':f(v);break;}
 case 'functions':{const f=x=>m.v===0?Math.abs(x-m.a)+m.b:m.v===1?Math.sqrt(x-m.a)+m.b:m.b/(x-m.a);body=axes()+graph(f);caption='Исследуй, для каких x формула имеет смысл. Отсутствие точки за пределами окна не равно отсутствию значения.';question=`Допустим ли x=${v}? Да или нет.`;target=(m.v===1?v>=m.a:m.v===2?v!==m.a:true)?'да':'нет';break;}
 case 'zeros':{body=axes()+graph(x=>m.roots.reduce((p,r)=>p*(x-r),1)/20);m.roots.forEach(r=>body+=dot(X(r),Y(0),r));caption='График произведения масштабирован по вертикали в 20 раз. Его нули остались на месте.';question='Сколько различных корней видно в полном списке: '+m.roots.join(', ')+'?';target=m.roots.length;break;}
 case 'hole':{body=axes()+graph(x=>x+m.h)+`<circle cx="${X(m.h)}" cy="${Y(2*m.h)}" r="7" fill="white" stroke="#c75544" stroke-width="3"/>`;caption=`После сокращения график прямой, но x=${m.h} исключён. Пустая точка сохраняет ограничение исходной дроби.`;question=`Можно ли подставить x=${v}? Да или нет.`;target=v===m.h?'нет':'да';break;}
 case 'interval':{body=axes()+graph(x=>m.den?(x-m.lo)/(x-m.hi):(x-m.lo)*(x-m.hi)/5);const z=m.den?(v-m.lo)/(v-m.hi):(v-m.lo)*(v-m.hi);caption=`Проверь знак ${m.den?'дроби':'произведения'} на каждом промежутке. ${m.den?'Правая граница запрещена.':'График по вертикали уменьшен в 5 раз.'}`;question=`Подходит ли x=${v} для ${m.strict?'<':'≤'}0? Да или нет.`;target=Number.isFinite(z)&&(m.strict?z<0:z<=0)?'да':'нет';break;}
 case 'intersection':{body=axes()+graph(x=>x*x)+graph(x=>(m.p+m.r)*x-m.p*m.r,'#e69e5a');caption=`Общие точки y=x² и y=${m.p+m.r}x−${m.p*m.r}. Некоторые точки могут быть вне окна.`;question=`При x=${v} совпадают значения двух функций? Да или нет.`;target=v*v===(m.p+m.r)*v-m.p*m.r?'да':'нет';break;}
 case 'system-lines':{body=axes()+graph(x=>(m.c-m.a*x)/m.b)+graph(x=>m.v===0?(m.c-m.a*x)/m.b:m.v===1?(2*m.c+1-2*m.a*x)/(2*m.b):(2*m.c-(2*m.a+1)*x)/(2*m.b),'#e69e5a');caption='Совпадающие, параллельные или пересекающиеся прямые дают разное число решений.';question='Сколько решений: одно, нет или бесконечно много?';target=['бесконечно много','нет','одно'][m.v];break;}
 case 'plane':case 'region':{body=axes();let inside;for(let ix=-20;ix<=20;ix++)for(let iy=-20;iy<=20;iy++){let x=ix/2,y=iy/2,ok=m.family==='plane'?x*x+y*y<=m.r2:y>=x+m.a&&(!m.system||x*x+y*y<=m.r*m.r);if(ok)body+=`<rect x="${X(x)-3}" y="${Y(y)-3}" width="6" height="6" fill="#7fbeb2" opacity=".65"/>`;}
  if(m.family==='plane'){body+=`<ellipse cx="280" cy="170" rx="${Math.sqrt(m.r2)*13}" ry="${Math.sqrt(m.r2)*13}" fill="none" stroke="#137f76" stroke-width="2"/>`;inside=Math.abs(p.x*p.x+p.y*p.y-m.r2)<1e-9;caption='Заливка помогает видеть круг; уравнению окружности соответствует только граница.';}else{body+=graph(x=>x+m.a);inside=p.y>=p.x+m.a&&(!m.system||p.x*p.x+p.y*p.y<=m.r*m.r);caption=m.system?'Оставлена общая часть круга и полуплоскости. Все границы включены.':'Закрашено y≥x+a; прямая тоже входит.';}body+=dot(X(p.x),Y(p.y),`(${p.x};${p.y})`);question='Удовлетворяет ли выбранная точка исходному условию? Да или нет.';target=inside?'да':'нет';break;}
 default:throw Error('Unknown edition model '+m.family);
 }
 return {svg:`<svg viewBox="0 0 560 340" role="img" aria-label="${esc(caption)}">${body}</svg>`,caption,question,target,construct};
}
function install(Models,M){const old=Models.mount;Models.mount=(el,m)=>{
 if(!m||m.kind!=='edition')return old(el,m);
 const fields=spec(m),p=Object.fromEntries(fields.map(f=>[f.key,f.value]));
 el.innerHTML='<section class="edition-lab"><p class="eyebrow">Математическая мастерская</p><h2>Измени → проверь → объясни</h2><p class="tiny">Исследование помогает понять способ. Самостоятельные результаты записываются отдельно в режиме проверки.</p><div class="edition-controls">'+fields.map(f=>`<label>${esc(f.label)} <output data-output="${f.key}">${f.value}</output><span><button type="button" data-shift="-1" data-key="${f.key}" aria-label="Уменьшить: ${esc(f.label)}">−</button><input type="range" aria-label="${esc(f.label)}" data-field="${f.key}" min="${f.min}" max="${f.max}" step="${f.step||1}" value="${f.value}"><button type="button" data-shift="1" data-key="${f.key}" aria-label="Увеличить: ${esc(f.label)}">+</button></span></label>`).join('')+'</div><div class="edition-drawing"></div><p class="edition-caption"></p><form class="edition-predict"><label class="edition-question"></label><div class="answer-line"><input aria-label="Ответ в модели" autocomplete="off"><button>Проверить опыт</button></div></form><p class="edition-feedback" role="status"></p><button class="quiet edition-reset" type="button">Вернуть исходную модель</button></section>';
 const feedback=el.querySelector('.edition-feedback'),drawing=el.querySelector('.edition-drawing');let result;
 function render(){result=investigate(m,p);drawing.innerHTML=result.svg;el.querySelector('.edition-caption').textContent=result.caption;el.querySelector('.edition-question').textContent=result.question;el.querySelector('.edition-predict input').hidden=result.construct;for(const f of fields){el.querySelector(`[data-field="${f.key}"]`).value=p[f.key];el.querySelector(`[data-output="${f.key}"]`).textContent=p[f.key];}feedback.textContent='';}
 for(const input of el.querySelectorAll('[data-field]'))input.oninput=()=>{p[input.dataset.field]=Number(input.value);render();};
 for(const b of el.querySelectorAll('[data-shift]'))b.onclick=()=>{const f=fields.find(f=>f.key===b.dataset.key);p[f.key]=Math.max(f.min,Math.min(f.max,p[f.key]+Number(b.dataset.shift)*(f.step||1)));render();};
 el.querySelector('.edition-reset').onclick=()=>{fields.forEach(f=>p[f.key]=f.value);render();};
 el.querySelector('form').onsubmit=e=>{e.preventDefault();const actual=result.construct?(m.family==='lines'?p.angle:[p.x,p.y]):el.querySelector('form input').value,ok=result.construct?JSON.stringify(actual)===JSON.stringify(result.target):M.equal(actual,result.target);feedback.textContent=ok?'Получилось. Объясни, почему это верно, затем измени данные и предскажи новый результат.':'Пока не совпало. Проверь направление, знак, границу или выбранную точку.';};
 if(m.family==='coordinates'||m.family==='region'||m.family==='plane'){let dragging=false;const move=e=>{const svg=drawing.querySelector('svg'),r=svg.getBoundingClientRect(),scale=Math.min(r.width/560,r.height/340),ox=r.left+(r.width-560*scale)/2,oy=r.top+(r.height-340*scale)/2;const f=fields[0],g=fields[1];p.x=Math.max(f.min,Math.min(f.max,Math.round(((e.clientX-ox)/scale-280)/13)));p.y=Math.max(g.min,Math.min(g.max,Math.round((170-(e.clientY-oy)/scale)/13)));render();};drawing.style.touchAction='none';drawing.onpointerdown=e=>{dragging=true;drawing.setPointerCapture(e.pointerId);move(e);};drawing.onpointermove=e=>{if(dragging)move(e);};drawing.onpointerup=drawing.onpointercancel=()=>dragging=false;}
 render();
 };}
const API={spec,investigate,install};if(typeof module!=='undefined'&&module.exports)module.exports=API;else install(root.WorkshopModels,root.WorkshopMath);
})(typeof window!=='undefined'?window:globalThis);
