(function(root){
'use strict';
function install(C){
 const stage=(title,ids)=>({title,ids:typeof ids==='string'?ids.split(' '):ids});
 C.paths=[
 {id:'foundation',title:'Основы 1–6 классов',about:'Восстановить смысл действий, уверенно работать со знаками, дробями и процентами.',stages:[stage('Число и действия','place compare add subtract multiply divide remainder order units'),stage('Доли и дроби','fraction fractioncompare fractionadd mixed reduce common unlike fractionmul fractiondiv'),stage('Десятичные дроби','decimal decimalcompare decimaladd decimalmul decimaldiv'),stage('Отношения и знаки','part whole ratio proportion percent percentwhole percentchange signed absolute signedsub signedmul signeddiv')],diagnostic:'add divide fraction unlike decimaldiv percent signed equation'},
 {id:'5',title:'Математика · 5 класс',about:'Числа, измерения, дроби, первые уравнения. Общая основа маршрутов Виленкина, Мерзляка и Петерсон; точный порядок зависит от издания.',stages:[stage('Учебная последовательность',C.grade5)],diagnostic:'place add divide fraction decimal segment area motion'},
 {id:'6',title:'Математика · 6 класс',about:'Делимость, отношения, дроби и рациональные числа. Укрепить основу перед алгеброй.',stages:[stage('Учебная последовательность',C.grade6)],diagnostic:'divisibility unlike decimaldiv percent signed equation area ratio'},
 {id:'7',title:'Алгебра · 7 класс',about:'От буквенного выражения к уравнениям, функциям, многочленам и системам.',stages:[stage('Язык алгебры','alg-rational alg-order alg-variable alg-compare alg-properties alg-identity core-brackets'),stage('Уравнение и модель','sec-linear sec-line core-work core-mixture'),stage('Многочлены','sec-powers sec-polynomial core-factor sec-square sec-difference core-grouping core-cubes'),stage('Системы','sec-system core-substitution core-elimination')],diagnostic:'signed fractiondiv alg-order alg-properties sec-linear sec-line sec-powers sec-system'},
 {id:'8',title:'Алгебра · 8 класс',about:'Дробные выражения и ограничения, корни, квадратные уравнения и первые неравенства.',stages:[stage('Алгебраические дроби','sec-domain sec-rational core-fraction-reduce core-fraction-add core-fraction-divide core-rational-equation'),stage('Корни','sec-root core-radical-extract core-radical-product core-radical-equation'),stage('Квадратные уравнения','sec-quadratic core-viete core-quadratic-general'),stage('Неравенства','sec-inequality core-inequality-system')],diagnostic:'core-factor sec-domain sec-rational sec-root sec-quadratic sec-inequality sec-line core-substitution'},
 {id:'9',title:'Алгебра · 9 класс',about:'Функции, метод интервалов, модуль, нелинейные системы и прогрессии.',stages:[stage('Функции','sec-parabola core-transform core-inverse'),stage('Знаки и расстояния','sec-intervals core-quadratic-inequality core-rational-inequality core-absolute-equation core-absolute-inequality'),stage('Системы и последовательности','core-nonlinear-system sec-arithmetic sec-geometric core-sequence')],diagnostic:'core-quadratic-general sec-inequality core-fraction-reduce sec-parabola core-absolute-equation core-substitution sec-arithmetic sec-geometric'},
 {id:'10',title:'Алгебра и начала анализа · 10 класс',about:'Степени, показательная и логарифмическая функции, окружность и тригонометрия. Распределение тем по классам зависит от учебника.',stages:[stage('Степени и рост','core-power-domain sec-exponential core-exp-equation core-exp-inequality'),stage('Логарифмы','sec-logarithm core-log-domain core-log-equation'),stage('Тригонометрия','sec-circle core-trig-identity core-trig-equation core-trig-graph')],diagnostic:'sec-powers sec-root sec-line core-power-domain sec-exponential sec-logarithm sec-circle sec-quadratic'},
 {id:'11',title:'Алгебра и начала анализа · 11 класс',about:'Логарифмические неравенства, производная, экстремумы и смысл интеграла. Это школьное углубление, а не обязательное ядро базового ЕГЭ.',stages:[stage('Повторение функций','core-exp-inequality core-log-domain core-log-equation core-log-inequality core-trig-graph'),stage('Изменение и накопление','sec-derivative core-derivative-rule core-extrema core-integral')],diagnostic:'sec-parabola core-transform core-log-domain core-exp-inequality core-log-equation sec-circle sec-derivative sec-inequality'},
 {id:'probability',title:'Вероятность и статистика · 7–11',about:'От таблицы исходов и наблюдаемой частоты до условной вероятности, ожидания и разброса.',stages:[stage('Данные и первые модели','chart piechart average sec-statistics core-frequency core-chart core-weighted'),stage('Считаем исходы','sets probability sec-outcomes core-product-rule core-permutations core-combinations'),stage('События','core-union sec-conditional core-independence'),stage('Старшая школа','core-binomial sec-expectation core-variance')],diagnostic:'fraction percent average probability sec-statistics sec-outcomes core-product-rule sec-conditional'}
 ];
 C.paths.forEach(p=>{p.ids=[...new Set(p.stages.flatMap(s=>s.ids))];p.diagnostic=p.diagnostic.split(' ');});
 C.pathById=Object.assign(Object.create(null),Object.fromEntries(C.paths.map(p=>[p.id,p])));
}
if(typeof module!=='undefined'&&module.exports)module.exports={install};else install(root.WorkshopCurriculum);
})(typeof window!=='undefined'?window:globalThis);
