(function(root){
'use strict';
const normalize=s=>String(s).trim().toLowerCase().replace(/ё/g,'е').replace(/−/g,'-').replace(/\s+/g,' ');
function generate(id,seed,M){
 const key=id.replace(/^v6f-/,''),R=M.rng(seed*7919+Array.from(key).reduce((s,c)=>s+c.charCodeAt(0)*37,1367)),pick=xs=>xs[R(0,xs.length-1)];
 const a=R(2,9),b=R(2,8),c=R(2,6),v=seed%3,q=M.q,F=M.fmt,add=M.add,sub=M.sub,mul=M.mul,div=M.div,N=x=>typeof x==='object'?x.n/x.d:x;
 const signed=x=>N(x)<0?'− '+F(mul(x,-1)):'+ '+F(x),D=x=>{const z=typeof x==='object'?x:q(x);return z.d===1?F(z):String(z.n/z.d).replace('.',',');};
 let prompt='',answer,format='',model={kind:'v6full'},data={key,a,b,c,v},steps=[],errors=[],alternatives=[];
 function S(p,z,why,method,wrong){steps.push({prompt:p,answer:z,why,hints:[why,method||p],errors:wrong||[],v6Full:true});}
 function T(p,z,family,raw){prompt=p;answer=z;model.family=family;Object.assign(data,raw||{});}
 function E(z,text,remedy){errors.push({value:z,text,remedy:remedy?'v6f-'+remedy:''});}
 function Q(p,z,why,method){S(p,z,why,method);}
 function fractionPair(){const den=pick([4,6,8,10,12]),n1=R(1,den-1),n2=R(1,den-1);return {u:q(n1,den),w:q(n2,den+pick([2,4,6]))};}
 switch(key){
 case 'mean-share':case 'mean-calculate':case 'mean-missing':case 'mean-weighted':{
  const values=key==='mean-calculate'?[a,a+b,a+c,a+b+c+1]:[a,a+b,a+2*b],sum=values.reduce((s,x)=>s+x,0),mean=q(sum,values.length);data.values=values;
  if(key==='mean-missing'){T(`Среднее ${values.length} чисел равно ${F(mean)}. Известны ${values.slice(0,-1).join(' и ')}. Найди пропущенное число.`,values.at(-1),'mean',{sum,mean});S('Какова сумма всех чисел?',sum,'Среднее умножаем на количество.',`${F(mean)} · ${values.length}`);S('Какова сумма известных чисел?',sum-values.at(-1),'Учитываем только перечисленные числа.');}
  else if(key==='mean-weighted'){const n1=b,n2=b+1,m1=a+4,m2=a;T(`В первой группе ${n1} измерений со средним ${m1}, во второй ${n2} измерений со средним ${m2}. Найди среднее всех измерений.`,q(n1*m1+n2*m2,n1+n2),'mean',{n1,n2,m1,m2,values:[...Array(n1).fill(m1),...Array(n2).fill(m2)]});S('Сумма результатов первой группы?',n1*m1,'Среднее группы умножаем на её размер.');S('Сумма результатов второй группы?',n2*m2,'Во второй группе другое число измерений.');S('Сколько всего измерений?',n1+n2,'Числа измерений складываются.');E(q(m1+m2,2),'Ты усреднил два средних без учёта размеров групп. Восстанови обе суммы.','mean-calculate');}
  else{T(key==='mean-share'?`В коробках ${values.join(', ')} карандашей. Их переложили так, чтобы стало поровну. Сколько будет в каждой?`:`Найди среднее чисел ${values.join('; ')}.`,mean,'mean',{sum,mean});S('Сколько всего?',sum,'Перераспределение не меняет общую сумму.');S('На сколько равных групп делим?',values.length,'Считаем все коробки или измерения.');E(sum,'Это общая сумма. Теперь раздели её на число значений.','mean-share');}break;
 }
 case 'percent-meaning':case 'percent-convert':case 'percent-common':case 'percent-part':case 'percent-small':case 'percent-whole':case 'percent-ratio':case 'percent-discount':case 'percent-increase':case 'percent-reverse':case 'percent-chain':{
  const total=a*200,p=key==='percent-small'?pick([q(1,2),q(3,2),q(5,2),125,150,175]):pick([10,15,20,25,30,40,60,75]),part=mul(total,div(p,100));data.total=total;data.percent=p;data.part=part;
  if(key==='percent-meaning'){T(`Весь запас — ${total} листов. Сколько листов составляет 1% запаса?`,total/100,'percent');S('Какое количество принято за 100%?',total,'Весь запас — целое.');S('На сколько одинаковых частей делим целое?',100,'Процент означает одну сотую.');}
  else if(key==='percent-convert'){const percent=pick([q(1,2),q(5,2),12,25,75,120,175]);data.percent=percent;data.direction=v%2;T(v%2?`Запиши ${F(div(percent,100))} в процентах. Введи число без знака %.`:`Запиши ${F(percent)}% в виде числа или обыкновенной дроби.`,v%2?percent:div(percent,100),'percent');S(v%2?'На какое число умножаем долю?':'На какое число делим проценты?',100,'Один процент — одна сотая.');S('Сколько процентов составляет всё целое?',100,'Ориентир 1 = 100%.');}
  else if(key==='percent-whole'){T(`${F(p)}% запаса составляют ${F(part)} л. Сколько литров во всём запасе?`,total,'percent');S('Сколько литров приходится на 1%?',total/100,'Часть делим на известный процент.',`${F(part)} : ${F(p)}`);S('На сколько умножить найденный 1%, чтобы получить всё целое?',100,'В целом сто процентов.');E(mul(part,div(p,100)),'Ты нашёл процент от уже известной части. Здесь нужно восстановить целое.','percent-part');}
  else if(key==='percent-ratio'){T(`Из ${total} семян взошло ${F(part)}. Сколько процентов семян взошло?`,p,'percent');S('Какое число стоит в знаменателе отношения?',total,'В знаменателе целое, принятое за 100%.');S('Какую долю составляют взошедшие семена?',div(part,total),'Часть делим на целое.');E(div(part,total),'Это доля, а требуется число процентов. Умножь на 100.','percent-convert');}
  else if(key==='percent-discount'||key==='percent-increase'){const up=key==='percent-increase',remain=add(100,mul(p,up?1:-1));T(`Цена ${total} рублей ${up?'выросла':'снизилась'} на ${F(p)}%. Найди новую цену.`,mul(total,div(remain,100)),'percent',{up});S(`Сколько рублей составляет ${up?'прибавка':'скидка'}?`,part,'Процент считается от старой цены.');S('Сколько процентов старой цены составляет новая?',remain,up?'Прибавляем процент роста к 100%.':'Вычитаем скидку из 100%.');E(part,'Это только изменение цены, а не новая цена.','percent-part');}
  else if(key==='percent-reverse'){const after=mul(total,div(sub(100,p),100));T(`После скидки ${F(p)}% цена стала ${F(after)} рублей. Какой была цена до скидки?`,total,'percent',{after});S('Сколько процентов старой цены осталось?',sub(100,p),'Новая цена — оставшаяся часть старой.');S('Сколько рублей составлял 1% старой цены?',total/100,'Новую цену делим на оставшийся процент.');E(mul(after,add(1,div(p,100))),'Обратная прибавка считалась бы уже от другой базы. Восстанови 100% старой цены.','percent-whole');}
  else if(key==='percent-chain'){const p1=pick([10,20,25]),p2=pick([10,20,25]),first=mul(total,div(100+p1,100)),final=mul(first,div(100-p2,100));T(`Цена ${total} рублей выросла на ${p1}%, затем снизилась на ${p2}% от новой цены. Найди итоговую цену.`,final,'percent',{p1,p2,first});S('Цена после первого изменения?',first,'Первый процент относится к исходному целому.');S('Сколько рублей составляет второе снижение?',mul(first,div(p2,100)),'Теперь база — цена после роста.');E(mul(total,q(100+p1-p2,100)),'Ты сложил проценты, хотя у второго изменения другая база.','percent-reverse');}
  else{const pc=key==='percent-common'?pick([5,15,25,50,75]):p;data.percent=pc;data.part=mul(total,div(pc,100));T(`Найди ${F(pc)}% от ${total}.`,data.part,'percent');S('Чему равен 1% исходного числа?',total/100,'Раздели целое на сто.');S('Во сколько раз нужная доля больше одного процента?',pc,'Умножь значение одного процента на число процентов.');E(div(total,pc),'Деление на число процентов не находит нужную часть. Сначала найди одну сотую.','percent-meaning');}break;
 }
 case 'pie-read':case 'pie-angle':case 'pie-build':{
  const p=pick([10,20,25,30,40,50,75]),total=a*20;data.percent=p;data.total=total;
  if(key==='pie-angle'){T(`Сектор занимает ${p}% круга. Найди его угол в градусах.`,q(360*p,100),'pie');S('Сколько градусов во всём круге?',360,'Круг — полный оборот.');S('Какую долю круга занимает сектор?',q(p,100),'Проценты переводим в долю.');}
  else if(key==='pie-build'){const p2=pick([10,15,20]),rest=100-p-p2;T(`Две категории занимают ${p}% и ${p2}% круга. Найди угол сектора третьей категории в градусах.`,q(rest*360,100),'pie',{p2,rest});S('Сколько процентов осталось третьей категории?',rest,'Все категории описывают одно целое.');S('Какую долю круга составляет остаток?',q(rest,100),'Остаток процентов делим на 100.');}
  else{T(`Всего опросили ${total} человек. Сектор с ответом «велосипед» занимает ${p}%. Сколько человек выбрали велосипед?`,q(total*p,100),'pie');S('Что принято за 100%?',total,'Все участники опроса.');S('Сколько человек приходится на 1%?',q(total,100),'Размер всего круга делим на сто.');}break;
 }
 case 'triangle-sides':case 'triangle-angles':case 'triangle-sum':case 'triangle-isosceles':case 'triangle-exists':{
  if(key==='triangle-sides'){const lengths=v===0?[a+3,a+3,a+3]:v===1?[a+3,a+3,a+2]:[a+2,a+3,a+4];T(`Стороны треугольника ${lengths.join(', ')} см. Назови его наиболее точный вид по сторонам: равносторонний, равнобедренный или разносторонний.`,['равносторонний','равнобедренный','разносторонний'][v],'triangle',{lengths});S('Сколько разных длин среди его сторон?',v+1,'Сравни числа, а не внешний вид рисунка.');S('Равны ли все три стороны? Напиши да или нет.',v===0?'да':'нет','Это определяет равносторонний треугольник.');}
  else if(key==='triangle-exists'){const x=a+2,y=b+2,z=v===0?x+y:v===1?x+y+1:Math.max(x,y);T(`Можно ли построить треугольник со сторонами ${x}, ${y}, ${z}? Ответь да или нет.`,v===2?'да':'нет','triangle',{lengths:[x,y,z]});const sorted=[x,y,z].sort((x,y)=>x-y);S('Какова сумма двух меньших сторон?',sorted[0]+sorted[1],'Она должна быть строго больше самой длинной.');S('Длина самой большой стороны?',sorted[2],'Равенства недостаточно: фигура вырождается в отрезок.');}
  else{const x=key==='triangle-isosceles'?pick([30,40,50,70,80,100,120]):pick([25,35,45,55,65]),y=key==='triangle-isosceles'?(180-x)/2:pick([30,40,50,60,90]),z=180-x-y;data.angles=[x,y,z];if(key==='triangle-angles'){const max=Math.max(x,y,z);T(`Углы треугольника ${x}°, ${y}°, ${z}°. Назови вид: остроугольный, прямоугольный или тупоугольный.`,max>90?'тупоугольный':max===90?'прямоугольный':'остроугольный','triangle');S('Какой угол самый большой?',max,'Для вида по углам достаточно проверить максимальный угол.');S('Сколько градусов в прямом угле?',90,'Сравни максимальный угол с 90°.');}else if(key==='triangle-isosceles'){T(`Угол между равными сторонами равнобедренного треугольника ${x}°. Найди один угол при основании.`,y,'triangle');S('Сумма двух углов при основании?',180-x,'Из 180° вычти угол при вершине.');S('На сколько равных углов делим остаток?',2,'Углы при основании равны.');}else{T(`Два угла треугольника ${x}° и ${y}°. Найди третий угол.`,z,'triangle');S('Сумма двух известных углов?',x+y,'Учитываем оба известных угла.');S('Сумма всех углов треугольника?',180,'Остаток до 180° — третий угол.');}}break;
 }
 case 'sets-members':case 'sets-intersection':case 'sets-union':case 'sets-count':case 'sets-subset':{
  const A=[a,a+1,a+3,a+5],B=[a+1,a+2,a+5,a+6];data.A=A;data.B=B;
  if(key==='sets-members'){const list=[a,a+1,a,a+3,a+1];T(`В записи множества повторили некоторые элементы: {${list.join(', ')}}. Сколько разных элементов?`,3,'sets',{list});S('Сколько раз записано число '+a+'?',2,'Повтор не создаёт нового элемента.');S('Повторяющиеся элементы считаем один раз? Ответь да или нет.','да','В множестве элементы различны.');}
  else if(key==='sets-count'){const onlyA=a+3,onlyB=b+2,both=c;T(`${onlyA+both} учеников любят шахматы, ${onlyB+both} любят рисовать, ${both} любят и то и другое. Сколько учеников любят хотя бы одно из двух занятий?`,onlyA+onlyB+both,'sets',{onlyA,onlyB,both});S('Сумма двух указанных численностей?',onlyA+onlyB+2*both,'В этой сумме общая группа учтена дважды.');S('Сколько учеников нужно вычесть один раз?',both,'Оставляем один экземпляр каждого общего элемента.');}
  else if(key==='sets-subset'){const subset=v===0?[A[0],A[2]]:[A[0],a+9];T(`A={${A.join(', ')}}, B={${subset.join(', ')}}. B является подмножеством A? Ответь да или нет.`,v===0?'да':'нет','sets',{B:subset});S('Первый элемент B входит в A?','да','Для подмножества нужны все элементы.');S('Последний элемент B входит в A?',v===0?'да':'нет','Один отсутствующий элемент опровергает подмножество.');}
  else{const intersection=A.filter(n=>B.includes(n)),union=[...new Set([...A,...B])],inter=key==='sets-intersection';T(`A={${A.join(', ')}}, B={${B.join(', ')}}. Сколько элементов в ${inter?'пересечении':'объединении'}?`,inter?intersection.length:union.length,'sets');S('Сколько элементов входят и в A, и в B?',intersection.length,'Посчитай общие числа один раз.');S(inter?'Нужно ли включать элемент, который есть только в A? Ответь да или нет.':'Сколько элементов получилось бы при сложении двух численностей?',inter?'нет':A.length+B.length,inter?'В пересечении только общие элементы.':'Из суммы вычтем повтор общей части.');}break;
 }
 case 'prime-test':case 'divisibility':case 'prime-factor':case 'prime-repair':case 'gcd-list':case 'gcd-primes':case 'gcd-packs':case 'coprime':case 'lcm-find':case 'lcm-primes':case 'lcm-events':{
  const gcd=(x,y)=>{while(y){[x,y]=[y,x%y];}return x;};
  if(key==='prime-test'){const n=pick([1,2,7,11,13,17,19,21,25,27,29,31,35,39,49]),ds=Array.from({length:n},(_,i)=>i+1).filter(d=>n%d===0);T(`Определи вид числа ${n}: простое, составное или ни то ни другое.`,n===1?'ни то ни другое':ds.length===2?'простое':'составное','factors',{n});S('Сколько натуральных делителей у числа?',ds.length,'Включи 1 и само число; у 1 это один и тот же делитель.');S('Сколько делителей должно быть у простого числа?',2,'Простое имеет ровно два различных натуральных делителя.');}
  else if(key==='divisibility'){const n=R(101,899),d=pick([2,3,5,9,10]);T(`Делится ли ${n} на ${d} без остатка? Ответь да или нет.`,n%d===0?'да':'нет','factors',{n,divisor:d});S(d===3||d===9?'Найди сумму цифр числа.':'Запиши последнюю цифру.',d===3||d===9?String(n).split('').reduce((s,z)=>s+Number(z),0):n%10,'Для 3 и 9 нужна сумма цифр, для 2,5,10 — последняя цифра.');S('Какой остаток получается при делении исходного числа на '+d+'?',n%d,'Проверь результат признаком или делением.');}
  else if(key==='prime-factor'||key==='prime-repair'){const primes=[2,2,pick([3,5]),pick([3,5,7])].sort((x,y)=>x-y),n=primes.reduce((p,z)=>p*z,1);data.n=n;data.primes=primes;if(key==='prime-factor'){T(`Разложи ${n} на простые множители. Запиши произведение через * или ·.`,primes,'factors');format='prime-factors';let remain=n;for(const p of primes.slice(0,-1)){S(`Найди наименьший простой делитель ${remain}.`,p,'Проверяй делимость начиная с 2, затем 3,5,7.');remain/=p;}S('Какой последний простой множитель остался?',remain,'В ответе сохрани все повторения.');}else{const missing=primes.at(-1),shown=primes.slice(0,-1);T(`${n}=${shown.join('·')}·?. Найди пропущенный простой множитель.`,missing,'factors',{shown});S('Найди произведение известных множителей.',n/missing,'Собери известную часть произведения.');S('На какое число нужно разделить исходное число?',n/missing,'Неизвестный множитель находят делением.');}}
  else{const x=a*c,y=b*c,g=gcd(x,y),l=x*y/g;data.x=x;data.y=y;if(key==='coprime'){const xx=a+3,yy=v===0?xx+1:2*xx;T(`Числа ${xx} и ${yy} взаимно простые? Ответь да или нет.`,gcd(xx,yy)===1?'да':'нет','factors',{x:xx,y:yy});S('Найди НОД этих чисел.',gcd(xx,yy),'Взаимная простота означает НОД=1.');S('Какой НОД у взаимно простых чисел?',1,'Составные числа тоже могут быть взаимно простыми.');}
  else if(key==='gcd-packs'){T(`Из ${x} карандашей и ${y} наклеек делают наибольшее число одинаковых наборов, без остатка. Сколько наборов получится?`,g,'factors');S('Число наборов должно делить оба запаса? Ответь да или нет.','да','Каждый предмет должен войти в одинаковые наборы.');S('Найди наибольший общий делитель запасов.',g,'Ищем наибольшее число наборов, не размер одного набора.');}
  else if(key==='lcm-events'){T(`Два сигнала звучат каждые ${x} и ${y} секунд. Сейчас прозвучали вместе. Через сколько секунд впервые снова прозвучат вместе?`,l,'factors');S('Найди НОД периодов.',g,'НОК можно вычислить через произведение и НОД.');S('Найди произведение периодов.',x*y,'Теперь раздели произведение на НОД.');}
  else{const isL=key.startsWith('lcm');T(`Найди ${isL?'НОК':'НОД'} чисел ${x} и ${y}.`,isL?l:g,'factors');if(isL){S('Найди НОД этих чисел.',g,'Для НОК используем все нужные простые множители.');S('Найди произведение чисел.',x*y,'НОК равен произведению, делённому на НОД.');E(g,'Это НОД — общий делитель. НОК должен делиться на оба исходных числа.','lcm-find');}else{if(key==='gcd-primes'){const factors=n=>{const result=[];for(let d=2;d<=n;d++)while(n%d===0){result.push(d);n/=d;}return result;};S('Разложи '+x+' на простые множители.',factors(x),'Дели последовательно на наименьший простой делитель.');steps.at(-1).answerFormat='prime-factors';S('Разложи '+y+' на простые множители.',factors(y),'Для НОД возьми только общие множители с наименьшим числом повторений.');steps.at(-1).answerFormat='prime-factors';}else{S('Выпиши все общие делители через точку с запятой.',Array.from({length:Math.min(x,y)},(_,i)=>i+1).filter(d=>x%d===0&&y%d===0),'Проверь каждый делитель меньшего числа и на втором числе.');steps.at(-1).answerFormat='unordered';S('Сколько общих делителей ты нашёл?',Array.from({length:g},(_,i)=>i+1).filter(d=>g%d===0).length,'Из списка выбери наибольший.');}E(l,'Это общее кратное. НОД, напротив, должен делить исходные числа.','gcd-list');}}}break;
 }
 case 'fraction-equivalent':case 'fraction-lcd':case 'fraction-convert':case 'fraction-compare':case 'fraction-add':case 'fraction-subtract':case 'fraction-decimal':case 'fraction-brackets':{
  let {u,w}=fractionPair();if(key==='fraction-subtract'&&N(u)<N(w))[u,w]=[w,u];data.u=u;data.w=w;
  const gcd=(x,y)=>y?gcd(y,x%y):x,lcd=u.d*w.d/gcd(u.d,w.d),un=u.n*lcd/u.d,wn=w.n*lcd/w.d;
  if(key==='fraction-equivalent'||key==='fraction-convert'){const factor=c,den=u.d*factor;T(`Заполни пропуск: ${F(u)} = ?/${den}. Введи числитель.`,u.n*factor,'fraction',{factor,den});S('Дополнительный множитель?',factor,'Новый знаменатель раздели на старый.');S('На что умножаем числитель?',factor,'Долю сохраняет одинаковое изменение числителя и знаменателя.');}
  else if(key==='fraction-lcd'){T(`Найди наименьший общий знаменатель дробей ${F(u)} и ${F(w)}.`,lcd,'fraction');S('Найди НОД знаменателей.',gcd(u.d,w.d),'Можно использовать простые множители.');S('Найди произведение знаменателей.',u.d*w.d,'НОК — произведение, делённое на НОД.');}
  else if(key==='fraction-compare'){T(`Сравни ${F(u)} и ${F(w)}. Введи <, > или =.`,N(u)>N(w)?'>':N(u)<N(w)?'<':'=','fraction');S('Общий знаменатель?',lcd,'Приведи к одинаковому размеру долей.');S('Новый числитель первой дроби?',un,'Умножь числитель на дополнительный множитель.');S('Новый числитель второй дроби?',wn,'Теперь сравни два числителя.');}
  else if(key==='fraction-decimal'){u=q(pick([1,3,7,9]),10);data.u=u;T(`Вычисли точно: ${D(u)} + ${F(w)}. Ответ можно записать обыкновенной дробью.`,add(u,w),'fraction');S('Запиши десятичное слагаемое обыкновенной дробью.',u,'Десятые имеют знаменатель 10.');S('Первое слагаемое изменило значение при переводе? Ответь да или нет.','нет','Изменилась только запись.');}
  else if(key==='fraction-brackets'){const outer=add(add(u,w),q(1,c)),inside=add(u,w);T(`Вычисли: ${F(outer)} − (${F(u)} + ${F(w)}).`,q(1,c),'fraction',{outer});S('Значение в скобках?',inside,'Сначала сложи дроби.');S('Какое действие осталось выполнить: сложение или вычитание?','вычитание','От первого числа вычитаем всю сумму.');}
  else{const plus=key==='fraction-add';T(`Вычисли: ${F(u)} ${plus?'+':'−'} ${F(w)}.`,plus?add(u,w):sub(u,w),'fraction',{plus});S('Наименьший общий знаменатель?',lcd,'Нужно складывать или вычитать доли одного размера.');S('Числитель первой дроби после приведения?',un,'Умножь числитель на lcd/старый знаменатель.');S('Числитель результата до сокращения?',plus?un+wn:un-wn,'Знаменатель уже общий и не меняется.');E(q(plus?u.n+w.n:u.n-w.n,u.d+w.d),'Знаменатели задают размер долей, их нельзя складывать.','fraction-lcd');}break;
 }
 case 'mixed-convert':case 'mixed-add':case 'mixed-subtract':case 'mixed-borrow':case 'whole-minus-fraction':{
  const den=pick([5,7,8,9]),n1=R(1,den-2),n2=R(n1+1,den-1),whole=a+b;let u=q(whole*den+n1,den),w=q(b*den+n2,den);data.u=u;data.w=w;data.den=den;data.whole=whole;data.n1=n1;data.n2=n2;const mix=z=>Math.floor(z.n/z.d)+' '+z.n%z.d+'/'+z.d;
  if(key==='mixed-convert'){const n=whole*den+n1;T(`Запиши ${whole} ${n1}/${den} неправильной дробью.`,u,'fraction');format='improper-fraction';S('Сколько долей в целой части?',whole*den,'Каждая единица содержит знаменатель долей.');S('Какой числитель получится после добавления дробной части?',n,'Складываем все доли.');}
  else if(key==='mixed-add'){T(`Вычисли ${mix(u)} + ${mix(w)}.`,add(u,w),'fraction');S('Сумма целых частей?',whole+b,'Дробные части пока оставь отдельно.');S('Сумма дробных частей?',q(n1+n2,den),'Если сумма не меньше единицы, выдели целую часть.');}
  else if(key==='whole-minus-fraction'){T(`Вычисли ${whole} − ${mix(w)}.`,sub(whole,w),'fraction',{u:q(whole)});S('Какую целую часть получим у уменьшаемого после занимания единицы?',whole-1,'Одну единицу превращаем в d/d.');S('Числитель дробной части уменьшаемого после занимания?',den,'В целой единице d долей по 1/d.');}
  else{if(key==='mixed-subtract'){u=q(whole*den+n2,den);w=q(b*den+n1,den);data.u=u;data.w=w;}T(`Вычисли ${mix(u)} − ${mix(w)}.`,sub(u,w),'fraction');if(key==='mixed-borrow'){S('Целая часть уменьшаемого после занимания единицы?',whole-1,'Дробной части не хватает: уменьшаем целую на 1.');S('Числитель дробной части после занимания?',n1+den,'Одна целая даёт d/d, а не 1/d.');S('Числитель дробной части результата?',n1+den-n2,'Теперь долей хватает для вычитания.');}else{S('Разность целых частей?',whole-b,'Дробной части хватает, занимание не требуется.');S('Разность дробных частей?',q(n2-n1,den),'Одинаковые доли вычитаем по числителям.');}}break;
 }
 case 'fraction-times-int':case 'fraction-multiply':case 'fraction-cancel':case 'mixed-multiply':case 'fraction-area':case 'fraction-part':case 'fraction-remain':case 'fraction-of-remainder':case 'fraction-volume':{
  let u=q(a,b+9),w=q(c,b+3);data.u=u;data.w=w;
  if(key==='fraction-part'||key==='fraction-remain'){const total=u.d*a*4,remain=key==='fraction-remain';T(remain?`Из ${total} л использовали ${F(u)} всего запаса. Сколько литров осталось?`:`Найди ${F(u)} от ${total}.`,mul(total,remain?sub(1,u):u),'fraction',{total,remain});if(remain)S('Какая доля осталась?',sub(1,u),'Из всего целого вычти потраченную долю.');S('Сколько в одной доле 1/'+u.d+'?',total/u.d,'Делим всё количество на знаменатель.');S('Сколько долей берём?',remain?u.d-u.n:u.n,'Числитель сообщает количество выбранных частей.');}
  else if(key==='fraction-of-remainder'){u=q(1,c);w=q(1,b);const total=c*b*a,first=mul(total,sub(1,u)),used=mul(first,w);T(`Из ${total} страниц прочитали ${F(u)} всей книги, затем ${F(w)} оставшихся страниц. Сколько страниц осталось после двух дней?`,sub(first,used),'fraction',{u,w,total,first});S('Сколько страниц осталось после первого дня?',first,'Вычти прочитанную долю всего.');S('Сколько страниц прочитали во второй день?',used,'Вторая доля берётся от остатка, а не от всей книги.');E(mul(total,sub(sub(1,u),w)),'Ты взял обе доли от всей книги. Во второй день целым является остаток.','fraction-remain');}
  else if(key==='fraction-volume'){const length=a*10,width=q(length*3,5),height=div(width,2);T(`Длина помещения ${length} м, ширина составляет 3/5 длины, высота — 1/2 ширины. Найди объём в м³.`,mul(mul(length,width),height),'solid',{length,width,height});S('Ширина помещения?',width,'Пять равных частей длины, берём три.');S('Высота помещения?',height,'Половина уже найденной ширины.');S('Площадь пола?',mul(length,width),'Для объёма останется умножить площадь на высоту.');}
  else{if(key==='fraction-times-int')w=q(c);if(key==='fraction-cancel'){u=q(a*c,(b+1)*3);w=q((b+1)*2,a*5);}if(key==='mixed-multiply'||key==='fraction-area'){u=q(a*2+1,2);w=q(b*3+1,3);}data.u=u;data.w=w;T(key==='fraction-area'?`Прямоугольник имеет длину ${F(u)} м и ширину ${F(w)} м. Найди площадь в м².`:`Вычисли ${F(u)} · ${F(w)}.`,mul(u,w),'fraction-area');S('Числитель произведения до сокращения?',u.n*w.n,'Перемножаем количества выбранных долей.');S('Знаменатель произведения до сокращения?',u.d*w.d,'Вся сетка состоит из произведения чисел долей.');E(add(u,w),'Это сумма, а нужна доля от доли или несколько одинаковых долей.','fraction-multiply');}break;
 }
 case 'distribute-add':case 'distribute-sub':case 'distribute-factor':case 'distribute-fractions':{
  const minus=key==='distribute-sub',x=20+b,y=c,outer=a;
  if(key==='distribute-fractions'){const u=q(b,b+c),w=q(c,b+c);T(`Вычисли удобно: ${F(u)}·${a*7} + ${F(w)}·${a*7}.`,a*7,'distribute',{outer:a*7,u,w,x:1,y:1,minus:false});S('Общий множитель?',a*7,'Оба слагаемых умножены на одно число.');S('Сумма дробей после вынесения?',1,'Числители в сумме дают знаменатель.');}
  else{T(key==='distribute-factor'?`Вычисли удобно: ${outer}·${x} + ${outer}·${y}.`:`Вычисли с помощью распределительного свойства: ${outer}·(${x} ${minus?'−':'+'} ${y}).`,outer*(minus?x-y:x+y),'distribute',{outer,x,y,minus});S('Первое произведение?',outer*x,'Внешний множитель умножает первый член.');S('Второе произведение?',outer*y,'Тот же множитель умножает и второй член.');S(minus?'Какую разность получаем в скобках?':'Какую сумму получаем в скобках?',minus?x-y:x+y,'Проверим итог альтернативным порядком вычислений.');E(outer*x+(minus?-y:y),'Внешний множитель должен действовать и на второе слагаемое.','distribute-add');}break;
 }
 case 'reciprocal':case 'fraction-divide-int':case 'fraction-divide':case 'mixed-divide':case 'fraction-unit-rate':case 'fraction-unknown':case 'whole-from-fraction':case 'whole-from-remainder':case 'whole-two-parts':case 'fraction-bar':case 'fraction-order':case 'fraction-complex':{
  let u=q(a,b+9),w=q(c,b+3);data.u=u;data.w=w;
  if(key==='reciprocal'){u=v%2?q(a*b+1,b):u;data.u=u;T(`Найди число, обратное к ${F(u)}.`,div(1,u),'division');S('Чему равно произведение взаимно обратных чисел?',1,'Это определение обратных чисел.');S('Какой числитель у обратной дроби?',u.d,'Числитель и знаменатель меняются местами.');}
  else if(key.startsWith('whole-')){u=q(1,c);w=q(1,b+2);const total=c*(b+2)*a*3,share=key==='whole-from-fraction'?u:key==='whole-from-remainder'?sub(1,u):sub(sub(1,u),w),known=mul(total,share);T(key==='whole-from-fraction'?`${F(u)} пути составляют ${F(known)} км. Найди весь путь.`:key==='whole-from-remainder'?`Потратили ${F(u)} запаса, осталось ${F(known)} л. Сколько было?`:`Прочитали ${F(u)} всей книги и ещё ${F(w)} всей книги. Осталось ${F(known)} страниц. Сколько страниц в книге?`,total,'fraction',{u,w,total,share,known});S('Какая доля соответствует известному количеству?',share,'Для остатка вычти потраченные доли из 1.');S('Сколько приходится на одну долю 1/'+share.d+'?',div(known,share.n),'Известное количество соответствует числителю доли.');E(mul(known,share),'Ты снова нашёл часть. Здесь нужно восстановить весь запас.','whole-from-fraction');}
  else if(key==='fraction-complex'){T(`Вычисли 1 / (1 + ${F(u)}). Всю сумму в скобках считаем знаменателем.`,div(1,add(1,u)),'division');S('Значение всего знаменателя?',add(1,u),'Сначала сложение в знаменателе.');S('На какое число нужно разделить 1?',add(1,u),'Дробная черта — деление на весь знаменатель.');}
  else if(key==='fraction-bar'){const numerator=add(u,w),denominator=add(w,1);T(`Вычисли (${F(u)} + ${F(w)}) / (${F(w)} + 1).`,div(numerator,denominator),'division',{numerator,denominator});S('Значение числителя?',numerator,'Сначала вся верхняя сумма.');S('Значение знаменателя?',denominator,'Теперь вся нижняя сумма.');}
  else if(key==='fraction-order'){T(`Вычисли слева направо: ${F(u)} : ${F(w)} · ${c}.`,mul(div(u,w),c),'division',{factor:c});S('Результат первого действия — деления?',div(u,w),'Умножение и деление равноправны; идём слева направо.');S('На какое число умножаем найденное частное?',c,'Последний множитель не входит в предыдущий делитель.');}
  else{if(key==='fraction-divide-int')w=q(c);if(key==='mixed-divide'){u=q(a*2+1,2);w=q(b*3+1,3);}if(key==='fraction-unit-rate')u=q(a*30);data.u=u;data.w=w;
   if(key==='fraction-unknown'){const x=div(u,w);T(`Реши уравнение x · ${F(w)} = ${F(u)}.`,x,'division');S('Какое действие находит неизвестный множитель: умножение или деление?','деление','Произведение делим на известный множитель.');S('Число, обратное известному множителю?',div(1,w),'Деление можно заменить умножением на обратное.');}
   else{T(key==='fraction-unit-rate'?`За ${F(w)} кг продукта заплатили ${F(u)} рублей. Какова цена одного килограмма?`:`Вычисли ${F(u)} : ${F(w)}.`,div(u,w),'division');S('Число, обратное делителю?',div(1,w),'Переворачиваем только делитель.');S('Знак действия после замены: умножение или сложение?','умножение','Деление заменили умножением на обратное число.');E(mul(u,w),'Ты умножил на сам делитель, а нужно на обратное число.','reciprocal');}}break;
 }
 case 'ratio-units':case 'ratio-reduce':case 'ratio-split':case 'ratio-difference':case 'proportion-check':case 'proportion-missing':case 'proportion-recipe':case 'proportion-percent':case 'direct':case 'inverse':case 'proportion-choice':case 'work-gardens':case 'joint-work':case 'motion-meeting':case 'scale-real':case 'scale-map':case 'scale-find':{
  const gcd=(x,y)=>y?gcd(y,x%y):x;
  if(key==='ratio-units'){const cm=a*10,meters=b;T(`Найди отношение ${cm} см к ${meters} м. Запиши его дробью.`,q(cm,meters*100),'ratio',{cm,meters});S('Сколько сантиметров во второй длине?',meters*100,'Перед сравнением длины должны иметь одну единицу.');S('Что записываем в числитель отношения?',cm,'Порядок величин в условии определяет порядок деления.');}
  else if(key==='ratio-reduce'){const x=a*c,y=b*c,g=gcd(x,y);T(`Сократи отношение ${x}:${y}. Введи два члена через точку с запятой.`,[x/g,y/g],'ratio',{x,y});S('На какое наибольшее число делятся оба члена?',g,'Оба члена отношения делим на их НОД.');S('Первый член после сокращения?',x/g,'Второй член сократи на то же число.');}
  else if(key==='ratio-split'){const total=(a+b)*c;T(`${total} наклеек разделили в отношении ${a}:${b}. Сколько получил первый ученик?`,a*c,'ratio',{parts:[a,b],total});S('Сколько равных частей всего?',a+b,'Складываем числа частей.');S('Сколько наклеек в одной части?',c,'Общее количество делим на сумму частей.');E(q(total*a,b),'Число '+b+' — только части второго ученика, не общее число частей.','ratio-reduce');}
  else if(key==='ratio-difference'){const first=a,second=a+b,difference=b*c;T(`Два количества относятся как ${first}:${second} и отличаются на ${difference}. Найди меньшее.`,first*c,'ratio',{parts:[first,second],difference});S('Сколько частей составляет разность?',b,'Вычитаем числа частей.');S('Размер одной части?',c,'Известную разность делим на число частей разности.');}
  else if(key==='proportion-check'){const x=a*c,y=b*c+(v===0?1:0);T(`Верна ли пропорция ${a}/${b} = ${x}/${y}? Ответь да или нет.`,a*y===b*x?'да':'нет','ratio',{x,y});S('Произведение крайних членов?',a*y,'Крайние стоят на внешних местах пропорции.');S('Произведение средних членов?',b*x,'Для верной пропорции произведения равны.');}
  else if(key==='proportion-missing'){T(`Найди x в пропорции x/${b*c} = ${a}/${b}.`,a*c,'ratio',{den:b*c});S('Чему равно произведение известных членов по диагонали?',a*b*c,'Получаем b·x=a·(b·c).');S('На что разделим это произведение для нахождения x?',b,'Это коэффициент при неизвестном.');}
  else if(key==='proportion-recipe'||key==='direct'){const old=b,price=a*15,newN=b+c,total=old*price;T(key==='direct'?`${old} м ткани стоят ${total} рублей. Сколько стоят ${newN} м по той же цене?`:`На ${old} порций нужно ${total} г крупы. Сколько граммов нужно на ${newN} порций того же размера?`,newN*price,'ratio',{old,newN,total,unit:price});S('Сколько приходится на одну единицу?',price,'Сначала стоимость метра или расход на порцию.');S('На сколько единиц умножаем?',newN,'Теперь учитываем новое количество.');}
  else if(key==='proportion-percent'){const total=a*100,p=b*5;T(`С помощью пропорции найди ${p}% от ${total}.`,total*p/100,'percent',{total,percent:p});S('Какое число должно стоять напротив 100%?',total,'Это исходное целое.');S('Чему равно произведение целого на нужный процент?',total*p,'Осталось разделить на 100.');}
  else if(key==='inverse'){const workers=b,days=c*3,newWorkers=b*3;T(`${workers} одинаковых работников выполняют работу за ${days} дней. За сколько дней выполнят её ${newWorkers} таких работников?`,c,'work',{workers,days,newWorkers,gardens:1,newGardens:1});S('Объём работы в человеко-днях?',workers*days,'Произведение числа работников и времени постоянно.');S('Во сколько раз работников стало больше?',3,'Время станет во столько же раз меньше.');}
  else if(key==='work-gardens'){const workers=b,days=c*2,gardens=c,newWorkers=b*2,newGardens=a*c;T(`${workers} работников обработали ${gardens} одинаковых огородов за ${days} дней. За сколько дней ${newWorkers} таких работников обработают ${newGardens} огородов?`,a*c,'work',{workers,days,gardens,newWorkers,newGardens});S('Сколько человеко-дней понадобилось на прежнюю работу?',workers*days,'Умножаем людей на дни.');S('Сколько человеко-дней нужно на один огород?',workers*days/gardens,'Делим на число прежних огородов.');S('Сколько человеко-дней нужно на новые огороды?',workers*days/gardens*newGardens,'Объём растёт пропорционально числу огородов.');}
  else if(key==='joint-work'){const t1=a*2,t2=a*3,rate=add(q(1,t1),q(1,t2));T(`Первый насос наполняет бак за ${t1} ч, второй за ${t2} ч. За сколько часов они наполнят бак вместе при постоянной скорости?`,div(1,rate),'work',{t1,t2,rate});S('Доля бака за час первым насосом?',q(1,t1),'Один бак делим на время.');S('Доля бака за час двумя насосами?',rate,'Складываем производительности, не времена.');E(q(t1+t2,2),'Среднее времён не описывает совместную работу. Найди долю бака за час.','fraction-add');}
  else if(key==='proportion-choice'){const choice=v,rows=choice===0?[[1,a],[2,2*a],[3,3*a]]:choice===1?[[1,a*6],[2,a*3],[3,a*2]]:[[1,a+2],[2,2*a+2],[3,3*a+2]];T(`Таблица пар (x;y): ${rows.map(z=>'('+z.join(';')+')').join(', ')}. Зависимость прямая, обратная или ни та ни другая?`,['прямая','обратная','ни та ни другая'][choice],'ratio',{rows});S('Отношение y/x для первой пары?',rows[0][1]/rows[0][0],'Для прямой пропорциональности оно должно быть постоянным.');S('Отношение y/x для второй пары?',q(rows[1][1],rows[1][0]),'Если оно меняется, проверь произведения xy.');S('Произведение xy для второй пары?',rows[1][0]*rows[1][1],'Для обратной пропорциональности постоянно произведение.');}
  else if(key==='motion-meeting'){const fast=a+b,slow=a,time=c,distance=(v===0?fast+slow:fast-slow)*time;T(v===0?`Между пешеходами ${distance} км. Они идут навстречу со скоростями ${fast} и ${slow} км/ч. Через сколько часов встретятся?`:`Велосипедист едет ${fast} км/ч и догоняет пешехода со скоростью ${slow} км/ч. Отставание ${distance} км. Через сколько часов догонит?`,time,'motion',{fast,slow,distance,meeting:v===0});S('Скорость сближения?',v===0?fast+slow:fast-slow,v===0?'При встрече складываем скорости.':'При догонке вычитаем скорость уходящего.');S('Какое расстояние нужно сократить?',distance,'Начальное отставание или расстояние между участниками.');}
  else{const scale=pick([10000,25000,50000,100000,200000]),map=a,real=scale*map;data.scale=scale;data.map=map;data.real=real;if(key==='scale-real'){T(`На карте масштаба 1:${scale} расстояние ${map} см. Сколько это километров на местности?`,q(real,100000),'scale');S('Действительное расстояние в сантиметрах?',real,'Масштаб связывает одинаковые единицы.');S('Сколько сантиметров в километре?',100000,'Километр — 1000 метров, в метре 100 сантиметров.');}else if(key==='scale-map'){T(`На местности ${F(q(real,100000))} км. Масштаб карты 1:${scale}. Найди расстояние на карте в см.`,map,'scale');S('Действительное расстояние в сантиметрах?',real,'Приводим к сантиметрам карты.');S('На какое число делим реальную длину?',scale,'Изображение меньше в знаменатель масштаба раз.');}else{T(`${map} см на карте соответствуют ${F(q(real,100000))} км на местности. Масштаб 1:n. Найди n.`,scale,'scale');S('Действительное расстояние в сантиметрах?',real,'Нельзя делить километры на сантиметры без перевода.');S('Сколько сантиметров карты соответствует этой длине?',map,'Для одной единицы делим реальную длину на длину изображения.');}}break;
 }
 case 'symmetry-axis':case 'symmetry-center':case 'symmetry-line':case 'symmetry-polygon':case 'circle-radius':case 'circle-length':case 'circle-area':case 'circle-inverse':case 'sphere-solids':{
  if(key.startsWith('symmetry')){const x=a-5,y=b-4,axis=v%2?'x':'y',center=c-3;let target;if(key==='symmetry-axis')target=axis==='x'?[x,-y]:[-x,y];else if(key==='symmetry-line')target=[2*center-x,y];else target=[-x,-y];
   if(key==='symmetry-polygon'){const points=[[x,y],[x+3,y],[x+1,y+2]],idx=v;target=[-points[idx][0],points[idx][1]];T(`Треугольник A(${points[0].join(';')}), B(${points[1].join(';')}), C(${points[2].join(';')}) отражают относительно оси y. Найди координаты образа вершины ${'ABC'[idx]}. Введи x; y.`,target,'symmetry',{points,x:points[idx][0],y:points[idx][1],axis:'y',target});}
   else T(`Точку (${x};${y}) отражают ${key==='symmetry-center'?'относительно начала координат':key==='symmetry-line'?'относительно прямой x='+center:'относительно оси '+axis}. Найди координаты образа x; y.`,target,'symmetry',{x,y,axis,center,target});
   S('Какова первая координата образа?',target[0],'Сохрани расстояние до выбранной оси или центра и выбери противоположную сторону.');S('Какова вторая координата образа?',target[1],'Проверь, должна ли эта координата меняться для данного отражения.');}
  else{const radius=a,pi=q(314,100);data.radius=radius;if(key==='circle-radius'){T(`Диаметр окружности ${radius*2} см. Найди радиус.`,radius,'circle');S('Сколько радиусов в диаметре?',2,'Диаметр проходит через центр.');S('Какое действие нужно: умножение или деление?','деление','Из диаметра находим половину.');}
  else if(key==='circle-length'){T(`Радиус окружности ${radius} см. Найди её длину, используя π≈3,14.`,mul(pi,2*radius),'circle');S('Диаметр окружности?',radius*2,'Сначала удвоим радиус.');S('На какое число умножаем диаметр в этой задаче?',pi,'Отношение длины окружности к диаметру равно π.');}
  else if(key==='circle-area'){T(`Радиус круга ${radius} см. Найди площадь, используя π≈3,14.`,mul(pi,radius*radius),'circle');S('Квадрат радиуса?',radius*radius,'В площади радиус умножается сам на себя.');S('Приближение числа π по условию?',pi,'Теперь умножаем квадрат радиуса на π.');E(mul(pi,radius*2),'Это длина окружности, а не площадь круга. Для площади нужен квадрат радиуса.','circle-length');}
  else if(key==='circle-inverse'){const length=mul(pi,radius*2);T(`Длина окружности ${D(length)} см. Найди радиус, используя π≈3,14.`,radius,'circle',{length});S('Диаметр окружности?',radius*2,'Раздели длину на π.');S('На сколько делим диаметр для получения радиуса?',2,'Радиус вдвое меньше диаметра.');}
  else{T(`Шар радиуса ${radius} см разрезали плоскостью через центр. Найди диаметр полученного круга.`,radius*2,'solid');S('Радиус центрального сечения?',radius,'Плоскость проходит через центр шара.');S('Во сколько раз диаметр больше радиуса?',2,'У сечения те же правила радиуса и диаметра.');}}break;
 }
 case 'signed-context':case 'signed-scale':case 'signed-order':case 'opposite':case 'minus-minus':case 'opposite-equation':case 'absolute':case 'absolute-roots':case 'distance-points':case 'absolute-shift':case 'negative-compare':case 'negative-fractions':case 'integers-between':case 'change':case 'change-final':case 'change-start':case 'line-positive':case 'line-negative':case 'line-chain':{
  const x=v===0?-a:v===1?a:0,y=b;data.x=x;data.y=y;
  if(key==='signed-context'){const below=v!==1;T(`Уровень моря принят за ноль. Точка расположена ${below?'ниже':'выше'} него на ${a*10} м. Запиши отметку точки со знаком.`,below?-a*10:a*10,'line',{x:0,y:below?-a*10:a*10});S('Расстояние до нулевого уровня в метрах?',a*10,'Модуль показывает величину, не направление.');S('Знак отметки: + или −?',below?'−':'+','Ниже выбранного нуля — минус.');}
  else if(key==='signed-scale'){const step=c,offset=-b;T(`На прямой соседние отметки подписаны 0 и ${step}. Точка на ${b} таких промежутков левее 0. Найди её координату.`,step*offset,'line',{x:0,y:step*offset,step});S('Цена одного деления?',step,'Соседние отметки отличаются на цену деления.');S('Модуль координаты точки?',step*b,'Умножь число промежутков на цену деления.');}
  else if(key==='signed-order'){const values=[-a,-b-10,c];T(`Какое число наименьшее: ${values.join('; ')}?`,Math.min(...values),'line',{values});S('Какое из двух отрицательных имеет больший модуль?',-b-10,'Более далёкое влево отрицательное число меньше.');S('Отрицательное число меньше положительного? Ответь да или нет.','да','На прямой отрицательные левее нуля, положительные правее.');}
  else if(key==='opposite'||key==='minus-minus'||key==='opposite-equation'){T(key==='opposite'?`Найди число, противоположное ${x}.`:key==='minus-minus'?`Вычисли −(${x}).`:`Реши уравнение −x=${x}.`,-x,'line');S('Модуль исходного числа?',Math.abs(x),'У противоположного числа тот же модуль.');S('Чему равна сумма числа и противоположного?',0,'Они взаимно погашаются.');}
  else if(key==='absolute'){const value=q(x*10+(x<0?-c:c),10);T(`Найди модуль числа ${D(value)}.`,q(Math.abs(value.n),value.d),'line',{value});S('Может ли расстояние быть отрицательным? Ответь да или нет.','нет','Модуль — расстояние до нуля.');S('Знаменатель точной дроби для исходного числа?',value.d,'Дробная часть сохраняется; меняется только знак отрицательного числа.');}
  else if(key==='absolute-roots'){T(`Найди все решения |x|=${a}. Запиши их через точку с запятой.`,[-a,a],'line',{radius:a});format='unordered';S('Сколько точек на расстоянии '+a+' от нуля?',2,'Одна слева, другая справа.');S('Координата левой точки?',-a,'В окончательном ответе укажи обе точки.');}
  else if(key==='absolute-shift'){const center=c-3;T(`Найди все решения |x−(${center})|=${a}. Ответы через точку с запятой.`,[center-a,center+a],'line',{center,radius:a});format='unordered';S('От какой точки отсчитывается расстояние?',center,'Выражение x−c связано с расстоянием до c.');S('Координата точки слева от неё?',center-a,'Для второго решения отступи вправо на ту же величину.');}
  else if(key==='distance-points'){T(`Найди расстояние между точками с координатами ${-a} и ${b}.`,a+b,'line',{x:-a,y:b});S('Расстояние от левой точки до нуля?',a,'Расстояния неотрицательны.');S('Расстояние от нуля до правой точки?',b,'Обе части вместе дают весь отрезок.');}
  else if(key==='negative-compare'||key==='negative-fractions'){const u=key==='negative-compare'?q(-a):q(-a,a+b),w=key==='negative-compare'?q(-b-1):q(-b,b+c);T(`Сравни ${F(u)} и ${F(w)}. Введи <, > или =.`,N(u)<N(w)?'<':N(u)>N(w)?'>':'=','line',{u,w});S('Модуль первого числа?',mul(u,-1),'Модуль отрицательного числа положителен.');S('Модуль второго числа?',mul(w,-1),'Большему модулю соответствует меньшее отрицательное число.');}
  else if(key==='integers-between'){const left=-a,right=b,include=v===1;T(`Сколько целых чисел удовлетворяют ${left} ${include?'≤':'<'} x < ${right}?`,right-left-1+(include?1:0),'line',{left,right,include});S('Наименьшее подходящее целое?',left+(include?0:1),'Проверь знак у левой границы.');S('Наибольшее подходящее целое?',right-1,'Правая граница не включена.');}
  else if(key==='line-positive'||key==='line-negative'){const start=-a,move=key==='line-positive'?b:-b;T(`Вычисли ${start} + (${move}), используя числовую прямую.`,start+move,'line',{start,move});S('Начальная координата?',start,'Начинаем с первого слагаемого.');S('Длина перемещения?',Math.abs(move),'Знак второго слагаемого задаёт направление.');}
  else if(key==='line-chain'){const start=-a,m1=b+3,m2=-c;T(`Старт в точке ${start}. Затем переместились на ${m1} вправо и на ${c} влево. Найди конечную координату.`,start+m1+m2,'line',{start,m1,m2});S('Координата после первого перемещения?',start+m1,'Движение вправо увеличивает координату.');S('Общее изменение координаты?',m1+m2,'Изменения складываем со знаками.');}
  else{const start=-a,move=b+c,end=start+move;data.start=start;data.move=move;data.end=end;if(key==='change'){T(`Температура изменилась с ${start}° до ${end}°. Найди изменение со знаком.`,move,'line');S('Конечная температура?',end,'Из конечного значения вычитаем начальное.');S('Число, противоположное начальной температуре?',-start,'Вычитание заменяем сложением противоположного.');}else if(key==='change-final'){T(`Температура была ${start}° и повысилась на ${move}°. Какой стала температура?`,end,'line');S('Начальная температура?',start,'Не теряй знак исходного значения.');S('Изменение со знаком?',move,'Повышение даёт положительное изменение.');}else{T(`После повышения на ${move}° стало ${end}°. Какова исходная температура?`,start,'line');S('Из какой температуры вычитаем изменение?',end,'Известно конечное значение.');S('Какое изменение нужно вычесть?',move,'Идём обратным ходом.');}}break;
 }
 case 'negative-add':case 'negative-decimal-add':case 'negative-fraction-add':case 'mixed-sign-add':case 'mixed-sign-decimal':case 'mixed-sign-fractions':case 'cancel-pairs':case 'subtract-rule':case 'subtract-negative':case 'subtract-fractions':case 'subtract-chain':case 'multiply-sign':case 'multiply-decimal':case 'multiply-fractions':case 'multiply-many':case 'divide-sign':case 'divide-decimal':case 'divide-fractions':case 'divide-unknown':{
  let u=q(-a),w=q(key.startsWith('negative')?-b:b+1),op='+';
  if(/decimal/.test(key)){u=q(-a*10-c,10);w=q((key.startsWith('negative')?-1:1)*(b*100+25),100);}
  if(/fraction/.test(key)){u=q(-a,a+b);w=q((key.startsWith('negative')?-1:1)*b,b+c);}
  if(key.startsWith('subtract')){op='−';w=q(key==='subtract-negative'?-b:b);}if(key==='subtract-fractions')w=q(-b,b+c);
  if(key.startsWith('multiply')){op='·';if(v===0)w=mul(w,-1);}if(key.startsWith('divide')){op=':';if(v===0)w=mul(w,-1);}
  if(key==='cancel-pairs'){const values=[-a*7,b,a*7,-c];T(`Вычисли удобно: ${values.map((z,i)=>i?signed(z):F(z)).join(' ')}.`,b-c,'chips',{values,u:q(b),w:q(-c),op:'+'});S('Сумма противоположных слагаемых?',0,'Найди пару с равными модулями и разными знаками.');S('Какие числа останутся? Введи их сумму.',b-c,'Считаем оставшиеся слагаемые.');}
  else if(key==='subtract-chain'){const values=[-a,b,c,-a-b];T(`Вычисли −${a} − (−${b}) + ${c} − ${a+b}.`,-2*a+c,'chips',{values,op:'+'});S('Во что превращается −(−'+b+')?',b,'Вычитание отрицательного заменяется прибавлением положительного.');S('Сумма всех положительных слагаемых?',b+c,'Отдельно собери отрицательные.');S('Сумма отрицательных слагаемых?',-2*a-b,'Теперь сложи две группы.');}
  else if(key==='multiply-many'){const values=v===0?[-a,-b,c,-1]:v===1?[-a,-b,-c,-1]:[-a,b,0,-c],prod=values.reduce((p,z)=>p*z,1);T(`Вычисли ${values.map(x=>'('+x+')').join(' · ')}.`,prod,'signs',{values,op:'·'});S('Сколько отрицательных множителей?',values.filter(x=>x<0).length,'При отсутствии нуля чётность определяет знак.');S('Есть ли нулевой множитель? Ответь да или нет.',values.includes(0)?'да':'нет','Любое произведение с нулём равно нулю.');}
  else if(key==='divide-unknown'){const x=v===0?-c:c,dividend=-a*x;T(`Найди x: ${dividend} : x = ${-a}.`,x,'equation',{A:0,B:0,C:0,D:0,solution:x,dividend,quotient:-a});S('Делимое в уравнении?',dividend,'Неизвестен делитель.');S('Известное частное?',-a,'Раздели делимое на частное.');}
  else{const ans=op==='+'?add(u,w):op==='−'?sub(u,w):op==='·'?mul(u,w):div(u,w);T(`Вычисли (${F(u)}) ${op} (${F(w)}).`,ans,op==='+'||op==='−'?'chips':'signs',{u,w,op});if(op==='−'){S('Число, противоположное вычитаемому?',mul(w,-1),'Вычитание заменяем сложением противоположного.');S('Модуль первого числа?',q(Math.abs(u.n),u.d),'Теперь используй правило сложения со знаками.');}else if(op==='+'&&N(u)*N(w)<0){S('Модуль первого слагаемого?',mul(u,-1),'При разных знаках модули вычитаются.');S('Модуль второго слагаемого?',q(Math.abs(w.n),w.d),'Знак результата принадлежит большему модулю.');}else{S('Модуль первого числа?',q(Math.abs(u.n),u.d),'Сначала удобно отделить знак от величины.');S('Модуль второго числа?',q(Math.abs(w.n),w.d),'Примени нужное действие к модулям, затем поставь знак.');}if(N(ans)!==0)E(mul(ans,-1),'Модуль получился верно, но знак — нет. Различи сложение и умножение.','mixed-sign-add');}break;
 }
 case 'rational-decimal':case 'rational-finite':case 'rational-period':case 'properties-group':case 'properties-product':case 'properties-factor':case 'properties-order':{
  if(key==='rational-decimal'){const value=q((v===1?1:-1)*(pick([125,175,375,625,875])+a*1000),1000);T(`Запиши ${D(value)} несократимой обыкновенной дробью.`,value,'fraction',{u:value,w:q(1)});format='reduced-fraction';S('Какой знаменатель соответствует трём знакам после запятой?',1000,'Тысячные доли имеют знаменатель тысячу.');S('Какой числитель получится до сокращения?',value.n*(1000/value.d),'Теперь раздели числитель и знаменатель на их НОД.');}
  else if(key==='rational-finite'){const den=pick([8,20,25,40,7,9,11,15]),num=pick([1,2,3,5]),u=q(num,den);let rest=u.d;while(rest%2===0)rest/=2;while(rest%5===0)rest/=5;T(`Дробь ${num}/${den} имеет конечную десятичную запись? Ответь да или нет.`,rest===1?'да':'нет','division',{u,rest});S('Знаменатель после сокращения дроби?',u.d,'Сначала обязательно сократи дробь.');S('Оставшийся множитель знаменателя после удаления всех двоек и пятёрок?',rest,'Если осталась только 1, запись конечная.');}
  else if(key==='rational-period'){const den=pick([3,9,6]),num=1;T(`В дроби 1/${den} выполни деление до второй цифры после запятой. Какова вторая цифра?`,Math.floor((10%den)*10/den),'division',{u:q(1,den),den});S('Первая цифра после запятой?',Math.floor(10/den),'Раздели 10 десятых на знаменатель.');S('Остаток после первого шага?',10%den,'Припиши ноль и продолжи деление.');}
  else if(key==='properties-group'){const values=[-a*11,b*3,a*11,-c];T(`Вычисли удобно: −${a*11} + ${b*3} + ${a*11} − ${c}.`,b*3-c,'chips',{values,u:q(b*3),w:q(-c),op:'+'});S('Сумма противоположных чисел?',0,'Сгруппируй равные модули с разными знаками.');S('Положительное слагаемое, оставшееся после сокращения пары?',b*3,'Теперь вычти последнее число.');}
  else if(key==='properties-product'){T(`Вычисли удобно: −0,25 · ${a} · 4.`,-a,'signs',{values:[q(-1,4),a,4],op:'·'});S('Чему равно −0,25·4?',-1,'Сгруппируй удобную пару множителей.');S('Какой множитель остался?',a,'Умножение на −1 меняет знак.');}
  else if(key==='properties-factor'){T(`Вычисли: (−${a})·${b} + (−${a})·${c}.`,-a*(b+c),'distribute',{outer:-a,x:b,y:c,minus:false});S('Общий множитель?',-a,'Вместе с модулем выносим и минус.');S('Сумма оставшихся множителей?',b+c,'Затем умножаем на общий множитель.');}
  else{T(`Вычисли −${a}² + (−${b})².`,b*b-a*a,'signs',{a,b,op:'squares'});S('Значение первого слагаемого −'+a+'²?',-a*a,'Без скобок минус не входит в основание степени.');S('Значение второго слагаемого?',b*b,'В скобках квадрат отрицательного числа положителен.');}break;
 }
 case 'brackets-plus':case 'brackets-minus':case 'brackets-factor':case 'brackets-nested':case 'coefficient-read':case 'coefficient-product':case 'coefficient-fraction':case 'like-recognize':case 'like-combine':case 'like-two-letters':case 'like-after-brackets':{
  const x=R(2,7);let k=0,constant=0,expr='';
  if(key==='brackets-plus'){k=a+1;constant=-b;expr=`${a}x + (x − ${b})`;S('Коэффициент при x после снятия скобок и приведения подобных?',k,'Плюс перед скобкой сохраняет знаки.');S('Свободное слагаемое после снятия скобок?',constant,'Минус перед числом остаётся минусом.');}
  else if(key==='brackets-minus'){k=a-1;constant=b;expr=`${a}x − (x − ${b})`;S('Во что превращается −(−'+b+')?',b,'Минус перед скобкой меняет знак каждого слагаемого.');S('Коэффициент при x?',k,`${a}x − x = (${a}−1)x.`);}
  else if(key==='brackets-factor'){k=-a;constant=a*b;expr=`−${a}(x − ${b})`;S('Коэффициент при x после умножения?',k,'Внешний множитель действует на оба слагаемых.');S('Свободное слагаемое после умножения?',constant,'Два отрицательных множителя дают положительное произведение.');}
  else if(key==='brackets-nested'){k=1;constant=-a+b-c;expr=`x − (${a} − (${b} − ${c}))`;S('Чему равна внутренняя скобка?',b-c,'Начни с самой внутренней скобки.');S('Чему равна внешняя скобка?',a-b+c,'Вычти весь результат внутренней скобки.');}
  else if(key==='coefficient-read'){k=pick([-1,1,-a,a]);T(`Назови коэффициент выражения ${k===-1?'−x':k===1?'x':k+'x'}.`,k,'algebra',{coefficient:k,constant:0,x,expr:k+'x'});S('Есть ли у выражения отрицательный знак? Ответь да или нет.',k<0?'да':'нет','Отсутствующий числовой множитель означает 1.');S('Модуль коэффициента?',Math.abs(k),'При отрицательном знаке коэффициент отрицателен.');break;}
  else if(key==='coefficient-product'||key==='coefficient-fraction'){const f=key==='coefficient-fraction'?q(-a,b):-a,g=key==='coefficient-fraction'?q(b,c):c;k=mul(f,g);T(`Найди коэффициент выражения (${F(f)}) · x · (${F(g)}).`,k,'algebra',{coefficient:k,constant:0,x,expr:`(${F(f)}) · x · (${F(g)})`});S('Какие числовые множители нужно перемножить? Введи их через ;.',[f,g],'Буква x остаётся, перемножаются числа.');S('Какой знак у коэффициента? Введи + или −.','−','Знаки числовых множителей разные.');break;}
  else if(key==='like-recognize'){T(`Даны ${a}x, ${b}y, −${c}x и ${a}. Сколько слагаемых подобны ${a}x (включая само ${a}x)?`,2,'algebra',{coefficient:a-c,yCoefficient:b,constant:a,x,expr:`${a}x + ${b}y − ${c}x + ${a}`});S('Какая буквенная часть нужна? Введи x или y.','x','Подобные имеют одинаковую буквенную часть.');S('Считать ли свободное число подобным слагаемому с x? Да или нет.','нет','Число и выражение с x — разные группы.');break;}
  else if(key==='like-two-letters'){T(`Упрости ${a}x + ${b}y − ${c}x + y. Введи коэффициенты при x и y через ;.`,[a-c,b+1],'algebra',{coefficient:a-c,yCoefficient:b+1,constant:0,x,expr:`${a}x + ${b}y − ${c}x + y`});S('Коэффициент при x?',a-c,'Собираем только группу x.');S('Коэффициент при y?',b+1,'У отдельной буквы y коэффициент 1.');break;}
  else if(key==='like-combine'){k=a+b-c;constant=0;expr=`${a}x + ${b}x − ${c}x`;S('Сумма положительных коэффициентов?',a+b,'Сначала сложи две положительные группы x.');S('Коэффициент после вычитания последней группы?',k,'Вычти c, не меняя буквенную часть.');}
  else{k=a-b;constant=a*c+b;expr=`${a}(x + ${c}) − ${b}(x − 1)`;S('Свободное слагаемое после раскрытия первой скобки?',a*c,'Множитель a умножает оба слагаемых.');S('Свободное слагаемое после раскрытия второй скобки с минусом?',b,'−b · (−1) = b.');S('Коэффициент при x после приведения подобных?',k,'Собери ax и −bx.');}
  T(`Упрости ${expr}, затем найди значение при x = ${x}.`,add(mul(k,x),constant),'algebra',{coefficient:k,constant,x,expr});E(sub(mul(k,x),constant),'Проверь знак свободного слагаемого после раскрытия скобок.','brackets-minus');break;
 }
 case 'equation-inverse':case 'equation-both':case 'equation-brackets':case 'equation-fractions':case 'equation-decimals':case 'equation-special':case 'equation-parts':case 'equation-motion':case 'equation-transfer':case 'equation-mixture':case 'review-equations':{
  const solution=R(2,12);let A=a,B=b,C=0,D=A*solution+B,expr=`${A}x + ${B} = ${D}`;
  if(key==='equation-both'){C=c;A=c+a;D=(A-C)*solution+B;expr=`${A}x + ${B} = ${C}x + ${D}`;}
  if(key==='equation-brackets'||key==='review-equations'){C=1;A=a;B=a*b-c;D=(A-C)*solution+B;expr=`${a}(x + ${b}) − ${c} = x + ${D}`;S('Свободное слагаемое слева после раскрытия скобок?',B,'Умножь число в скобке на внешний множитель, затем вычти последнее число.');}
  if(key==='equation-fractions'){A=q(1,a);B=q(1,b);D=add(mul(A,solution),B);expr=`x/${a} + 1/${b} = ${F(D)}`;S('Что останется справа, если вычесть 1/'+b+' из обеих частей?',sub(D,B),'Одна операция выполняется с обеими частями.');}
  if(key==='equation-decimals'){A=q(a,10);B=q(b,10);D=add(mul(A,solution),B);expr=`${Dstr(A)}x + ${Dstr(B)} = ${Dstr(D)}`;}
  function Dstr(z){return typeof z==='object'?String(z.n/z.d).replace('.',','):String(z);}
  if(key==='equation-special'){const same=v!==1;T(`После упрощения уравнение имеет вид ${a}x + ${b} = ${a}x + ${same?b:b+c}. Сколько решений: «нет», «одно» или «любое число»?`,same?'любое число':'нет','equation',{A:a,B:b,C:a,D:same?b:b+c,solution:null});S('Что останется при вычитании '+a+'x и '+b+' из обеих частей? Введи правую часть в равенстве 0 = ... .',same?0:c,'Оба слагаемых с x исчезнут.');S('Получилось верное равенство? Да или нет.',same?'да':'нет','0=0 верно при любом x, а 0=c при c≠0 невозможно.');break;}
  if(key==='equation-parts'){A=a+1;B=0;D=A*solution;expr=`x + ${a}x = ${D}`;T(`На двух полках ${D} книг. На второй в ${a} раза больше, чем на первой. Сколько на первой? Обозначь это число x.`,solution,'equation',{A,B,C,D,solution,expr});S('Сколько равных частей всего?',a+1,'Первая полка — одна часть, вторая — a таких частей.');S('Общее число книг?',D,'Раздели целое на количество частей.');break;}
  if(key==='equation-motion'){const speed=a*5,time=b,distance=(speed+solution)*time;A=time;B=speed*time;D=distance;expr=`(${speed} + x) · ${time} = ${distance}`;T(`Два велосипедиста выехали навстречу. За ${time} ч вместе прошли ${distance} км. Скорость первого ${speed} км/ч. Найди скорость второго x.`,solution,'equation',{A,B,C,D,solution,expr});S('Скорость сближения?',distance/time,'Весь совместный путь делим на время.');S('Сколько нужно вычесть из скорости сближения?',speed,'Сумма скоростей включает известную скорость.');break;}
  if(key==='equation-transfer'){const n=c,first=solution+c+n,second=solution+c-n;T(`В первой коробке ${first} деталей, во второй ${second}. Сколько деталей надо переложить из первой во вторую, чтобы стало поровну?`,n,'equation',{A:2,B:0,C:0,D:first-second,solution:n,expr:`${first} − x = ${second} + x`});S('На сколько деталей в первой больше?',first-second,'Каждая переложенная деталь уменьшает разницу на две.');S('На сколько уменьшается разница при перекладывании одной детали?',2,'Первая теряет одну, вторая получает одну.');break;}
  if(key==='equation-mixture'){const total=100*a,p=10,p2=20,water=total/2;T(`В ${total} г раствора содержится ${p}% соли. Выпарили только воду, и стало ${p2}% соли. Сколько граммов воды выпарили?`,water,'equation',{A:q(-p2,100),B:total*p2/100,C:0,D:total*p/100,solution:water,expr:`0,2 · (${total} − x) = ${total*p/100}`,mixture:true,total});S('Сколько граммов соли было и осталось?',total*p/100,'Соль не испаряется, её масса сохраняется.');S('Какова масса нового раствора?',total/2,'Масса соли — теперь 20% новой массы.');E(total*p2/100,'20% относятся к новому раствору. Сохраняется масса соли.','percent-whole');break;}
  T(`Реши уравнение ${expr}.`,solution,'equation',{A,B,C,D,solution,expr});S('Какой коэффициент при x останется после вычитания слагаемого с x справа?',sub(A,C),'Вычти одно и то же слагаемое с x из обеих частей.');S('Какое число останется справа после вычитания свободного слагаемого слева?',sub(D,B),'Вычти B из обеих частей.');E(-solution,'Проверь знаки при вычитании одинаковых слагаемых с обеих сторон.','equation-both');break;
 }
 case 'perpendicular-angle':case 'perpendicular-build':case 'perpendicular-distance':case 'parallel-definition':case 'parallel-build':case 'parallel-grid':case 'coordinates-read':case 'coordinates-place':case 'coordinates-axis':case 'coordinates-rectangle':case 'coordinates-polygon':case 'review-geometry':{
  const x=R(-4,3),y=R(-3,3),dx=R(1,3),dy=R(1,3);
  if(key==='perpendicular-angle'){const angle=R(1,8)*10;T(`Направление первой прямой образует угол ${angle}° с горизонталью. Прибавь прямой угол: какое направление получится?`,angle+90,'construction',{angle,perpendicular:true,x,y,dx:1,dy:0});S('Сколько градусов в прямом угле?',90,'При повороте на четверть оборота получается перпендикуляр.');S('Вычесть или прибавить 90° просит условие? Введи «прибавить» или «вычесть».','прибавить','У прямой есть и противоположное направление.');}
  else if(key==='perpendicular-build'){T(`Горизонтальная прямая y=${y}. Из точки A(${x};${y+3}) опусти перпендикуляр. Введи координаты его основания через ;.`,[x,y],'construction',{x,y:y+3,targetX:x,targetY:y,baseY:y,perpendicular:true});S('Какая x-координата останется у основания?',x,'Перпендикуляр к горизонтальной прямой вертикален.');S('Какая y-координата у всех точек исходной прямой?',y,'Основание принадлежит этой прямой.');}
  else if(key==='perpendicular-distance'){T(`Найди расстояние от A(${x};${y+dy}) до горизонтальной прямой y=${y}.`,dy,'construction',{x,y:y+dy,targetX:x,targetY:y,baseY:y,perpendicular:true});S('Высота точки?',y+dy,'Отсчитываем по вертикали.');S('Высота прямой?',y,'Возьми модуль разности высот.');}
  else if(key==='parallel-definition'){const same=v!==1;T(`Одна прямая проходит по ступеньке (${dx} вправо; ${dy} вверх), другая по ступеньке (${dx*2} вправо; ${same?dy*2:dy*2+1} вверх). Прямые различны. Параллельны ли они? Да или нет.`,same?'да':'нет','construction',{x,y,dx,dy,dx2:dx*2,dy2:same?dy*2:dy*2+1});S('Во сколько раз вырос горизонтальный шаг?',2,'Вертикальный должен вырасти во столько же раз.');S('Какой вертикальный шаг требовался бы для параллельности?',dy*2,'Сравни с указанным шагом.');}
  else if(key==='parallel-build'||key==='parallel-grid'){T(`Из A(${x};${y}) повтори направление: ${dx} клетки вправо и ${dy} вверх. Каковы координаты второй точки?`,[x+dx,y+dy],'construction',{x,y,dx,dy,targetX:x+dx,targetY:y+dy});S('Новая горизонтальная координата?',x+dx,'При движении вправо x увеличивается.');S('Новая вертикальная координата?',y+dy,'Повторенная ступенька сохраняет направление.');}
  else if(key==='coordinates-axis'){const X=v===0?0:x||2,Y=v===1?0:y||-2,ans=X===0?'y':Y===0?'x':'ни одной';T(`На какой оси лежит точка (${X};${Y})? Введи x, y или «ни одной».`,ans,'coordinates',{x:X,y:Y,targetX:X,targetY:Y});S('Первая координата?',X,'На оси y она равна нулю.');S('Вторая координата?',Y,'На оси x она равна нулю.');}
  else if(key==='coordinates-read'||key==='coordinates-place'){T(`Точка расположена на ${Math.abs(x)} клетки ${x<0?'левее':'правее'} и на ${Math.abs(y)} клетки ${y<0?'ниже':'выше'} начала координат. Запиши координаты через ;.`,[x,y],'coordinates',{x,y,targetX:x,targetY:y});S('Горизонтальная координата?',x,'Влево — отрицательное направление.');S('Вертикальная координата?',y,'Вниз — отрицательное направление.');}
  else if(key==='coordinates-rectangle'){T(`Три последовательные вершины прямоугольника: (${x};${y}), (${x+dx};${y}), (${x+dx};${y+dy}). Найди четвёртую вершину.`,[x,y+dy],'coordinates',{x,y,targetX:x,targetY:y+dy,rectangle:[x,y,dx,dy]});S('x-координата четвёртой вершины?',x,'Последняя сторона должна быть вертикальной.');S('y-координата четвёртой вершины?',y+dy,'Верхняя сторона горизонтальна.');}
  else{T(`Вершины прямоугольника идут по порядку: (${x};${y}), (${x+dx};${y}), (${x+dx};${y+dy}), (${x};${y+dy}). Найди ${key==='review-geometry'?'периметр':'площадь'}.`,key==='review-geometry'?2*(dx+dy):dx*dy,'coordinates',{x,y,targetX:x+dx,targetY:y+dy,rectangle:[x,y,dx,dy]});S('Горизонтальная сторона?',dx,'Вычти x-координаты концов.');S('Вертикальная сторона?',dy,'Вычти y-координаты концов.');}break;
 }
 case 'graph-read':case 'graph-build':case 'graph-journey':case 'graph-speed':case 'graph-temperature':{
  const values=key==='graph-temperature'?[-a,b,-c]:key==='graph-journey'?[0,a,a,c<a?c:0]:[a,a+b,a+2*b,a+3*b],times=values.map((_,i)=>i*c),index=R(1,values.length-1);data.values=values;data.times=times;data.index=index;
  if(key==='graph-journey'){T(`В таблице расстояния от дома по часам: 0, ${a}, ${a}, ${values[3]} км. Какой путь пройден за три часа?`,a+Math.abs(a-values[3]),'graph',{times:[0,1,2,3]});S('Путь в первый час?',a,'Сначала расстояние от дома растёт.');S('Путь за час остановки?',0,'Расстояние постоянно.');S('Путь при возвращении?',Math.abs(a-values[3]),'Берём положительную длину участка возвращения.');E(values[3],'Это расстояние от дома в конце, а спрашивается весь путь.','graph-journey');}
  else if(key==='graph-temperature'){T(`Измерения температуры: −${a}°, ${b}°, −${c}°. Найди размах температуры.`,b+Math.max(a,c),'graph');S('Наибольшая температура?',b,'Максимум — самая высокая точка.');S('Наименьшая температура?',-Math.max(a,c),'Минимум из отрицательных дальше влево от нуля.');}
  else if(key==='graph-speed'){T(`Путь за ${c} ч изменился с ${a} до ${a+b} км. Найди скорость в км/ч.`,q(b,c),'graph');S('Изменение пути?',b,'Конечный путь минус начальный.');S('Длительность участка?',c,'Раздели приращение пути на приращение времени.');}
  else if(key==='graph-build'){T(`В таблице время ${times.join('; ')} и значение ${values.join('; ')}. Запиши координаты точки для времени ${times[index]} через ;.`,[times[index],values[index]],'graph');S('Горизонтальная координата?',times[index],'На оси x отмечено время.');S('Вертикальная координата?',values[index],'Бери значение из того же столбца.');}
  else{T(`В таблице время ${times.join('; ')} и значение ${values.join('; ')}. Найди значение при времени ${times[index]}.`,values[index],'graph');S('Номер нужного столбца, если первый считать первым?',index+1,'Найди время в первой строке.');S('Какое значение стоит под этим временем?',values[index],'Следи за соответствием строк.');}break;
 }
 case 'review-numbers':case 'review-fractions':case 'review-ratios':case 'review-signed':case 'project-budget':case 'project-garden':case 'project-route':{
  if(key==='review-numbers'){const count=b,mean=a*100,p=pick([10,15,20,25]),total=count*mean;T(`Средняя цена ${count} товаров — ${mean} руб. На всю покупку скидка ${p}%. Сколько заплатят?`,total*(100-p)/100,'percent',{total,percent:100-p});S('Стоимость до скидки?',total,'Среднее умножаем на количество.');S('Сколько процентов цены останется?',100-p,'Скидка вычитается из 100%.');}
  if(key==='review-fractions'){const u=q(1,a),w=q(1,b),den=q(c,a*b);T(`Вычисли (${F(u)} + ${F(w)}) : ${F(den)}.`,div(add(u,w),den),'fraction',{u,w,divisor:den});S('Общий знаменатель первых двух дробей?',a*b/M.gcd(a,b),'Найди НОК знаменателей.');S('Сумма в скобках?',add(u,w),'Сначала скобки, затем деление.');S('Дробь, обратная делителю?',div(1,den),'Деление заменяем умножением на обратную.');}
  if(key==='review-ratios'){const workers=a,days=b,gardens=c,newWorkers=a*c,newGardens=b;T(`${workers} землекопов обрабатывают ${gardens} одинаковых огородов за ${days} дней. Сколько дней нужно ${newWorkers} таким землекопам для ${newGardens} огородов?`,q(workers*days*newGardens,gardens*newWorkers),'work',{workers,days,gardens,newWorkers,newGardens});S('Человеко-дней на один огород?',q(workers*days,gardens),'Сначала приведи работу к одному огороду.');S('Человеко-дней на новый объём?',q(workers*days*newGardens,gardens),'Умножь на число новых огородов.');}
  if(key==='review-signed'){T(`Вычисли −${a} − (−${b}) · ${c}.`,-a+b*c,'chips',{u:q(-a),w:q(b*c),op:'+',values:[-a,b*c]});S('Произведение в выражении?',-b*c,'Умножение раньше вычитания.');S('Число, которое теперь прибавим к −'+a+'?',b*c,'Вычитание отрицательного заменяем сложением.');}
  if(key==='project-budget'){const price=a*100,count=c,p=pick([10,15,20,25]),delivery=b*20,total=price*count;T(`${count} наборов по ${price} руб. продают со скидкой ${p}%. Доставка ${delivery} руб. без скидки. Найди весь платёж.`,total*(100-p)/100+delivery,'percent',{total,percent:100-p,delivery});S('Цена наборов до скидки?',total,'Количество умножь на цену.');S('Цена наборов после скидки?',total*(100-p)/100,'Доставку ещё не включаем.');S('Стоимость доставки?',delivery,'Её прибавляем полностью.');}
  if(key==='project-garden'){const scale=pick([100,200,500]),length=a,width=b,den=c,area=length*width*(scale/100)**2;T(`На плане 1:${scale} прямоугольный огород ${length} см на ${width} см. Под зелень отвели 1/${den} площади. Сколько м² под зеленью?`,q(area,den),'scale',{scale,length,width,area,den});S('Настоящая длина в метрах?',length*scale/100,'Сначала восстанови длину, затем переведи сантиметры в метры.');S('Настоящая ширина в метрах?',width*scale/100,'Масштаб действует на обе длины.');S('Полная площадь в м²?',area,'Перемножь настоящие длины.');}
  if(key==='project-route'){const s1=a*10,s2=b*10,t1=2,t2=1,stop=q(1,2),distance=s1*t1+s2*t2;T(`Ехали ${t1} ч со скоростью ${s1} км/ч и ${t2} ч со скоростью ${s2} км/ч. Затем остановка 0,5 ч. Найди среднюю скорость всей поездки.`,q(distance*2,7),'motion',{s1,s2,t1,t2,stop,distance});answer=q(distance*2,7);S('Общий путь?',distance,'Сложи произведения скорости на время движения.');S('Всё время с остановкой?',q(7,2),'Включи и время без движения.');E((s1+s2)/2,'Скорости нельзя просто усреднить: длительности различны, есть остановка.','mean-weighted');}break;
 }
 default:throw Error('Неизвестное занятие подробного курса: '+id);
 }
 for(const s of steps){if(Array.isArray(s.answer)&&format==='unordered')s.answerFormat='unordered';}
 model.key=key;model.data=data;
 return {prompt,answer,steps,model,data,errors,alternatives,answerFormat:format,v6Full:true,unit:''};
}
function install(M){
 const oldGenerate=M.generate,oldAccepts=M.accepts;
 M.generate=function(id,seed){return id.startsWith('v6f-')?generate(id,seed,M):oldGenerate(id,seed);};
 M.accepts=function(text,target){
  if(!target.v6Full)return oldAccepts(text,target);
  if(target.answerFormat==='unordered'){
   const parts=String(text).replace(/−/g,'-').split(';').map(x=>x.trim());const remaining=(Array.isArray(target.answer)?target.answer:[target.answer]).slice();
   return parts.length===remaining.length&&parts.every(p=>{const i=remaining.findIndex(a=>M.equal(p,a));if(i<0)return false;remaining.splice(i,1);return true;});
  }
  if(typeof target.answer==='string')return [target.answer,...(target.alternatives||[])].some(a=>normalize(text)===normalize(a));
  return oldAccepts(text,target)||(target.alternatives||[]).some(a=>M.equal(text,a));
 };
}
const API={generate,install};if(typeof module!=='undefined'&&module.exports)module.exports=API;else{root.WorkshopV6Math=API;install(root.WorkshopMath);}
})(typeof window!=='undefined'?window:globalThis);
