(function(root){
'use strict';
const FAMILIES={
 'fraction-parts':'parts','fraction-line':'parts','fraction-same-compare':'compare','fraction-unit-compare':'compare','fraction-kind':'parts','fraction-same-add':'add','fraction-same-sub':'subtract','fraction-sharing':'divide','mixed-extract':'parts','mixed-convert':'parts','mixed-add':'add','mixed-subtract':'subtract','mixed-borrow':'subtract','whole-minus-fraction':'subtract','fraction-equivalent':'equivalent','fraction-convert':'equivalent','fraction-reduce':'equivalent','fraction-reduce-check':'equivalent','fraction-lcd':'equivalent','fraction-compare':'compare','fraction-add':'add','fraction-subtract':'subtract','fraction-brackets':'subtract','fraction-times-int':'multiply','fraction-multiply':'multiply','fraction-cancel':'multiply','mixed-multiply':'multiply','fraction-area':'multiply','fraction-part':'multiply','fraction-remain':'subtract','fraction-of-remainder':'multiply','reciprocal':'divide','fraction-divide-int':'divide','fraction-divide':'divide','mixed-divide':'divide','fraction-unit-rate':'divide','whole-from-fraction':'divide','whole-from-remainder':'divide','whole-two-parts':'divide','review-fractions':'divide'
};
function generate(id,seed,M,old,C){
 const k=id.slice(4),R=M.rng(seed*4201+[...k].reduce((s,c)=>s+c.charCodeAt(0)*19,1709)),pick=xs=>xs[R(0,xs.length-1)],q=M.q,F=M.fmt,add=M.add,sub=M.sub,mul=M.mul,div=M.div,N=x=>typeof x==='object'?x.n/x.d:x,D=x=>String(N(x)).replace('.',',');
 const a=R(2,9),b=R(2,8),c=R(2,6);let data={key:k,a,b,c},steps=[],errors=[],answer,prompt,model={kind:'v5lab',family:'number'},format='';
 const S=(p,z,why,extra)=>steps.push({prompt:p,answer:z,why,hints:[why,extra||p],v6Full:true}),T=(p,z,f,raw)=>{prompt=p;answer=z;if(f)model={kind:'v5lab',family:f};Object.assign(data,raw||{});},E=(value,text,remedy)=>errors.push({value,text,remedy:remedy?'v5f-'+remedy:''});
 if(C.byId[id].sharedKey){const t=old('v6f-'+C.byId[id].sharedKey,seed);t.v5Full=true;t.data.sharedKey=C.byId[id].sharedKey;for(const part of [t,...t.steps])for(const e of part.errors||[]){const candidate=e.remedy?.replace('v6f-','v5f-');if(C.byId[candidate])e.remedy=candidate;}if(FAMILIES[k])t.model={kind:'v5lab',family:'fraction',op:FAMILIES[k],data:t.data};return t;}
 switch(k){
 case 'table-read':case 'table-total':case 'chart-read':case 'chart-difference':{
  const values=[a*5,b*5,c*5],labels=['Понедельник','Вторник','Среда'],i=R(0,2);data={...data,values,labels,i};
  if(k==='table-read'){T(`В таблице «Выдано книг»: понедельник — ${values[0]}, вторник — ${values[1]}, среда — ${values[2]}. Сколько книг выдано в ${['понедельник','вторник','среду'][i]}?`,values[i],'chart');S('В каких единицах данные: книги или часы?','книги','Название измеряемой величины указано в таблице.');S('Какой номер строки нужен: 1, 2 или 3?',i+1,'Сопоставь день с подписью строки.');}
  else if(k==='table-total'){const total=values.reduce((s,n)=>s+n,0);T(`За три дня выдали ${total} книг. В понедельник ${values[0]}, во вторник ${values[1]}. Сколько в среду?`,values[2],'chart');S('Сколько книг выдали за первые два дня?',values[0]+values[1],'Сначала сложи известные части.');S('Какое действие находит остаток: сложение или вычитание?','вычитание','Из общего количества убираем известное.');}
  else if(k==='chart-read'){T(`На диаграмме одна клетка означает ${c} книг. Столбец «Вторник» имеет высоту ${b} клеток. Сколько книг он изображает?`,c*b,'chart',{step:c,height:b});S('Сколько книг в одной клетке?',c,'Прочитай цену деления.');S('Сколько одинаковых клеток надо взять?',b,'Высота задана количеством клеток.');}
  else{T(`Диаграмма показывает ${a*5+b*5} посетителей в субботу и ${b*5} в воскресенье. На сколько больше было в субботу?`,a*5,'chart',{first:a*5+b*5,second:b*5});S('Сколько посетителей было в субботу?',a*5+b*5,'Сравниваем именно эти две категории.');S('Для вопроса «на сколько» нужно вычитание или деление?','вычитание','Разность показывает добавочную часть.');}break;
 }
 case 'place-value':case 'place-build':case 'place-neighbors':{
  const digits=[a,0,b,c],n=1000*a+10*b+c;data.digits=digits;data.n=n;
  if(k==='place-value'){const pos=R(0,3),units=[1000,100,10,1];T(`Каков вклад цифры ${digits[pos]} в разряде ${['тысяч','сотен','десятков','единиц'][pos]} числа ${n}?`,digits[pos]*units[pos],'number',{pos});S('Сколько единиц в одном таком разряде?',units[pos],'Разряд определяет вес цифры.');S('Какую цифру умножаем на этот вес?',digits[pos],'Цифра может быть нулём.');}
  else if(k==='place-build'){T(`Запиши число: ${a} тысячи, 0 сотен, ${b} десятков и ${c} единиц.`,n,'number');S('Вклад тысяч?',a*1000,'Умножь число тысяч на тысячу.');S('Вклад десятков?',b*10,'Не теряй нулевой разряд сотен.');E(a*100+b*10+c,'Пропущен ноль сотен: тысячи стали сотнями.','place-value');}
  else{const center=a*1000;T(`Запиши предыдущее и следующее натуральные числа для ${center} через точку с запятой.`,[center-1,center+1],'number',{center});S('На сколько соседние натуральные числа отличаются?',1,'Делаем один шаг по числовому ряду.');S('Предыдущее число?',center-1,'Вычитаем единицу с переходом через нули.');}break;
 }
 case 'segment-length':case 'broken-length':case 'length-units':case 'scale-step':case 'scale-point':case 'natural-between':{
  if(k==='segment-length'){T(`Концы отрезка на линейке стоят на отметках ${a} см и ${a+b+c} см. Найди длину.`,b+c,'line',{start:a,end:a+b+c});S('Начальная отметка?',a,'Из конечной отметки вычтем начальную.');S('Конечная отметка?',a+b+c,'Сдвиг начала не должен входить в длину.');E(a+b+c,'Это отметка конца, а длина начинается не от нуля.','segment-length');}
  else if(k==='broken-length'){const sides=[a,b,c,a+1];T(`У замкнутой ломаной стороны ${sides.join(', ')} см. Найди периметр.`,2*a+b+c+1,'line',{sides});S('Сумма первых двух сторон?',a+b,'Считаем каждую сторону один раз.');S('Сумма двух остальных?',c+a+1,'Осталось сложить две полученные суммы.');}
  else if(k==='length-units'){T(`Вырази ${a} м ${b} см в сантиметрах.`,100*a+b,'number');S('Сколько сантиметров в метре?',100,'Единица длины стала меньше.');S(`Сколько сантиметров в ${a} метрах?`,100*a,'После перевода добавь оставшиеся сантиметры.');}
  else if(k==='natural-between'){const low=a*10,high=low+b;T(`Сколько натуральных чисел удовлетворяют ${low}<n<${high}?`,b-1,'line',{low,high});S('Наименьшее подходящее число?',low+1,'Левая граница не входит.');S('Наибольшее подходящее число?',high-1,'Правая граница тоже не входит.');}
  else if(k==='scale-step'){T(`Между отметками ${a*10} и ${a*10+b*c} на шкале ${b} равных промежутков. Найди цену деления.`,c,'line',{start:a*10,end:a*10+b*c,intervals:b});S('Разность подписанных значений?',b*c,'Сначала найди величину всего отрезка.');S('На сколько промежутков делим эту разность?',b,'Риски и промежутки имеют разное количество.');}
  else{T(`Цена деления ${c}. Точка стоит через ${a} промежутков вправо от нуля. Найди координату.`,a*c,'line');S('Значение одного промежутка?',c,'Это единица счёта по шкале.');S('Сколько промежутков прошли?',a,'Умножь количество на цену деления.');}break;
 }
 case 'line-ray':case 'angle-parts':case 'circle-shapes':{
  if(k==='line-ray'){const kind=pick(['отрезок','луч','прямая']),count={отрезок:2,луч:1,прямая:0}[kind];T(`Фигура — ${kind}. Сколько у неё концов?`,count,'line',{kind});S('Нужно считать границы рисунка или самой фигуры?','фигуры','Бесконечную фигуру на листе изображают только частично.');S('Может ли видимая часть быть короче самой фигуры? Ответь да или нет.','да','У луча и прямой продолжение бесконечно.');}
  else if(k==='angle-parts'){const names=pick(['ABC','KLM','PQR']);T(`Какая буква обозначает вершину угла ${names}?`,names[1],'angle',{names});S('Какой по порядку буквой записывают вершину?',2,'Вершина — общее начало лучей.');S('Сколько сторон у угла?',2,'Стороны являются лучами.');}
  else{const i=R(0,3),name=['окружность','круг','шар','цилиндр'][i];T(['Как называется граница круга?','Как называется плоская фигура вместе с внутренностью, ограниченная окружностью?','Как называется тело, похожее на мяч?','Как называется тело с двумя равными круглыми основаниями, похожее на прямую банку?'][i],name,'circle',{i});S('Плоская фигура или тело: что спрашивается? Введи фигура или тело.',i<2?'фигура':'тело','Отделяем плоское от объёмного.');S('Шар имеет объём? Ответь да или нет.','да','Шар — тело, в отличие от круга.');}break;
 }
 case 'natural-compare':{const x=a*1000+b*100+R(0,99),y=a*1000+c*100+R(0,99);T(`Сравни ${x} и ${y}. Введи <, > или =.`,x>y?'>':x<y?'<':'=','number',{x,y});S('Сколько цифр у каждого числа?',4,'Количество разрядов одинаково.');S('С какого направления сравниваем цифры: слева или справа?','слева','Решает первый отличающийся разряд.');break;}
 case 'natural-add':case 'add-smart':case 'sum-change':case 'natural-subtract':case 'subtract-sum':case 'difference-change':{
  const x=a*100+R(0,99),y=b*10+c;data.x=x;data.y=y;
  if(k==='natural-add'){T(`Вычисли ${x}+${y}.`,x+y,'column');S('Сумма единиц этих чисел?',x%10+y%10,'Из десяти единиц образуется десяток.');S('Сколько десятков переносится из единиц?',Math.floor((x%10+y%10)/10),'Учти этот перенос при сложении десятков.');}
  else if(k==='add-smart'){const first=R(11,89),last=100-first;T(`Вычисли удобно: ${first}+${y}+${last}.`,100+y,'number',{first,last});S('Какую сумму даёт удобная пара?',100,'Первое и третье слагаемые дополняют до ста.');S('Какое слагаемое осталось?',y,'Сложи его с круглым числом.');}
  else if(k==='sum-change'){T(`Вычисли ${a*10-1}+${y}. Перенеси единицу от второго слагаемого к первому.`,a*10-1+y,'number',{x:a*10-1});S('Первое слагаемое после переноса?',a*10,'Оно увеличилось на 1.');S('Второе слагаемое после переноса?',y-1,'Оно должно уменьшиться на ту же единицу.');}
  else if(k==='natural-subtract'){const xx=a*100+R(0,3);T(`Вычисли ${xx}−${y}.`,xx-y,'column',{x:xx});S('Сколько единиц даст размен одного десятка?',10,'Размен сохраняет число.');S('Какое сложение проверит результат? Введи число, которое надо прибавить к разности.',y,'Разность плюс вычитаемое равна уменьшаемому.');}
  else if(k==='subtract-sum'){T(`Вычисли ${x}−(${y}+${c}).`,x-y-c,'number');S('Сумма в скобках?',y+c,'Убрать нужно обе части.');S('После раскрытия скобок перед вторым числом будет плюс или минус?','минус','Вычитание суммы — последовательное вычитание слагаемых.');}
  else{const yy=b*10-1;T(`Вычисли удобно: ${x}−${yy}. Увеличь оба числа на 1.`,x-yy,'line',{y:yy});S('Новое уменьшаемое?',x+1,'Сдвигаем обе точки одинаково.');S('Новое вычитаемое?',yy+1,'Разность сохраняется.');}break;
 }
 case 'expression-value':case 'expression-story':case 'equation-add':case 'equation-sub':case 'equation-story':{
  if(k==='expression-value'){T(`Найди ${b}a+${c} при a=${a}.`,a*b+c,'number');S('Чему равно произведение после подстановки?',a*b,'Заменяем букву данным числом.');S('Какое действие осталось: сложение или умножение?','сложение','Умножение уже выполнено.');}
  else if(k==='expression-story'){const price=b*10;T(`Купили ${a} альбомов по ${price} рублей. Доставка всего заказа ${c*10} рублей. Сколько заплатили?`,a*price+c*10,'number',{price});S('Стоимость альбомов?',a*price,'Умножаем количество на цену.');S('Сколько раз добавляем доставку?',1,'Она относится ко всему заказу.');}
  else if(k==='equation-add'){const x=a*10;T(`Реши x+${b}=${x+b}.`,x,'equation',{x,form:'add'});S('Какое действие нужно для неизвестного слагаемого: сложение или вычитание?','вычитание','Из суммы убираем известную часть.');S('Из какого числа вычитаем?',x+b,'Это правая часть равенства.');}
  else if(k==='equation-sub'){const x=a*10,sw=seed%2;T(sw?`Реши x−${b}=${x-b}.`:`Реши ${x+b}−x=${b}.`,x,'equation',{x,sw,form:'sub'});S('Неизвестное — уменьшаемое или вычитаемое?',sw?'уменьшаемое':'вычитаемое','Роль неизвестного определяет обратное действие.');S('Сколько получится в левой части после верной подстановки?',sw?x-b:b,'Она должна совпасть с правой частью.');}
  else{T(`После продажи ${a} билетов осталось ${b*10}. Сколько было?`,a+b*10,'equation',{form:'story'});S('Проданные и оставшиеся — части или целое?','части','Вместе они составляют исходное количество.');S('Нужно сложение или вычитание?','сложение','Восстанавливаем целое из частей.');}break;
 }
 case 'equation-product':case 'equation-quotient':{
  const x=a+c,total=x*b,swap=seed%2;data.x=x;data.total=total;data.swap=swap;
  if(k==='equation-product'){T(`Реши ${b}·x=${total}.`,x,'equation');S('Произведение?',total,'Это результат умножения.');S('На какой известный множитель делим произведение?',b,'Получим неизвестный множитель.');}
  else{T(swap?`Реши x:${b}=${x}.`:`Реши ${total}:x=${b}.`,swap?total:x,'equation');S('Что неизвестно: делимое или делитель?',swap?'делимое':'делитель','Важна позиция x относительно знака деления.');S('Нужно умножение или деление?',swap?'умножение':'деление','Проверь результат обратным действием.');}
  break;
 }
 case 'natural-multiply':case 'multiply-column':case 'division-share':case 'division-measure':case 'division-column':case 'remainder-find':case 'remainder-pack':{
  if(k==='natural-multiply'){T(`В ${a} рядах по ${b} мест. Сколько мест?`,a*b,'array',{x:a,y:b});S('Мест в одном ряду?',b,'Размер одинаковой группы.');S('Сколько групп?',a,'Умножаем, а не складываем размеры и количество.');}
  else if(k==='multiply-column'){const x=a*10+c,y=b*10+c;T(`Вычисли ${x}·${y}.`,x*y,'array',{x,y});S(`Произведение на единицы ${c}?`,x*c,'Первое частичное произведение.');S(`Произведение на ${b} десятков?`,x*b*10,'Десятки в десять раз крупнее единиц.');}
  else if(k==='division-column'){const result=a*100+c,divisor=b,total=result*divisor;T(`Вычисли уголком ${total}:${divisor}.`,result,'longdivision',{total,divisor});S('Первая цифра частного (сотни)?',a,'Подбирай цифру по первому неполному делимому.');S('Цифра десятков в частном?',0,'Нулевой разряд нельзя пропустить.');S('Последняя цифра частного?',c,'Проверь умножением на делитель.');E(a*10+c,'Пропущен ноль десятков в частном.','place-value');}
  else if(k==='division-share'||k==='division-measure'){T(k==='division-share'?`${a*b} карточек разложили поровну в ${a} конвертов. Сколько карточек в каждом?`:`${a*b} карточек раскладывают по ${a} в конверт. Сколько конвертов?`,b,'array',{total:a*b,divisor:a});S('Делимое — всё количество. Чему оно равно?',a*b,'Считаем общий запас.');S('Делитель?',a,'Это либо число групп, либо размер группы, как сказано в условии.');}
  else{const divisor=b+1,quot=a*2,rem=R(1,divisor-1),total=divisor*quot+rem;T(k==='remainder-find'?`Раздели ${total} на ${divisor} с остатком. Ответ: неполное частное; остаток.`:`${total} книг нужно упаковать все. В коробке не более ${divisor}. Сколько коробок нужно?`,k==='remainder-find'?[quot,rem]:quot+1,'array',{total,divisor,quot,rem});S('Сколько полных групп?',quot,'Подбери произведение не больше всего количества.');S('Сколько осталось вне полных групп?',rem,'Остаток меньше делителя; для упаковки всего понадобится ещё одна коробка.');}break;
 }
 case 'order-brackets':case 'order-equal':case 'power-read':case 'power-order':case 'calculator-order':{
  if(k==='order-brackets'){const start=a*(b+c)+c;T(`Вычисли ${start}−${a}·(${b}+${c}).`,c,'number',{start});S('Значение в скобках?',b+c,'Первый приоритет у скобок.');S('Произведение перед вычитанием?',a*(b+c),'Умножение раньше вычитания.');}
  else if(k==='order-equal'){T(`Вычисли ${a*b}:${b}·${c}.`,a*c,'number');S('Какое действие первым: деление или умножение?','деление','Равноправные действия идут слева направо.');S('Результат первого действия?',a,'Теперь умножай на последний множитель.');}
  else if(k==='power-read'){const base=c,pow=pick([2,3,4]);T(`Вычисли ${base} в степени ${pow}.`,base**pow,'array',{base,pow});S('Какой множитель повторяется?',base,'Это основание.');S('Сколько раз он повторяется?',pow,'Это показатель степени.');E(base*pow,'Ты умножил основание на показатель. Степень повторяет основание множителем.','power-read');}
  else if(k==='power-order'){T(`Вычисли ${a}·${b}²+${c}.`,a*b*b+c,'number');S('Значение степени?',b*b,'Квадрат означает два одинаковых множителя.');S('Значение произведения?',a*b*b,'Теперь добавь последнее число.');}
  else{T(`Найди ${a}+${b}·${c}. Калькулятор с последовательным вводом не учитывает приоритет. Сначала вычисли произведение.`,a+b*c,'number');S('Произведение?',b*c,'Отдельно введи умножение.');S('Что к нему прибавить?',a,'Так порядок действий будет соблюдён.');}break;
 }
 case 'divisors-all':{const n=pick([12,18,20,24,30,36,40,42,48,60]);const ds=Array.from({length:n},(_,i)=>i+1).filter(x=>n%x===0);T(`Выпиши все положительные делители ${n} через точку с запятой.`,ds,'factors',{n});format='unordered';S('Наименьший положительный делитель?',1,'Единица делит любое натуральное число.');S('Наибольший делитель?',n,'Число делится на себя. Проверь промежуточные пары множителей.');break;}
 case 'divisibility-digit':{const tens=a,divisor=pick([3,9]);const digits=Array.from({length:10},(_,i)=>i).filter(x=>(tens*10+x)%divisor===0);T(`Число ${tens}? делится на ${divisor}. Найди все возможные цифры вместо ?. Запиши через точку с запятой.`,digits,'factors',{tens,divisor});format='unordered';S('Какая известная часть суммы цифр?',tens,'Сумма цифр должна делиться на '+divisor+'.');S('Наибольшая допустимая цифра вообще?',9,'Проверь все цифры от 0 до 9, не только первую подходящую.');break;}
 case 'formula-distance':case 'formula-perimeter':case 'area-grid':case 'area-missing':case 'area-cut':case 'area-units':case 'land-units':case 'solid-elements':case 'solid-surface':case 'volume-layers':case 'volume-litres':case 'circle-radius':{
  if(k==='formula-distance'){T(`Скорость ${a*3} км/ч, движение ${b} ч без остановок. Найди путь в километрах.`,a*3*b,'motion',{speed:a*3,time:b});S('Путь за один час?',a*3,'Это скорость в км/ч.');S('Число одинаковых часовых участков?',b,'Умножаем на время.');}
  else if(k==='formula-perimeter'){T(`У прямоугольника стороны ${a} и ${b} см. Найди периметр.`,2*(a+b),'area');S('Сумма двух разных сторон?',a+b,'Ещё две стороны повторяют эти длины.');S('Сколько таких пар сторон?',2,'Удваиваем всю сумму.');}
  else if(k==='area-grid'){T(`Прямоугольник ${a} на ${b} см. Найди площадь в см².`,a*b,'area');S('Квадратиков 1 см² в одном ряду?',a,'Считаем по длине.');S('Сколько рядов?',b,'Умножаем количество в ряду на число рядов.');}
  else if(k==='area-missing'){T(`Площадь прямоугольника ${a*b} см², длина ${a} см. Найди ширину.`,b,'area');S('Какое действие обратное умножению: деление или сложение?','деление','Стороны перемножаются для площади.');S('На какое число делим площадь?',a,'Это известная сторона.');}
  else if(k==='area-cut'){const x=a+c,y=b+c;T(`Из прямоугольника ${x}×${y} вырезали угол ${a}×${b}. Найди оставшуюся площадь.`,x*y-a*b,'area',{x,y});S('Площадь большого прямоугольника?',x*y,'Сначала всё покрытие.');S('Площадь выреза?',a*b,'Вырез вычитаем один раз.');}
  else if(k==='area-units'){const unit=pick(['м²','дм²']),factor=unit==='м²'?10000:100;T(`Вырази ${a} ${unit} в см².`,a*factor,'area',{unit,factor});S('Во сколько раз меняется единица длины?',Math.sqrt(factor),'Для площади меняются сразу два измерения.');S('Во сколько раз меняется единица площади?',factor,'Возводим коэффициент длины в квадрат.');}
  else if(k==='land-units'){T(`Вырази ${a} га ${b} а в м².`,a*10000+b*100,'area');S('Площадь гектаров в м²?',a*10000,'Гектар содержит 10 000 м².');S('Площадь аров в м²?',b*100,'Ар содержит 100 м².');}
  else if(k==='solid-elements'){T(`У прямоугольного параллелепипеда измерения ${a}, ${b}, ${c} см. Найди сумму длин всех рёбер.`,4*(a+b+c),'solid');S('Сумма трёх разных измерений?',a+b+c,'Это три направления рёбер.');S('Рёбер каждого направления?',4,'Не считай только видимые на рисунке.');}
  else if(k==='solid-surface'){T(`Коробка ${a}×${b}×${c} см закрыта со всех сторон. Найди площадь поверхности.`,2*(a*b+a*c+b*c),'solid');S('Сумма площадей трёх разных граней?',a*b+a*c+b*c,'У каждой грани есть равная противоположная.');S('На какое число умножаем эту сумму?',2,'Считаем все шесть граней.');}
  else if(k==='volume-layers'){T(`Параллелепипед ${a}×${b}×${c} см. Найди объём в см³.`,a*b*c,'solid');S('Кубиков в одном слое?',a*b,'Площадь основания в единичных квадратах.');S('Количество слоёв?',c,'В каждом слое одинаковое число кубиков.');}
  else if(k==='volume-litres'){T(`Вырази ${a} л ${b*25} мл в миллилитрах.`,a*1000+b*25,'number');S('Сколько миллилитров в литре?',1000,'Это тысяча равных мелких объёмов.');S('Сколько миллилитров в целой части?',a*1000,'Теперь прибавь остаток.');}
  else{const reverse=seed%2;T(reverse?`Диаметр окружности ${2*a} см. Найди радиус.`:`Радиус окружности ${a} см. Найди диаметр.`,reverse?a:2*a,'circle',{reverse});S('Сколько радиусов укладывается в диаметре?',2,'Они идут от центра в противоположные стороны.');S('Нужно умножение или деление?',reverse?'деление':'умножение','Восстанавливаем нужное измерение по двойному отношению.');}break;
 }
 case 'fraction-parts':case 'fraction-line':case 'fraction-same-compare':case 'fraction-unit-compare':case 'fraction-kind':case 'fraction-same-add':case 'fraction-same-sub':case 'fraction-sharing':case 'mixed-extract':case 'fraction-reduce':case 'fraction-reduce-check':{
  const den=b+4,n=R(1,den-1),m=R(1,den-1);data.den=den;data.n=n;data.m=m;
  if(k==='fraction-parts'){T(`Одинаковое целое разделили на ${den} равных долей. Выбрали ${n}. Какую долю целого выбрали?`,q(n,den),'fraction');S('Знаменатель?',den,'Всего равных частей в единице.');S('Числитель?',n,'Выбрано именно столько частей.');}
  else if(k==='fraction-line'){const num=den+n;T(`Каждая единица прямой поделена на ${den} равных промежутков. Точка через ${num} таких промежутков от нуля. Запиши координату дробью.`,q(num,den),'fraction',{num});S('Размер одного промежутка?',q(1,den),'Это одна доля единицы.');S('Сколько целых единиц прошли?',1,'После первой единицы остаётся ещё несколько долей.');}
  else if(k==='fraction-same-compare'){T(`Сравни ${n}/${den} и ${m}/${den}. Введи <, > или =.`,n>m?'>':n<m?'<':'=','fraction');S('Размер одной доли в обеих дробях?',q(1,den),'Знаменатели одинаковые.');S('Сравниваем числители или знаменатели?','числители','Размер частей уже один и тот же.');}
  else if(k==='fraction-unit-compare'){const other=den+c;T(`Сравни 1/${den} и 1/${other}. Введи <, > или =.`,'>','fraction',{other});S('На сколько частей поделили первое целое?',den,'Целые одинакового размера.');S('При увеличении числа частей одна доля уменьшается или увеличивается?','уменьшается','Тот же запас разрезан мельче.');}
  else if(k==='fraction-kind'){const num=pick([n,den,den+n]);T(`Дробь ${num}/${den} правильная или неправильная?`,num<den?'правильная':'неправильная','fraction',{num});S('Сравни числитель со знаменателем: <, > или =.',num<den?'<':num===den?'=':'>','Проверяем, достигнута ли единица.');S('Дробь со значением 1 правильная? Ответь да или нет.','нет','Числитель уже не меньше знаменателя.');}
  else if(k==='fraction-same-add'||k==='fraction-same-sub'){const plus=k==='fraction-same-add',nn=plus?n:Math.max(n,m),mm=plus?m:Math.min(n,m);T(`Вычисли ${nn}/${den} ${plus?'+':'−'} ${mm}/${den}.`,q(plus?nn+mm:nn-mm,den),'fraction',{n:nn,m:mm});S('Какой знаменатель останется?',den,'Размер доли не изменяется.');S('Числитель до сокращения?',plus?nn+mm:nn-mm,'Соединяем или убираем части одинакового размера.');E(q(plus?nn+mm:nn-mm,2*den),'Знаменатель не складывается: размер доли остаётся прежним.','fraction-parts');}
  else if(k==='fraction-sharing'){T(`${a} одинаковых пирогов разделили поровну между ${den} друзьями. Сколько пирога получил каждый?`,q(a,den),'fraction');S('На сколько частей режем каждый пирог?',den,'По одной части каждому другу.');S('Сколько таких долей достанется каждому?',a,'По одной от каждого пирога.');}
  else if(k==='mixed-extract'){const num=a*den+n;T(`Выдели целую часть ${num}/${den}. Запиши: целая часть; числитель оставшейся дробной части (знаменатель ${den}).`,[a,n],'fraction',{num});S('Неполное частное числителя и знаменателя?',a,'Это число полных целых.');S('Остаток деления?',n,'Он меньше знаменателя и становится числителем.');}
  else{const g=M.gcd(n,den),nn=n/g,dd=den/g,factor=k==='fraction-reduce-check'?a*c:a;T(`Сократи ${nn*factor}/${dd*factor} до несократимой дроби.`,q(nn,dd),'fraction',{num:nn*factor,den:dd*factor});format='reduced-fraction';S('Наибольший общий делитель числителя и знаменателя?',factor,'Можно делить постепенно или сразу на НОД.');S('Новый знаменатель после деления на НОД?',dd,'На этот же делитель делится и числитель.');}break;
 }
 case 'decimal-place':case 'decimal-fraction':case 'decimal-zeros':case 'decimal-compare':case 'decimal-between':{
  if(k==='decimal-place'){const num=a*1000+b*100+c;T(`Каков вклад цифры ${c} в числе ${D(q(num,1000))}? Запиши её значение десятичной дробью.`,q(c,1000),'decimal',{num,scale:1000});S('Какой это разряд: десятые, сотые или тысячные?','тысячные','После запятой считаем три позиции.');S('Знаменатель дроби этого разряда?',1000,'Цифра показывает число тысячных.');}
  else if(k==='decimal-fraction'){const num=a*10+c;T(`Запиши ${D(q(num,1000))} обыкновенной несократимой дробью.`,q(num,1000),'decimal',{num,scale:1000});format='reduced-fraction';S('Знаменатель до сокращения?',1000,'В записи три знака после запятой, включая ведущий ноль.');S('Числитель до сокращения?',num,'Сколько всего тысячных?');}
  else if(k==='decimal-zeros'){const x=q(a*10+b,10);T(`Записи ${D(x)} и ${D(x)}00 равны? Ответь да или нет.`,'да','decimal',{x});S('Меняется ли значение при добавлении нулей справа после запятой? Ответь да или нет.','нет','Десятые можно раздробить на сотые.');S('Одна десятая — сколько сотых?',10,'Смена записи сохраняет величину.');}
  else if(k==='decimal-compare'){const x=q(a,10),y=q(a*10-c,100);T(`Сравни ${D(x)} и ${D(y)}. Введи <, > или =.`,'>','decimal',{x,y});S('Сколько сотых в первом числе?',a*10,'Десятые переводим в сотые.');S('Сколько сотых во втором?',a*10-c,'Теперь можно сравнить целые количества сотых.');}
  else{const left=q(a,10),right=q(a+1,10),middle=q(2*a+1,20);T(`Найди число точно посередине между ${D(left)} и ${D(right)}.`,middle,'decimal',{left,right});S('Расстояние между границами?',q(1,10),'Соседние десятые отличаются на 0,1.');S('Половина этого расстояния?',q(1,20),'Добавь её к левой границе.');}break;
 }
 case 'decimal-add':case 'decimal-carry':case 'decimal-subtract':case 'decimal-borrow':case 'decimal-money':case 'decimal-times-int':case 'decimal-times-ten':case 'decimal-divide-int':case 'decimal-divide-zero':case 'decimal-divide-ten':case 'decimal-multiply':case 'decimal-small-product':case 'decimal-area':case 'decimal-divide':case 'decimal-portion':case 'decimal-reverse':case 'project-recipe':{
  let x=q(a*10+b,10),y=q(b*10+c,100),op='add',sx=10,sy=100;
  if(k==='decimal-carry'){x=q(a*10+8,100);y=q(b*10+7,100);sx=100;}
  if(k==='decimal-subtract'||k==='decimal-borrow'||k==='decimal-money')op='subtract';
  if(k==='decimal-borrow'){x=q(a);y=q(b*10+c,100);sx=1;}
  if(k==='decimal-money'){x=q(a*100);y=add(q(b*100+c*25,100),q(c*100+b*25,100));sx=100;}
  if(['decimal-times-int','decimal-times-ten','decimal-multiply','decimal-small-product','decimal-area','project-recipe'].includes(k))op='multiply';
  if(k==='decimal-times-int'){x=q(a*100+b*10+c,100);y=q(b);sx=100;sy=1;}
  if(k==='decimal-times-ten'){y=q(pick([10,100,1000]));sy=1;}
  if(k==='decimal-multiply'||k==='decimal-area'){x=q(a*10+c,10);y=q(b,10);sx=sy=10;}
  if(k==='decimal-small-product'){x=q(a,100);y=q(c,10);sx=100;sy=10;}
  if(k.startsWith('decimal-divide')||k==='decimal-portion'||k==='decimal-reverse')op='divide';
  if(k==='decimal-divide-int'){y=q(b);x=q((a*10+c)*b,10);sx=10;sy=1;}
  if(k==='decimal-divide-zero'){y=q(b);x=q((a*100+c)*b,100);sx=100;sy=1;}
  if(k==='decimal-divide-ten'){y=q(pick([10,100,1000]));sy=1;}
  if(['decimal-divide','decimal-reverse'].includes(k)){y=q(b,10);x=mul(y,q(a*10+c,10));sx=100;sy=10;}
  if(k==='decimal-portion'){y=pick([q(1,4),q(1,5),q(1,8)]);x=mul(y,a+c);sx=1000;sy=1000;}
  if(k==='project-recipe'){x=q(c,20);y=q(a+b);sx=100;sy=1;}
  const result={add,subtract:sub,multiply:mul,divide:div}[op](x,y);data={...data,x,y,op,sx,sy};
  if(k==='decimal-area')prompt=`Длина прямоугольника ${D(x)} м, ширина ${D(y)} м. Найди площадь в м².`;
  else if(k==='decimal-portion')prompt=`${D(x)} л разливают порциями по ${D(y)} л. Сколько порций получится?`;
  else if(k==='decimal-money')prompt=`Сумма двух покупок ${D(y)} рубля. Оплатили ${D(x)} рублями. Найди сдачу.`;
  else if(k==='project-recipe')prompt=`На одну порцию нужно ${D(x)} кг крупы. Нужно ${D(y)} порций. Сколько килограммов потребуется?`;
  else prompt=`Вычисли ${D(x)} ${ {add:'+',subtract:'−',multiply:'·',divide:':'}[op]} ${D(y)}.`;
  answer=result;model={kind:'v5lab',family:'decimal',op};
  if(op==='add'||op==='subtract'){const scale=100;S('Сколько сотых в первом числе?',Math.round(N(x)*scale),'Целые и десятые тоже вырази в сотых.');S('Сколько сотых во втором числе?',Math.round(N(y)*scale),'Теперь обе величины в одинаковых единицах.');S(`Сколько сотых ${op==='add'?'в сумме':'в разности'}?`,Math.round(N(result)*scale),'Останется вернуться к десятичной записи.');E(q(Math.round(N(result)*100),10),'Сотые превращены в десятые: ответ изменился в 10 раз.','decimal-place');}
  else if(op==='multiply'){S('Знаменатель первого числа при записи в выбранных мелких долях?',sx,'Здесь используем '+sx+' долей в единице; нули можно дописать справа.');S('Произведение целых числителей в этих долях?',Math.round(N(x)*sx)*Math.round(N(y)*sy),'Первое число × '+sx+', второе × '+sy+'.');S('Знаменатель произведения?',sx*sy,'Перемножаются и числители, и знаменатели.');E(mul(result,10),'Проверь размер доли: в произведении потерян один десятичный разряд.','decimal-multiply');}
  else{let factor=1;while(!Number.isInteger(N(y)*factor)&&factor<10000)factor*=10;S('На что умножить оба числа, чтобы делитель стал целым?',factor,'Увеличиваем оба числа одинаково; если делитель уже целый, множитель 1.');S('Новый делитель?',Math.round(N(y)*factor),'Теперь деление на натуральное число.');S('Новое делимое?',mul(x,factor),'Меняется и делимое, иначе частное изменилось бы.');E(div(result,10),'Проверь, одинаково ли изменены оба числа. Умножь ответ на исходный делитель.','decimal-divide');}break;
 }
 case 'round-decimal':case 'round-carry':{const raw=k==='round-carry'?a*100+96:a*1000+b*100+c*10+R(0,9),scale=k==='round-carry'?100:1000,places=k==='round-carry'?1:2,power=10**places,result=q(Math.floor(raw/(scale/power)+0.5),power);T(`Округли ${D(q(raw,scale))} до ${places===1?'десятых':'сотых'}.`,result,'decimal',{raw,scale,places});S('Какая цифра сразу после сохраняемого разряда?',raw%10,'Именно она определяет направление округления.');S('Нужно увеличить сохраняемый разряд? Ответь да или нет.',raw%10>=5?'да':'нет','Пять и больше округляются вверх.');break;}
 case 'angle-kind':case 'angle-measure':case 'angle-build':case 'angle-sum':{
  const deg=pick([25,40,65,90,110,135,160,180]);data.deg=deg;
  if(k==='angle-kind'){T(`Угол ${deg}°. Какой он: острый, прямой, тупой или развёрнутый?`,deg<90?'острый':deg===90?'прямой':deg===180?'развёрнутый':'тупой','angle');S('Градусная мера прямого угла?',90,'С ним сравниваем угол.');S('Градусная мера развёрнутого?',180,'Это вторая граница классификации.');}
  else if(k==='angle-measure'){const start=a*5,end=start+b*10;T(`Лучи на одной шкале транспортира стоят на ${start}° и ${end}°. Найди угол между ними.`,end-start,'angle',{start,end});S('Отметка первого луча?',start,'Он не обязательно совпадает с нулём.');S('Какое действие находит угол: сложение или вычитание?','вычитание','Вычти начальную отметку из конечной.');}
  else if(k==='angle-build'){const start=b*5,target=start+a*10;T(`Первый луч на шкале расположен на ${start}°. Построй второй на ${a*10}° дальше по возрастанию шкалы. На какой отметке он окажется?`,target,'angle',{start,target});S('На сколько градусов поворачиваем?',a*10,'Отсчёт начинается от первого луча.');S('К какой отметке прибавляем угол?',start,'Ноль шкалы не совпадает с первым лучом.');}
  else{const first=a*5,total=first+b*10;T(`Луч внутри угла ${total}° отделяет часть ${first}°. Найди другую часть.`,b*10,'angle',{first,total});S('Мера всего угла?',total,'Части в сумме дают целое.');S('Какую часть вычитаем?',first,'Это уже известная часть.');}break;
 }
 case 'project-room':{const x=a+2,y=b+2,cover=q(5,2),area=x*y;T(`Комната ${x}×${y} м. Упаковка покрытия рассчитана на 2,5 м². Сколько целых упаковок нужно купить без запаса, чтобы покрыть весь пол?`,Math.ceil(area/2.5),'area',{x,y,cover});S('Площадь пола?',area,'Перемножь длину и ширину.');S('Сколько упаковок получается по точному делению?',div(area,cover),'Если число дробное, потребуется ещё одна целая упаковка.');break;}
 default:throw Error('No V5 generator: '+k);
 }
 if(FAMILIES[k]){model.family='fraction';model.op=FAMILIES[k];}
 model.data=data;return {prompt,answer,steps,errors,answerFormat:format,model,data,v6Full:true,v5Full:true};
}
function install(M,C){const old=M.generate;M.generate=(id,seed)=>id.startsWith('v5f-')?generate(id,seed,M,old,C):old(id,seed);}
const API={generate,install,FAMILIES};if(typeof module!=='undefined'&&module.exports)module.exports=API;else{root.WorkshopV5Math=API;install(root.WorkshopMath,root.WorkshopCurriculum);}
})(typeof window!=='undefined'?window:globalThis);
