(function(root){
'use strict';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=x=>x&&typeof x==='object'?x.n/x.d:Number(x||0),fmt=x=>Number.isInteger(num(x))?String(num(x)):String(Math.round(num(x)*100000)/100000).replace('.',','),frac=x=>x&&typeof x==='object'?(x.d===1?String(x.n):x.n+'/'+x.d):fmt(x);
const gcd=(a,b)=>b?gcd(b,a%b):Math.abs(a),lcm=(a,b)=>a*b/gcd(a,b);
const line=(x,y,X,Y,color='#285e62',dash=false)=>`<line x1="${x}" y1="${y}" x2="${X}" y2="${Y}" stroke="${color}" stroke-width="2" ${dash?'stroke-dasharray="6 5"':''}/>`;
const text=(x,y,s,size=18)=>`<text x="${x}" y="${y}" text-anchor="middle" font-size="${size}">${esc(s)}</text>`;
const rect=(x,y,w,h,c='#78bfb2')=>`<rect x="${x}" y="${y}" width="${Math.max(0,w)}" height="${Math.max(0,h)}" rx="3" fill="${c}"/>`;
const dot=(x,y,s,drag=false)=>`<circle ${drag?'data-v6-drag="point" tabindex="0" role="slider" aria-label="Передвинь точку B стрелками"':''} cx="${x}" cy="${y}" r="${drag?10:6}" fill="${drag?'#d78338':'#147c71'}"/>`+text(x,y-17,s);
function field(key,label,min,max,value,step=1,options){return {key,label,min,max,value:Math.max(min,Math.min(max,value)),step,options};}
function spec(m){const d=m.data,f=m.family;
 if(f==='mean'){const vals=d.values||[d.a,d.b,d.c];return [field('move','Передать единиц от наибольшего столбца наименьшему',0,Math.max(...vals),0)];}
 if(f==='percent')return [field('total','Что принято за 100%',100,5000,Math.ceil((d.total||100)/100)*100,100),field('p','Сколько процентов берём',0,200,num(d.percent||25),.5)];
 if(f==='pie')return [field('angle','Поверни луч: угол сектора',0,360,90,1)];
 if(f==='triangle')return [field('x','Положение вершины по горизонтали',80,520,300,10),field('y','Высота вершины',40,260,80,10)];
 if(f==='sets')return [field('region','Выбери область',0,3,0,1,['Только A','Общая часть','Только B','Всё объединение'])];
 if(f==='factors')return [field('divisor','Пробный делитель',2,Math.max(2,Math.min(60,d.n||d.x||24)),2)];
 if(f==='fraction')return [field('den','Разбей каждое целое на равные доли',1,Math.min(240,lcm(d.u?.d||4,d.w?.d||6)*2),d.u?.d||4)];
 if(f==='fraction-area')return [field('horizontal','Доля ширины: число четвертей',1,12,3),field('vertical','Доля высоты: число третей',1,9,2)];
 if(f==='division')return [field('portion','Размер порции: число шестых',1,12,2),field('whole','Количество целых',1,6,2)];
 if(f==='distribute')return [field('outer','Общий множитель (высота)',1,12,Math.abs(d.outer||3)),field('left','Первая ширина',1,12,Math.min(12,d.x||4)),field('right','Вторая ширина',1,12,d.y||3),field('cut','Раздвинуть части',0,1,0,1,['Вместе','Раздвинуть']),field('subtract','Действие',0,1,d.minus?1:0,1,['Сложение','Вычитание'])];
 if(f==='ratio')return [field('one','Сколько единиц в одной доле',1,20,d.c||3)];
 if(f==='work')return [field('workers','Число одинаковых работников',1,40,d.newWorkers||d.workers||4),field('gardens','Число одинаковых огородов',1,100,d.newGardens||d.gardens||2)];
 if(f==='motion')return [field('time','Часов движения',0,8,1,.5),field('stop','Часов остановки',0,4,0,.5)];
 if(f==='scale')return [field('length','Длина на плане, см',1,12,d.length||d.map||3),field('factor','Масштаб 1 :',100,200000,d.scale||100,100)];
 if(f==='symmetry'||f==='coordinates'||f==='construction'&&!d.angle)return [field('x','Координата x точки B',-12,12,0),field('y','Координата y точки B',-12,12,0)];
 if(f==='construction')return [field('angle','Направление новой прямой, градусы',0,179,0)];
 if(f==='circle')return [field('r','Радиус',1,10,d.radius||3),field('unroll','Развернуть длину окружности',0,100,0,10)];
 if(f==='solid')return [field('turn','Повернуть модель, градусов',-80,80,20,10),field('slice','Высота сечения, %',0,100,50,5)];
 if(f==='line'){const x=num(d.x),y=num(d.y);return [field('position','Положение точки',Math.min(-20,x,y)-10,Math.max(20,x,y)+10,0,.5)];}
 if(f==='chips')return [field('positive','Положительных единиц',0,20,Math.min(20,Math.abs(Math.round(num(d.w)||5)))),field('negative','Отрицательных единиц',0,20,Math.min(20,Math.abs(Math.round(num(d.u)||3)))),field('cancel','Убрать противоположные пары',0,1,0,1,['Показать все','Сократить пары'])];
 if(f==='signs')return [field('a','Первый множитель',-10,10,-3),field('b','Второй множитель',-10,10,4)];
 if(f==='algebra')return [field('x','Подставь x',-6,6,d.x||2),field('group','Собери подобные',0,1,0,1,['Исходное выражение','После упрощения'])];
 if(f==='graph')return [field('index','Номер столбца таблицы',0,d.values.length-1,0)];
 if(f==='equation')return [];
 throw Error('No interactive model for '+f);
}
function investigate(m,p){
 const d=m.data,f=m.family;let body='',caption='',question='',target=0,construct=false,readout='',extra='';
 const X=x=>300+x*11,Y=y=>170-y*11;
 const axes=()=>{let s='';for(let i=-12;i<=12;i++){s+=line(X(i),Y(-12),X(i),Y(12),'#e0e9e4')+line(X(-12),Y(i),X(12),Y(i),'#e0e9e4');if(i&&i%3===0)s+=text(X(i),Y(0)+18,i,13)+text(X(0)-16,Y(i)+4,i,13);}return s+line(X(-13),Y(0),X(13),Y(0))+line(X(0),Y(-13),X(0),Y(13))+text(X(14),Y(0)+5,'x')+text(X(0),Y(14),'y');};
 switch(f){
 case 'mean':{const values=(d.values||[d.a,d.b,d.c]).slice(),lo=values.indexOf(Math.min(...values)),hi=values.indexOf(Math.max(...values));values[lo]+=p.move;values[hi]-=p.move;const sum=values.reduce((a,b)=>a+b,0),mean=sum/values.length,max=Math.max(...values,mean)+1,w=500/values.length;values.forEach((v,i)=>{const h=v/max*190;body+=rect(50+i*w,270-h,w*.7,h)+text(50+i*w+w*.35,290,fmt(v),16);});body+=line(40,270-mean/max*190,560,270-mean/max*190,'#c97831',true);caption='Перекладывай из самого высокого столбца в самый низкий. Общая сумма сохраняется. Пунктир — уровень среднего.';readout=`Общая сумма ${fmt(sum)}, величин ${values.length}.`;question='Каков уровень среднего после перекладывания?';target=mean;break;}
 case 'percent':{const q=p.p/100;for(let block=0;block<2;block++)for(let i=0;i<100;i++){const fill=Math.max(0,Math.min(1,p.p-block*100-i)),x=60+block*255+i%10*21,y=70+Math.floor(i/10)*20;body+=rect(x,y,19,18,'#e1ebe4');if(fill)body+=rect(x,y,19*fill,18,block?'#df9b58':'#78bfb2');}body+=text(155,45,'Одно целое = 100%')+text(410,45,'Ещё одно целое')+text(300,320,`${fmt(p.p)}% = ${fmt(q)} целого`);caption='Выбери процент и базу. Две сетки позволяют увидеть больше 100%; половина клетки — 0,5%. При смене базы закрашенная доля та же, количество другое.';readout=`100% = ${p.total}; 1% = ${fmt(p.total/100)}. Условие задачи ниже остаётся прежним.`;question=`Какое количество составляет ${fmt(p.p)}% от ${p.total}?`;target=p.total*q;break;}
 case 'pie':{const angle=p.angle*Math.PI/180,r=110,x=300+r*Math.sin(angle),y=170-r*Math.cos(angle);body=`<circle cx="300" cy="170" r="${r}" fill="#e0ebe5"/>`;if(p.angle===360)body+=`<circle cx="300" cy="170" r="${r}" fill="#78bfb2"/>`;else if(p.angle)body+=`<path d="M300 170 L300 60 A110 110 0 ${p.angle>180?1:0} 1 ${x} ${y} Z" fill="#78bfb2"/>`;body+=line(300,170,x,y,'#c67e36')+text(300,315,p.angle+'° из 360°');const percent=d.rest??num(d.percent);caption=`Построй сектор для ${fmt(percent)}% целого: поверни луч и проверь.`;question='Угол выбран верно?';target=percent*3.6;construct=true;readout=`Нужный процент ${fmt(percent)}. Сначала найди долю полного оборота.`;break;}
 case 'triangle':{const A=[100,290],B=[500,290],C=[p.x,p.y],dist=(u,v)=>Math.hypot(u[0]-v[0],u[1]-v[1]),a=dist(B,C),b=dist(A,C),c=400,angle=(u,v,w)=>Math.acos(Math.max(-1,Math.min(1,(v*v+w*w-u*u)/(2*v*w))))*180/Math.PI,alpha=angle(a,b,c),beta=angle(b,a,c),gamma=180-alpha-beta;body=`<polygon points="${A} ${B} ${C}" fill="#e0eee7" stroke="#23776e" stroke-width="3"/>`+text(95,318,'A')+text(505,318,'B')+text(p.x,p.y-12,'C')+`<circle data-v6-drag="triangle" tabindex="0" role="slider" aria-label="Вершина C: передвинь стрелками" cx="${p.x}" cy="${p.y}" r="10" fill="#d78338"/>`+text(160,275,fmt(alpha)+'°',16)+text(438,275,fmt(beta)+'°',16)+text(p.x,p.y+30,fmt(gamma)+'°',16);caption='Передвигай вершину ползунками. Сравни углы при симметричном и несимметричном положении. Сумма не меняется. Рисунок исследовательский, длины измерены в условных единицах.';question='Какова сумма трёх углов при текущем положении?';target=180;readout=`AC ≈ ${fmt(b/40)}, BC ≈ ${fmt(a/40)}, AB = 10. Можно ли получить треугольник, если AC + BC ≤ AB?`;break;}
 case 'sets':{const A=d.A,B=d.B,onlyA=A.filter(x=>!B.includes(x)),both=A.filter(x=>B.includes(x)),onlyB=B.filter(x=>!A.includes(x)),vals=[onlyA,both,onlyB,[...new Set(A.concat(B))]][p.region];body=`<ellipse cx="230" cy="170" rx="145" ry="105" fill="#91cabc" fill-opacity=".6" stroke="#287c6e"/><ellipse cx="370" cy="170" rx="145" ry="105" fill="#e7b780" fill-opacity=".5" stroke="#ba7535"/>`+text(175,170,onlyA.join(', '))+text(300,170,both.join(', '))+text(425,170,onlyB.join(', '))+text(180,45,'A')+text(420,45,'B');caption='Общие элементы записаны ровно один раз в пересечении. Выбери область и посчитай её элементы.';question='Сколько различных элементов в выбранной области?';target=vals.length;readout=['Только A: A без B','Пересечение: одновременно A и B','Только B: B без A','Объединение: A или B (включая общие)'][p.region];break;}
 case 'factors':{const n=d.n||d.x||d.a*d.c,other=d.y,whole=Math.floor(n/p.divisor),rest=n%p.divisor;body=text(300,70,`${n} = ${p.divisor} · ${whole} + ${rest}`,25);for(let i=0;i<p.divisor;i++)body+=rect(40+i*520/p.divisor,120,Math.max(2,500/p.divisor),60);body+=text(300,225,`Остаток ${rest}`);if(other)body+=text(300,280,`У ${other} остаток ${other%p.divisor}`);caption=other?'Проверь, делит ли выбранное число оба числа без остатка. Перебирая общие делители, найди наибольший.':'Разложи число на равные группы. Делитель подходит, если остаток нулевой. Для простоты нужны ровно два натуральных делителя: 1 и само число.';question=other?'Выбранное число — общий делитель? Да или нет.':'Делится ли число без остатка? Да или нет.';target=rest===0&&(!other||other%p.divisor===0)?'да':'нет';break;}
 case 'fraction':{const u=d.u||{n:1,d:4},w=d.w||{n:1,d:6},values=[num(u),num(w)],max=Math.max(1,Math.ceil(Math.max(...values.map(Math.abs)))),unit=480/max;values.forEach((v,i)=>{const y=90+i*100;body+=rect(60,y,480,42,'#e2eae4')+rect(60,y,Math.min(480,Math.abs(v)*unit),42,i?'#e1a16b':'#72b6a8');for(let j=0;j<=p.den*max;j++)body+=line(60+j*unit/p.den,y,60+j*unit/p.den,y+42,'#fff');body+=text(300,y-15,(i?frac(w):frac(u))+(v<0?' (показан модуль)':''));});caption='Полоски используют одинаковый размер целого. Меняй знаменатель разбиения: границы исходных долей должны совпасть с новыми делениями. Цветная длина при этом не меняется.';question='Совместимо ли выбранное разбиение с обоими знаменателями? Да или нет.';target=p.den%(u.d||1)===0&&p.den%(w.d||1)===0?'да':'нет';readout=`Каждое целое делится на ${p.den} частей. Для общего знаменателя важна кратность обоим исходным знаменателям.`;break;}
 case 'fraction-area':{const u=p.horizontal/4,w=p.vertical/3,unit=75;for(let x=0;x<12;x++)for(let y=0;y<9;y++){const on=x<p.horizontal&&y<p.vertical;body+=rect(70+x*unit/4,50+y*unit/3,unit/4-1,unit/3-1,on?'#5fae9e':'#e5ede7');}for(let x=0;x<=3;x++)body+=line(70+x*unit,50,70+x*unit,275);for(let y=0;y<=3;y++)body+=line(70,50+y*unit,295,50+y*unit);body+=text(410,120,`${p.horizontal}/4 ширины`)+text(410,165,`${p.vertical}/3 высоты`)+text(410,220,'Клетка = 1/12');caption='Жирные линии ограничивают единичные квадраты. Четверть ширины и треть высоты дают двенадцатую площади. Можно выйти за одно целое.';question='Какова площадь закрашенной части в единичных квадратах?';target=u*w;break;}
 case 'division':{const total=p.whole*6,portion=p.portion;for(let i=0;i<total;i++)body+=rect(40+i*520/total,125,520/total-1,65,Math.floor(i/portion)%2?'#e1a16b':'#72b6a8');for(let i=0;i<=p.whole;i++)body+=line(40+i*520/p.whole,110,40+i*520/p.whole,208);body+=text(300,75,`${p.whole} : ${portion}/6`)+text(300,255,'Каждый цветовой отрезок — одна порция');caption='Разделить — узнать, сколько раз порция помещается в величине. Последняя порция может быть неполной. Меняй размер порции и замечай обратную зависимость.';question='Сколько порций, включая часть последней?';target=total/portion;readout=`Всего ${p.whole} целых; размер порции ${portion}/6. Деление на дробь может увеличить число.`;break;}
 case 'distribute':{const a=p.outer,b=p.left,c=p.right,all=b+c,u=Math.min(460/all,170/a),gap=p.cut?24:0;body=rect(50,75,b*u,a*u)+rect(50+b*u+gap,75,c*u,a*u,'#e2a16b')+text(26,75+a*u/2,a)+text(50+b*u/2,100+a*u,b)+text(50+b*u+gap+c*u/2,100+a*u,c);if(p.subtract)for(let i=0;i<c;i++)body+=line(50+(b+i)*u+gap,75,50+(b+i+1)*u+gap,75+a*u,'#984b2d');caption=p.subtract?'Из ширины всего прямоугольника убрали правую часть. Убирается вся её площадь.':'Разрежь прямоугольник на две части. Общий множитель (высота) действует на каждую ширину.';readout=p.subtract?`${a} · (${all} − ${c}) = ${a} · ${all} − ${a} · ${c}`:`${a} · (${b} + ${c}) = ${a} · ${b} + ${a} · ${c}`;question=p.subtract?'Какова оставшаяся площадь?':'Какова площадь двух частей вместе?';target=a*(p.subtract?b:b+c);break;}
 case 'ratio':{const parts=d.parts||[d.a,d.b],unit=460/Math.max(...parts);parts.forEach((n,row)=>{for(let i=0;i<n;i++)body+=rect(60+i*unit,90+row*100,unit-3,55,row?'#dda064':'#72b9a8');body+=text(300,160+row*100,`${n} долей · ${p.one} единиц в доле`);});caption='Меняй размер одной доли. Количества меняются, отношение количества долей сохраняется.';question='Сколько единиц в двух полосках вместе?';target=(parts[0]+parts[1])*p.one;readout=`Отношение ${parts[0]} : ${parts[1]}. Отношение частей — не доля первой части от всего.`;break;}
 case 'work':{const cost=d.workers?d.workers*d.days/d.gardens:12,days=p.gardens*cost/p.workers;body=text(300,65,`${p.gardens} огородов × ${fmt(cost)} чел.-дн.`)+text(300,110,'Одинаковый объём каждого огорода');const w=480/Math.min(20,p.workers);for(let i=0;i<Math.min(20,p.workers);i++){body+=`<circle cx="${60+i*w+w/2}" cy="175" r="7" fill="#287e70"/>`+line(60+i*w+w/2,184,60+i*w+w/2,213);}body+=text(300,275,`${p.workers} работников делят общий объём`);caption='Условия модели: одинаковая постоянная производительность, работа без помех. Число огородов не ограничено одним; ползунок показывает до 100. Сравни удвоение огородов и удвоение работников.';question='Сколько дней займёт работа? Можно ответить дробью.';target=days;readout=`Один огород требует ${fmt(cost)} человеко-дней. Сначала весь объём, затем делим на работников.`;break;}
 case 'motion':{
  const s1=d.fast||d.s1||10,s2=d.slow||d.s2||5,meeting=d.meeting!==false,distance=d.distance||100,t=p.time,one=s1*t;
  if(m.key==='project-route'){
   const total=one+s2,width=460,firstWidth=width*one/total;
   body=rect(70,140,firstWidth,65)+rect(70+firstWidth,140,width-firstWidth,65,'#e1a16b')+text(300,80,'Один путь, два участка')+text(300,255,`${fmt(one)} км + ${s2} км`);
   target=total/(t+1+p.stop);question='Средняя скорость с учётом остановки?';readout=`Путь: ${s1}·${fmt(t)} + ${s2}·1. Время: ${fmt(t)} + 1 + ${fmt(p.stop)}.`;
   caption='Первый участок длится выбранное время, второй — 1 час. Ширины цветных отрезков пропорциональны пройденному пути. Остановка добавляет время, но не путь.';
  }else{
   const second=distance+(meeting?-s2:s2)*t,low=Math.min(0,one,second),high=Math.max(distance,one,second),xx=z=>60+(z-low)/(high-low)*480;
   body=line(60,180,540,180)+line(60,240,540,240)+dot(xx(one),180,'Первый')+dot(xx(second),240,'Второй')+text(xx(0),310,'0',16)+text(xx(distance),310,distance,16)+line(xx(one),210,xx(second),210,'#c58542');
   target=Math.abs(second-one);question='Каково расстояние между участниками после движения?';readout=`Начальное расстояние ${distance}; скорости ${s1} и ${s2}. Координаты сейчас: ${fmt(one)} и ${fmt(second)}.`;
   caption='Обе строки используют одну координатную шкалу. При встречном движении скорости сближения складываются, при погоне — вычитаются. После встречи расстояние снова растёт. Остановка после движения меняет время наблюдения, но не положения.';
  }break;
 }
 case 'scale':{body=rect(80,90,p.length*28,110)+line(80,230,80+p.length*28,230)+text(80+p.length*14,260,p.length+' см на плане')+text(300,55,`Масштаб 1 : ${p.factor}`);caption='Масштаб сравнивает одинаковые единицы длины. Сначала восстанови сантиметры местности, затем переведи в метры. Масштаб площадей потребовал бы квадрата коэффициента.';question='Какой длине в метрах соответствует эта сторона?';target=p.length*p.factor/100;readout=`На плане ${p.length} см. 1 м = 100 см.`;break;}
 case 'symmetry':case 'coordinates':case 'construction':{
  if(f==='construction'&&d.angle){const draw=(a,c)=>{const r=a*Math.PI/180;return line(300-130*Math.cos(r),170+130*Math.sin(r),300+130*Math.cos(r),170-130*Math.sin(r),c);};body=draw(d.angle,'#258577')+draw(p.angle,'#ce853f');caption=`Зелёная прямая направлена под ${d.angle}°. Поверни оранжевую так, чтобы получился прямой угол.`;target=(d.angle+90)%180;question='Проверь перпендикулярность.';construct=true;break;}
  body=axes();let tx=d.targetX??d.x,ty=d.targetY??d.y;
  if(f==='symmetry'){[tx,ty]=d.target;const axis=m.key==='symmetry-line'?d.center:0;if(m.key==='symmetry-center')body+=dot(X(0),Y(0),'O');else body+=(d.axis==='x'&&m.key!=='symmetry-line')?line(X(-12),Y(axis),X(12),Y(axis),'#b77630'):line(X(axis),Y(-12),X(axis),Y(12),'#b77630');caption=m.key==='symmetry-center'?'Построй отражение точки A относительно начала координат.':'Построй отражение A относительно оранжевой оси. Сохрани расстояние до оси.';}
  else if(f==='construction'){tx=d.targetX??(d.x+d.dx);ty=d.targetY??(d.y+d.dy);if(d.perpendicular){body+=line(X(-12),Y(d.baseY),X(12),Y(d.baseY),'#b77630');caption='Перемести B на исходную прямую так, чтобы AB был перпендикуляром.';}else{body+=line(X(-10),Y(-8),X(-10+d.dx*3),Y(-8+d.dy*3),'#b77630');caption=`Из A повтори шаг ${d.dx} вправо и ${d.dy} вверх. Построй B: AB параллелен оранжевому отрезку.`;}}
  else caption=`Поставь B в (${tx}; ${ty}). Сначала x, затем y. Для прямоугольника проверь совпадение координат соседних вершин.`;
  if(d.rectangle){const [x,y,w,h]=d.rectangle;body+=`<path d="M${X(x)} ${Y(y)} L${X(x+w)} ${Y(y)} L${X(x+w)} ${Y(y+h)}" fill="none" stroke="#238273" stroke-width="3"/>`;}
  if(d.points)body+=`<polygon points="${d.points.map(z=>X(z[0])+','+Y(z[1])).join(' ')}" fill="#91c9b8" fill-opacity=".25" stroke="#258273"/>`;
  if(f!=='coordinates')body+=dot(X(d.x),Y(d.y),'A')+line(X(d.x),Y(d.y),X(p.x),Y(p.y),'#d1ad75',true);
  body+=dot(X(p.x),Y(p.y),'B',true);target=[tx,ty];construct=true;question='Передвинь точку и проверь построение.';readout=`Текущая точка B(${p.x}; ${p.y}). Доступны перетаскивание, ползунки и стрелки клавиатуры на точке.`;break;
 }
 case 'circle':{const r=p.r*10,circ=2*Math.PI*r,progress=p.unroll/100;body=`<circle cx="180" cy="160" r="${r}" fill="#deece3" stroke="#218173" stroke-width="3"/>`+line(180,160,180+r,160,'#bf7537')+text(180+r/2,148,'r='+p.r)+line(335,80,335,80+Math.min(240,circ/3)*progress,'#bf7537')+text(440,120,'Длина: 2πr')+text(440,175,'Площадь: πr²')+text(430,260,fmt(progress*100)+'% нити');caption='Нить с окружности разворачивается в отрезок; справа она показана в масштабе 1:3. Площадь круга измеряет заполнение внутри, а длина — границу.';question=m.key==='circle-area'?'Найди площадь при π=3,14.':'Найди длину окружности при π=3,14.';target=m.key==='circle-area'?3.14*p.r*p.r:6.28*p.r;break;}
 case 'solid':{const turn=p.turn*Math.PI/180,project=(x,y,z)=>[300+(x*Math.cos(turn)-z*Math.sin(turn))*80,190-y*80+(x*Math.sin(turn)+z*Math.cos(turn))*28];if(m.key==='sphere-solids'){body=`<circle cx="300" cy="170" r="112" fill="#dfede5" stroke="#258578" stroke-width="3"/>`;const h=(p.slice-50)/50,r=Math.sqrt(Math.max(0,1-h*h))*112;body+=`<ellipse cx="300" cy="${170-h*105}" rx="${r}" ry="${Math.max(1,r*.25)}" fill="#e6ab6c" fill-opacity=".5" stroke="#bb7e3e"/>`;caption='Плоскость сечения шара даёт круг. Двигай плоскость: наибольший круг проходит через центр. На краю он превращается в точку.';question='На какой высоте в процентах находится наибольшее сечение?';target=50;}else{const vertices=[];for(let y=0;y<=1;y++)for(let z=0;z<=1;z++)for(let x=0;x<=1;x++)vertices.push(project((x-.5)*2,y*2-1,(z-.5)*2));for(let i=0;i<8;i++)for(const bit of [1,2,4])if(!(i&bit))body+=line(...vertices[i],...vertices[i|bit]);const h=p.slice/50-1,pts=[[-1,h,-1],[1,h,-1],[1,h,1],[-1,h,1]].map(v=>project(...v));body+=`<polygon points="${pts.map(v=>v.join(',')).join(' ')}" fill="#e8b16d" fill-opacity=".6"/>`;caption='Поверни каркас и передвинь горизонтальное сечение. У прямоугольного параллелепипеда такие сечения имеют одинаковую площадь. Модель показывает форму, не масштаб чисел задачи.';question='Длина 6, ширина 4, высота 3. Каков объём?';target=72;}break;}
 case 'line':{const min=Math.min(-20,num(d.x),num(d.y))-10,max=Math.max(20,num(d.x),num(d.y))+10,xx=v=>50+(v-min)/(max-min)*500,step=Math.max(1,Math.ceil((max-min)/12));body=line(45,185,555,185);for(let i=Math.ceil(min/step)*step;i<=max;i+=step)body+=line(xx(i),180,xx(i),190)+text(xx(i),214,i,15);body+=dot(xx(num(d.x)),185,'A')+dot(xx(p.position),185,'B');caption='Передвигай B. Направление задаёт знак изменения, длина отрезка — расстояние. Расстояние никогда не отрицательно.';readout=`A = ${frac(d.x||0)}, B = ${fmt(p.position)}.`;question='Каково расстояние от A до B?';target=Math.abs(p.position-num(d.x));break;}
 case 'chips':{const pairs=Math.min(p.positive,p.negative),pos=p.positive-(p.cancel?pairs:0),neg=p.negative-(p.cancel?pairs:0);for(let i=0;i<pos;i++)body+=rect(55+i%10*48,60+Math.floor(i/10)*50,38,38)+text(74+i%10*48,86+Math.floor(i/10)*50,'+');for(let i=0;i<neg;i++)body+=rect(55+i%10*48,195+Math.floor(i/10)*50,38,38,'#e7b17c')+text(74+i%10*48,221+Math.floor(i/10)*50,'−');caption='Положительная и отрицательная единицы вместе дают ноль. Удали противоположные пары: значение суммы сохранится. Для дробей такими единицами могут быть одинаковые доли целого.';question='Каково значение набора жетонов?';target=p.positive-p.negative;readout=`До сокращения: ${p.positive} + (−${p.negative}). Можно удалить ${pairs} нулевых пар.`;break;}
 case 'signs':{const product=p.a*p.b;body=text(300,90,`(${p.a}) · (${p.b})`,32)+line(70,220,530,220);const x=300+product*2;body+=dot(300,220,'0')+line(300,212,x,212,'#bf7933')+dot(x,220,'?');caption='Меняй знак одного множителя и следи за направлением. Изменение знака обоих множителей возвращает прежний знак. Ноль даёт ноль независимо от другого числа.';question='Каково произведение?';target=product;readout=`Модули множителей ${Math.abs(p.a)} и ${Math.abs(p.b)}.`;break;}
 case 'algebra':{const k=num(d.coefficient),c=num(d.constant),ky=num(d.yCoefficient),expr=d.expr||`${k}x + ${c}`,simple=`${fmt(k)}x ${c<0?'−':'+'} ${fmt(Math.abs(c))}${ky?' + '+ky+'y':''}`;body=text(300,95,p.group?simple:expr,22)+rect(125,140,145,80)+rect(330,140,145,80,'#e5b079')+text(198,186,fmt(k)+' × x')+text(402,186,'число '+fmt(c))+text(300,280,`x = ${p.x}${ky?'; y = 1':''}`);caption='Собери слагаемые с x отдельно от свободных чисел. Упрощение должно сохранять значение при любой подстановке. Здесь при наличии y принимаем y=1.';question='Найди значение после подстановки.';target=k*p.x+c+ky;readout='Изменение вида записи не меняет значение выражения.';break;}
 case 'graph':{const values=d.values,times=d.times,min=Math.min(0,...values),max=Math.max(...values,1),tx=t=>60+t/Math.max(...times)*480,yy=y=>280-(y-min)/(max-min)*230;body=line(60,280,550,280)+line(60,285,60,40)+`<polyline points="${values.map((y,i)=>tx(times[i])+','+yy(y)).join(' ')}" fill="none" stroke="#258579" stroke-width="3"/>`;values.forEach((y,i)=>{body+=dot(tx(times[i]),yy(y),i===p.index?'?':y)+text(tx(times[i]),310,times[i],16);});body+=line(tx(times[p.index]),280,tx(times[p.index]),yy(values[p.index]),'#ba762d',true)+text(575,300,'t');caption=m.key==='graph-journey'?'График показывает расстояние от дома: при возвращении оно падает. Суммарный путь при возвращении продолжает расти.':'Найди нужный момент по горизонтали, затем поднимись к графику. Значения в таблице и точки должны соответствовать.';question=`Какое значение соответствует времени ${times[p.index]}?`;target=values[p.index];readout=`Время: ${times.join(' | ')}. Значение: ${values.map((v,i)=>i===p.index?'?':v).join(' | ')}.`;break;}
 default:throw Error('Unsupported model '+f);
 }
 return {svg:`<svg viewBox="${['symmetry','coordinates','construction'].includes(f)&&!d.angle?'130 0 340 350':'0 0 600 350'}" role="img" aria-label="${esc(caption)}">${body}</svg>`,caption,question,target,construct,readout,extra};
}
function install(Models,M){const old=Models.mount;Models.mount=function(el,m){
 if(!m||m.kind!=='v6full')return old(el,m);
 if(m.family==='equation')return mountEquation(el,m,M);
 const fields=spec(m),p=Object.fromEntries(fields.map(f=>[f.key,f.value]));
 el.innerHTML='<section class="v6-lab"><p class="eyebrow">Исследуй своими руками</p><div class="v6-figure"></div><p class="v6-caption"></p><div class="v6-controls">'+fields.map(f=>`<div class="v6-control"><label for="v6-${f.key}">${esc(f.label)} <output data-out="${f.key}"></output></label>${f.options?`<select id="v6-${f.key}" data-field="${f.key}">${f.options.map((x,i)=>`<option value="${i}">${esc(x)}</option>`).join('')}</select>`:`<div class="v6-range"><button type="button" data-adjust="${f.key}" data-delta="-1" aria-label="Уменьшить: ${esc(f.label)}">−</button><input type="range" id="v6-${f.key}" data-field="${f.key}" min="${f.min}" max="${f.max}" step="${f.step}" value="${f.value}"><button type="button" data-adjust="${f.key}" data-delta="1" aria-label="Увеличить: ${esc(f.label)}">+</button></div>`}</div>`).join('')+'</div><p class="v6-readout"></p><form class="v6-model-check"><label class="v6-question" for="v6-prediction"></label><div class="answer-line"><input id="v6-prediction" aria-label="Ответ к исследованию" autocomplete="off"><button>Проверить модель</button></div></form><p class="v6-result" role="status"></p><p class="tiny">Исследование — работа с помощью. Самостоятельная проверка вверху урока даёт новые числа и скрывает модель. Ползунки не меняют условие задачи ниже.</p></section>';
 let result;
 function draw(){result=investigate(m,p);el.querySelector('.v6-figure').innerHTML=result.svg;el.querySelector('.v6-caption').textContent=result.caption;el.querySelector('.v6-readout').textContent=result.readout;el.querySelector('.v6-question').textContent=result.question;el.querySelector('#v6-prediction').hidden=result.construct;fields.forEach(f=>{el.querySelector(`[data-field="${f.key}"]`).value=p[f.key];el.querySelector(`[data-out="${f.key}"]`).textContent=f.options?'':fmt(p[f.key]);});el.querySelector('.v6-result').textContent='';}
 function update(k,v){const f=fields.find(x=>x.key===k);if(!f||!Number.isFinite(v))return;p[k]=Math.max(f.min,Math.min(f.max,Math.round(v/f.step)*f.step));draw();}
 el.addEventListener('input',e=>{if(e.target.dataset.field)update(e.target.dataset.field,Number(e.target.value));});
 el.addEventListener('change',e=>{if(e.target.dataset.field)update(e.target.dataset.field,Number(e.target.value));});
 el.addEventListener('click',e=>{const b=e.target.closest('[data-adjust]');if(b){const f=fields.find(f=>f.key===b.dataset.adjust);update(f.key,p[f.key]+Number(b.dataset.delta)*f.step);}});
 el.querySelector('form').onsubmit=e=>{e.preventDefault();let ok;if(result.construct){ok=Array.isArray(result.target)?p.x===result.target[0]&&p.y===result.target[1]:Math.abs(p.angle-result.target)<.01;}else{const v=el.querySelector('#v6-prediction').value.trim();if(typeof result.target==='string')ok=v.toLowerCase().replace(/ё/g,'е')===result.target;else{const q=M.parse(v);ok=!!q&&Math.abs(num(q)-result.target)<1e-7;}}el.querySelector('.v6-result').textContent=ok?'Верно. Измени один параметр и объясни, что сохранится, а что изменится.':result.construct?'Пока нет. Проверь оба условия построения: положение и направление.':'Пока нет. Назови целое, единицу измерения и действие. Измени один параметр и проследи связь.';};
 let dragging=false;
 el.addEventListener('pointerdown',e=>{if(!e.target.matches('[data-v6-drag]'))return;dragging=true;el.setPointerCapture(e.pointerId);e.preventDefault();});
 el.addEventListener('pointermove',e=>{if(!dragging)return;const svg=el.querySelector('svg'),pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const z=pt.matrixTransform(svg.getScreenCTM().inverse());const fx=fields.find(f=>f.key==='x'),fy=fields.find(f=>f.key==='y');p.x=Math.max(fx.min,Math.min(fx.max,Math.round((m.family==='triangle'?z.x:(z.x-300)/11)/fx.step)*fx.step));p.y=Math.max(fy.min,Math.min(fy.max,Math.round((m.family==='triangle'?z.y:(170-z.y)/11)/fy.step)*fy.step));draw();});
 el.addEventListener('pointerup',()=>{dragging=false;});el.addEventListener('pointercancel',()=>{dragging=false;});
 el.addEventListener('keydown',e=>{if(!e.target.matches('[data-v6-drag]'))return;const map={ArrowLeft:['x',-1],ArrowRight:['x',1],ArrowUp:['y',1],ArrowDown:['y',-1]};if(map[e.key]){e.preventDefault();const [k,v]=map[e.key];const f=fields.find(f=>f.key===k);update(k,p[k]+v*f.step*(m.family==='triangle'&&k==='y'?-1:1));el.querySelector('[data-v6-drag]').focus();}});draw();
 };}
function mountEquation(el,m,M){
 const d=m.data;let initial={A:d.A,B:d.B,C:d.C,D:d.D};if(m.key==='divide-unknown')initial={A:d.quotient,B:0,C:0,D:d.dividend};
 let s=Object.fromEntries(Object.entries(initial).map(([k,v])=>[k,typeof v==='object'?v:M.q(v)])),history=[];
 el.innerHTML='<section class="v6-lab"><p class="eyebrow">Равновесие уравнения</p><p>Выполни одно и то же действие с обеими частями. Цель — оставить x слева и число справа. При переносе знаки меняются потому, что с обеих сторон вычитается одно слагаемое.</p>'+(d.expr?'<p class="v6-original">Исходная запись: '+esc(d.expr)+'. Ниже скобки раскрыты.</p>':'')+'<div class="v6-eq-display"></div><div class="v6-eq-controls"><label>Операция<select id="v6-op"><option value="constant">Прибавить число к обеим частям</option><option value="x">Прибавить несколько x к обеим частям</option><option value="divide">Разделить обе части на число</option></select></label><label>Число (можно отрицательное или дробь)<input id="v6-operand" value="1" autocomplete="off"></label><div class="row"><button type="button" data-eq="apply">Применить</button><button type="button" data-eq="undo" class="quiet">Отменить шаг</button><button type="button" data-eq="reset" class="quiet">Начать заново</button></div></div><p class="v6-result" role="status"></p><ol class="v6-eq-history"></ol><p class="tiny">Для вычитания прибавь отрицательное число. Делить на ноль нельзя. Эти действия не засчитываются как самостоятельная проверка.</p></section>';
 const expr=(a,b)=>M.fmt(a)+'x '+(b.n<0?'− '+M.fmt(M.mul(b,-1)):'+ '+M.fmt(b));
 function draw(){el.querySelector('.v6-eq-display').innerHTML='<div>'+esc(expr(s.A,s.B))+'</div><strong>=</strong><div>'+esc(expr(s.C,s.D))+'</div>';el.querySelector('.v6-eq-history').innerHTML=history.map(h=>'<li>'+esc(h.label)+'</li>').join('');}
 el.onclick=e=>{const b=e.target.closest('[data-eq]');if(!b)return;const out=el.querySelector('.v6-result');if(b.dataset.eq==='reset'){s=Object.fromEntries(Object.entries(initial).map(([k,v])=>[k,typeof v==='object'?v:M.q(v)]));history=[];out.textContent='Начальное уравнение восстановлено.';draw();return;}if(b.dataset.eq==='undo'){const h=history.pop();if(h)s=h.before;out.textContent='Последний шаг отменён.';draw();return;}const z=M.parse(el.querySelector('#v6-operand').value),op=el.querySelector('#v6-op').value;if(!z||op==='divide'&&!z.n){out.textContent='Введи число или дробь. Деление на ноль недопустимо.';return;}try{const before={...s};if(op==='constant'){s={...s,B:M.add(s.B,z),D:M.add(s.D,z)};}else if(op==='x'){s={...s,A:M.add(s.A,z),C:M.add(s.C,z)};}else s=Object.fromEntries(Object.entries(s).map(([k,v])=>[k,M.div(v,z)]));history.push({before,label:(op==='divide'?'Обе части разделены на ':op==='x'?'К обеим частям прибавлено x · ':'К обеим частям прибавлено ')+M.fmt(z)});out.textContent=s.A.n===s.A.d&&!s.B.n&&!s.C.n?'Получено x = '+M.fmt(s.D)+'. Проверь подстановкой в исходное уравнение.':!s.A.n&&!s.C.n?(M.equal(M.fmt(s.B),s.D)?'Равенство верно при любом x.':'Получилось неверное числовое равенство: решений нет.'):'Равенство сохранено. Какое слагаемое удобнее убрать следующим?';draw();}catch(err){out.textContent='Числа стали слишком большими. Отмени шаг или начни заново.';}};draw();
}
const API={spec,investigate,install};if(typeof module!=='undefined'&&module.exports)module.exports=API;else{root.WorkshopV6Models=API;install(root.WorkshopModels,root.WorkshopMath);}
})(typeof window!=='undefined'?window:globalThis);
