/* Account cabinet. Cookie credentials stay on this origin; trainer frames receive task data only. */
(function(){
'use strict';
const $=id=>document.getElementById(id), main=$('main'), E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=x=>JSON.parse(JSON.stringify(x));
const labels=window.LearningOutcomes?.labels||{started:'Начато',together:'Разобрали вместе',hinted:'Решено с подсказкой',independent:'Решено самостоятельно',repeated:'Самостоятельно повторено',practiced:'Верно на знакомом задании'};
let account=null,csrf='',students=[],assignments=[],attempts=[],lessons=[],activeLesson=null,activeAttempt=null,routeNumber=0,dispose=()=>{},workspace=null,overview=null;
const actionWaiters=new Map();
const commutative=new Set(['stroke','erase','undo','reference']);
let listingPollAt=0;
let catalogMode='exam',sheet=0,polling=false,sending=false,connected=true,outbox=[],rejected=[],retryTimer=null,toastTimer=null,authInvite=null;
const inviteParams=new URLSearchParams(location.hash.slice(1));
if(inviteParams.has('invite')){authInvite=inviteParams.get('invite');history.replaceState(null,'',location.pathname+location.search);}
const teacher=()=>account?.role==='teacher';
const itemFor=a=>window.LearningCatalog?.items.find(i=>i.trainerId===a.trainerId&&i.contentId===a.contentId)||window.LearningCatalog?.get(a.contentId)||window.LearningCatalog?.get(a.trainerId);
const titleFor=a=>a.trainerId==='board'?'Общая доска':itemFor(a)?.title||'Задание';
const getItems=()=>window.LearningCatalog?.items||[];
const activeRoute=()=>location.hash.slice(1)||'home';
function notice(message,error=false){$('notice').textContent=message;$('notice').hidden=!message;$('notice').classList.toggle('error',error);if(error&&(outbox.length||rejected.length)){const b=document.createElement('button');b.className='small';b.style.marginLeft='12px';b.textContent='Скачать неподтверждённую работу';b.onclick=exportUnsent;$('notice').append(b);}}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5000);}
function errorText(error){const code=error?.code||error?.message||'';if(error?.name==='AbortError'||error instanceof TypeError)return 'Нет связи с сервером. Проверьте интернет; введённая работа остаётся в этой вкладке.';
if(code==='LEARNING_ACCESS_INVALID')return 'Неверные данные входа или ссылка уже использована. Проверьте логин и пароль; при необходимости запросите новый вход.';
if(error?.status===401)return 'Войдите в кабинет снова. Несохранённую работу можно скачать перед выходом.';
if(code==='LEARNING_ATTEMPT_ARCHIVED')return 'Эта работа перенесена в архив. История сохранена; новую попытку можно начать в курсе.';
if(error?.status===409)return 'Работа уже изменилась на другом устройстве. Мы открыли сохранённую версию; Ваши неподтверждённые действия доступны для скачивания.';
if(error?.status===429)return 'Слишком много действий за короткое время. Подождите несколько секунд.';
const map={LEARNING_INVALID_CREDENTIALS:'Неверный логин или пароль.',LEARNING_LOGIN_FAILED:'Неверный логин или пароль.',LEARNING_INVITE_INVALID:'Приглашение недействительно или уже использовано. Попросите Наталью Михайловну выдать новую ссылку.',LEARNING_TOKEN_INVALID:'Ссылка недействительна или уже использована. Попросите новую ссылку.',LEARNING_LOGIN_EXISTS:'Этот логин уже занят. Выберите другой.',LEARNING_STORAGE_UNAVAILABLE:'Кабинет временно недоступен. Попробуйте немного позже.',LEARNING_STORAGE_NOT_CONFIGURED:'Кабинет ещё готовится к работе. Попробуйте позже.',LEARNING_FORBIDDEN:'Для этого действия нет доступа.',LEARNING_CSRF:'Вход устарел. Обновите страницу перед продолжением.'};
return map[code]||(error?.status>=500?'Сервер временно не отвечает. Попробуйте позже.':error?.status===400?'Проверьте данные формы. Логин: от 3 до 48 латинских букв, цифр, точек, дефисов или подчёркиваний; пароль — от 12 символов.':'Не удалось выполнить действие. Попробуйте ещё раз.');}
async function api(path,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const res=await fetch('/api/learning'+path,{...options,signal:controller.signal,credentials:'same-origin',cache:'no-store',headers:{...(options.body&&!(options.body instanceof FormData)?{'Content-Type':'application/json'}:{}),...(options.method&&options.method!=='GET'&&csrf?{'X-CSRF-Token':csrf}:{}),...options.headers}});let data;try{data=await res.json();}catch(_){throw Object.assign(Error('INVALID_RESPONSE'),{status:res.status});}if(!res.ok)throw Object.assign(Error(data.error||'REQUEST_FAILED'),{status:res.status,code:data.error,data});if(data.csrfToken)csrf=data.csrfToken;return data;}finally{clearTimeout(timer);}}
const post=(path,body)=>api(path,{method:'POST',body:JSON.stringify(body)});
const date=raw=>raw?new Date(raw).toLocaleDateString('ru-RU',{day:'numeric',month:'short'}):'';
function download(name,value){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportUnsent(){download('mathexam-unsaved-work.json',{exportedAt:new Date().toISOString(),outbox,rejected});}
function navigate(hash){if(activeRoute()===hash)render();else location.hash=hash;}
function closeModal(){$('modal').close();$('modal-content').replaceChildren();}
function modal(title,html){$('modal-content').innerHTML=`<div class="dialog-heading"><h2 id="modal-title">${E(title)}</h2><button class="dialog-close" id="dialog-close" aria-label="Закрыть">×</button></div>${html}`;$('dialog-close').onclick=closeModal;$('modal').showModal();}
$('modal').addEventListener('click',e=>{if(e.target===$('modal')){const r=$('modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
function bindAsyncForm(id,fn){const form=$(id);form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('[type=submit]'),error=form.querySelector('.form-error');button.disabled=true;if(error)error.textContent='';try{await fn(new FormData(form));}catch(err){if(error)error.textContent=errorText(err);else notice(errorText(err),true);}finally{if(button.isConnected)button.disabled=false;}});}
function authPage(mode='login'){
 ++routeNumber;dispose();dispose=()=>{};$('sidebar').hidden=true;$('account').replaceChildren();main.innerHTML=`<div class="auth-layout"><section class="auth-intro"><p class="eyebrow">МАТЕМАТИКА С НАТАЛЬЕЙ МИХАЙЛОВНОЙ</p><h1>Каждый шаг<br>остаётся с Вами.</h1><p class="lead">Продолжайте с того места, где остановились. Дома, на занятии или вместе с преподавателем.</p><ul class="auth-list"><li><b>01</b><span>Задания и курс в одном месте</span></li><li><b>02</b><span>Личная работа и общие объяснения</span></li><li><b>03</b><span>Прогресс сохраняется между устройствами</span></li></ul></section><section class="auth-card"><h2>${authInvite?'Добро пожаловать':mode==='recover'?'Восстановить доступ':'Войти в кабинет'}</h2><form id="auth-form" class="form-stack">${authInvite?'':`<label>Логин<input name="login" autocomplete="username" autocapitalize="none" spellcheck="false" minlength="3" maxlength="48" required></label>`}${mode==='recover'?'<label>Код восстановления<input name="code" autocomplete="off" autocapitalize="none" spellcheck="false" required></label>':''}<label>${authInvite||mode==='recover'?'Новый пароль':'Пароль'}<input name="password" type="password" autocomplete="${authInvite||mode==='recover'?'new-password':'current-password'}" minlength="${authInvite||mode==='recover'?12:1}" maxlength="128" required></label>${authInvite||mode==='recover'?'<p>Не менее 12 символов. Используйте пароль, который не применяете на других сайтах.</p><label>Повторите пароль<input name="confirm" type="password" autocomplete="new-password" minlength="12" maxlength="128" required></label>':''}<p class="form-error" role="alert"></p><button class="primary" type="submit">${authInvite?'Сохранить пароль и войти':mode==='recover'?'Восстановить и войти':'Войти'} →</button></form>${!authInvite?`<button class="subtle small" id="auth-switch">${mode==='recover'?'Вернуться ко входу':'Не помню пароль'}</button><p class="form-hint">${mode==='recover'?'Ученикам новую ссылку выдаёт Наталья Михайловна. Преподаватель может использовать сохранённый код восстановления.':'Логин и приглашение выдаёт Наталья Михайловна.'}</p>`:''}</section></div>`;
 $('auth-switch')?.addEventListener('click',()=>authPage(mode==='recover'?'login':'recover'));
 bindAsyncForm('auth-form',async form=>{const password=form.get('password');if((authInvite||mode==='recover')&&password!==form.get('confirm')){$('auth-form').querySelector('.form-error').textContent='Пароли не совпадают.';return;}let result;if(authInvite)result=await post('/activate',{token:authInvite,password});else if(mode==='recover')result=await post('/recover',{login:form.get('login'),code:form.get('code'),password});else result=await post('/login',{login:form.get('login'),password});authInvite=null;account=result.account;csrf=result.csrfToken||csrf;loadQueue();await refreshData();renderShell();navigate('home');if(result.recoveryCodes?.length)showCodes(result.recoveryCodes);});
}
function showCodes(codes){modal('Сохраните коды восстановления',`<p>Каждый код можно использовать один раз. Храните их отдельно от пароля.</p><pre id="recovery-codes"></pre><div class="dialog-actions"><button id="save-codes" class="primary">Скачать коды</button><button id="done-codes">Готово</button></div>`);$('recovery-codes').textContent=codes.join('\n');$('save-codes').onclick=()=>download('mathexam-recovery-codes.json',{login:account.login,codes});$('done-codes').onclick=closeModal;}
function renderShell(){if(!account)return;$('sidebar').hidden=false;$('account').innerHTML=`<span class="avatar" aria-hidden="true">${E(account.name?.slice(0,1))}</span><span class="account-name">${E(account.name)}<small>${teacher()?'Преподаватель':'Ученик'}</small></span><button class="subtle small" id="logout">Выйти</button>`;$('logout').onclick=logout;const nav=teacher()?[['home','Обзор'],['students','Мои ученики'],['assignments','Домашние задания'],['lessons','Групповые уроки'],['course','Курс и тренажёры'],['reports','Итоги и планы']]:[['home','Сегодня'],['assignments','Мои задания'],['course','Мой курс'],['repeat','Повторить трудное'],['lessons','Мои занятия']];$('navigation').innerHTML=nav.map(([id,title])=>`<a href="#${id}" data-nav="${id}">${title}</a>`).join('');}
async function logout(){if(outbox.length){modal('Есть несохранённая работа','<p>Перед выходом дождитесь сохранения или скачайте свои действия.</p><div class="dialog-actions"><button id="unsent-download">Скачать</button><button id="leave-anyway">Выйти</button></div>');$('unsent-download').onclick=exportUnsent;$('leave-anyway').onclick=async()=>{closeModal();await leave();};}else await leave();}
async function leave(){try{await post('/logout',{});}catch(e){notice(errorText(e),true);return;}account=null;csrf='';dispose();workspace=null;overview=null;activeLesson=null;activeAttempt=null;clearTimeout(retryTimer);authPage();}
function queueKey(){return 'mathexam.learning.outbox.'+account.id;}
function loadQueue(){outbox=[];rejected=[];try{const saved=JSON.parse(sessionStorage.getItem(queueKey())||'null');if(saved&&Array.isArray(saved.outbox)&&Array.isArray(saved.rejected)){outbox=saved.outbox;rejected=saved.rejected;}}catch(_){notice('Не удалось прочитать неподтверждённые действия этой вкладки.',true);}}
function saveQueue(){if(!account)return;try{sessionStorage.setItem(queueKey(),JSON.stringify({outbox,rejected}));}catch(_){notice('Браузер не сохранил резервную копию. Не закрывайте вкладку до отправки действий.',true);}}
async function refreshData(){const actor=account?.id;if(!actor)return;const results=await Promise.all([api('/attempts'),api('/assignments'),api('/lessons'),teacher()?api('/teacher/students'):Promise.resolve({students:[]})]);if(account?.id!==actor)return;attempts=results[0].attempts||[];assignments=results[1].assignments||[];lessons=results[2].lessons||[];students=results[3].students||[];}
function remember(attempt){if(!attempt)return;const index=attempts.findIndex(a=>a.id===attempt.id);if(index<0)attempts.push(attempt);else if(attempt.version>=attempts[index].version)attempts[index]=attempt;if(activeAttempt?.id===attempt.id&&attempt.version>=activeAttempt.version)activeAttempt=attempt;if(activeLesson){for(const seat of activeLesson.seats||[])if(seat.attemptId===attempt.id)seat.attempt=attempt;if(activeLesson.common?.id===attempt.id)activeLesson.common=attempt;if(activeLesson.presentation?.attempt?.id===attempt.id)activeLesson.presentation.attempt=attempt;}}
function queuedFor(id){return outbox.filter(a=>a.attemptId===id);}
function effective(attempt){
 const pending=queuedFor(attempt.id);if(!pending.length||attempt.archivedAt)return attempt;
 const copy=clone(attempt),states=pending.filter(q=>!commutative.has(q.body.type));
 const stateCurrent=states.length&&states[0].body.expectedTrainerVersion===(attempt.trainerVersion??attempt.version);
 for(const {body}of pending){
  if(stateCurrent&&body.payload.state)copy.state=clone(body.payload.state);
  if(body.type==='stroke'&&!copy.strokes.some(s=>s.id===body.payload.id))copy.strokes.push({...clone(body.payload),author:account.id,role:account.role});
  if(body.type==='erase'||body.type==='undo')copy.strokes=copy.strokes.filter(s=>s.id!==body.payload.strokeId);
 }
 return copy;
}
function action(attemptId,type,payload){
 const a=attempts.find(x=>x.id===attemptId)||activeAttempt||activeLesson?.common;if(!a||a.id!==attemptId||a.archivedAt)return Promise.resolve(false);
 const last=outbox.at(-1);
 if(type==='state'&&last?.attemptId===attemptId&&last.body.type==='state'&&(!sending||last!==outbox[0]))last.body.payload=clone(payload);
 else{
  const body={opId:crypto.randomUUID(),expectedVersion:a.version,type,payload:clone(payload)};
  if(!commutative.has(type)){
   let expected=a.trainerVersion??a.version;
   for(const q of queuedFor(attemptId))if(!commutative.has(q.body.type))expected=Math.max(expected,(q.body.expectedTrainerVersion??q.body.expectedVersion)+1);
   body.expectedTrainerVersion=expected;
  }
  outbox.push({attemptId,body});
 }
 const queued=outbox.at(-1);const promise=new Promise(resolve=>{const waiting=actionWaiters.get(queued.body.opId)||[];waiting.push(resolve);actionWaiters.set(queued.body.opId,waiting);});
 saveQueue();updateConnection();updateWorkspace();pump();return promise;
}
function resolveAction(opId,result){for(const resolve of actionWaiters.get(opId)||[])resolve(result);actionWaiters.delete(opId);}
function quarantine(id,error,{dependentOnly=false,failedOpId=null}={}){const discard=q=>q.attemptId===id&&(!dependentOnly||!commutative.has(q.body.type)||q.body.opId===failedOpId);const dropped=outbox.filter(discard);outbox=outbox.filter(q=>!discard(q));for(const q of dropped){rejected.push({...q,error:error.code||error.message,at:new Date().toISOString()});resolveAction(q.body.opId,false);}saveQueue();}
async function pump(){if(sending||!account||!outbox.length)return;sending=true;const q=outbox[0],actor=account.id;try{const r=await post('/attempts/'+encodeURIComponent(q.attemptId)+'/actions',q.body);if(account?.id!==actor)return;outbox=outbox.filter(p=>p.body.opId!==q.body.opId);remember(r.attempt);if(r.attempt?.archivedAt)quarantine(q.attemptId,Error('LEARNING_ATTEMPT_ARCHIVED'));connected=true;resolveAction(q.body.opId,true);const pendingState=queuedFor(q.attemptId).find(p=>!commutative.has(p.body.type));const newerTrainer=(!commutative.has(q.body.type)&&(r.attempt?.trainerVersion??0)>(q.body.expectedTrainerVersion??q.body.expectedVersion)+1)||(pendingState&&(r.attempt?.trainerVersion??0)>(pendingState.body.expectedTrainerVersion??pendingState.body.expectedVersion));if(newerTrainer){quarantine(q.attemptId,Error('NEWER_SERVER_WORK'),{dependentOnly:true});notice('Во время сохранения тренажёр обновился в другом окне. Поздние действия сохранены отдельно; их можно скачать.',true);}saveQueue();if(r.evaluation&&workspace?.id===q.attemptId)toast(r.evaluation.correct?(r.evaluation.complete?'Верно. Результат сохранён.':'Шаг верный.'):'Пока неверно. Попробуйте ещё раз или откройте подсказку.');}
catch(error){if(account?.id!==actor)return;if(error.status&&error.status<500&&error.status!==429){quarantine(q.attemptId,error,{dependentOnly:!(['LEARNING_ATTEMPT_ARCHIVED','LEARNING_FORBIDDEN','LEARNING_NOT_FOUND'].includes(error.code)||[401,403,404].includes(error.status)),failedOpId:q.body.opId});notice(errorText(error),true);try{remember(await api('/attempts/'+encodeURIComponent(q.attemptId)));}catch(_){};}else{connected=false;notice(errorText(error),true);clearTimeout(retryTimer);retryTimer=setTimeout(pump,2500);}}
finally{sending=false;updateWorkspace();updateOverview();updateConnection();if(outbox.length&&connected)queueMicrotask(pump);}}
function updateConnection(){const target=$('save-state'),attention=rejected.some(q=>q.attemptId===workspace?.id);if(target){target.textContent=!connected?'Нет связи':outbox.length?'Сохраняем…':attention?'Открыта серверная версия; есть неподтверждённые действия':rejected.length?'В другой работе есть неподтверждённые действия':'Все изменения сохранены';target.classList.toggle('pending',!connected||!!outbox.length||!!rejected.length);}if($('conflict-download'))$('conflict-download').hidden=!rejected.length;}
async function openContent(id,{fresh=false,sourceAttemptId}={}){const item=window.LearningCatalog.get(id);if(!item)return;if(teacher()){assignmentDialog({contentId:id});return;}try{const lessonId=fresh&&workspace?.lesson&&activeLesson?activeLesson.id:null;const body={opId:crypto.randomUUID(),trainerId:item.trainerId,contentId:item.contentId,fresh};if(sourceAttemptId)body.sourceAttemptId=sourceAttemptId;if(lessonId)body.lessonId=lessonId;const r=await post('/attempts',body);remember(r.attempt);if(lessonId)navigate('lesson='+lessonId);else navigate('attempt='+r.attempt.id);}catch(e){notice(errorText(e),true);}}
function attemptCard(a){return `<article class="card"><span class="badge ${a.outcome==='independent'||a.outcome==='repeated'?'':'warm'}">${E(labels[a.outcome]||'Начато')}</span><h3>${E(titleFor(a))}</h3><p>${a.updatedAt?'Последняя работа '+date(a.updatedAt):'Задание готово к работе'}</p><div class="actions"><a class="button primary" href="#attempt=${encodeURIComponent(a.id)}">${['independent','repeated','hinted','together','practiced'].includes(a.outcome)?'Посмотреть решение':'Продолжить'} →</a></div></article>`;}
function home(){const recent=[...attempts].filter(a=>!a.archivedAt).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))),pending=assignments.filter(a=>a.status==='published'&&!['independent','repeated'].includes(a.attempt?.outcome));main.innerHTML=`<div class="page-heading"><div><p class="eyebrow">${teacher()?'ВАШ УЧЕБНЫЙ КАБИНЕТ':'ХОРОШИЙ МОМЕНТ ДЛЯ СЛЕДУЮЩЕГО ШАГА'}</p><h1>${teacher()?'Здравствуйте, '+E(account.name):'Моя математика'}</h1><p>${teacher()?'Назначайте задания, наблюдайте за работой и подключайтесь, когда нужна помощь.':'Ваша работа сохраняется. Можно продолжить здесь или открыть кабинет на другом устройстве.'}</p></div>${teacher()?'<button class="primary" id="new-lesson">Начать групповой урок →</button>':''}</div>${teacher()?`<section class="hero-card"><div><span class="badge">Всё для следующего занятия</span><h2>У каждого — своя работа.<br>Объяснение — для всей группы.</h2><p>Четыре живых окна на листе, совместное решение и отдельная история каждого ученика.</p><div class="actions"><button class="primary" id="new-assignment">Выдать задание</button><a class="button" href="#students">Мои ученики</a></div></div><span class="hero-number" aria-hidden="true">4×2</span></section><div class="stat-strip"><div><strong>${students.length}</strong><span>учеников в кабинете</span></div><div><strong>${assignments.filter(a=>a.status==='published').length}</strong><span>выданных заданий</span></div><div><strong>${lessons.length}</strong><span>групповых занятий</span></div></div>`:recent.length?`<section class="hero-card"><div><span class="badge">Продолжить работу</span><h2>${E(titleFor(recent[0]))}</h2><p>${E(labels[recent[0].outcome]||'Начато')}. Условие, записи и введённые ответы остаются на месте.</p><a class="button primary" href="#attempt=${encodeURIComponent(recent[0].id)}">Открыть мою работу →</a></div><span class="hero-number" aria-hidden="true">↗</span></section>`:`<section class="hero-card"><div><span class="badge">Начнём с понятного шага</span><h2>Выберите тему или откройте задание преподавателя.</h2><p>После первого решения здесь появится кнопка продолжения.</p><a class="button primary" href="#course">Открыть мой курс →</a></div><span class="hero-number" aria-hidden="true">1</span></section>`}<div class="section-heading"><h2>${teacher()?'Последние работы':'Задания от Натальи Михайловны'}</h2><a href="#${teacher()?'students':'assignments'}">Посмотреть все →</a></div>${teacher()?recent.length?`<div class="cards">${recent.slice(0,3).map(attemptCard).join('')}</div>`:'<div class="empty">Создайте ученика и выдайте первое задание. Его работа появится здесь.</div>':pending.length?assignmentList(pending.slice(0,4)):'<div class="empty"><h2>Новых домашних заданий пока нет</h2><p>Можно выбрать тему в курсе или вернуться к трудной задаче.</p><a class="button" href="#course">Мой курс</a></div>'}`;$('new-lesson')?.addEventListener('click',lessonDialog);$('new-assignment')?.addEventListener('click',()=>assignmentDialog());}
function rosterPage(){main.innerHTML=`<div class="page-heading"><div><p class="eyebrow">ПОСТОЯННЫЕ УЧЕНИКИ</p><h1>Мои ученики</h1><p>У каждого ученика свой вход и история. Приглашение нужно только при первом входе.</p></div><button class="primary" id="add-student">Добавить ученика +</button></div>${students.length?`<div class="list">${students.map(s=>`<article class="list-row"><div class="student-name"><span class="avatar">${E(s.name.slice(0,1))}</span><div><h3>${E(s.name)}</h3><p>Логин: ${E(s.login)} · ${s.active?'Кабинет активирован':'Ожидает первого входа'}</p></div></div><div class="actions"><a class="button small" href="#student=${encodeURIComponent(s.id)}">Работа ученика</a><button class="small" data-assign-student="${E(s.id)}">Задание</button><button class="subtle small" data-reset-login="${E(s.id)}">Новый вход</button></div></article>`).join('')}</div>`:'<div class="empty"><h2>Пригласите первого ученика</h2><p>Достаточно имени и простого логина. Пароль ученик задаст сам.</p></div>'}`;$('add-student').onclick=studentDialog;main.querySelectorAll('[data-assign-student]').forEach(b=>b.onclick=()=>assignmentDialog({learnerIds:[b.dataset.assignStudent]}));main.querySelectorAll('[data-reset-login]').forEach(b=>b.onclick=()=>recoveryDialog(b.dataset.resetLogin));}
function inviteMarkup(token){const link=new URL(location.pathname,location.origin);link.hash='invite='+token;return `<div class="invite-result"><p>Отправьте ученику эту личную ссылку. После входа она перестанет действовать.</p><label>Личная ссылка<input id="invite-link" readonly value="${E(link.href)}"></label><div class="actions"><button type="button" id="copy-invite" class="small">Скопировать ссылку</button></div></div>`;}
function bindCopy(){if($('copy-invite'))$('copy-invite').onclick=async()=>{try{await navigator.clipboard.writeText($('invite-link').value);toast('Ссылка скопирована.');}catch(_){$('invite-link').focus();$('invite-link').select();toast('Выделенная ссылка готова для копирования.');}};}
function studentDialog(){modal('Новый ученик',`<form id="student-form" class="form-stack"><label>Имя ученика<input name="name" maxlength="80" autocomplete="off" required></label><label>Логин для входа<input name="login" pattern="[a-zA-Z0-9._-]{3,48}" minlength="3" maxlength="48" autocapitalize="none" spellcheck="false" autocomplete="off" required></label><p>Латинские буквы, цифры, точка, дефис или подчёркивание. Пароль ученик задаст сам.</p><p class="form-error" role="alert"></p><button class="primary" type="submit">Создать приглашение</button></form><div id="invitation"></div>`);bindAsyncForm('student-form',async form=>{const r=await post('/teacher/students',{name:form.get('name'),login:form.get('login')});await refreshData();if(activeRoute()==='students')rosterPage();$('student-form').hidden=true;$('invitation').innerHTML=inviteMarkup(r.invitationToken);bindCopy();});}
function recoveryDialog(id){const s=students.find(x=>x.id===id);modal('Новый вход: '+s.name,`<p>Ученик сможет задать новый пароль по личной ссылке. Учебная история останется.</p><button class="primary" id="issue-recovery">Выдать новую ссылку</button><p id="recovery-error" class="form-error" role="alert"></p><div id="invitation"></div>`);$('issue-recovery').onclick=async()=>{$('issue-recovery').disabled=true;try{const r=await post('/teacher/students/'+encodeURIComponent(id)+'/recovery',{});$('invitation').innerHTML=inviteMarkup(r.invitationToken);$('issue-recovery').hidden=true;bindCopy();}catch(e){$('recovery-error').textContent=errorText(e);$('issue-recovery').disabled=false;}};}
function assignmentList(rows){return `<div class="list">${rows.map(a=>`<article class="list-row"><div><span class="badge ${a.status==='draft'?'warm':'neutral'}">${a.status==='draft'?'Черновик':E(labels[a.attempt?.outcome]||'К выполнению')}</span><h3>${E(a.title||titleFor(a.attempt||a))}</h3><p>${teacher()?E(students.find(s=>s.id===a.learnerId)?.name||'Ученик')+' · ':''}${a.dueAt?'К '+date(a.dueAt):'Без срока'}</p></div><div class="actions"><a class="button ${teacher()?'':'primary'}" href="#assignment=${encodeURIComponent(a.id)}">${teacher()?'Открыть задание':'Задание и фотографии'} →</a>${a.attemptId?`<a class="button small" href="#attempt=${encodeURIComponent(a.attemptId)}">Тренажёр</a>`:''}</div></article>`).join('')}</div>`;}
function assignmentPage(){main.innerHTML=`<div class="page-heading"><div><p class="eyebrow">ОТ УРОКА К УРОКУ</p><h1>${teacher()?'Домашние задания':'Мои задания'}</h1><p>${teacher()?'Общее задание выдаётся каждому отдельно. В работе ученика видны помощь, исправления и новое самостоятельное решение.':'Здесь задания Натальи Михайловны. Тренажёр, фотографии решения и обратная связь собраны вместе.'}</p></div>${teacher()?'<button class="primary" id="create-assignment">Новое задание +</button>':''}</div>${assignments.length?assignmentList(assignments):'<div class="empty">Заданий пока нет.</div>'}`;$('create-assignment')?.addEventListener('click',()=>assignmentDialog());}
function extensionContext(){return{account,api,navigate,notice,catalog:window.LearningCatalog,students,assignments,attempts,onRefresh:async()=>{await refreshData();await render();}};}
function assignmentDialog(options={}){if(window.LearningTeaching?.createAssignment){window.LearningTeaching.createAssignment({...extensionContext(),...options});return;}const items=getItems();modal('Подготовить задание',`<form id="assignment-form" class="form-stack"><label>Название<input name="title" maxlength="160" value="Практика к следующему занятию" required></label><label>Тренажёр<select name="content">${items.map(i=>`<option value="${E(i.id)}" ${options.contentId===i.id?'selected':''}>${i.position?'№'+i.position+' · ':''}${E(i.title)}</option>`).join('')}</select></label><fieldset><legend>Кому выдать</legend><div class="checkbox-list">${students.map(s=>`<label class="checkbox-row"><input type="checkbox" name="student" value="${E(s.id)}" ${options.learnerIds?.includes(s.id)?'checked':''}>${E(s.name)}</label>`).join('')}</div></fieldset><label>Срок<input name="due" type="date"></label><p>Каждый ученик получит своё рабочее место с одинаковым начальным условием.</p><p class="form-error" role="alert"></p><button class="primary" type="submit">Создать черновик</button></form>`);bindAsyncForm('assignment-form',async form=>{const learnerIds=form.getAll('student');if(!learnerIds.length){$('assignment-form').querySelector('.form-error').textContent='Выберите хотя бы одного ученика.';return;}const item=LearningCatalog.get(form.get('content'));const body={opId:crypto.randomUUID(),title:form.get('title'),learnerIds,trainerId:item.trainerId,contentId:item.contentId};if(form.get('due'))body.dueAt=form.get('due');const result=await post('/assignments',body);closeModal();await refreshData();if(result.assignments?.[0])navigate('assignment='+result.assignments[0].id);else navigate('assignments');});}
function coursePage(){main.innerHTML=`<div class="page-heading"><div><p class="eyebrow">ОДИН КУРС · ОДНА ИСТОРИЯ</p><h1>Мой курс</h1><p>Откройте тему или привычный номер задания ЕГЭ. В обоих видах сохраняются те же решения.</p></div></div><div class="search-row"><div class="segmented" role="group" aria-label="Вид курса"><button data-course-mode="topics" aria-pressed="${catalogMode==='topics'}">По темам</button><button data-course-mode="exam" aria-pressed="${catalogMode==='exam'}">Задания 1–21</button></div><label>Найти тип задачи<input type="search" id="course-search" placeholder="Дроби, уравнения, площадь…"></label></div><p class="status-line">${getItems().length} учебных тренажёров. Успех в одной задаче ещё не означает освоения всего номера.</p><div id="catalog-grid" class="catalog-grid"></div><div class="section-heading"><h2>Проверочная работа</h2></div><section class="panel"><h3>Вариант из 21 задания</h3><p class="muted">По одному авторскому заданию на позицию. Можно продолжить на другом устройстве; разбор откроется после завершения.</p><div class="actions"><a class="button primary" href="#exam">Пробная работа · 21 задание →</a><a class="button" href="#diagnostic">Определить пробелы</a></div></section>`;main.querySelectorAll('[data-course-mode]').forEach(b=>b.onclick=()=>{catalogMode=b.dataset.courseMode;main.querySelectorAll('[data-course-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));drawCatalog();});$('course-search').oninput=drawCatalog;drawCatalog();}
function drawCatalog(){const query=$('course-search').value.toLocaleLowerCase('ru'),items=getItems();const topics=LearningCatalog.topics||[];const groups=catalogMode==='topics'?topics.map(t=>({id:t.id,title:t.title,items:items.filter(i=>i.topicId===t.id)})):Array.from({length:21},(_,n)=>({id:String(n+1),title:LearningCatalog.positions?.[n]?.title||'Задание '+(n+1),items:items.filter(i=>i.position===n+1)}));$('catalog-grid').innerHTML=groups.map(g=>{const rows=g.items.filter(i=>(i.title+' '+i.position).toLocaleLowerCase('ru').includes(query));if(!rows.length)return '';return `<section class="catalog-group">${catalogMode==='exam'?`<span class="number">${g.id.padStart(2,'0')}</span>`:'<span class="badge neutral">Учебная тема</span>'}<h2>${E(g.title)}</h2><details ${query?'open':''}><summary>${rows.length} ${rows.length===1?'тип задачи':'типов задач'} — выбрать</summary><ul class="catalog-items">${rows.map(i=>{const matches=attempts.filter(a=>a.contentId===i.contentId&&a.trainerId===i.trainerId&&!a.archivedAt);const latest=matches.at(-1);return `<li><button data-content="${E(i.id)}">${E(i.title)}</button><small>${teacher()?(matches.length?'Работали ученики: '+new Set(matches.map(a=>a.learnerId)).size:'Пока не назначали'):latest?E(labels[latest.outcome]||'Начато'):'Ещё не открывали'}</small></li>`;}).join('')}</ul></details></section>`;}).join('')||'<div class="empty">Таких тем не найдено. Попробуйте другое слово.</div>';$('catalog-grid').querySelectorAll('[data-content]').forEach(b=>b.onclick=()=>openContent(b.dataset.content));}
function repeatPage(){const rows=attempts.filter(a=>!a.archivedAt&&['hinted','together','practiced'].includes(a.outcome));main.innerHTML=`<div class="page-heading"><div><p class="eyebrow">ЗАКРЕПИТЬ ПОНИМАНИЕ</p><h1>Повторить трудное</h1><p>После помощи полезно решить новый аналог самостоятельно. Предыдущий разбор останется в истории.</p></div></div>${rows.length?`<div class="cards">${rows.map(a=>`<article class="card"><span class="badge warm">${E(labels[a.outcome])}</span><h3>${E(titleFor(a))}</h3><div class="actions"><button class="primary" data-repeat="${E(a.id)}">Новый аналог →</button><a class="button small" href="#attempt=${E(a.id)}">Мой разбор</a></div></article>`).join('')}</div>`:'<div class="empty"><h2>Здесь появятся задачи для закрепления</h2><p>Задачи, разобранные вместе или с подсказкой, можно будет повторить на новых числах.</p><a class="button" href="#course">Выбрать тему</a></div>'}`;main.querySelectorAll('[data-repeat]').forEach(b=>b.onclick=()=>{const a=attempts.find(x=>x.id===b.dataset.repeat);openContent(itemFor(a).id,{fresh:true,sourceAttemptId:a.id});});}
function lessonsPage(){main.innerHTML=`<div class="page-heading"><div><p class="eyebrow">РАБОТАЕМ ВМЕСТЕ</p><h1>${teacher()?'Групповые уроки':'Мои занятия'}</h1><p>${teacher()?'До восьми учеников. Все работают в своих заданиях, Вы видите их миниатюры и подключаетесь к нужной работе.':'Во время занятия Ваша работа остаётся слева, а объяснение Натальи Михайловны появляется рядом.'}</p></div>${teacher()?'<button class="primary" id="create-lesson">Новый урок +</button>':''}</div>${lessons.length?`<div class="list">${[...lessons].reverse().map(l=>`<article class="list-row"><div><span class="badge neutral">${date(l.createdAt)}</span><h3>${E(l.title)}</h3><p>${teacher()?(l.seats?.length||0)+' учеников · два листа по четыре':'Моя работа и объяснение преподавателя'}</p></div><a class="button primary" href="#lesson=${encodeURIComponent(l.id)}">Открыть урок →</a></article>`).join('')}</div>`:'<div class="empty"><h2>Занятий пока нет</h2><p>'+(teacher()?'Добавьте учеников, чтобы собрать первый урок.':'Назначенное занятие появится здесь.')+'</p></div>'}`;$('create-lesson')?.addEventListener('click',lessonDialog);}
function lessonDialog(){if(!students.length){studentDialog();return;}modal('Новый групповой урок',`<form id="lesson-form" class="form-stack"><label>Название занятия<input name="title" value="Математика · ${new Date().toLocaleDateString('ru-RU')}" maxlength="160" required></label><fieldset><legend>Ученики · от 1 до 8</legend><div class="checkbox-list">${students.map(s=>`<label class="checkbox-row"><input name="student" type="checkbox" value="${E(s.id)}">${E(s.name)}</label>`).join('')}</div></fieldset><p>Откроется последняя работа каждого ученика. На уроке можно выбрать другое задание.</p><p class="form-error" role="alert"></p><button class="primary" type="submit">Открыть урок →</button></form>`);bindAsyncForm('lesson-form',async form=>{const ids=form.getAll('student');if(!ids.length||ids.length>8){$('lesson-form').querySelector('.form-error').textContent='Выберите от одного до восьми учеников.';return;}const r=await post('/lessons',{opId:crypto.randomUUID(),title:form.get('title'),learnerIds:ids}),l=r.lesson||r;lessons.push(l);closeModal();navigate('lesson='+l.id);});}
async function lessonAction(type,payload){const lessonId=activeLesson?.id;if(!lessonId)return null;try{const r=await post('/lessons/'+encodeURIComponent(lessonId)+'/actions',{opId:crypto.randomUUID(),expectedVersion:activeLesson.version,type,payload});if(activeLesson?.id!==lessonId)return r.lesson||r;activeLesson=r.lesson||r;for(const s of activeLesson.seats||[])if(s.attempt)remember(s.attempt);if(activeLesson.common)remember(activeLesson.common);updateWorkspace();updateOverview();return activeLesson;}catch(e){notice(errorText(e),true);try{const latest=await api('/lessons/'+encodeURIComponent(lessonId));if(activeLesson?.id===lessonId){activeLesson=latest;updateWorkspace();updateOverview();}}catch(_){}return null;}}
function lessonSeat(learnerId){return activeLesson?.seats?.find(s=>s.learnerId===learnerId);}
async function showLesson(id,learnerId,serial=routeNumber){const next=await api('/lessons/'+encodeURIComponent(id));if(serial!==routeNumber)return;activeLesson=next;for(const s of activeLesson.seats||[])if(s.attempt)remember(s.attempt);if(activeLesson.common)remember(activeLesson.common);if(!teacher()){const mine=activeLesson.seats?.find(s=>s.learnerId===account.id);if(mine?.attempt){activeAttempt=mine.attempt;mountWorkspace(mine.attempt,{lesson:true,learnerId:mine.learnerId});}else{mountWaitingLesson();}return;}
 if(learnerId){const a=learnerId==='common'?activeLesson.common:lessonSeat(learnerId)?.attempt;if(a){activeAttempt=a;mountWorkspace(a,{lesson:true,learnerId});return;}}
 mountOverview();}
function mountWaitingLesson(){
 main.innerHTML=`<a class="back-link" href="#lessons">← Мои занятия</a><h1>${E(activeLesson.title)}</h1><div class="work-columns" id="work-columns" data-mobile-view="watch"><section class="work-panel empty"><h2>Скоро начнём</h2><p>Наталья Михайловна готовит Ваше задание. Оставьте эту страницу открытой.</p></section>${watchPanelMarkup()}</div>`;
 overview={waiting:true,watchFrame:null,watchDraw:null,watchId:null};
 $('watch-expand').onclick=()=>{const expanded=$('work-columns').classList.toggle('watch-expanded');$('watch-expand').textContent=expanded?'Вернуться к двум окнам':'Развернуть объяснение ↗';overview?.watchFrame?.fit();overview?.watchDraw?.draw();};
 updateWatch();dispose=()=>{overview?.watchFrame?.destroy();overview?.watchDraw?.destroy();overview=null;};
}
function overviewHtml(){return `<div class="page-heading"><div><a class="back-link" href="#lessons">← Все занятия</a><h1>${E(activeLesson.title)}</h1><p>Нажмите на работу, чтобы открыть её крупно и решать вместе.</p></div><div class="actions"><button class="primary" id="lesson-assign">Выдать задание</button><button id="expand-overview">Развернуть 4 работы ↗</button>${activeLesson.common?'<button id="open-common">Общая доска</button>':''}<button id="stop-presentation" ${activeLesson.presentation?.target?'':'hidden'}>Завершить объяснение</button></div></div><nav class="lesson-roster" id="lesson-roster" aria-label="Ученики занятия"></nav><div id="lesson-grid" class="lesson-grid"></div><nav id="sheet-tabs" class="sheet-tabs" aria-label="Листы урока"></nav>`;}
function mountOverview(){main.innerHTML=overviewHtml();overview={frames:new Map(),drawings:new Map(),key:''};$('lesson-assign').onclick=()=>lessonAssignmentDialog();$('expand-overview').onclick=()=>{const expanded=document.body.classList.toggle('board-focus');$('expand-overview').textContent=expanded?'Вернуться в кабинет':'Развернуть 4 работы ↗';};$('open-common')?.addEventListener('click',()=>openSeat('common'));$('stop-presentation').onclick=()=>lessonAction('present',{target:null});updateOverview();dispose=()=>{document.body.classList.remove('board-focus');overview?.frames?.forEach(f=>f.destroy());overview?.drawings?.forEach(d=>d.destroy());overview=null;};}
async function openSeat(id){if(activeLesson.presentation?.target)await lessonAction('present',{target:id});navigate('lesson='+activeLesson.id+'&student='+encodeURIComponent(id));}
function updateOverview(){if(!overview||!activeLesson)return;if(overview.waiting){const mine=activeLesson.seats?.find(s=>s.learnerId===account.id);if(mine?.attempt)render();else updateWatch();return;}if(!$('lesson-grid'))return;const seats=activeLesson.seats||[];sheet=Math.min(sheet,Math.max(0,Math.ceil(seats.length/4)-1));const visible=seats.slice(sheet*4,sheet*4+4),key=visible.map(s=>s.learnerId+':'+s.attempt?.id).join('|');$('lesson-roster').innerHTML=seats.map(s=>`<button data-seat="${E(s.learnerId)}">${E(s.name)}${s.attempt?.state?.help?' · нужна помощь':''}</button>`).join('');$('lesson-roster').querySelectorAll('[data-seat]').forEach(b=>b.onclick=()=>openSeat(b.dataset.seat));$('stop-presentation').hidden=!activeLesson.presentation?.target;
 if(overview.key!==key){overview.frames.forEach(f=>f.destroy());overview.drawings.forEach(d=>d.destroy());overview.frames.clear();overview.drawings.clear();$('lesson-grid').innerHTML=visible.map(s=>`<article class="lesson-tile"><header class="tile-heading"><div><h3>${E(s.name)}</h3><p>${E(s.attempt?titleFor(s.attempt):'Задание пока не выбрано')}</p></div><button data-open-seat="${E(s.learnerId)}">Открыть ↗</button></header><div class="tile-preview" data-preview-seat="${E(s.learnerId)}"><div class="trainer-host" id="preview-${E(s.learnerId)}">${s.attempt?'':'<div class="blank-board">Выберите задание<br>для этого ученика</div>'}</div></div><footer class="tile-footer"><span id="status-${E(s.learnerId)}">${E(labels[s.attempt?.outcome]||'Ожидает задания')}</span><button class="subtle small" data-show-drawing="${E(s.learnerId)}" ${s.attempt?'':'hidden'}>Доска</button></footer></article>`).join('');for(const s of visible){if(!s.attempt)continue;const item=itemFor(s.attempt);if(item){const f=new LearningTrainerFrame($('preview-'+s.learnerId),{item,attempt:s.attempt,readOnly:true,preview:true});overview.frames.set(s.learnerId,f);}}
 $('lesson-grid').querySelectorAll('[data-open-seat]').forEach(b=>b.onclick=()=>{const seat=lessonSeat(b.dataset.openSeat);if(seat.attempt)openSeat(seat.learnerId);else lessonAssignmentDialog([seat.learnerId]);});$('lesson-grid').querySelectorAll('[data-preview-seat]').forEach(b=>b.onclick=()=>{const seat=lessonSeat(b.dataset.previewSeat);if(seat.attempt)openSeat(seat.learnerId);else lessonAssignmentDialog([seat.learnerId]);});$('lesson-grid').querySelectorAll('[data-show-drawing]').forEach(b=>b.onclick=()=>{const id=b.dataset.showDrawing,host=$('preview-'+id);if(overview.drawings.has(id)){overview.drawings.get(id).destroy();overview.drawings.delete(id);host.classList.remove('drawing-host');overview.frames.get(id).element.hidden=false;b.textContent='Доска';}else{overview.frames.get(id).element.hidden=true;host.classList.add('drawing-host');const draw=new LearningDrawing(host,{readOnly:true});draw.update(lessonSeat(id)?.attempt?.strokes);overview.drawings.set(id,draw);b.textContent='Тренажёр';}});overview.key=key;}
 for(const s of visible){if(s.attempt){overview.frames.get(s.learnerId)?.update(s.attempt,{readOnly:true});overview.drawings.get(s.learnerId)?.update(s.attempt.strokes);if($('status-'+s.learnerId))$('status-'+s.learnerId).textContent=labels[s.attempt.outcome]||'Начато';}}
 $('sheet-tabs').innerHTML=Array.from({length:Math.ceil(seats.length/4)},(_,i)=>`<button data-sheet="${i}" aria-current="${sheet===i?'page':'false'}">Ученики ${i*4+1}–${Math.min(i*4+4,seats.length)}</button>`).join('');$('sheet-tabs').querySelectorAll('[data-sheet]').forEach(b=>b.onclick=()=>{sheet=Number(b.dataset.sheet);updateOverview();});}
function lessonAssignmentDialog(selectedIds){const selected=selectedIds||activeLesson.seats.map(s=>s.learnerId);modal('Задание на урок',`<form id="lesson-assignment-form" class="form-stack"><label>Тренажёр<select name="content">${getItems().map(i=>`<option value="${E(i.id)}">${i.position?'№'+i.position+' · ':''}${E(i.title)}</option>`).join('')}</select></label><fieldset><legend>Ученики</legend><div class="checkbox-list">${[...activeLesson.seats,{learnerId:'common',name:'Общая доска'}].map(s=>`<label class="checkbox-row"><input type="checkbox" name="student" value="${E(s.learnerId)}" ${selected.includes(s.learnerId)?'checked':''}>${E(s.name)}</label>`).join('')}</div></fieldset><p>У каждого будет своя попытка с одинаковым условием.</p><p class="form-error" role="alert"></p><button class="primary" type="submit">Выдать на урок</button></form>`);bindAsyncForm('lesson-assignment-form',async form=>{const learnerIds=form.getAll('student');if(!learnerIds.length){$('lesson-assignment-form').querySelector('.form-error').textContent='Выберите ученика.';return;}const item=LearningCatalog.get(form.get('content'));const result=await lessonAction('assign',{learnerIds,trainerId:item.trainerId,contentId:item.contentId});if(!result)return;closeModal();await refreshData();updateOverview();toast('Задания подготовлены для урока.');});}
function watchPanelMarkup(visible=true){return `<aside id="watch-panel" class="watch-panel" ${visible?'':'hidden'}><header class="watch-panel-header"><p class="eyebrow">ОБЩИЙ РАЗБОР</p><h2>Наталья Михайловна объясняет</h2><p id="watch-caption">Ваша личная работа сохраняется</p><button id="watch-expand" class="small">Развернуть объяснение ↗</button></header><div id="watch-placeholder" class="watch-placeholder">Когда преподаватель начнёт объяснение, здесь появится работа, которую разбирает группа.</div><div class="trainer-host" id="watch-trainer" hidden></div><div class="drawing-host" id="watch-drawing" hidden></div></aside>`;}
function workspaceMarkup(a,lesson){const person=a.learnerId===a.teacherId?'Общая доска':students.find(s=>s.id===a.learnerId)?.name||account.name;return `<header class="workspace-heading"><a class="back-link" href="#${lesson?'lesson='+activeLesson.id:'home'}" id="workspace-back">← ${lesson&&teacher()?'Все работы':lesson?'Мои занятия':'Мой кабинет'}</a><div class="page-heading"><div><span class="badge neutral">${lesson?E(activeLesson.title)+' · '+E(person):teacher()?E(person):'Моя работа'}</span><h1>${E(titleFor(a))}</h1><p><span id="attempt-outcome">${E(labels[a.outcome]||'Начато')}</span> · <span id="save-state" class="save-state">Все изменения сохранены</span></p></div><div class="actions">${teacher()?'<button id="trainer-control">Подключиться к тренажёру</button>':''}${lesson&&teacher()?'<button id="present-work">Объяснять группе</button><button id="workspace-assign">Другое задание</button>':''}<button id="show-history">История решения</button><button id="conflict-download" hidden>Скачать неподтверждённое</button></div></div><p id="control-notice" class="notice" hidden></p><div id="archived-notice" class="notice" hidden>Результаты перенесены в архив. История решения сохранена. <a href="#course">Начать новую попытку в курсе →</a></div></header>${lesson&&teacher()?'<nav id="workspace-roster" class="lesson-roster" aria-label="Переключить ученика"></nav>':''}<section id="history-bar" class="history-bar" hidden></section><div class="workspace-tabs segmented" role="group" aria-label="Работа и объяснение" ${lesson&&!teacher()?'':'hidden'}><button data-mobile-tab="own" aria-pressed="true">Моя работа</button><button data-mobile-tab="watch" aria-pressed="false">Наталья Михайловна объясняет</button></div><div class="work-columns" id="work-columns" data-mobile-view="own"><section class="work-panel"><header class="work-panel-header"><h2 id="work-panel-title">Задание</h2><div class="segmented" role="group" aria-label="Рабочее поле"><button data-work-view="trainer" aria-pressed="true">Тренажёр</button><button data-work-view="board" aria-pressed="false">Лист для решения</button></div></header><div class="trainer-host" id="trainer-host"></div><div id="drawing-panel" hidden><div class="board-tools" role="group" aria-label="Инструменты доски"><button id="pen" class="small" aria-pressed="true">Перо</button><button id="eraser" class="small" aria-pressed="false">Ластик</button><label><span class="sr-only">Цвет</span><input id="pen-color" type="color" value="${teacher()?'#16804c':'#23352d'}"></label><label>Толщина<input id="pen-width" type="range" min="1" max="12" value="3"></label><button id="undo-stroke" class="small">Отменить свой штрих</button></div><div class="drawing-host" id="drawing-host"></div></div></section>${watchPanelMarkup(lesson&&!teacher())}</div><div id="reference-host" class="reference-host"></div>`;}
function mountWorkspace(a,{lesson=false,learnerId=null}={}){main.innerHTML=workspaceMarkup(a,lesson);workspace={id:a.id,lesson,learnerId,frame:null,draw:null,watchFrame:null,watchDraw:null,watchId:null,history:null,reference:null,historyLoading:false};const editable=owns(a),item=itemFor(a);if(item)workspace.frame=new LearningTrainerFrame($('trainer-host'),{item,attempt:effective(a),readOnly:!editable,onChange:trainerChange});else $('trainer-host').innerHTML='<div class="blank-board">Для этого задания пока нет подключённого тренажёра.</div>';
 workspace.draw=new LearningDrawing($('drawing-host'),{actorId:account.id,color:teacher()?'#16804c':'#23352d',onStroke:s=>action(workspace.id,'stroke',s),onErase:id=>action(workspace.id,'erase',{strokeId:id})});
 main.querySelectorAll('[data-work-view]').forEach(b=>b.onclick=()=>{const board=b.dataset.workView==='board';$('drawing-panel').hidden=!board;$('trainer-host').hidden=board;main.querySelectorAll('[data-work-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));workspace.draw.draw();});
 main.querySelectorAll('[data-mobile-tab]').forEach(b=>b.onclick=()=>{$('work-columns').dataset.mobileView=b.dataset.mobileTab;main.querySelectorAll('[data-mobile-tab]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));workspace.watchDraw?.draw();workspace.draw.draw();});
 $('pen').onclick=()=>setPen('pen');$('eraser').onclick=()=>setPen('eraser');$('pen-color').oninput=e=>{workspace.draw.color=e.target.value;};$('pen-width').oninput=e=>{workspace.draw.width=Number(e.target.value);};$('undo-stroke').onclick=()=>{const last=[...effective(activeAttempt).strokes].reverse().find(s=>s.author===account.id||s.actor?.id===account.id);if(last)action(workspace.id,'undo',{strokeId:last.id});else toast('Ваших штрихов пока нет.');};
 $('trainer-control')?.addEventListener('click',async()=>{if(queuedFor(a.id).length){toast('Дождитесь сохранения текущих действий.');return;}const id=workspace.id;$('trainer-control').disabled=true;try{const latest=await api('/attempts/'+encodeURIComponent(id));if(!workspace||workspace.id!==id)return;remember(latest);await action(id,'control',{controller:latest.controller==='teacher'?'student':'teacher'});}catch(error){notice(errorText(error),true);}finally{updateWorkspace();}});
 $('workspace-assign')?.addEventListener('click',()=>lessonAssignmentDialog([workspace.learnerId]));
 $('watch-expand')?.addEventListener('click',()=>{const expanded=$('work-columns').classList.toggle('watch-expanded');$('watch-expand').textContent=expanded?'Вернуться к двум окнам':'Развернуть объяснение ↗';workspace.watchFrame?.fit();workspace.watchDraw?.draw();});
 if($('workspace-roster')){$('workspace-roster').innerHTML=[...activeLesson.seats,{learnerId:'common',name:'Общая доска'}].map(s=>`<button data-workspace-seat="${E(s.learnerId)}" aria-current="${s.learnerId===learnerId}">${E(s.name)}</button>`).join('');$('workspace-roster').querySelectorAll('[data-workspace-seat]').forEach(b=>b.onclick=()=>openSeat(b.dataset.workspaceSeat));}
 $('present-work')?.addEventListener('click',()=>lessonAction('present',{target:activeLesson.presentation?.target===workspace.learnerId?null:workspace.learnerId}));
 $('show-history').onclick=showHistory;$('conflict-download').onclick=exportUnsent;
 $('workspace-back').onclick=async e=>{if(lesson&&teacher()&&activeLesson.presentation?.target){e.preventDefault();await lessonAction('present',{target:null});navigate('lesson='+activeLesson.id);}};
 if(window.LearningReferences&&a.taskSpec)workspace.reference=LearningReferences.mount($('reference-host'),{taskSpec:a.taskSpec,mode:'practice',onReference:()=>{if(!workspace.history)action(a.id,'reference',{id:'fipi-2027'});},onHelp:async(level,details)=>{if(!owns(activeAttempt)||workspace.history){toast('Сейчас просмотр работы.');return false;}return await action(a.id,'hint',{});}});
 if(a.trainerId==='board'){main.querySelector('[data-work-view=board]').click();$('trainer-control')?.setAttribute('hidden','');}
 updateWorkspace();dispose=()=>{workspace?.frame?.destroy();workspace?.draw?.destroy();workspace?.watchFrame?.destroy();workspace?.watchDraw?.destroy();workspace?.reference?.destroy();workspace=null;};}
function owns(a){return !!a&&!a.archivedAt&&connected&&!workspace?.history&&!queuedFor(a.id).some(q=>q.body.type==='control')&&(teacher()?a.controller==='teacher':a.learnerId===account.id&&a.controller==='student');}
function setPen(tool){workspace.draw.tool=tool;$('pen').setAttribute('aria-pressed',String(tool==='pen'));$('eraser').setAttribute('aria-pressed',String(tool==='eraser'));}
function trainerChange(change){if(!workspace||workspace.history)return;const a=activeAttempt;if(!owns(a))return;const {kind,details,state}=change;if(kind==='newtask'||kind==='new-task'){if(teacher()){toast('Чтобы выдать новый вариант, выберите задание на урок.');return;}if(queuedFor(a.id).length){toast('Сначала дождитесь сохранения текущей работы.');return;}openContent(itemFor(a).id,{fresh:true,sourceAttemptId:a.id});return;}const type=kind==='check'?'check':kind==='hint'?'hint':kind==='reference'?'reference':'state';const payload=type==='state'?{state}:type==='check'?{state,details}:type==='hint'?{state,...(Number.isInteger(details.step)?{step:details.step}:{})}:{id:String(details.id||'reference')};action(a.id,type,payload);}
function updateWorkspace(){if(!workspace||!activeAttempt||workspace.id!==activeAttempt.id)return;const a=workspace.history?.current||effective(activeAttempt),viewing=!!workspace.history,archived=!!activeAttempt.archivedAt,editable=!viewing&&owns(activeAttempt);workspace.frame?.update(a,{readOnly:!editable});workspace.draw?.update(a.strokes,{readOnly:viewing||archived||!connected});if($('attempt-outcome'))$('attempt-outcome').textContent=labels[a.outcome]||'Начато';if($('trainer-control')){$('trainer-control').textContent=activeAttempt.controller==='teacher'?'Вернуть управление ученику':'Подключиться к тренажёру';$('trainer-control').disabled=viewing||archived||queuedFor(a.id).length>0;}
 const controlled=teacher()?activeAttempt.controller!=='teacher':activeAttempt.controller==='teacher';$('archived-notice').hidden=!archived;$('control-notice').hidden=!controlled||viewing||archived;$('control-notice').textContent=teacher()?'Вы наблюдаете за работой. Для изменения тренажёра нажмите «Подключиться». На листе можно писать вместе.':'Наталья Михайловна объясняет в Вашем тренажёре. Вы можете делать записи на листе.';
 for(const id of ['pen','eraser','pen-color','pen-width','undo-stroke'])$(id).disabled=viewing||archived||!connected;if($('workspace-assign'))$('workspace-assign').disabled=viewing;
 if($('present-work')){$('present-work').textContent=activeLesson?.presentation?.target===workspace.learnerId?'Завершить объяснение':'Объяснять группе';$('present-work').disabled=viewing||archived;}
 $('reference-host').hidden=viewing;updateConnection();updateWatch();}
function updateWatch(){const view=workspace?.lesson?workspace:overview?.waiting?overview:null;if(!view||teacher())return;const a=activeLesson?.presentation?.attempt;const available=!!a;$('watch-placeholder').hidden=available;$('watch-trainer').hidden=!available||a?.trainerId==='board';$('watch-drawing').hidden=!available;$('watch-panel').classList.toggle('watch-board-only',a?.trainerId==='board');if(!a){view.watchFrame?.destroy();view.watchDraw?.destroy();view.watchFrame=null;view.watchDraw=null;view.watchId=null;return;}if(view.watchId!==a.id){view.watchFrame?.destroy();view.watchDraw?.destroy();view.watchFrame=null;const item=itemFor(a);if(item)view.watchFrame=new LearningTrainerFrame($('watch-trainer'),{item,attempt:a,readOnly:true});view.watchDraw=new LearningDrawing($('watch-drawing'),{readOnly:true});view.watchId=a.id;}view.watchFrame?.update(a,{readOnly:true});view.watchDraw?.update(a.strokes);$('watch-caption').textContent=activeLesson.presentation.target==='common'?'Общая доска · только просмотр':'Совместный разбор · только просмотр';}
function applyRecorded(a,event){const p=event.payload||{};a.version=event.revision;if(!commutative.has(event.type))a.trainerVersion=(a.trainerVersion||0)+1;if(p.state)a.state=clone(p.state);if(event.type==='control')a.controller=p.controller;if(event.type==='stroke')a.strokes.push({...clone(p),author:event.actor?.id||event.actor,role:event.actor?.role,at:event.at});if(event.type==='erase'||event.type==='undo')a.strokes=a.strokes.filter(s=>s.id!==p.strokeId);if(p.after){if(p.after.outcome)a.outcome=p.after.outcome;if(p.after.assistance)a.assistance=clone(p.after.assistance);if(p.after.controller)a.controller=p.after.controller;if(p.after.archivedAt)a.archivedAt=p.after.archivedAt;}return a;}
async function showHistory(){if(!workspace||workspace.historyLoading)return;if(queuedFor(workspace.id).length){toast('Дождитесь сохранения действий, затем откройте историю.');return;}workspace.historyLoading=true;$('show-history').disabled=true;try{if(teacher()&&workspace.lesson&&activeLesson.presentation?.target)await lessonAction('present',{target:null});const id=workspace.id,first=await api('/attempts/'+encodeURIComponent(id)+'/history?after=0&limit=100'),through=first.version,events=[...(first.events||[])].filter(e=>e.revision<=through);let page=first;while(page.hasMore&&page.nextAfter<through){page=await api('/attempts/'+encodeURIComponent(id)+'/history?after='+page.nextAfter+'&limit=100&through='+through);events.push(...(page.events||[]).filter(e=>e.revision<=through));}if(!workspace||workspace.id!==id)return;if(!first.initialAttempt)throw Error('HISTORY_INITIAL_MISSING');workspace.history={initial:clone(first.initialAttempt),events,current:null};$('history-bar').hidden=false;$('history-bar').innerHTML='<div class="page-heading"><div><h2>История решения</h2><p>Запись только для просмотра. Текущая работа остаётся на месте.</p></div><div class="actions"><button id="export-history" class="small">Скачать запись</button><button id="exit-history" class="small">К текущей работе</button></div></div><label class="sr-only" for="history-range">Момент записи</label><input id="history-range" type="range" min="0" step="1"><output id="history-time" for="history-range"></output>';$('history-range').max=events.length;$('history-range').value=events.length;$('history-range').oninput=seekHistory;$('export-history').onclick=()=>download('mathexam-attempt-'+id+'.json',{initialAttempt:first.initialAttempt,events,version:through});$('exit-history').onclick=()=>{workspace.history=null;$('history-bar').hidden=true;workspace.frame?.update(effective(activeAttempt),{readOnly:!owns(activeAttempt),force:true});updateWorkspace();};seekHistory();}catch(e){notice(errorText(e),true);}finally{if(workspace)workspace.historyLoading=false;if($('show-history'))$('show-history').disabled=false;}}
function seekHistory(){const h=workspace.history,n=Number($('history-range').value),a=clone(h.initial);for(let i=0;i<n;i++)applyRecorded(a,h.events[i]);h.current=a;const e=h.events[n-1],names={state:'Работа в тренажёре',check:'Проверка ответа',hint:'Подсказка',reference:'Справочный лист',stroke:'Запись на листе',erase:'Удаление штриха',undo:'Отмена штриха',control:'Передача управления',archive:'Перенос результатов в архив'};$('history-time').textContent=e?new Date(e.at).toLocaleString('ru-RU')+' · '+(names[e.type]||'Действие')+' · '+(e.actor?.role==='teacher'?'преподаватель':'ученик'):'Начало работы';workspace.frame?.update(a,{readOnly:true,force:true});updateWorkspace();}
async function extension(page,id){if(window.LearningTeaching?.mount){const cleanup=await LearningTeaching.mount(main,{...extensionContext(),page,id});if(typeof cleanup==='function')dispose=cleanup;return;}if(page==='student'){const s=students.find(x=>x.id===id);main.innerHTML=`<a class="back-link" href="#students">← Ученики</a><h1>${E(s?.name||'Ученик')}</h1><div class="cards">${attempts.filter(a=>a.learnerId===id).map(attemptCard).join('')||'<div class="empty">Сохранённых работ пока нет.</div>'}</div>`;return;}if(page==='assignment'){const a=assignments.find(x=>x.id===id);main.innerHTML=`<a class="back-link" href="#assignments">← Задания</a><h1>${E(a?.title||'Задание')}</h1>${a?.attempt?attemptCard(a.attempt):'<p>Задание готовится.</p>'}`;return;}main.innerHTML='<h1>Итоги и планы</h1><p>Выберите ученика, чтобы посмотреть его работу.</p><a class="button" href="#students">Мои ученики</a>';}
async function render(){if(!account){authPage();return;}const serial=++routeNumber;dispose();dispose=()=>{};workspace=null;overview=null;activeAttempt=null;activeLesson=null;const route=activeRoute(),params=new URLSearchParams(route),page=route.split('=')[0].split('&')[0];document.querySelectorAll('[data-nav]').forEach(a=>a.setAttribute('aria-current',a.dataset.nav===page?'page':'false'));document.title=(teacher()?'Кабинет преподавателя':'Мой кабинет')+' · MathExam';main.innerHTML='<section class="loading-panel"><span class="loading-dot"></span><p>Открываем работу…</p></section>';try{if(params.has('attempt')){const opened=await api('/attempts/'+encodeURIComponent(params.get('attempt')));if(serial!==routeNumber)return;activeAttempt=opened;remember(activeAttempt);mountWorkspace(activeAttempt);}else if(params.has('lesson')){await showLesson(params.get('lesson'),params.get('student'),serial);}else if((params.has('run')||page==='exam'||page==='diagnostic')&&window.LearningExam?.mount){const mounted=await LearningExam.mount(main,{...extensionContext(),id:params.get('run')||null,mode:page==='diagnostic'?'diagnostic':'exam'});dispose=typeof mounted==='function'?mounted:()=>mounted?.destroy?.();}else if(params.has('student'))await extension('student',params.get('student'));else if(params.has('assignment'))await extension('assignment',params.get('assignment'));else if(page==='students'&&teacher())rosterPage();else if(page==='assignments')assignmentPage();else if(page==='course')coursePage();else if(page==='repeat')repeatPage();else if(page==='lessons')lessonsPage();else if(page==='reports'&&teacher())await extension('reports');else home();if(serial===routeNumber)main.focus({preventScroll:true});}catch(e){if(serial!==routeNumber)return;notice(errorText(e),true);main.innerHTML='<section class="empty"><h1>Не удалось открыть работу</h1><p>Сохранённые данные остаются на сервере. Можно повторить подключение.</p><button id="retry-page" class="primary">Попробовать снова</button></section>';$('retry-page').onclick=render;}}
async function poll(){if(!account||polling||document.hidden||sending)return;polling=true;try{if(activeLesson){const lesson=await api('/lessons/'+encodeURIComponent(activeLesson.id));if(activeLesson?.id!==lesson.id)return;activeLesson=lesson;for(const s of lesson.seats||[])if(s.attempt)remember(s.attempt);if(lesson.common)remember(lesson.common);if(workspace?.lesson){const a=workspace.learnerId==='common'?lesson.common:lesson.seats?.find(s=>s.learnerId===workspace.learnerId)?.attempt;if(!a||a.archivedAt||a.id!==workspace.id){if(!a||a.archivedAt)quarantine(workspace.id,Error('LEARNING_ATTEMPT_ARCHIVED'));activeAttempt=null;await render();return;}activeAttempt=a;}updateOverview();updateWorkspace();}else if(activeAttempt){const id=activeAttempt.id,a=await api('/attempts/'+encodeURIComponent(id));if(activeAttempt?.id!==id)return;remember(a);if(a.archivedAt&&queuedFor(id).length)quarantine(id,Error('LEARNING_ATTEMPT_ARCHIVED'));updateWorkspace();}if(!activeLesson&&!activeAttempt&&!$('modal').open&&Date.now()-listingPollAt>15000&&['home','students','assignments','lessons','repeat'].includes(activeRoute())){listingPollAt=Date.now();const before=JSON.stringify([students,assignments,attempts,lessons]);await refreshData();if(JSON.stringify([students,assignments,attempts,lessons])!==before)await render();}connected=true;updateConnection();if(outbox.length)pump();}catch(e){connected=false;updateConnection();if(!outbox.length)notice(errorText(e),true);}finally{polling=false;}}
window.addEventListener('hashchange',render);window.addEventListener('online',()=>{poll();pump();});window.addEventListener('beforeunload',e=>{if(outbox.length){e.preventDefault();e.returnValue='';}});document.addEventListener('visibilitychange',()=>{if(!document.hidden){poll();pump();}});setInterval(poll,2200);
window.LearningApp={api,navigate,account:()=>account,refresh:async()=>{await refreshData();render();},exportUnsent};
(async()=>{try{try{const status=await api('/status');if(status.trainerOrigin)window.LearningTrainerOrigin=status.trainerOrigin;}catch(_){}if(authInvite){authPage();return;}const session=await api('/session');account=session.account;csrf=session.csrfToken||csrf;loadQueue();await refreshData();renderShell();await render();if(outbox.length)pump();}catch(e){if(e.status===401){authPage();}else{authPage();notice(errorText(e),true);}}})();
})();
