/* Course presentation only. Attempts and points are owned by the server. */
(function(root){
'use strict';
const E=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const complete=new Set(['independent','repeated','hinted','together','practiced']);
function publicHref(item){try{const url=new URL(item.publicUrl||item.url,'https://mathexam.space');return url.origin==='https://mathexam.space'?url.href:'';}catch(_){return '';}}
function mountRoute(host,context){
 const map=root.LearningPreparation, teacher=()=>context.account.role==='teacher';
 const profile=context.profile||{course:'foundations',goal:null,focus:''},oge=profile.course==='oge';
 const own=(context.attempts||[]).filter(a=>a.learnerId===context.account.id&&!a.archivedAt);
 let alive=true,mode='tasks',goalKey=profile.goal||'pass',rewards=null,rewardsError=false,plan=null,planError=false,progress=null,progressError=false;
 const section=document.createElement('section');section.className='preparation';host.replaceChildren(section);
 function entryFor(id){const listed=map.get(id);if(listed)return listed;const item=context.catalog.get(id);return item?{id:item.id,managedId:item.id,title:item.title,kind:'managed',tier:'core',url:'/learning/#practice='+encodeURIComponent(item.id),publicUrl:item.url}:null;}
 function attemptsFor(entry){const item=context.catalog.get(entry.managedId);return item?own.filter(a=>a.trainerId===item.trainerId&&a.contentId===item.contentId):[];}
 function progressFor(entry){const item=context.catalog.get(entry.managedId);return item&&progress?.find(p=>p.trainerId===item.trainerId&&p.contentId===item.contentId);}
 function hasCompleted(entry){return progress?!!progressFor(entry)?.completed:attemptsFor(entry).some(a=>complete.has(a.outcome));}
 function latest(entry){if(progress)return progressFor(entry)?.latest||null;return attemptsFor(entry).sort((a,b)=>String(b.updatedAt||b.createdAt).localeCompare(String(a.updatedAt||a.createdAt)))[0];}
 function state(entry){const a=latest(entry);return a?(context.labels[a.outcome]||'Начато'):progress?'Ещё не начинали':'История темы пока не загружена';}
 function openButton(entry){const a=latest(entry),done=a&&complete.has(a.outcome);return `<button type="button" class="${done?'':'primary'}" data-prep-start="${E(entry.managedId)}" ${done?'data-prep-fresh="true"':''}>${teacher()?'Назначить ученику':done?'Новый пример':a?'Продолжить':'Начать задание'} →</button>${a?`<a class="button small" href="#attempt=${encodeURIComponent(a.id)}">Моё решение</a>`:''}`;}
 function entryCard(entry,reason=''){
  const managed=entry.managedId&&context.catalog.get(entry.managedId),href=publicHref(entry);
  return `<article class="prep-task" data-prep-item="${E(entry.id)}"><span class="prep-kind">${managed?'Результат в кабинете':'Практика на сайте'}</span><h3>${E(entry.title)}</h3>${reason?`<p>${E(reason)}</p>`:''}${entry.note?`<p class="small">${E(entry.note)}</p>`:''}${!teacher()&&managed?`<p class="prep-task-status">${E(state(entry))}</p>`:''}<div class="actions">${managed?openButton(entry):''}${href?`<a class="button ${managed?'small':''}" href="${E(href)}" target="_blank" rel="noopener">${managed?'Исследовать в лаборатории':'Открыть упражнение'} ↗</a>`:''}</div>${!managed?'<p class="small">Эта страница не передаёт результат в кабинет. Решение можно разобрать с преподавателем.</p>':''}</article>`;
 }
 function rewardsMarkup(){
  if(teacher())return '<section class="prep-reward-note"><b>Личный опыт ученика</b><p>За завершённое новое условие — 10 баллов; за самостоятельное решение — ещё 5. Открытие страницы баллов не добавляет. Баллы не являются экзаменационной оценкой.</p></section>';
  if(!rewards)return `<section class="prep-rewards" aria-live="polite"><p>${rewardsError?'Баллы сейчас не загрузились. Сохранённые решения остаются в кабинете.':'Загружаем Ваш учебный опыт…'}</p>${rewardsError?'<button type="button" data-prep-retry>Обновить баллы</button>':''}</section>`;
  const points=Math.max(0,Number(rewards.totalPoints)||0),within=Math.max(0,Math.min(100,Number(rewards.pointsWithinLevel)||0));
  return `<section class="prep-rewards" aria-label="Мой учебный опыт"><div class="prep-reward-head"><div><span class="eyebrow">МОЙ ОБЩИЙ ОПЫТ</span><h2>Уровень <span data-prep-level>${E(rewards.level)}</span></h2></div><strong class="prep-points"><span data-prep-points>${points}</span><small>баллов</small></strong></div><progress max="100" value="${within}" aria-label="До следующего уровня"></progress><p>До следующего уровня: ${Math.max(0,Number(rewards.nextLevelAt)-points)} баллов. Завершённых разных условий: ${E(rewards.uniqueCompleted)}.</p><div class="prep-badges">${rewards.badges.length?rewards.badges.map(b=>`<span class="prep-badge">✦ ${E(b.title)}</span>`).join(''):'<span class="small">Первое достижение появится после завершённого задания.</span>'}</div><details><summary>За что даются баллы</summary><p>За завершённое условие — 10 баллов. За самостоятельное решение — ещё 5, один раз. Подсказки доступны всегда. Повторное открытие и знакомый пример не прибавляют баллы заново.</p><p>Это общий опыт за всё время, включая работы, перенесённые в архив. Текущий учебный прогресс показывается отдельно. Баллы не являются оценкой за ОГЭ.</p></details></section>`;
 }
 function homeworkMarkup(){
  if(teacher())return '';
  const rows=(context.assignments||[]).filter(a=>a.learnerId===context.account.id&&a.status==='published');
  if(!rows.length)return '';
  return `<section class="prep-homework"><h2>От Натальи Михайловны</h2><div class="list">${rows.map(a=>{const sent=a.attempt?.submission;return `<article class="list-row"><div><h3>${E(a.title)}</h3><p>${sent?sent.stale?'Есть изменения после сдачи':sent.status==='revise'?'Нужно исправить':'Работа сдана':'Тренажёр и работа в тетради'}${a.dueAt?' · к '+E(new Date(a.dueAt).toLocaleDateString('ru-RU')):''}</p></div><a class="button primary" href="#assignment=${encodeURIComponent(a.id)}">Открыть домашку →</a></article>`;}).join('')}</div></section>`;
 }
 function recommendations(){
  const saved=plan?.items?.map(item=>({entry:entryFor(item.catalogId),reason:item.reason})).filter(x=>x.entry);
  if(saved?.length)return saved;
  const ids=oge?map.goals[goalKey].managedIds:map.groups.flatMap(g=>g.items.filter(i=>i.tier==='core'&&i.managedId).map(i=>i.managedId));
  return [...new Set(ids)].map(id=>({entry:map.get(id),reason:''})).filter(x=>x.entry);
 }
 function tasksMarkup(){
  const list=recommendations(),remaining=list.filter(x=>!hasCompleted(x.entry)),next=remaining.slice(0,3);
  const total=list.length,finished=total-remaining.length;
  return `${homeworkMarkup()}<section class="prep-next"><div class="section-heading"><h2>${teacher()?'Подобрать следующее задание':plan?.items?.length?'Рекомендации преподавателя':'Следующие шаги'}</h2></div><p>${teacher()?'Выберите материал, затем ученика и письменную часть домашней работы.':planError?'Личный план сейчас не загрузился. Ниже — общий маршрут; домашняя работа остаётся выше.':plan?.note?E(plan.note):oge?E(map.goals[goalKey].lead):'Начните с нужной темы. Если основа уже понятна, можно сразу перейти дальше.'}</p>${!teacher()?`<p class="small">${progress?'В этом списке есть завершённые примеры к '+finished+' из '+total+' тренажёров. Это ещё не означает полного освоения тем.':progressError?'Полная история сейчас не загрузилась. Показаны доступные недавние работы; сохранённые решения не потеряны.':'Загружаем историю всех тем…'}</p>`:''}<div class="prep-task-grid">${(teacher()?list.slice(0,3):next.length?next:list.slice(0,3)).map(x=>entryCard(x.entry,x.reason)).join('')}</div></section><section><div class="section-heading"><h2>${oge?'Базовые темы, к которым можно вернуться':'Полный маршрут основ'}</h2></div><p>Все темы доступны. Предыдущие решения сохраняются.</p>${map.groups.map((g,index)=>`<details class="prep-group"><summary><span class="prep-group-number">${index+1}</span><span>${E(g.title)}</span><span class="prep-group-count">${g.items.filter(i=>i.tier==='core').length} шагов</span></summary><p>${E(g.lead)}</p><div class="prep-task-grid">${g.items.filter(i=>i.tier==='core').map(i=>entryCard(i)).join('')}</div></details>`).join('')}</section>${oge?`<section><div class="section-heading"><h2>Экзаменационная практика</h2></div><p>Разборы на сайте открываются отдельно. Эти материалы пока не передают результат в кабинет автоматически.</p><div class="prep-task-grid">${map.goals[goalKey].publicItems.map(i=>entryCard(i)).join('')}</div></section>`:''}`;
 }
 function labMarkup(){return `<section class="prep-lab"><h2>Выбрать и исследовать</h2><p>Здесь можно свободно пробовать модели и способы решения. Для сохранения результата и начисления баллов нажмите «Начать задание» у материала с отметкой «Результат в кабинете».</p><label class="prep-search">Найти тему<input type="search" data-prep-search placeholder="Деление, проценты, углы…"></label><div data-prep-lab-groups>${labGroups('')}</div></section>`;}
 function labGroups(query){return map.groups.map(g=>{const items=g.items.filter(i=>(g.title+' '+i.title).toLocaleLowerCase('ru').includes(query));return items.length?`<details class="prep-group" ${query?'open':''}><summary><span>${E(g.title)}</span><span class="prep-group-count">${items.length} материалов</span></summary><p>${E(g.lead)}</p><div class="prep-task-grid">${items.map(i=>entryCard(i)).join('')}</div></details>`:'';}).join('')||'<p>Такой темы пока не найдено. Попробуйте другое слово.</p>';}
 function render(){if(!alive)return;section.innerHTML=`<div class="page-heading"><div><p class="eyebrow">${oge?'ПОДГОТОВКА К ОГЭ':'ОТДЕЛЬНЫЙ БАЗОВЫЙ КУРС'}</p><h1>${oge?'Мой маршрут ОГЭ':'Математические основы'}</h1><p class="lead">${oge?'Своя цель, свои задания и понятный следующий шаг.':'От понятного действия — к самостоятельному решению.'}</p>${oge?`<p class="prep-goal" data-prep-goal>${E(map.goals[goalKey].title)}${!profile.goal&&!teacher()?' · стартовый маршрут, цель можно уточнить с преподавателем':''}</p>`:''}${profile.focus?`<p class="prep-focus">${E(profile.focus)}</p>`:''}</div></div>${teacher()&&oge?`<label>Посмотреть подборку<select data-prep-goal-select><option value="pass" ${goalKey==='pass'?'selected':''}>Уверенно сдать</option><option value="grade5" ${goalKey==='grade5'?'selected':''}>Подготовка на 5</option></select></label>`:''}${rewardsMarkup()}<div class="prep-modes segmented" role="group" aria-label="Режим курса"><button type="button" data-prep-mode="tasks" aria-pressed="${mode==='tasks'}">Задания</button><button type="button" data-prep-mode="lab" aria-pressed="${mode==='lab'}">Лаборатория</button></div><div data-prep-content>${mode==='tasks'?tasksMarkup():labMarkup()}</div><p class="prep-course-link"><a href="https://mathexam.space/foundations/" target="_blank" rel="noopener">Весь базовый курс без входа ↗</a></p>`;
  section.querySelectorAll('[data-prep-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.prepMode;render();section.querySelector('[data-prep-mode="'+mode+'"]').focus();});
  section.querySelector('[data-prep-goal-select]')?.addEventListener('change',e=>{goalKey=e.target.value;render();});
  section.querySelector('[data-prep-search]')?.addEventListener('input',e=>{section.querySelector('[data-prep-lab-groups]').innerHTML=labGroups(e.target.value.trim().toLocaleLowerCase('ru'));bindStarts();});
  section.querySelector('[data-prep-retry]')?.addEventListener('click',load);bindStarts();
 }
 function bindStarts(){section.querySelectorAll('[data-prep-start]').forEach(button=>button.onclick=async()=>{button.disabled=true;const entry=entryFor(button.dataset.prepStart),a=entry&&latest(entry);try{await context.openContent(button.dataset.prepStart,button.dataset.prepFresh==='true'&&a?{fresh:true,sourceAttemptId:a.id}:{});}finally{if(button.isConnected)button.disabled=false;}});}
 async function load(){if(teacher())return;const result=await Promise.allSettled([context.api('/rewards'),context.api('/plan'),context.api('/progress')]);if(!alive)return;if(result[0].status==='fulfilled'){rewards=result[0].value.rewards||result[0].value;rewardsError=false;}else rewardsError=true;if(result[1].status==='fulfilled'){plan=result[1].value.plan||result[1].value;planError=false;}else planError=true;if(result[2].status==='fulfilled'){progress=result[2].value.progress;progressError=false;}else progressError=true;render();}
 render();load();return()=>{alive=false;section.remove();};
}
root.LearningPreparationUI={mountRoute};
})(window);
