/* Free-choice route: all results refer to saved attempts, never to page/video views. */
(function(root,factory){'use strict';const value=factory();if(typeof module==='object'&&module.exports)module.exports=value;else root.LearningRoute=value;})(typeof globalThis==='undefined'?this:globalThis,function(){
'use strict';
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const B='oge-basics:',P='path:';
const groups=[
 {id:'equations',title:'Линейные уравнения',lead:'Сохранить равенство, раскрыть скобки, разобраться с минусами.',items:['equations-linear','equations-signs','equations-brackets','equations-fractions'].map(x=>P+x),basis:['negative-number-line','negative-add-subtract','order-of-operations','fraction-common-denominator','multiplication-division'].map(x=>B+x),video:'linear-equation'},
 {id:'fractions',title:'Дроби и вычисления',lead:'Понять размер доли и уверенно выполнять действия.',items:['practice-fraction-add','practice-fraction-divide','practice-fraction-expression','practice-decimals','practice-decimal-division'].map(x=>P+x),basis:['fraction-meaning','fraction-common-denominator','decimal-add-subtract','multiplication-division/decimal-divisor-shift'].map(x=>B+x)},
 {id:'percent',title:'Проценты и пропорции',lead:'Определить целое, найти часть и составить пропорцию.',items:['practice-percent-part','practice-percent-whole','practice-percent-rate','practice-direct-proportion'].map(x=>P+x),basis:['percentages/percent-meaning','percentages/percent-choose-question','percentages/proportion','fraction-meaning'].map(x=>B+x)},
 {id:'geometry',title:'Первые геометрические задачи',lead:'Углы, клетки, длины и площади. Отдельные темы для тренировки.',items:['practice-spokes','practice-triangle-angle','grid','practice-fence'].map(x=>P+x),basis:['units-length-time','units-area','order-of-operations'].map(x=>B+x),video:'adjacent-angles'},
 {id:'word',title:'Задачи и рассуждения',lead:'Читать условие, выбирать величины, проверять смысл ответа.',items:['practice-meeting','practice-river','practice-ratio-parts','practice-logic-order'].map(x=>P+x),basis:['multiplication-division','units-length-time','percentages/proportion'].map(x=>B+x)},
 {id:'data',title:'Таблицы, формулы и диаграммы',lead:'Находить данные и аккуратно подставлять их в формулу.',items:['practice-chart','practice-ranking','practice-interval-data','practice-temperature'].map(x=>P+x),basis:['negative-add-subtract','order-of-operations','decimal-add-subtract'].map(x=>B+x)}
].map(g=>Object.freeze({...g,items:Object.freeze(g.items),basis:Object.freeze(g.basis)}));
const deeper={
 'fraction-common-denominator':['fraction-meaning','multiplication-division'],
 'decimal-add-subtract':['order-of-operations','multiplication-division'],
 'negative-add-subtract':['negative-number-line'],
 'order-of-operations':['multiplication-division'],
 'multiplication-division':['multiplication-division/multiplication-meaning','multiplication-division/tabular-division'],
 'multiplication-division/decimal-divisor-shift':['multiplication-division/decimal-division-natural','multiplication-division/long-division-one-digit'],
 'percentages/proportion':['fraction-meaning','multiplication-division'],
 'percentages/percent-choose-question':['percentages/percent-meaning'],
 'percentages/percent-meaning':['fraction-meaning'],
 'units-area':['units-length-time','multiplication-division']
};
const focused={
 'equations-linear':['order-of-operations','multiplication-division'],
 'equations-signs':['negative-number-line','negative-add-subtract','multiplication-division'],
 'equations-brackets':['order-of-operations','negative-add-subtract','multiplication-division'],
 'equations-fractions':['fraction-meaning','fraction-common-denominator','multiplication-division']
};
function groupFor(id){return groups.find(g=>g.items.includes(id))||null;}
function itemFor(catalog,attempt){return catalog.items.find(i=>i.trainerId===attempt.trainerId&&i.contentId===attempt.contentId)||null;}
function ownAttempts(attempts,account){return attempts.filter(a=>a.learnerId===account.id&&!a.archivedAt);}
function latestFor(attempts,item){return attempts.filter(a=>!a.archivedAt&&a.contentId===item.contentId&&a.trainerId===item.trainerId).sort((a,b)=>String(b.updatedAt||b.createdAt).localeCompare(String(a.updatedAt||a.createdAt)))[0]||null;}
function progress(attempts,ids,catalog){const relevant=attempts.filter(a=>!a.archivedAt&&ids.some(id=>{const i=catalog.get(id);return i&&i.contentId===a.contentId&&i.trainerId===a.trainerId;}));return {opened:new Set(relevant.map(a=>a.trainerId+':'+a.contentId)).size,total:ids.length,independent:relevant.filter(a=>['independent','repeated'].includes(a.outcome)).length,helped:relevant.filter(a=>['hinted','together'].includes(a.outcome)).length,started:relevant.filter(a=>a.outcome==='started').length};}
function prerequisites(item,catalog,topicId){if(!item)return [];const g=groups.find(x=>x.id===topicId&&x.items.includes(item.id))||groupFor(item.id);const ids=item.family==='remediation'?(deeper[item.contentId]||[]).map(x=>B+x):focused[item.contentId]?focused[item.contentId].map(x=>B+x):g?.basis||[];return ids.map(id=>catalog.get(id)).filter(i=>i&&i.id!==item.id);}
function returnAttempt(attempts,account,id,currentId){if(typeof id!=='string'||id===currentId)return null;return ownAttempts(attempts,account).find(a=>a.id===id)||null;}
function status(attempt,labels){if(!attempt)return 'Ещё не открывали';const main=labels[attempt.outcome]||'Начато';const hint=attempt.outcome==='started'&&(attempt.assistance?.hints>0||attempt.assistance?.teacher)?' · с помощью':'';return main+hint;}
function mount(host,ctx){const {catalog,account,attempts,labels,openContent,api}=ctx;let alive=true;const mine=ownAttempts(attempts,account),all=groups.flatMap(g=>g.items),total=progress(mine,all,catalog),recent=[...mine].sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))[0];
 const rows=(ids,basis=false)=>`<ul class="route-items">${ids.map(id=>{const i=catalog.get(id);if(!i)return '';const a=latestFor(mine,i);return `<li><button type="button" ${basis?'data-route-basis':'data-route-item'}="${E(i.id)}">${E(i.title)} <span aria-hidden="true">↗</span></button><small>${E(status(a,labels))}</small></li>`;}).join('')}</ul>`;
 host.innerHTML=`<section class="route-intro"><div><p class="eyebrow">В СВОЁМ ТЕМПЕ</p><h1>Мой маршрут</h1><p class="lead">Выбирайте, что интересно или нужно сейчас. Все темы открыты: можно вернуться к основам и продолжить свою задачу.</p></div><button type="button" data-route-welcome>Как здесь заниматься</button></section><section class="route-progress panel" aria-label="Мой сохранённый прогресс"><div><strong>${total.opened} / ${total.total}</strong><span>тренажёров маршрута открыто</span></div><div><strong>${total.independent}</strong><span>попыток решено самостоятельно</span></div><div><strong>${total.helped}</strong><span>попыток решено с помощью</span></div><p>Здесь результаты конкретных задач. Просмотр инструкции или видео не считается решением.</p></section>${recent?`<section class="route-continue panel"><div><span class="badge neutral">Можно продолжить</span><h2>${E(itemFor(catalog,recent)?.title||'Моя задача')}</h2><p>${E(status(recent,labels))}</p></div><a class="button primary" href="#attempt=${encodeURIComponent(recent.id)}">Продолжить мою работу →</a></section>`:''}<section class="panel route-recommendations" aria-label="Рекомендации преподавателя"><h2>Наталья Михайловна рекомендует</h2><div data-route-plan aria-live="polite"><p>Загружаем рекомендации…</p></div></section><div class="section-heading"><h2>Выберите тему</h2><a href="#assignments">Моя домашняя работа →</a></div><div class="route-grid">${groups.map(g=>{const p=progress(mine,g.items,catalog);return `<section class="route-card panel" id="route-${g.id}"><p class="eyebrow">${g.id==='geometry'?'ПОДБОРКА ТЕМ':'МОЖНО НАЧАТЬ ЗДЕСЬ'}</p><h2>${E(g.title)}</h2><p>${E(g.lead)}</p><p class="route-count">Открыто ${p.opened} из ${p.total} · самостоятельно решено попыток: ${p.independent}</p><progress value="${p.opened}" max="${p.total}" aria-label="Открыто тренажёров: ${p.opened} из ${p.total}"></progress>${rows(g.items)}${g.video?`<button type="button" class="small route-video" data-route-video="${g.video}">▶ Посмотреть разбор${g.id==='geometry'?' смежных углов':''}</button>`:''}<details class="route-foundations"><summary>↘ Вспомнить более ранние темы</summary><p>Это необязательная помощь. Любую основу можно открыть отдельно.</p>${rows(g.basis,true)}</details></section>`;}).join('')}</div><section class="panel route-extra"><h2>Можно вернуться ещё дальше</h2><p>Таблица умножения, деление уголком и смысл дроби — нормальная часть подготовки. Выбирайте нужный шаг без обязательной очереди.</p>${rows(['multiplication-division/multiplication-meaning','multiplication-division/multiplication-mixed','multiplication-division/long-division-one-digit','multiplication-division/long-division-from-simple-to-decimals','fraction-meaning','negative-number-line'].map(x=>B+x),true)}<p><a href="#course">Полный каталог и курс ЕГЭ база →</a></p></section>`;
 host.querySelector('[data-route-welcome]').onclick=()=>window.MathExamWelcome?.open();
 function bind(container){container.querySelectorAll('[data-route-item],[data-route-basis]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await openContent(b.dataset.routeItem||b.dataset.routeBasis,{topicId:groupFor(b.dataset.routeItem)?.id});}finally{if(b.isConnected)b.disabled=false;}});container.querySelectorAll('[data-route-video]').forEach(b=>b.onclick=()=>window.MathExamWelcome?.openVideo(b.dataset.routeVideo));}
 bind(host);async function loadPlan(){const target=host.querySelector('[data-route-plan]');try{const result=await api('/plan');if(!alive||!target.isConnected)return;const plan=result.plan||result,items=(plan.items||[]).filter(i=>catalog.get(i.catalogId));target.innerHTML=`${plan.note?`<p class="route-plan-note">${E(plan.note)}</p>`:''}${items.length?`<p>Вы можете выбирать порядок и заглядывать в другие темы.</p><ul class="route-items">${items.map(entry=>{const i=catalog.get(entry.catalogId);return `<li><button type="button" data-route-item="${E(i.id)}">${E(i.title)} →</button><p>${E(entry.reason)}</p><small>${E(status(latestFor(mine,i),labels))}</small></li>`;}).join('')}</ul>`:'<p>Персональные рекомендации появятся здесь. Пока можно выбрать любую тему ниже.</p>'}`;bind(target);}catch(_){if(alive&&target.isConnected){target.innerHTML='<p>Рекомендации пока не загрузились. Ваши темы остаются доступными.</p><button type="button" class="small">Повторить загрузку</button>';target.querySelector('button').onclick=loadPlan;}}}loadPlan();return()=>{alive=false;};}
function mountSupport(host,ctx){const {catalog,attempt,attempts,account,labels}=ctx,item=itemFor(catalog,attempt),basis=prerequisites(item,catalog,ctx.topicId),back=returnAttempt(attempts,account,ctx.returnTo,attempt.id),group=groupFor(item?.id);host.innerHTML=`${back?`<div class="route-return"><div><b>Вы повторяете основу</b><span>Исходная задача и её записи сохранены.</span></div><a class="button primary" href="#attempt=${encodeURIComponent(back.id)}">Вернуться к моей задаче →</a></div>`:''}<div class="route-support-actions"><div class="actions"><button type="button" class="primary" data-submit-attempt>Сдать Наталье Михайловне</button><button type="button" class="small" data-support-video="${group?.video||'homework-help'}">▶ ${group?.video?'Видеоразбор':'Как заниматься'}</button><a href="#route" class="button small">Мой маршрут</a></div><p data-submit-status role="status"></p></div>${basis.length?`<details class="route-foundations"><summary>↘ Нужна основа? Можно заглянуть в раннюю тему</summary><p>Повторение откроется отдельной работой. Затем вернитесь к этой же задаче.</p><ul class="route-items">${basis.map(i=>`<li><button type="button" data-support-basis="${E(i.id)}">${E(i.title)} →</button><small>${E(status(latestFor(ownAttempts(attempts,account),i),labels))}</small></li>`).join('')}</ul></details>`:''}`;
 host.querySelector('[data-submit-attempt]').onclick=ctx.submit;host.querySelector('[data-support-video]').onclick=e=>window.MathExamWelcome?.openVideo(e.currentTarget.dataset.supportVideo);
 host.querySelectorAll('[data-support-basis]').forEach(b=>b.onclick=async()=>{if(!ctx.canLeave())return;b.disabled=true;try{await ctx.openContent(b.dataset.supportBasis,{returnTo:back?.id||attempt.id,topicId:group?.id||ctx.topicId});}finally{if(b.isConnected)b.disabled=false;}});}
return Object.freeze({groups:Object.freeze(groups),groupFor,prerequisites,progress,returnAttempt,latestFor,mount,mountSupport});
});
